function(add_firmware_unit_test)
    cmake_parse_arguments(TEST "" "NAME" "SOURCES;TEST_SOURCES;INCLUDE_DIRECTORIES" ${ARGN})
    if(NOT TEST_NAME OR NOT TEST_TEST_SOURCES)
        message(FATAL_ERROR "add_firmware_unit_test requires NAME and TEST_SOURCES")
    endif()

    add_executable(${TEST_NAME} ${TEST_TEST_SOURCES})
    target_include_directories(${TEST_NAME} PRIVATE ${TEST_INCLUDE_DIRECTORIES})
    target_link_libraries(${TEST_NAME} PRIVATE GTest::gtest_main)

    if(TEST_SOURCES)
        add_library(${TEST_NAME}_firmware STATIC ${TEST_SOURCES})
        target_include_directories(${TEST_NAME}_firmware PRIVATE ${TEST_INCLUDE_DIRECTORIES})
        set_target_properties(${TEST_NAME}_firmware PROPERTIES C_STANDARD 23 C_STANDARD_REQUIRED YES C_EXTENSIONS OFF)
        target_link_libraries(${TEST_NAME} PRIVATE ${TEST_NAME}_firmware)
    endif()
    set_target_properties(${TEST_NAME} PROPERTIES CXX_STANDARD 17 CXX_STANDARD_REQUIRED YES CXX_EXTENSIONS OFF)

    if(MSVC)
        target_compile_options(${TEST_NAME} PRIVATE /W4 /WX)
        if(TEST_SOURCES)
            target_compile_options(${TEST_NAME}_firmware PRIVATE /W4 /WX)
        endif()
    elseif(CMAKE_C_COMPILER_ID MATCHES "GNU|Clang|AppleClang")
        target_compile_options(${TEST_NAME} PRIVATE -Wall -Wextra -Wpedantic -Werror)
        if(TEST_SOURCES)
            target_compile_options(${TEST_NAME}_firmware PRIVATE -Wall -Wextra -Wpedantic -Werror)
        endif()
    endif()

    if(PER_TEST_SANITIZERS AND CMAKE_C_COMPILER_ID MATCHES "GNU|Clang|AppleClang")
        target_compile_options(${TEST_NAME} PRIVATE -fsanitize=address,undefined -fno-omit-frame-pointer)
        target_link_options(${TEST_NAME} PRIVATE -fsanitize=address,undefined)
        if(TEST_SOURCES)
            target_compile_options(${TEST_NAME}_firmware PRIVATE -fsanitize=address,undefined -fno-omit-frame-pointer)
            target_link_options(${TEST_NAME}_firmware PRIVATE -fsanitize=address,undefined)
        endif()
    endif()

    gtest_discover_tests(${TEST_NAME} PROPERTIES LABELS unit)
endfunction()
