PER Firmware: source/a_box/main.c File Reference
main.c File Reference
"Abox" node source code
#include "main.h"
#include <stdint.h>
#include "adbms.h"
#include "common/can_library/faults_common.h"
#include "common/can_library/generated/A_BOX.h"
#include "common/freertos/freertos.h"
#include "common/phal/can.h"
#include "common/phal/gpio.h"
#include "common/phal/rcc.h"
#include "common/heartbeat/heartbeat.h"
Functions
void HardFault_Handler (void)
void bms_task (void)
void background_can_update (void)
void check_faults (void)
void report_telemetry (void)
DEFINE_TASK (bms_task, 200, osPriorityHigh, STACK_2048)
DEFINE_TASK (background_can_update, 2, osPriorityHigh, STACK_2048)
DEFINE_TASK (check_faults, 10, osPriorityNormal, STACK_512)
DEFINE_TASK (fault_library_periodic, A_BOX_FAULT_SYNC_PERIOD_MS, osPriorityNormal, STACK_1024)
DEFINE_TASK (report_telemetry, PACK_STATS_PERIOD_MS, osPriorityLow, STACK_512)
void heartbeat_wrapper (void)
DEFINE_TASK (heartbeat_wrapper, HEARTBEAT_PERIOD_MS, osPriorityLow, STACK_512)
int main (void)
Variables
SPI_InitConfig_t bms_spi_config
GPIOInitConfig_t gpio_config []
static constexpr uint32_t TargetCoreClockrateHz = 16'000'000
ClockRateConfig_t clock_config
uint32_t APB1ClockRateHz
uint32_t APB2ClockRateHz
uint32_t AHBClockRateHz
uint32_t PLLClockRateHz
adbms_bms_t g_bms = {0}
uint8_t g_bms_tx_buf [ADBMS_SPI_TX_BUFFER_SIZE] = {0}
static constexpr float MIN_V_FOR_BALANCE = 3.0f
static constexpr float MIN_DELTA_FOR_BALANCE = 0.1f
status_leds_t status_leds = { .heartbeat_port = (GPIOB), .heartbeat_pin = (5), .connection_port = (GPIOB), .connection_pin = (4), .error_port = (GPIOB), .error_pin = (9), .preflight_callback = (nullptr), .state = HEARTBEAT_STATE_PREFLIGHT }
Detailed Description
"Abox" node source code
Author
Irving Wang (irvin.nosp@m.gw@p.nosp@m.urdue.nosp@m..edu), Millan Kumar (kumar.nosp@m.798@.nosp@m.purdu.nosp@m.e.ed.nosp@m.u)
Definition in file main.c.
Function Documentation
background_can_update()
void background_can_update (void)
Definition at line 156 of file main.c.
References CAN_rx_update(), and CAN_tx_update().
Referenced by main(), and main().
bms_task()
void bms_task (void)
Definition at line 161 of file main.c.
References adbms_periodic(), g_bms, MIN_DELTA_FOR_BALANCE, and MIN_V_FOR_BALANCE.
Referenced by main().
check_faults()
void check_faults (void)
Definition at line 165 of file main.c.
References g_bms, IMD_STATUS_PIN, IMD_STATUS_PORT, adbms_bms_t::max_therm_temp, adbms_bms_t::min_therm_temp, PHAL_readGPIO(), and update_fault().
Referenced by main().
DEFINE_TASK() [1/6]
DEFINE_TASK (background_can_update , 2 , osPriorityHigh , STACK_2048)
DEFINE_TASK() [2/6]
DEFINE_TASK (bms_task , 200 , osPriorityHigh , STACK_2048)
DEFINE_TASK() [3/6]
DEFINE_TASK (check_faults , 10 , osPriorityNormal , STACK_512)
DEFINE_TASK() [4/6]
DEFINE_TASK (fault_library_periodic , A_BOX_FAULT_SYNC_PERIOD_MS , osPriorityNormal , STACK_1024)
DEFINE_TASK() [5/6]
DEFINE_TASK (heartbeat_wrapper , HEARTBEAT_PERIOD_MS , osPriorityLow , STACK_512)
DEFINE_TASK() [6/6]
DEFINE_TASK (report_telemetry , PACK_STATS_PERIOD_MS , osPriorityLow , STACK_512)
HardFault_Handler()
void HardFault_Handler (void) extern
Definition at line 178 of file main.c.
References ERROR_LED_PIN, and ERROR_LED_PORT.
Referenced by crit_enter(), main(), main(), and rtc_config_cb().
heartbeat_wrapper()
void heartbeat_wrapper (void)
Definition at line 102 of file main.c.
main()
int main (void)
Definition at line 104 of file main.c.
References adbms6380_set_cs_high(), adbms_init(), background_can_update(), bms_spi_config, bms_task(), CAN_library_init(), check_faults(), clock_config, fault_library_periodic(), g_bms, g_bms_tx_buf, gpio_config, HardFault_Handler(), PHAL_configureClockRates(), PHAL_FDCAN_init(), PHAL_initGPIO(), PHAL_SPI_init(), report_telemetry(), START_HEARTBEAT_TASK, and START_TASK.
report_telemetry()
void report_telemetry (void)
Definition at line 150 of file main.c.
References adbms_bms_t::avg_therm_temp, g_bms, and adbms_bms_t::sum_voltage.
Referenced by main().
Variable Documentation
AHBClockRateHz
uint32_t AHBClockRateHz extern
Definition at line 17 of file rcc.c.
APB1ClockRateHz
uint32_t APB1ClockRateHz extern
Definition at line 15 of file rcc.c.
APB2ClockRateHz
uint32_t APB2ClockRateHz extern
Definition at line 16 of file rcc.c.
Referenced by main(), and main().
bms_spi_config
SPI_InitConfig_t bms_spi_config
Initial value:
= {
    .data_len      = 8,
    .nss_sw        = false,
    .nss_gpio_port = (GPIOB),
    .nss_gpio_pin  = (0),
    .rx_dma_cfg    = nullptr,
    .tx_dma_cfg    = nullptr,
    .periph        = SPI1,
    .cpol          = 0,
    .cpha          = 0,
    .data_rate     = 500'000,
}
Definition at line 21 of file main.c.
Referenced by main().
clock_config
ClockRateConfig_t clock_config
Initial value:
= {
    .clock_source           = CLOCK_SOURCE_HSE,
    .use_pll                = false,
    .system_clock_target_hz = TargetCoreClockrateHz,
    .ahb_clock_target_hz    = (TargetCoreClockrateHz / 1),
    .apb1_clock_target_hz   = (TargetCoreClockrateHz / (1)),
    .apb2_clock_target_hz   = (TargetCoreClockrateHz / (1)),
}
Definition at line 69 of file main.c.
Referenced by main(), and main().
g_bms
adbms_bms_t g_bms = {0}
Definition at line 84 of file main.c.
Referenced by bms_task(), check_faults(), main(), and report_telemetry().
g_bms_tx_buf
uint8_t g_bms_tx_buf[ADBMS_SPI_TX_BUFFER_SIZE] = {0}
Definition at line 85 of file main.c.
Referenced by main().
gpio_config
GPIOInitConfig_t gpio_config[]
Definition at line 35 of file main.c.
Referenced by main(), and main().
MIN_DELTA_FOR_BALANCE
float MIN_DELTA_FOR_BALANCE = 0.1f static constexpr
Definition at line 88 of file main.c.
Referenced by bms_task().
MIN_V_FOR_BALANCE
float MIN_V_FOR_BALANCE = 3.0f static constexpr
Definition at line 87 of file main.c.
Referenced by bms_task().
PLLClockRateHz
uint32_t PLLClockRateHz extern
Definition at line 18 of file rcc.c.
status_leds
status_leds_t status_leds = { .heartbeat_port = (GPIOB), .heartbeat_pin = (5), .connection_port = (GPIOB), .connection_pin = (4), .error_port = (GPIOB), .error_pin = (9), .preflight_callback = (nullptr), .state = HEARTBEAT_STATE_PREFLIGHT }
Definition at line 102 of file main.c.
Referenced by driver_interface_periodic().
TargetCoreClockrateHz
uint32_t TargetCoreClockrateHz = 16'000'000 static constexpr
Definition at line 68 of file main.c.