PER Firmware: source/a_box/adbms/adbms.h File Reference
adbms.h File Reference
Primary logic and interface for ADBMS battery management system driver.
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "adbms6380.h"
#include "common/phal/spi.h"
#include "common/strbuf/strbuf.h"
Data Structures
struct adbms_module_t
Per-ADBMS module measurements, config, and error flags.
struct adbms_bms_t
Top-level ADBMS driver state, I/O buffers, measurements, and error flags.
Macros
#define ADBMS_MODULE_COUNT (8)
#define ADBMS_PEC_FAIL_MAX_RETRIES (3)
#define ADBMS_GPIO_R1 (10000.0f)
#define ADBMS_GPIO_VIN (3.0f)
#define ADBMS_SPI_TX_BUFFER_SIZE (ADBMS6380_COMMAND_PKT_SIZE + (ADBMS_MODULE_COUNT * ADBMS6380_SINGLE_DATA_PKT_SIZE))
#define ADBMS_SPI_RX_BUFFER_SIZE (ADBMS6380_SINGLE_DATA_PKT_SIZE * ADBMS_MODULE_COUNT)
#define ADBMS_REGA_REFON (true)
#define ADBMS_REGA_CTH (0b110)
#define ADBMS_REGB_OV_THRESHOLD (4.2f)
#define ADBMS_REGB_UV_THRESHOLD (3.0f)
#define ADBMS_ADCV_RD (false)
#define ADBMS_ADCV_CONT (true)
#define ADBMS_ADCV_DCP (false)
#define ADBMS_ADCV_RSTF (true)
#define ADBMS_ADCV_OW (0b00)
#define ADBMS_ADAX_OW (false)
#define ADBMS_ADAX_PUP (false)
#define ADBMS_ADAX_CH (0b00000)
Enumerations
enum adbms_state_t { ADBMS_STATE_IDLE = 0 , ADBMS_STATE_CONNECTED }
ADBMS driver connection/operation state.
Functions
void adbms_init (adbms_bms_t *bms, SPI_InitConfig_t *spi, uint8_t *tx_buf)
Initialize the ADBMS driver instance and TX buffer.
bool adbms_write_rega (adbms_bms_t *bms)
Calculate and write REGA configuration to all modules.
bool adbms_write_regb (adbms_bms_t *bms)
Calculate and write REGB configuration to all modules.
bool adbms_read_and_check_rega (adbms_bms_t *bms)
Read back REGA and compare with cached configuration.
bool adbms_read_and_check_regb (adbms_bms_t *bms)
Read back REGB and compare with cached configuration.
void adbms_connect (adbms_bms_t *bms)
Perform the connect/bring-up sequence for all modules.
void adbms_read_cells (adbms_bms_t *bms)
Read all cell voltages and update module/pack statistics.
void adbms_read_therms (adbms_bms_t *bms)
Read all GPIO/thermistor values (voltage and calculate temperature) and update module/pack statistics.
void adbms_calculate_balance_cells (adbms_bms_t *bms, float min_voltage, float min_delta)
Compute per-cell discharge flags based on pack voltage spread.
void adbms_balance_and_update_regb (adbms_bms_t *bms, float min_voltage, float min_delta)
Compute discharge flags and write REGB to apply balancing.
void adbms_periodic (adbms_bms_t *bms, float min_voltage_for_balance, float min_delta_for_balance)
Periodic service routine for connection, measurements, and balancing.
Detailed Description
Primary logic and interface for ADBMS battery management system driver.
Author
Millan Kumar (kumar.nosp@m.798@.nosp@m.purdu.nosp@m.e.ed.nosp@m.u)
Definition in file adbms.h.
Macro Definition Documentation
ADBMS_ADAX_CH
#define ADBMS_ADAX_CH (0b00000)
Definition at line 47 of file adbms.h.
Referenced by adbms_read_therms().
ADBMS_ADAX_OW
#define ADBMS_ADAX_OW (false)
Definition at line 45 of file adbms.h.
Referenced by adbms_read_therms().
ADBMS_ADAX_PUP
#define ADBMS_ADAX_PUP (false)
Definition at line 46 of file adbms.h.
Referenced by adbms_read_therms().
ADBMS_ADCV_CONT
#define ADBMS_ADCV_CONT (true)
Definition at line 41 of file adbms.h.
Referenced by adbms_connect().
ADBMS_ADCV_DCP
#define ADBMS_ADCV_DCP (false)
Definition at line 42 of file adbms.h.
Referenced by adbms_connect().
ADBMS_ADCV_OW
#define ADBMS_ADCV_OW (0b00)
Definition at line 44 of file adbms.h.
Referenced by adbms_connect().
ADBMS_ADCV_RD
#define ADBMS_ADCV_RD (false)
Definition at line 40 of file adbms.h.
Referenced by adbms_connect().
ADBMS_ADCV_RSTF
#define ADBMS_ADCV_RSTF (true)
Definition at line 43 of file adbms.h.
Referenced by adbms_connect().
ADBMS_GPIO_R1
#define ADBMS_GPIO_R1 (10000.0f)
Definition at line 26 of file adbms.h.
Referenced by adbms_read_therms().
ADBMS_GPIO_VIN
#define ADBMS_GPIO_VIN (3.0f)
Definition at line 28 of file adbms.h.
Referenced by adbms_read_therms().
ADBMS_MODULE_COUNT
#define ADBMS_MODULE_COUNT (8)
Definition at line 20 of file adbms.h.
Referenced by adbms_calculate_balance_cells(), adbms_init(), adbms_periodic(), adbms_read_and_check_rega(), adbms_read_and_check_regb(), adbms_read_cells(), adbms_read_therms(), adbms_write_rega(), and adbms_write_regb().
ADBMS_PEC_FAIL_MAX_RETRIES
#define ADBMS_PEC_FAIL_MAX_RETRIES (3)
Definition at line 23 of file adbms.h.
Referenced by adbms_read_and_check_rega(), adbms_read_and_check_regb(), adbms_read_cells(), and adbms_read_therms().
ADBMS_REGA_CTH
#define ADBMS_REGA_CTH (0b110)
Definition at line 37 of file adbms.h.
Referenced by adbms_write_rega().
ADBMS_REGA_REFON
#define ADBMS_REGA_REFON (true)
Definition at line 36 of file adbms.h.
Referenced by adbms_write_rega().
ADBMS_REGB_OV_THRESHOLD
#define ADBMS_REGB_OV_THRESHOLD (4.2f)
Definition at line 38 of file adbms.h.
Referenced by adbms_write_regb().
ADBMS_REGB_UV_THRESHOLD
#define ADBMS_REGB_UV_THRESHOLD (3.0f)
Definition at line 39 of file adbms.h.
Referenced by adbms_write_regb().
ADBMS_SPI_RX_BUFFER_SIZE
#define ADBMS_SPI_RX_BUFFER_SIZE (ADBMS6380_SINGLE_DATA_PKT_SIZE * ADBMS_MODULE_COUNT)
Definition at line 34 of file adbms.h.
ADBMS_SPI_TX_BUFFER_SIZE
#define ADBMS_SPI_TX_BUFFER_SIZE (ADBMS6380_COMMAND_PKT_SIZE + (ADBMS_MODULE_COUNT * ADBMS6380_SINGLE_DATA_PKT_SIZE))
Definition at line 31 of file adbms.h.
Referenced by adbms_init().
Enumeration Type Documentation
adbms_state_t
enum adbms_state_t
ADBMS driver connection/operation state.
Enumerator
ADBMS_STATE_IDLE
Driver is idle; not connected or awaiting re-connection.
ADBMS_STATE_CONNECTED
Driver is connected; periodic reads/balancing are active.
Definition at line 52 of file adbms.h.
Function Documentation
adbms_balance_and_update_regb()
void adbms_balance_and_update_regb (adbms_bms_t * bms, float min_voltage, float min_delta)
Compute discharge flags and write REGB to apply balancing.
Calls adbms_calculate_balance_cells(), writes REGB, and verifies it.
Parameters
bms Pointer to driver state.
min_voltage Minimum pack voltage required to allow balancing.
min_delta Voltage delta above minimum to start discharging.
Definition at line 244 of file adbms.c.
References adbms_calculate_balance_cells(), adbms_read_and_check_regb(), ADBMS_STATE_IDLE, adbms_write_regb(), and adbms_bms_t::state.
Referenced by adbms_periodic().
adbms_calculate_balance_cells()
void adbms_calculate_balance_cells (adbms_bms_t * bms, float min_voltage, float min_delta)
Compute per-cell discharge flags based on pack voltage spread.
If balancing is disabled, clears all discharge flags. If the pack minimum voltage is below min_voltage, no balancing occurs. Otherwise, discharges cells above (min + delta).
Parameters
bms Pointer to driver state.
min_voltage Minimum pack voltage required to allow balancing.
min_delta Voltage delta above minimum to start discharging.
Definition at line 211 of file adbms.c.
References ADBMS6380_CELL_COUNT, ADBMS_MODULE_COUNT, adbms_module_t::cell_voltages, adbms_bms_t::is_discharge_enabled, adbms_module_t::is_discharging, adbms_bms_t::min_voltage, and adbms_bms_t::modules.
Referenced by adbms_balance_and_update_regb().
adbms_connect()
void adbms_connect (adbms_bms_t * bms)
Perform the connect/bring-up sequence for all modules.
Writes REGA/REGB, verifies read-back, and starts ADCV conversions.
Parameters
bms Pointer to driver state.
Definition at line 165 of file adbms.c.
References adbms6380_adcv(), adbms6380_prepare_command(), adbms6380_set_cs_high(), adbms6380_set_cs_low(), ADBMS_ADCV_CONT, ADBMS_ADCV_DCP, ADBMS_ADCV_OW, ADBMS_ADCV_RD, ADBMS_ADCV_RSTF, adbms_read_and_check_rega(), adbms_read_and_check_regb(), ADBMS_STATE_CONNECTED, ADBMS_STATE_IDLE, adbms_write_rega(), adbms_write_regb(), strbuf_t::data, adbms_bms_t::err_connect, adbms_bms_t::err_spi, strbuf_t::length, PHAL_SPI_transfer_noDMA(), adbms_bms_t::spi, adbms_bms_t::state, strbuf_clear(), and adbms_bms_t::tx_strbuf.
Referenced by adbms_periodic().
adbms_init()
void adbms_init (adbms_bms_t * bms, SPI_InitConfig_t * spi, uint8_t * tx_buf)
Initialize the ADBMS driver instance and TX buffer.
Sets the driver state to idle, clears discharge flags (and discharged enabled), and sets the provided SPI config and TX buffer into the internal strbuf.
Parameters
bms Pointer to driver state to initialize.
spi SPI configuration used for ADBMS transactions.
tx_buf Backing buffer for TX command/data packets.
Definition at line 21 of file adbms.c.
References ADBMS6380_CELL_COUNT, ADBMS6380_RDAUX_CMD_COUNT, ADBMS6380_RDCV_CMD_COUNT, ADBMS_MODULE_COUNT, ADBMS_SPI_TX_BUFFER_SIZE, ADBMS_STATE_IDLE, adbms_bms_t::err_cell_voltage_pecs, adbms_bms_t::err_connect, adbms_bms_t::err_gpio_voltage_pecs, adbms_bms_t::err_rega_mismatch, adbms_module_t::err_rega_mismatch, adbms_bms_t::err_rega_pec, adbms_bms_t::err_regb_mismatch, adbms_module_t::err_regb_mismatch, adbms_bms_t::err_regb_pec, adbms_bms_t::err_spi, adbms_bms_t::is_discharge_enabled, adbms_module_t::is_discharging, adbms_bms_t::modules, adbms_bms_t::spi, adbms_bms_t::state, and adbms_bms_t::tx_strbuf.
Referenced by main().
adbms_periodic()
void adbms_periodic (adbms_bms_t * bms, float min_voltage_for_balance, float min_delta_for_balance)
Periodic service routine for connection, measurements, and balancing.
If idle, attempts to connect. When connected, reads cells and thermistors, then updates balancing + REGB.
Parameters
bms Pointer to driver state.
min_voltage_for_balance Minimum pack voltage required to allow balancing.
min_delta_for_balance Voltage delta above minimum to start discharging.
Definition at line 384 of file adbms.c.
References adbms6380_wake(), adbms_balance_and_update_regb(), adbms_connect(), ADBMS_MODULE_COUNT, adbms_read_cells(), adbms_read_therms(), ADBMS_STATE_CONNECTED, ADBMS_STATE_IDLE, adbms_bms_t::spi, and adbms_bms_t::state.
Referenced by g_bms_periodic().
adbms_read_and_check_rega()
bool adbms_read_and_check_rega (adbms_bms_t * bms)
Read back REGA and compare with cached configuration.
Sets per-module and aggregated mismatch flags when the read-back does not match the cached REGA data.
Parameters
bms Pointer to driver state.
Returns
False on SPI failure, PEC error, or when there is a mismatch; true otherwise.
Definition at line 97 of file adbms.c.
References adbms6380_prepare_command(), adbms6380_read_data_with_retries(), ADBMS6380_READ_PEC_FAILURE, ADBMS6380_READ_SPI_FAILURE, ADBMS6380_READ_SUCCESS, ADBMS6380_SINGLE_DATA_PKT_SIZE, ADBMS6380_SINGLE_DATA_RAW_SIZE, ADBMS_MODULE_COUNT, ADBMS_PEC_FAIL_MAX_RETRIES, strbuf_t::data, adbms_bms_t::err_rega_mismatch, adbms_module_t::err_rega_mismatch, adbms_bms_t::err_rega_pec, adbms_bms_t::err_spi, adbms_bms_t::modules, RDCFGA, adbms_module_t::rega, adbms_bms_t::rx_buf, adbms_bms_t::spi, strbuf_clear(), and adbms_bms_t::tx_strbuf.
Referenced by adbms_connect().
adbms_read_and_check_regb()
bool adbms_read_and_check_regb (adbms_bms_t * bms)
Read back REGB and compare with cached configuration.
Sets per-module and aggregated mismatch flags when the read-back does not match the cached REGB data.
Parameters
bms Pointer to driver state.
Returns
False on SPI failure, PEC error, or when there is a mismatch; true otherwise.
Definition at line 131 of file adbms.c.
References adbms6380_prepare_command(), adbms6380_read_data_with_retries(), ADBMS6380_READ_PEC_FAILURE, ADBMS6380_READ_SPI_FAILURE, ADBMS6380_READ_SUCCESS, ADBMS6380_SINGLE_DATA_PKT_SIZE, ADBMS6380_SINGLE_DATA_RAW_SIZE, ADBMS_MODULE_COUNT, ADBMS_PEC_FAIL_MAX_RETRIES, strbuf_t::data, adbms_bms_t::err_regb_mismatch, adbms_module_t::err_regb_mismatch, adbms_bms_t::err_regb_pec, adbms_bms_t::err_spi, adbms_bms_t::modules, RDCFGB, adbms_module_t::regb, adbms_bms_t::rx_buf, adbms_bms_t::spi, strbuf_clear(), and adbms_bms_t::tx_strbuf.
Referenced by adbms_balance_and_update_regb(), and adbms_connect().
adbms_read_cells()
void adbms_read_cells (adbms_bms_t * bms)
Read all cell voltages and update module/pack statistics.
Updates per-module min/max/avg/sum and aggregated min/max/avg/sum for the full pack.
Parameters
bms Pointer to driver state.
Definition at line 257 of file adbms.c.
References ADBMS6380_CELL_COUNT, adbms6380_read_cell_voltages(), ADBMS_MODULE_COUNT, ADBMS_PEC_FAIL_MAX_RETRIES, ADBMS_STATE_IDLE, adbms_bms_t::avg_voltage, adbms_module_t::avg_voltage, adbms_module_t::cell_voltages, adbms_module_t::cell_voltages_raw, adbms_bms_t::err_cell_voltage_pecs, adbms_bms_t::err_spi, adbms_bms_t::max_voltage, adbms_module_t::max_voltage, adbms_bms_t::min_voltage, adbms_module_t::min_voltage, adbms_bms_t::modules, adbms_bms_t::rx_buf, adbms_bms_t::spi, adbms_bms_t::state, adbms_bms_t::sum_voltage, adbms_module_t::sum_voltage, and adbms_bms_t::tx_strbuf.
Referenced by adbms_periodic().
adbms_read_therms()
void adbms_read_therms (adbms_bms_t * bms)
Read all GPIO/thermistor values (voltage and calculate temperature) and update module/pack statistics.
Updates per-module min/max/avg for thermistor temperatures and aggregated min/max/avg for the full pack.
Parameters
bms Pointer to driver state.
Definition at line 309 of file adbms.c.
References adbms6380_adax(), ADBMS6380_GPIO_COUNT, adbms6380_prepare_command(), adbms6380_read_gpio_voltages(), adbms6380_set_cs_high(), adbms6380_set_cs_low(), ADBMS_ADAX_CH, ADBMS_ADAX_OW, ADBMS_ADAX_PUP, ADBMS_GPIO_R1, ADBMS_GPIO_VIN, ADBMS_MODULE_COUNT, ADBMS_PEC_FAIL_MAX_RETRIES, ADBMS_STATE_IDLE, adbms_bms_t::avg_therm_temp, adbms_module_t::avg_therm_temp, strbuf_t::data, adbms_bms_t::err_gpio_voltage_pecs, adbms_bms_t::err_spi, strbuf_t::length, adbms_bms_t::max_therm_temp, adbms_module_t::max_therm_temp, adbms_bms_t::min_therm_temp, adbms_module_t::min_therm_temp, adbms_bms_t::modules, PHAL_SPI_transfer_noDMA(), adbms_bms_t::rx_buf, adbms_bms_t::spi, adbms_bms_t::state, strbuf_clear(), thermistor_R_to_T(), adbms_module_t::therms_temps, adbms_module_t::therms_voltages, and adbms_bms_t::tx_strbuf.
Referenced by adbms_periodic().
adbms_write_rega()
bool adbms_write_rega (adbms_bms_t * bms)
Calculate and write REGA configuration to all modules.
Parameters
bms Pointer to driver state.
Returns
True on successful SPI transfer, false on failure.
Definition at line 55 of file adbms.c.
References adbms6380_calculate_cfg_rega(), adbms6380_prepare_command(), adbms6380_prepare_data_packet(), adbms6380_set_cs_high(), adbms6380_set_cs_low(), ADBMS_MODULE_COUNT, ADBMS_REGA_CTH, ADBMS_REGA_REFON, strbuf_t::data, adbms_bms_t::err_spi, strbuf_t::length, adbms_bms_t::modules, PHAL_SPI_transfer_noDMA(), adbms_module_t::rega, adbms_bms_t::spi, strbuf_clear(), adbms_bms_t::tx_strbuf, and WRCFGA.
Referenced by adbms_connect().
adbms_write_regb()
bool adbms_write_regb (adbms_bms_t * bms)
Calculate and write REGB configuration to all modules.
Computes REGB with OV/UV thresholds and discharge flags, then writes the configuration to all modules.
Parameters
bms Pointer to driver state.
Returns
True on successful SPI transfer, false on failure.
Definition at line 75 of file adbms.c.
References adbms6380_calculate_cfg_regb(), adbms6380_prepare_command(), adbms6380_prepare_data_packet(), adbms6380_set_cs_high(), adbms6380_set_cs_low(), ADBMS_MODULE_COUNT, ADBMS_REGB_OV_THRESHOLD, ADBMS_REGB_UV_THRESHOLD, strbuf_t::data, adbms_bms_t::err_spi, adbms_module_t::is_discharging, strbuf_t::length, adbms_bms_t::modules, PHAL_SPI_transfer_noDMA(), adbms_module_t::regb, adbms_bms_t::spi, strbuf_clear(), adbms_bms_t::tx_strbuf, and WRCFGB.
Referenced by adbms_balance_and_update_regb(), and adbms_connect().