PER Firmware: common/amk/amk.h File Reference
amk.h File Reference
Modernized AMK driver.
#include "common/can_library/generated/MCAN.h"
#include <stdint.h>
Data Structures
struct AMK_t
Enumerations
enum AMK_motor_state_t : uint8_t {
AMK_STATE_OFF = 0 , AMK_STATE_STARTING = 1 , AMK_STATE_RUNNING = 2 , AMK_STATE_RECOVERING = 3 ,
AMK_STATE_FATAL = 4
}
Functions
void AMK_init (AMK_t *amk, void(*set_func)(void), INVA_SET_data_t *set, INVA_CRIT_data_t *crit, INVA_INFO_data_t *info, INVA_TEMPS_data_t *temps, INVA_ERR_1_data_t *err1, INVA_ERR_2_data_t *err2, bool *precharge_ptr)
void AMK_reset (AMK_t *amk)
void AMK_set_torque (AMK_t *amk, int16_t torque_percent)
void AMK_periodic (AMK_t *amk)
Detailed Description
Modernized AMK driver.
Author
Irving Wang (irvin.nosp@m.gw@p.nosp@m.urdue.nosp@m..edu)
Cole Roberts (rober.nosp@m.638@.nosp@m.purdu.nosp@m.e.ed.nosp@m.u)
Chris McGalliard (cpmcg.nosp@m.alli.nosp@m.ard@g.nosp@m.mail.nosp@m..com)
Definition in file amk.h.
Enumeration Type Documentation
AMK_motor_state_t
enum AMK_motor_state_t : uint8_t
Enumerator
AMK_STATE_OFF
AMK_STATE_STARTING
AMK_STATE_RUNNING
AMK_STATE_RECOVERING
AMK_STATE_FATAL
Definition at line 16 of file amk.h.
Function Documentation
AMK_init()
void AMK_init (AMK_t * amk, void(* set_func)(void), INVA_SET_data_t * set, INVA_CRIT_data_t * crit, INVA_INFO_data_t * info, INVA_TEMPS_data_t * temps, INVA_ERR_1_data_t * err1, INVA_ERR_2_data_t * err2, bool * precharge_ptr)
Definition at line 20 of file amk.c.
References AMK_DEFAULT_NEG_LIMIT, AMK_DEFAULT_POS_LIMIT, AMK_STATE_OFF, AMK_t::crit, AMK_t::err1, AMK_t::err2, AMK_t::info, AMK_t::next_state, AMK_t::precharge_ptr, AMK_t::set, AMK_t::set_function, AMK_t::state, and AMK_t::temps.
Referenced by init_amks().
AMK_periodic()
void AMK_periodic (AMK_t * amk)
Definition at line 81 of file amk.c.
References AMK_CAN_ERR_ID, AMK_DC_BUS_ID, AMK_DEFAULT_NEG_LIMIT, AMK_DEFAULT_POS_LIMIT, AMK_reset(), AMK_STATE_FATAL, AMK_STATE_OFF, AMK_STATE_RECOVERING, AMK_STATE_RUNNING, AMK_STATE_STARTING, AMK_stop(), AMK_t::err1, AMK_t::info, AMK_t::next_state, AMK_t::precharge_ptr, AMK_t::set, AMK_t::set_function, and AMK_t::state.
Referenced by AMK_task().
AMK_reset()
void AMK_reset (AMK_t * amk)
Definition at line 52 of file amk.c.
References AMK_t::set.
Referenced by AMK_periodic().
AMK_set_torque()
void AMK_set_torque (AMK_t * amk, int16_t torque_percent)
Definition at line 58 of file amk.c.
References AMK_STATE_RUNNING, AMK_t::set, and AMK_t::state.
Referenced by fsm_periodic().