PER Firmware: common/amk/amk.c File Reference
amk.c File Reference
Modernized AMK driver.
#include "common/amk/amk.h"
Functions
void AMK_init (AMK_t *amk, void(*set_function)(void), void(*log_function)(void), INVA_SET_data_t *set, INVA_CRIT_data_t *crit, INVA_INFO_data_t *info, INVA_TEMPS_data_t *temps, INVA_ERR_1_data_t *err1, INVA_ERR_2_data_t *err2, bool *precharge_ptr)
void AMK_reset (AMK_t *amk)
void AMK_set_torque (AMK_t *amk, int16_t torque_percent)
static void AMK_stop (AMK_t *amk)
void AMK_periodic (AMK_t *amk)
Variables
static constexpr uint32_t AMK_CAN_ERR_ID = 3587U
static constexpr uint32_t AMK_DC_BUS_ID = 1049U
static constexpr int16_t AMK_DEFAULT_POS_LIMIT = 2140
static constexpr int16_t AMK_DEFAULT_NEG_LIMIT = -1
Detailed Description
Modernized AMK driver.
Author
Irving Wang (irvin.nosp@m.gw@p.nosp@m.urdue.nosp@m..edu)
Cole Roberts (rober.nosp@m.638@.nosp@m.purdu.nosp@m.e.ed.nosp@m.u)
Chris McGalliard (cpmcg.nosp@m.alli.nosp@m.ard@g.nosp@m.mail.nosp@m..com)
Definition in file amk.c.
Function Documentation
AMK_init()
void AMK_init (AMK_t * amk, void(* set_function)(void), void(* log_function)(void), INVA_SET_data_t * set, INVA_CRIT_data_t * crit, INVA_INFO_data_t * info, INVA_TEMPS_data_t * temps, INVA_ERR_1_data_t * err1, INVA_ERR_2_data_t * err2, bool * precharge_ptr)
Definition at line 20 of file amk.c.
References AMK_DEFAULT_NEG_LIMIT, AMK_DEFAULT_POS_LIMIT, AMK_STATE_OFF, AMK_t::crit, AMK_t::err1, AMK_t::err2, AMK_t::info, AMK_t::log_function, AMK_t::next_state, AMK_t::precharge_ptr, AMK_t::set, AMK_t::set_function, AMK_t::state, and AMK_t::temps.
Referenced by main().
AMK_periodic()
void AMK_periodic (AMK_t * amk)
Definition at line 79 of file amk.c.
References AMK_CAN_ERR_ID, AMK_DC_BUS_ID, AMK_DEFAULT_NEG_LIMIT, AMK_DEFAULT_POS_LIMIT, AMK_reset(), AMK_STATE_INIT, AMK_STATE_OFF, AMK_STATE_RUNNING, AMK_stop(), AMK_t::err1, AMK_t::info, AMK_t::log_function, AMK_t::next_state, AMK_t::precharge_ptr, AMK_t::set, AMK_t::set_function, and AMK_t::state.
Referenced by amk_test_thread().
AMK_reset()
void AMK_reset (AMK_t * amk)
Definition at line 54 of file amk.c.
References AMK_t::set.
Referenced by AMK_periodic().
AMK_set_torque()
void AMK_set_torque (AMK_t * amk, int16_t torque_percent)
Definition at line 60 of file amk.c.
References AMK_t::set.
Referenced by amk_test_thread().
AMK_stop()
static void AMK_stop (AMK_t * amk) static
Definition at line 70 of file amk.c.
References AMK_DEFAULT_NEG_LIMIT, and AMK_t::set.
Referenced by AMK_periodic().
Variable Documentation
AMK_CAN_ERR_ID
uint32_t AMK_CAN_ERR_ID = 3587U static constexpr
Definition at line 13 of file amk.c.
Referenced by AMK_periodic().
AMK_DC_BUS_ID
uint32_t AMK_DC_BUS_ID = 1049U static constexpr
Definition at line 14 of file amk.c.
Referenced by AMK_periodic().
AMK_DEFAULT_NEG_LIMIT
int16_t AMK_DEFAULT_NEG_LIMIT = -1 static constexpr
Definition at line 18 of file amk.c.
Referenced by AMK_init(), AMK_periodic(), and AMK_stop().
AMK_DEFAULT_POS_LIMIT
int16_t AMK_DEFAULT_POS_LIMIT = 2140 static constexpr
Definition at line 17 of file amk.c.
Referenced by AMK_init(), and AMK_periodic().