var annotated_dup =
[
    [ "codegen", "namespacecodegen.html", [
      [ "BxcanFilterBankContext", "classcodegen_1_1BxcanFilterBankContext.html", null ],
      [ "BxcanFilterContext", "classcodegen_1_1BxcanFilterContext.html", "classcodegen_1_1BxcanFilterContext" ],
      [ "FdcanFilterContext", "classcodegen_1_1FdcanFilterContext.html", "classcodegen_1_1FdcanFilterContext" ],
      [ "FilterRenderContext", "classcodegen_1_1FilterRenderContext.html", "classcodegen_1_1FilterRenderContext" ],
      [ "NodeRenderContext", "classcodegen_1_1NodeRenderContext.html", "classcodegen_1_1NodeRenderContext" ],
      [ "PeripheralContext", "classcodegen_1_1PeripheralContext.html", null ],
      [ "RxEntry", "classcodegen_1_1RxEntry.html", "classcodegen_1_1RxEntry" ],
      [ "RxPeripheralContext", "classcodegen_1_1RxPeripheralContext.html", "classcodegen_1_1RxPeripheralContext" ],
      [ "ScalingMessage", "classcodegen_1_1ScalingMessage.html", "classcodegen_1_1ScalingMessage" ],
      [ "SignalCodec", "classcodegen_1_1SignalCodec.html", "classcodegen_1_1SignalCodec" ],
      [ "TxEntry", "classcodegen_1_1TxEntry.html", "classcodegen_1_1TxEntry" ],
      [ "TypeRenderContext", "classcodegen_1_1TypeRenderContext.html", "classcodegen_1_1TypeRenderContext" ]
    ] ],
    [ "linker", "namespacelinker.html", [
      [ "BusLinker", "classlinker_1_1BusLinker.html", "classlinker_1_1BusLinker" ]
    ] ],
    [ "mapper", "namespacemapper.html", [
      [ "FDCANFilters", "classmapper_1_1FDCANFilters.html", "classmapper_1_1FDCANFilters" ],
      [ "FilterBank", "classmapper_1_1FilterBank.html", "classmapper_1_1FilterBank" ],
      [ "NodeMapping", "classmapper_1_1NodeMapping.html", "classmapper_1_1NodeMapping" ]
    ] ],
    [ "parser", "namespaceparser.html", [
      [ "Bus", "classparser_1_1Bus.html", "classparser_1_1Bus" ],
      [ "BusView", "classparser_1_1BusView.html", "classparser_1_1BusView" ],
      [ "Fault", "classparser_1_1Fault.html", "classparser_1_1Fault" ],
      [ "FaultModule", "classparser_1_1FaultModule.html", "classparser_1_1FaultModule" ],
      [ "Message", "classparser_1_1Message.html", "classparser_1_1Message" ],
      [ "Node", "classparser_1_1Node.html", "classparser_1_1Node" ],
      [ "RxMessage", "classparser_1_1RxMessage.html", "classparser_1_1RxMessage" ],
      [ "Signal", "classparser_1_1Signal.html", "classparser_1_1Signal" ],
      [ "SystemContext", "classparser_1_1SystemContext.html", "classparser_1_1SystemContext" ]
    ] ],
    [ "utils", "namespaceutils.html", [
      [ "bcolors", "classutils_1_1bcolors.html", "classutils_1_1bcolors" ]
    ] ],
    [ "__attribute__", "struct____attribute____.html", "struct____attribute____" ],
    [ "adbms_bms_t", "structadbms__bms__t.html", "structadbms__bms__t" ],
    [ "adbms_module_t", "structadbms__module__t.html", "structadbms__module__t" ],
    [ "adc1_dma_buffer_t", "structadc1__dma__buffer__t.html", "structadc1__dma__buffer__t" ],
    [ "ADCChannelConfig_t", "structADCChannelConfig__t.html", "structADCChannelConfig__t" ],
    [ "ADCInitConfig_t", "structADCInitConfig__t.html", "structADCInitConfig__t" ],
    [ "AMK_config_t", "structAMK__config__t.html", "structAMK__config__t" ],
    [ "AMK_objects_t", "structAMK__objects__t.html", "structAMK__objects__t" ],
    [ "AMK_t", "structAMK__t.html", "structAMK__t" ],
    [ "bangbang_t", "structbangbang__t.html", "structbangbang__t" ],
    [ "bar_t", "structbar__t.html", "structbar__t" ],
    [ "BMI088_Handle_t", "structBMI088__Handle__t.html", "structBMI088__Handle__t" ],
    [ "can_stats_t", "structcan__stats__t.html", "structcan__stats__t" ],
    [ "CanMsgTypeDef_t", "structCanMsgTypeDef__t.html", "structCanMsgTypeDef__t" ],
    [ "car_t", "structcar__t.html", "structcar__t" ],
    [ "celsius_t", "structcelsius__t.html", "structcelsius__t" ],
    [ "centimeters_t", "structcentimeters__t.html", "structcentimeters__t" ],
    [ "ClockRateConfig_t", "structClockRateConfig__t.html", "structClockRateConfig__t" ],
    [ "days_t", "structdays__t.html", "structdays__t" ],
    [ "degrees_t", "structdegrees__t.html", "structdegrees__t" ],
    [ "dma_init_t", "structdma__init__t.html", "structdma__init__t" ],
    [ "ethernet_config_t", "structethernet__config__t.html", "structethernet__config__t" ],
    [ "euler_angles_t", "structeuler__angles__t.html", "structeuler__angles__t" ],
    [ "fahrenheit_t", "structfahrenheit__t.html", "structfahrenheit__t" ],
    [ "fault_t", "structfault__t.html", "structfault__t" ],
    [ "feet_t", "structfeet__t.html", "structfeet__t" ],
    [ "flash_operation_context_t", "structflash__operation__context__t.html", "structflash__operation__context__t" ],
    [ "FREERTOS_periodic_task_params_t", "structFREERTOS__periodic__task__params__t.html", "structFREERTOS__periodic__task__params__t" ],
    [ "FREERTOS_queue_params_t", "structFREERTOS__queue__params__t.html", "structFREERTOS__queue__params__t" ],
    [ "GPIOInitConfig_t", "structGPIOInitConfig__t.html", "structGPIOInitConfig__t" ],
    [ "grams_t", "structgrams__t.html", "structgrams__t" ],
    [ "hours_t", "structhours__t.html", "structhours__t" ],
    [ "IMU_data_t", "structIMU__data__t.html", "structIMU__data__t" ],
    [ "imu_data_t", "structimu__data__t.html", "structimu__data__t" ],
    [ "inches_t", "structinches__t.html", "structinches__t" ],
    [ "kilograms_t", "structkilograms__t.html", "structkilograms__t" ],
    [ "kph_t", "structkph__t.html", "structkph__t" ],
    [ "lerp_lut_t", "structlerp__lut__t.html", "structlerp__lut__t" ],
    [ "lut_entry_t", "structlut__entry__t.html", "structlut__entry__t" ],
    [ "matrix3x3_t", "structmatrix3x3__t.html", "structmatrix3x3__t" ],
    [ "menu_element_t", "structmenu__element__t.html", "structmenu__element__t" ],
    [ "menu_page_t", "structmenu__page__t.html", "structmenu__page__t" ],
    [ "meters_t", "structmeters__t.html", "structmeters__t" ],
    [ "miles_t", "structmiles__t.html", "structmiles__t" ],
    [ "millimeters_t", "structmillimeters__t.html", "structmillimeters__t" ],
    [ "milliseconds_t", "structmilliseconds__t.html", "structmilliseconds__t" ],
    [ "minutes_t", "structminutes__t.html", "structminutes__t" ],
    [ "mph_t", "structmph__t.html", "structmph__t" ],
    [ "mps_t", "structmps__t.html", "structmps__t" ],
    [ "NAV_PVT_data_t", "structNAV__PVT__data__t.html", "structNAV__PVT__data__t" ],
    [ "NAV_RELPOSNED_data_t", "structNAV__RELPOSNED__data__t.html", "structNAV__RELPOSNED__data__t" ],
    [ "page_handler_t", "structpage__handler__t.html", "structpage__handler__t" ],
    [ "pascals_t", "structpascals__t.html", "structpascals__t" ],
    [ "pdu_rail_fault_map_t", "structpdu__rail__fault__map__t.html", "structpdu__rail__fault__map__t" ],
    [ "pdu_rail_voltage_mv_t", "structpdu__rail__voltage__mv__t.html", "structpdu__rail__voltage__mv__t" ],
    [ "pdu_state_t", "structpdu__state__t.html", "structpdu__state__t" ],
    [ "pdu_switch_output_t", "structpdu__switch__output__t.html", "structpdu__switch__output__t" ],
    [ "PHAL_SD_Cmd_t", "structPHAL__SD__Cmd__t.html", "structPHAL__SD__Cmd__t" ],
    [ "PHAL_USB_Event_t", "structPHAL__USB__Event__t.html", "structPHAL__USB__Event__t" ],
    [ "PHAL_USB_TransferEvent_t", "structPHAL__USB__TransferEvent__t.html", "structPHAL__USB__TransferEvent__t" ],
    [ "pounds_t", "structpounds__t.html", "structpounds__t" ],
    [ "powertrain_t", "structpowertrain__t.html", "structpowertrain__t" ],
    [ "psi_t", "structpsi__t.html", "structpsi__t" ],
    [ "pVCU_struct", "structpVCU__struct.html", "structpVCU__struct" ],
    [ "radians_t", "structradians__t.html", "structradians__t" ],
    [ "raw_adc1_values_t", "structraw__adc1__values__t.html", "structraw__adc1__values__t" ],
    [ "raw_adc2_values_t", "structraw__adc2__values__t.html", "structraw__adc2__values__t" ],
    [ "raw_adc3_values_t", "structraw__adc3__values__t.html", "structraw__adc3__values__t" ],
    [ "raw_adc4_values_t", "structraw__adc4__values__t.html", "structraw__adc4__values__t" ],
    [ "raw_adc_values_t", "structraw__adc__values__t.html", "structraw__adc__values__t" ],
    [ "RTC_date_t", "structRTC__date__t.html", "structRTC__date__t" ],
    [ "RTC_time_t", "structRTC__time__t.html", "structRTC__time__t" ],
    [ "RTC_timestamp_t", "structRTC__timestamp__t.html", "structRTC__timestamp__t" ],
    [ "SD_CardInfo", "structSD__CardInfo.html", "structSD__CardInfo" ],
    [ "SD_CID", "structSD__CID.html", "structSD__CID" ],
    [ "SD_CSD", "structSD__CSD.html", "structSD__CSD" ],
    [ "sdc_node_t", "structsdc__node__t.html", "structsdc__node__t" ],
    [ "seconds_t", "structseconds__t.html", "structseconds__t" ],
    [ "SPI_InitConfig_t", "structSPI__InitConfig__t.html", "structSPI__InitConfig__t" ],
    [ "SPMC_t", "structSPMC__t.html", "structSPMC__t" ],
    [ "status_leds_t", "structstatus__leds__t.html", "structstatus__leds__t" ],
    [ "strbuf_t", "structstrbuf__t.html", "structstrbuf__t" ],
    [ "timestamped_frame_t", "structtimestamped__frame__t.html", "structtimestamped__frame__t" ],
    [ "torque_request_t", "structtorque__request__t.html", "structtorque__request__t" ],
    [ "usart_active_transfer_t", "structusart__active__transfer__t.html", "structusart__active__transfer__t" ],
    [ "usart_init_t", "structusart__init__t.html", "structusart__init__t" ],
    [ "usart_rx_errors_t", "structusart__rx__errors__t.html", "structusart__rx__errors__t" ],
    [ "usart_tx_errors_t", "structusart__tx__errors__t.html", "structusart__tx__errors__t" ],
    [ "vector3_t", "structvector3__t.html", "structvector3__t" ],
    [ "xVCU_struct", "structxVCU__struct.html", "structxVCU__struct" ],
    [ "yVCU_struct", "structyVCU__struct.html", "structyVCU__struct" ]
];