var annotated_dup =
[
    [ "bootloader_commands", "namespacebootloader__commands.html", [
      [ "BootloaderCommand", "classbootloader__commands_1_1BootloaderCommand.html", "classbootloader__commands_1_1BootloaderCommand" ]
    ] ],
    [ "bootloader_download", "namespacebootloader__download.html", [
      [ "Bootloader", "classbootloader__download_1_1Bootloader.html", "classbootloader__download_1_1Bootloader" ],
      [ "CANRxThread", "classbootloader__download_1_1CANRxThread.html", "classbootloader__download_1_1CANRxThread" ]
    ] ],
    [ "can_process", "namespacecan__process.html", [
      [ "CANRxThread", "classcan__process_1_1CANRxThread.html", "classcan__process_1_1CANRxThread" ],
      [ "CANTxThread", "classcan__process_1_1CANTxThread.html", "classcan__process_1_1CANTxThread" ]
    ] ],
    [ "linker", "namespacelinker.html", [
      [ "BusLinker", "classlinker_1_1BusLinker.html", "classlinker_1_1BusLinker" ]
    ] ],
    [ "mapper", "namespacemapper.html", [
      [ "FDCANFilters", "classmapper_1_1FDCANFilters.html", "classmapper_1_1FDCANFilters" ],
      [ "FilterBank", "classmapper_1_1FilterBank.html", "classmapper_1_1FilterBank" ],
      [ "NodeMapping", "classmapper_1_1NodeMapping.html", "classmapper_1_1NodeMapping" ]
    ] ],
    [ "parser", "namespaceparser.html", [
      [ "Bus", "classparser_1_1Bus.html", "classparser_1_1Bus" ],
      [ "BusView", "classparser_1_1BusView.html", "classparser_1_1BusView" ],
      [ "Fault", "classparser_1_1Fault.html", "classparser_1_1Fault" ],
      [ "FaultModule", "classparser_1_1FaultModule.html", "classparser_1_1FaultModule" ],
      [ "Message", "classparser_1_1Message.html", "classparser_1_1Message" ],
      [ "Node", "classparser_1_1Node.html", "classparser_1_1Node" ],
      [ "RxMessage", "classparser_1_1RxMessage.html", "classparser_1_1RxMessage" ],
      [ "Signal", "classparser_1_1Signal.html", "classparser_1_1Signal" ],
      [ "SystemContext", "classparser_1_1SystemContext.html", "classparser_1_1SystemContext" ]
    ] ],
    [ "utils", "namespaceutils.html", [
      [ "bcolors", "classutils_1_1bcolors.html", "classutils_1_1bcolors" ]
    ] ],
    [ "_WIZCHIP", "struct__WIZCHIP.html", "struct__WIZCHIP" ],
    [ "adbms_bms_t", "structadbms__bms__t.html", "structadbms__bms__t" ],
    [ "adbms_module_t", "structadbms__module__t.html", "structadbms__module__t" ],
    [ "ADCChannelConfig_t", "structADCChannelConfig__t.html", "structADCChannelConfig__t" ],
    [ "ADCInitConfig_t", "structADCInitConfig__t.html", "structADCInitConfig__t" ],
    [ "ADCReadings_t", "structADCReadings__t.html", "structADCReadings__t" ],
    [ "adv_feature_t", "structadv__feature__t.html", "structadv__feature__t" ],
    [ "AMK_t", "structAMK__t.html", "structAMK__t" ],
    [ "auto_switches_t", "structauto__switches__t.html", "structauto__switches__t" ],
    [ "bangbang_t", "structbangbang__t.html", "structbangbang__t" ],
    [ "BMI088_Handle_t", "structBMI088__Handle__t.html", "structBMI088__Handle__t" ],
    [ "BootlaoderSharedMemory_t", "structBootlaoderSharedMemory__t.html", "structBootlaoderSharedMemory__t" ],
    [ "can_peripheral_stats_t", "structcan__peripheral__stats__t.html", "structcan__peripheral__stats__t" ],
    [ "can_stats_t", "structcan__stats__t.html", "structcan__stats__t" ],
    [ "CanMsgTypeDef_t", "structCanMsgTypeDef__t.html", "structCanMsgTypeDef__t" ],
    [ "car_t", "structcar__t.html", "structcar__t" ],
    [ "ClockRateConfig_t", "structClockRateConfig__t.html", "structClockRateConfig__t" ],
    [ "config_t", "structconfig__t.html", "structconfig__t" ],
    [ "cooling_request_t", "structcooling__request__t.html", "structcooling__request__t" ],
    [ "cpu_time_t", "structcpu__time__t.html", "structcpu__time__t" ],
    [ "daq_hub_t", "structdaq__hub__t.html", "structdaq__hub__t" ],
    [ "daq_rx_frame_reader_t", "structdaq__rx__frame__reader__t.html", "structdaq__rx__frame__reader__t" ],
    [ "daq_tx_frame_writer_t", "structdaq__tx__frame__writer__t.html", "structdaq__tx__frame__writer__t" ],
    [ "daq_variable_t", "structdaq__variable__t.html", "structdaq__variable__t" ],
    [ "dashboard_input_state_t", "structdashboard__input__state__t.html", "structdashboard__input__state__t" ],
    [ "DIR", "structDIR.html", "structDIR" ],
    [ "dma_init_t", "structdma__init__t.html", "structdma__init__t" ],
    [ "driver_pedal_profile_t", "structdriver__pedal__profile__t.html", "structdriver__pedal__profile__t" ],
    [ "eeprom", "structeeprom.html", "structeeprom" ],
    [ "eth_config_t", "structeth__config__t.html", "structeth__config__t" ],
    [ "FATFS", "structFATFS.html", "structFATFS" ],
    [ "fault_t", "structfault__t.html", "structfault__t" ],
    [ "FFOBJID", "structFFOBJID.html", "structFFOBJID" ],
    [ "FIL", "structFIL.html", "structFIL" ],
    [ "FILINFO", "structFILINFO.html", "structFILINFO" ],
    [ "FloatConvert_t", "unionFloatConvert__t.html", "unionFloatConvert__t" ],
    [ "GPIOInitConfig_t", "structGPIOInitConfig__t.html", "structGPIOInitConfig__t" ],
    [ "GPS_Handle_t", "structGPS__Handle__t.html", "structGPS__Handle__t" ],
    [ "i2c_handle_t", "structi2c__handle__t.html", "structi2c__handle__t" ],
    [ "IMU_data_t", "structIMU__data__t.html", "structIMU__data__t" ],
    [ "lerp_lut_t", "structlerp__lut__t.html", "structlerp__lut__t" ],
    [ "lut_entry_t", "structlut__entry__t.html", "structlut__entry__t" ],
    [ "menu_element_t", "structmenu__element__t.html", "structmenu__element__t" ],
    [ "menu_page_t", "structmenu__page__t.html", "structmenu__page__t" ],
    [ "MKFS_PARM", "structMKFS__PARM.html", "structMKFS__PARM" ],
    [ "NAV_PVT_t", "structNAV__PVT__t.html", "structNAV__PVT__t" ],
    [ "page_handler_t", "structpage__handler__t.html", "structpage__handler__t" ],
    [ "pedal_calibration_t", "structpedal__calibration__t.html", "structpedal__calibration__t" ],
    [ "pedal_faults_t", "structpedal__faults__t.html", "structpedal__faults__t" ],
    [ "pedal_values_t", "structpedal__values__t.html", "structpedal__values__t" ],
    [ "PHAL_SD_Cmd_t", "structPHAL__SD__Cmd__t.html", "structPHAL__SD__Cmd__t" ],
    [ "phys_mem", "structphys__mem.html", "structphys__mem" ],
    [ "q_handle_t", "structq__handle__t.html", "structq__handle__t" ],
    [ "QUADSPI_Config_t", "structQUADSPI__Config__t.html", "structQUADSPI__Config__t" ],
    [ "raw_adc_values_t", "structraw__adc__values__t.html", "structraw__adc__values__t" ],
    [ "RTC_date_t", "structRTC__date__t.html", "structRTC__date__t" ],
    [ "RTC_time_t", "structRTC__time__t.html", "structRTC__time__t" ],
    [ "RTC_timestamp_t", "structRTC__timestamp__t.html", "structRTC__timestamp__t" ],
    [ "sched_t", "structsched__t.html", "structsched__t" ],
    [ "SD_CardInfo", "structSD__CardInfo.html", "structSD__CardInfo" ],
    [ "SD_CID", "structSD__CID.html", "structSD__CID" ],
    [ "SD_CSD", "structSD__CSD.html", "structSD__CSD" ],
    [ "sdc_node_t", "structsdc__node__t.html", "structsdc__node__t" ],
    [ "SPI_InitConfig_t", "structSPI__InitConfig__t.html", "structSPI__InitConfig__t" ],
    [ "SPMC_t", "structSPMC__t.html", "structSPMC__t" ],
    [ "strbuf_t", "structstrbuf__t.html", "structstrbuf__t" ],
    [ "ThreadWrapper_t", "structThreadWrapper__t.html", "structThreadWrapper__t" ],
    [ "timestamped_frame_t", "structtimestamped__frame__t.html", "structtimestamped__frame__t" ],
    [ "torque_request_t", "structtorque__request__t.html", "structtorque__request__t" ],
    [ "usart_active_transfer_t", "structusart__active__transfer__t.html", "structusart__active__transfer__t" ],
    [ "usart_init_t", "structusart__init__t.html", "structusart__init__t" ],
    [ "usart_rx_buf_t", "structusart__rx__buf__t.html", "structusart__rx__buf__t" ],
    [ "usart_rx_errors_t", "structusart__rx__errors__t.html", "structusart__rx__errors__t" ],
    [ "usart_tx_errors_t", "structusart__tx__errors__t.html", "structusart__tx__errors__t" ],
    [ "voltage_t", "structvoltage__t.html", "structvoltage__t" ],
    [ "wiz_NetInfo", "structwiz__NetInfo.html", "structwiz__NetInfo" ],
    [ "wiz_NetTimeout", "structwiz__NetTimeout.html", "structwiz__NetTimeout" ],
    [ "wiz_PhyConf", "structwiz__PhyConf.html", "structwiz__PhyConf" ]
];