var annotated_dup =
[
    [ "linker", "namespacelinker.html", [
      [ "BusLinker", "classlinker_1_1BusLinker.html", "classlinker_1_1BusLinker" ]
    ] ],
    [ "mapper", "namespacemapper.html", [
      [ "FDCANFilters", "classmapper_1_1FDCANFilters.html", null ],
      [ "FilterBank", "classmapper_1_1FilterBank.html", null ],
      [ "NodeMapping", "classmapper_1_1NodeMapping.html", null ]
    ] ],
    [ "parser", "namespaceparser.html", [
      [ "Bus", "classparser_1_1Bus.html", null ],
      [ "BusView", "classparser_1_1BusView.html", null ],
      [ "Fault", "classparser_1_1Fault.html", null ],
      [ "FaultModule", "classparser_1_1FaultModule.html", null ],
      [ "Message", "classparser_1_1Message.html", "classparser_1_1Message" ],
      [ "Node", "classparser_1_1Node.html", "classparser_1_1Node" ],
      [ "RxMessage", "classparser_1_1RxMessage.html", null ],
      [ "Signal", "classparser_1_1Signal.html", null ],
      [ "SystemContext", "classparser_1_1SystemContext.html", null ]
    ] ],
    [ "utils", "namespaceutils.html", [
      [ "bcolors", "classutils_1_1bcolors.html", null ]
    ] ],
    [ "__attribute__", "struct____attribute____.html", null ],
    [ "adbms_bms_t", "structadbms__bms__t.html", "structadbms__bms__t" ],
    [ "adbms_module_t", "structadbms__module__t.html", "structadbms__module__t" ],
    [ "adc1_dma_buffer_t", "structadc1__dma__buffer__t.html", null ],
    [ "ADCChannelConfig_t", "structADCChannelConfig__t.html", null ],
    [ "ADCInitConfig_t", "structADCInitConfig__t.html", null ],
    [ "AMK_t", "structAMK__t.html", null ],
    [ "auto_switches_t", "structauto__switches__t.html", null ],
    [ "bangbang_t", "structbangbang__t.html", null ],
    [ "BMI088_Handle_t", "structBMI088__Handle__t.html", null ],
    [ "can_peripheral_stats_t", "structcan__peripheral__stats__t.html", null ],
    [ "can_stats_t", "structcan__stats__t.html", null ],
    [ "CanMsgTypeDef_t", "structCanMsgTypeDef__t.html", "structCanMsgTypeDef__t" ],
    [ "car_t", "structcar__t.html", null ],
    [ "ClockRateConfig_t", "structClockRateConfig__t.html", null ],
    [ "cooling_request_t", "structcooling__request__t.html", null ],
    [ "daq_hub_t", "structdaq__hub__t.html", "structdaq__hub__t" ],
    [ "dashboard_input_state_t", "structdashboard__input__state__t.html", null ],
    [ "dma_init_t", "structdma__init__t.html", null ],
    [ "ethernet_config_t", "structethernet__config__t.html", null ],
    [ "fault_t", "structfault__t.html", null ],
    [ "GPIOInitConfig_t", "structGPIOInitConfig__t.html", null ],
    [ "GPS_Handle_t", "structGPS__Handle__t.html", null ],
    [ "IMU_data_t", "structIMU__data__t.html", null ],
    [ "lerp_lut_t", "structlerp__lut__t.html", null ],
    [ "lut_entry_t", "structlut__entry__t.html", null ],
    [ "menu_element_t", "structmenu__element__t.html", null ],
    [ "menu_page_t", "structmenu__page__t.html", null ],
    [ "NAV_PVT_t", "structNAV__PVT__t.html", null ],
    [ "page_handler_t", "structpage__handler__t.html", null ],
    [ "pedal_values_t", "structpedal__values__t.html", null ],
    [ "periodic_task_params_t", "structperiodic__task__params__t.html", null ],
    [ "PHAL_SD_Cmd_t", "structPHAL__SD__Cmd__t.html", "structPHAL__SD__Cmd__t" ],
    [ "raw_adc1_values_t", "structraw__adc1__values__t.html", null ],
    [ "raw_adc2_values_t", "structraw__adc2__values__t.html", null ],
    [ "raw_adc3_values_t", "structraw__adc3__values__t.html", null ],
    [ "raw_adc4_values_t", "structraw__adc4__values__t.html", null ],
    [ "RTC_date_t", "structRTC__date__t.html", null ],
    [ "RTC_time_t", "structRTC__time__t.html", null ],
    [ "RTC_timestamp_t", "structRTC__timestamp__t.html", null ],
    [ "SD_CardInfo", "structSD__CardInfo.html", "structSD__CardInfo" ],
    [ "SD_CID", "structSD__CID.html", "structSD__CID" ],
    [ "SD_CSD", "structSD__CSD.html", "structSD__CSD" ],
    [ "sdc_node_t", "structsdc__node__t.html", null ],
    [ "SPI_InitConfig_t", "structSPI__InitConfig__t.html", "structSPI__InitConfig__t" ],
    [ "SPMC_t", "structSPMC__t.html", null ],
    [ "status_leds_t", "structstatus__leds__t.html", null ],
    [ "strbuf_t", "structstrbuf__t.html", null ],
    [ "timestamped_frame_t", "structtimestamped__frame__t.html", null ],
    [ "torque_request_t", "structtorque__request__t.html", null ],
    [ "usart_active_transfer_t", "structusart__active__transfer__t.html", "structusart__active__transfer__t" ],
    [ "usart_init_t", "structusart__init__t.html", "structusart__init__t" ],
    [ "usart_rx_errors_t", "structusart__rx__errors__t.html", "structusart__rx__errors__t" ],
    [ "usart_tx_errors_t", "structusart__tx__errors__t.html", "structusart__tx__errors__t" ],
    [ "voltage_t", "structvoltage__t.html", null ]
];