PER Firmware: source/pdu/auto_switch/auto_switch.h File Reference
auto_switch.h File Reference
#include <source/pdu/main.h>
#include <stdbool.h>
#include <stdint.h>
Data Structures
struct voltage_t
struct auto_switches_t
Macros
#define SHUNT_R 10000000
#define ADC_MAX 4095
#define LV_24V_R1 47000
#define LV_24V_R2 3400
#define LV_5V_R1 4300
#define LV_5V_R2 3400
#define LV_3V3_R1 4300
#define LV_3V3_R2 10000
#define AMK_24V_R1 124300
#define AMK_24V_R2 10000
#define HP_CS_R1 180
#define HP_CS_R2 330
#define HP_CS_R3 500
#define HP_CS_R_SENSE 0.002
#define CS_GAIN 100
Enumerations
enum switches_t {
SW_PUMP_1 , SW_PUMP_2 , SW_SDC , SW_AUX ,
SW_FAN_1 , SW_FAN_2 , SW_DASH , SW_ABOX ,
SW_MAIN , CS_24V , CS_5V , CS_SWITCH_COUNT ,
SW_BLT , SW_CRIT_5V , SW_NCRIT_5V , SW_DAQ ,
SW_FAN_5V
}
Functions
void setSwitch (switches_t auto_switch_enum, bool state)
Enable or disable a switch.
bool getSwitchStatus (switches_t auto_switch_enum)
Check if a switch is enabled.
void autoSwitchPeriodic ()
Combined function that calls updateVoltage() and updateCurrent()
void checkSwitchFaults ()
Checks the status of various auto switches to ensure rails are ok. Sets fault and activates blink indicator if not..
Variables
auto_switches_t auto_switches
Detailed Description
Author
Gavin Zyonse (gzyon.nosp@m.se@p.nosp@m.urdue.nosp@m..edu)
Version
1.0
Date
2023-11-09
Copyright
Copyright (c) 2023
Definition in file auto_switch.h.
Macro Definition Documentation
ADC_MAX
#define ADC_MAX 4095
Definition at line 20 of file auto_switch.h.
Referenced by calcCurrent_HP(), calcCurrent_LP(), calcCurrent_Total(), and calcVoltage().
AMK_24V_R1
#define AMK_24V_R1 124300
Definition at line 29 of file auto_switch.h.
Referenced by updateVoltage().
AMK_24V_R2
#define AMK_24V_R2 10000
Definition at line 30 of file auto_switch.h.
Referenced by updateVoltage().
CS_GAIN
#define CS_GAIN 100
Definition at line 39 of file auto_switch.h.
Referenced by calcCurrent_Total().
HP_CS_R1
#define HP_CS_R1 180
Definition at line 33 of file auto_switch.h.
Referenced by calcCurrent_HP().
HP_CS_R2
#define HP_CS_R2 330
Definition at line 34 of file auto_switch.h.
Referenced by calcCurrent_HP().
HP_CS_R3
#define HP_CS_R3 500
Definition at line 35 of file auto_switch.h.
Referenced by calcCurrent_HP().
HP_CS_R_SENSE
#define HP_CS_R_SENSE 0.002
Definition at line 38 of file auto_switch.h.
Referenced by calcCurrent_Total().
LV_24V_R1
#define LV_24V_R1 47000
Definition at line 23 of file auto_switch.h.
Referenced by updateVoltage().
LV_24V_R2
#define LV_24V_R2 3400
Definition at line 24 of file auto_switch.h.
Referenced by updateVoltage().
LV_3V3_R1
#define LV_3V3_R1 4300
Definition at line 27 of file auto_switch.h.
Referenced by updateVoltage().
LV_3V3_R2
#define LV_3V3_R2 10000
Definition at line 28 of file auto_switch.h.
Referenced by updateVoltage().
LV_5V_R1
#define LV_5V_R1 4300
Definition at line 25 of file auto_switch.h.
Referenced by updateVoltage().
LV_5V_R2
#define LV_5V_R2 3400
Definition at line 26 of file auto_switch.h.
Referenced by updateVoltage().
SHUNT_R
#define SHUNT_R 10000000
Definition at line 19 of file auto_switch.h.
Enumeration Type Documentation
switches_t
enum switches_t
Enumerator
SW_PUMP_1
SW_PUMP_2
SW_SDC
SW_AUX
SW_FAN_1
SW_FAN_2
SW_DASH
SW_ABOX
SW_MAIN
CS_24V
CS_5V
CS_SWITCH_COUNT
SW_BLT
SW_CRIT_5V
SW_NCRIT_5V
SW_DAQ
SW_FAN_5V
Definition at line 42 of file auto_switch.h.
Function Documentation
autoSwitchPeriodic()
void autoSwitchPeriodic ()
Combined function that calls updateVoltage() and updateCurrent()
Voltage on each rail is stored at: auto_switches.voltage.in_24v auto_switches.voltage.out_5v auto_switches.voltage.out_3v3
Current through each switch is stored at: auto_switches.current[auto_switch_enum]
Definition at line 188 of file auto_switch.c.
References updateCurrent(), and updateVoltage().
Referenced by main().
checkSwitchFaults()
void checkSwitchFaults ()
Checks the status of various auto switches to ensure rails are ok. Sets fault and activates blink indicator if not..
Definition at line 193 of file auto_switch.c.
References ABOX_NFLT_GPIO_Port, ABOX_NFLT_Pin, BLT_NFLT_GPIO_Port, BLT_NFLT_Pin, CRIT_5V_NFLT_GPIO_Port, CRIT_5V_NFLT_Pin, DAQ_NFLT_GPIO_Port, DAQ_NFLT_Pin, DASH_NFLT_GPIO_Port, DASH_NFLT_Pin, FAN_1_NFLT_GPIO_Port, FAN_1_NFLT_Pin, FAN_2_NFLT_GPIO_Port, FAN_2_NFLT_Pin, LED_5V_CRIT, LED_5V_NCRIT, LED_ABOX, LED_BLINK, LED_BLT, LED_control(), LED_DAQ, LED_DASH, LED_FAN_1, LED_FAN_2, LED_MAIN, main(), MAIN_NFLT_GPIO_Port, MAIN_NFLT_Pin, NCRIT_5V_NFLT_GPIO_Port, NCRIT_5V_NFLT_Pin, PHAL_readGPIO(), and update_fault().
Referenced by main().
getSwitchStatus()
bool getSwitchStatus (switches_t auto_switch_enum)
Check if a switch is enabled.
Parameters
auto_switch_enum Switch to check
Returns
1 if enabled, 0 if disabled
Definition at line 151 of file auto_switch.c.
References AUX_HP_CTRL_GPIO_Port, AUX_HP_CTRL_Pin, BLT_CTRL_GPIO_Port, BLT_CTRL_Pin, CRIT_5V_CTRL_GPIO_Port, CRIT_5V_CTRL_Pin, FAN_1_CTRL_GPIO_Port, FAN_1_CTRL_Pin, FAN_2_CTRL_GPIO_Port, FAN_2_CTRL_Pin, FAN_5V_CTRL_GPIO_Port, FAN_5V_CTRL_Pin, NCRIT_5V_CTRL_GPIO_Port, NCRIT_5V_CTRL_Pin, PHAL_readGPIO(), PUMP_1_CTRL_GPIO_Port, PUMP_1_CTRL_Pin, PUMP_2_CTRL_GPIO_Port, PUMP_2_CTRL_Pin, SW_AUX, SW_BLT, SW_CRIT_5V, SW_FAN_1, SW_FAN_2, SW_FAN_5V, SW_NCRIT_5V, SW_PUMP_1, and SW_PUMP_2.
setSwitch()
void setSwitch (switches_t auto_switch_enum, bool state)
Enable or disable a switch.
Parameters
auto_switch_enum Switch to enable or disable
state 1 to enable, 0 to disable
Definition at line 93 of file auto_switch.c.
References AUX_HP_CTRL_GPIO_Port, AUX_HP_CTRL_Pin, BLT_CTRL_GPIO_Port, BLT_CTRL_Pin, FAN_1_CTRL_GPIO_Port, FAN_1_CTRL_Pin, FAN_2_CTRL_GPIO_Port, FAN_2_CTRL_Pin, FAN_5V_CTRL_GPIO_Port, FAN_5V_CTRL_Pin, LED_5V_CRIT, LED_5V_FAN, LED_5V_NCRIT, LED_ABOX, LED_AUX_1, LED_BLT, LED_control(), LED_DAQ, LED_DASH, LED_FAN_1, LED_FAN_2, LED_MAIN, LED_PUMP_1, LED_PUMP_2, LED_SDC, NCRIT_5V_CTRL_GPIO_Port, NCRIT_5V_CTRL_Pin, PHAL_writeGPIO(), PUMP_1_CTRL_GPIO_Port, PUMP_1_CTRL_Pin, PUMP_2_CTRL_GPIO_Port, PUMP_2_CTRL_Pin, SW_ABOX, SW_AUX, SW_BLT, SW_CRIT_5V, SW_DAQ, SW_DASH, SW_FAN_1, SW_FAN_2, SW_FAN_5V, SW_MAIN, SW_NCRIT_5V, SW_PUMP_1, SW_PUMP_2, and SW_SDC.
Referenced by preflightChecks(), and update_cooling_periodic().
Variable Documentation
auto_switches
auto_switches_t auto_switches extern
Definition at line 19 of file auto_switch.c.
Referenced by calcCurrent_Total(), send_iv_readings(), updateCurrent(), and updateVoltage().