PER Firmware: source/pdu/auto_switch/auto_switch.c File Reference
auto_switch.c File Reference
#include "auto_switch.h"
#include "common/can_library/faults_common.h"
#include "common/can_library/generated/PDU.h"
#include "common/phal/gpio.h"
#include "led.h"
#include "main.h"
Functions
static void updateCurrent ()
static void updateVoltage ()
static uint16_t calcCurrent_HP (uint16_t)
static uint16_t calcCurrent_LP (uint16_t)
static void calcCurrent_Total ()
static uint16_t calcVoltage (uint16_t, int, int)
static void setMuxChannel (uint8_t channel)
static void updateMux ()
uint16_t getMuxReading (uint8_t channel)
void setSwitch (switches_t auto_switch_enum, bool state)
Enable or disable a switch.
bool getSwitchStatus (switches_t auto_switch_enum)
Check if a switch is enabled.
void autoSwitchPeriodic ()
Combined function that calls updateVoltage() and updateCurrent()
void checkSwitchFaults ()
Checks the status of various auto switches to ensure rails are ok. Sets fault and activates blink indicator if not..
Variables
auto_switches_t auto_switches
static uint16_t mux_readings [6]
static uint8_t mux_index
Detailed Description
Author
Gavin Zyonse (gzyon.nosp@m.se@p.nosp@m.urdue.nosp@m..edu)
Version
1.0
Date
2023-11-09
Copyright
Copyright (c) 2023
Definition in file auto_switch.c.
Function Documentation
autoSwitchPeriodic()
void autoSwitchPeriodic ()
Combined function that calls updateVoltage() and updateCurrent()
Voltage on each rail is stored at: auto_switches.voltage.in_24v auto_switches.voltage.out_5v auto_switches.voltage.out_3v3
Current through each switch is stored at: auto_switches.current[auto_switch_enum]
Definition at line 253 of file auto_switch.c.
References updateCurrent(), updateMux(), and updateVoltage().
Referenced by main().
calcCurrent_HP()
uint16_t calcCurrent_HP (uint16_t current) static
Definition at line 89 of file auto_switch.c.
References ADC_MAX, ADC_REF_mV, HP_CS_R1, HP_CS_R2, and HP_CS_R3.
Referenced by updateCurrent().
calcCurrent_LP()
uint16_t calcCurrent_LP (uint16_t current) static
Definition at line 96 of file auto_switch.c.
References ADC_MAX, and ADC_REF_mV.
Referenced by updateCurrent().
calcCurrent_Total()
void calcCurrent_Total () static
Definition at line 102 of file auto_switch.c.
References ADC_MAX, adc_readings, ADC_REF_mV, auto_switches, CS_24V, CS_5V, CS_GAIN, auto_switches_t::current, HP_CS_R_SENSE, ADCReadings_t::v24_cs, and ADCReadings_t::v5_cs.
Referenced by updateCurrent().
calcVoltage()
uint16_t calcVoltage (uint16_t voltage, int r1, int r2) static
Definition at line 116 of file auto_switch.c.
References ADC_MAX, and ADC_REF_mV.
Referenced by updateVoltage().
checkSwitchFaults()
void checkSwitchFaults ()
Checks the status of various auto switches to ensure rails are ok. Sets fault and activates blink indicator if not..
Definition at line 259 of file auto_switch.c.
References ABOX_NFLT_GPIO_Port, ABOX_NFLT_Pin, BLT_NFLT_GPIO_Port, BLT_NFLT_Pin, CRIT_5V_NFLT_GPIO_Port, CRIT_5V_NFLT_Pin, DASH_NFLT_GPIO_Port, DASH_NFLT_Pin, DLBK_NFLT_GPIO_Port, DLBK_NFLT_Pin, DLFR_NFLT_GPIO_Port, DLFR_NFLT_Pin, FAN_5V_NFLT_GPIO_Port, FAN_5V_NFLT_Pin, is_latched(), LED_5V_CRIT, LED_ABOX, LED_BLINK, LED_BLT, LED_control(), LED_DASH, LED_DLBK, LED_DLFR, LED_MAIN, LED_OFF, LED_TV, MAIN_NFLT_GPIO_Port, MAIN_NFLT_Pin, PHAL_readGPIO(), TV_NFLT_GPIO_Port, TV_NFLT_Pin, and update_fault().
Referenced by main().
getMuxReading()
uint16_t getMuxReading (uint8_t channel)
Definition at line 74 of file auto_switch.c.
References mux_readings.
getSwitchStatus()
bool getSwitchStatus (switches_t auto_switch_enum)
Check if a switch is enabled.
Parameters
auto_switch_enum Switch to check
Returns
1 if enabled, 0 if disabled
Definition at line 204 of file auto_switch.c.
References BLT_CTRL_GPIO_Port, BLT_CTRL_Pin, CRIT_5V_CTRL_GPIO_Port, CRIT_5V_CTRL_Pin, DLBK_CTRL_GPIO_Port, DLBK_CTRL_Pin, DLFR_CTRL_GPIO_Port, DLFR_CTRL_Pin, FAN_1_CTRL_GPIO_Port, FAN_1_CTRL_Pin, FAN_2_CTRL_GPIO_Port, FAN_2_CTRL_Pin, FAN_3_CTRL_GPIO_Port, FAN_3_CTRL_Pin, FAN_4_CTRL_GPIO_Port, FAN_4_CTRL_Pin, FAN_5V_CTRL_GPIO_Port, FAN_5V_CTRL_Pin, HXFAN_CTRL_GPIO_Port, HXFAN_CTRL_Pin, PHAL_readGPIO(), PUMP_1_CTRL_GPIO_Port, PUMP_1_CTRL_Pin, PUMP_2_CTRL_GPIO_Port, PUMP_2_CTRL_Pin, SW_BLT, SW_CRIT_5V, SW_DLBK, SW_DLFR, SW_FAN_1, SW_FAN_2, SW_FAN_3, SW_FAN_4, SW_FAN_5V, SW_HXFAN, SW_PUMP_1, SW_PUMP_2, SW_TV, TV_CTRL_GPIO_Port, and TV_CTRL_Pin.
setMuxChannel()
static void setMuxChannel (uint8_t channel) static
Definition at line 82 of file auto_switch.c.
References MUX_CTRL_A_GPIO_Port, MUX_CTRL_A_Pin, MUX_CTRL_B_GPIO_Port, MUX_CTRL_B_Pin, MUX_CTRL_C_GPIO_Port, MUX_CTRL_C_Pin, and PHAL_writeGPIO().
Referenced by updateMux().
setSwitch()
void setSwitch (switches_t auto_switch_enum, bool state)
Enable or disable a switch.
Parameters
auto_switch_enum Switch to enable or disable
state 1 to enable, 0 to disable
Definition at line 125 of file auto_switch.c.
References BLT_CTRL_GPIO_Port, BLT_CTRL_Pin, CRIT_5V_CTRL_GPIO_Port, CRIT_5V_CTRL_Pin, CS_24V, CS_5V, CS_SWITCH_COUNT, DLBK_CTRL_GPIO_Port, DLBK_CTRL_Pin, DLFR_CTRL_GPIO_Port, DLFR_CTRL_Pin, FAN_1_CTRL_GPIO_Port, FAN_1_CTRL_Pin, FAN_2_CTRL_GPIO_Port, FAN_2_CTRL_Pin, FAN_3_CTRL_GPIO_Port, FAN_3_CTRL_Pin, FAN_4_CTRL_GPIO_Port, FAN_4_CTRL_Pin, FAN_5V_CTRL_GPIO_Port, FAN_5V_CTRL_Pin, HXFAN_CTRL_GPIO_Port, HXFAN_CTRL_Pin, LED_5V_CRIT, LED_5V_FAN, LED_ABOX, LED_BLT, LED_control(), LED_DAQ, LED_DASH, LED_DLBK, LED_DLFR, LED_HXFAN, LED_MAIN, LED_PUMP_1, LED_PUMP_2, LED_SDC, LED_TV, PHAL_writeGPIO(), PUMP_1_CTRL_GPIO_Port, PUMP_1_CTRL_Pin, PUMP_2_CTRL_GPIO_Port, PUMP_2_CTRL_Pin, SW_ABOX, SW_AMK1, SW_AMK2, SW_BLT, SW_CRIT_5V, SW_DAQ, SW_DASH, SW_DLBK, SW_DLFR, SW_FAN_1, SW_FAN_2, SW_FAN_3, SW_FAN_4, SW_FAN_5V, SW_HXFAN, SW_MAIN, SW_PUMP_1, SW_PUMP_2, SW_SDC, SW_TV, TV_CTRL_GPIO_Port, and TV_CTRL_Pin.
Referenced by main(), and update_cooling_periodic().
updateCurrent()
void updateCurrent () static
Definition at line 35 of file auto_switch.c.
References ADCReadings_t::abox_cs, adc_readings, auto_switches, calcCurrent_HP(), calcCurrent_LP(), calcCurrent_Total(), auto_switches_t::current, ADCReadings_t::dash_cs, ADCReadings_t::dlbk_cs, ADCReadings_t::dlfr_cs, ADCReadings_t::hxfan_imon, ADCReadings_t::main_cs, mux_readings, ADCReadings_t::pump_1_imon, ADCReadings_t::pump_2_imon, ADCReadings_t::sdc_imon, SW_ABOX, SW_AMK1, SW_AMK2, SW_DASH, SW_DLBK, SW_DLFR, SW_FAN_1, SW_FAN_2, SW_FAN_3, SW_FAN_4, SW_HXFAN, SW_MAIN, SW_PUMP_1, SW_PUMP_2, and SW_SDC.
Referenced by autoSwitchPeriodic().
updateMux()
static void updateMux () static
Definition at line 68 of file auto_switch.c.
References adc_readings, mux_index, ADCReadings_t::mux_out, mux_readings, and setMuxChannel().
Referenced by autoSwitchPeriodic().
updateVoltage()
void updateVoltage () static
Definition at line 62 of file auto_switch.c.
References adc_readings, auto_switches, calcVoltage(), voltage_t::in_24v, LV_24V_R1, LV_24V_R2, LV_3V3_R1, LV_3V3_R2, LV_5V_R1, LV_5V_R2, voltage_t::out_3v3, voltage_t::out_5v, ADCReadings_t::v24_vs, ADCReadings_t::v3v3_vs, ADCReadings_t::v5_vs, and auto_switches_t::voltage.
Referenced by autoSwitchPeriodic().
Variable Documentation
auto_switches
auto_switches_t auto_switches
Definition at line 20 of file auto_switch.c.
Referenced by calcCurrent_Total(), send_iv_readings(), updateCurrent(), and updateVoltage().
mux_index
uint8_t mux_index static
Definition at line 22 of file auto_switch.c.
Referenced by updateMux().
mux_readings
uint16_t mux_readings[6] static
Definition at line 21 of file auto_switch.c.
Referenced by getMuxReading(), updateCurrent(), and updateMux().