PER Firmware: common/bmi088/bmi088.c File Reference
bmi088.c File Reference
BMI088 IMU driver.
#include "bmi088.h"
#include <stdbool.h>
#include <stdint.h>
#include "common/phal/spi.h"
#include "common_defs.h"
#include "main.h"
Functions
static void BMI088_selectGyro (BMI088_Handle_t *bmi)
static void BMI088_selectAccel (BMI088_Handle_t *bmi)
bool BMI088_init (BMI088_Handle_t *bmi)
void BMI088_wakeAccel (BMI088_Handle_t *bmi)
bool BMI088_initAccel (BMI088_Handle_t *bmi)
Setup the accelerometer, must be done 50ms or longer after POR.
bool BMI088_gyroOK (BMI088_Handle_t *bmi)
Do self test of gyroscope.
bool BMI088_gyroSelfTestStart (BMI088_Handle_t *bmi)
Start the gyro self test.
bool BMI088_gyroSelfTestComplete (BMI088_Handle_t *bmi)
Check the status of the most recent Gyro self test.
bool BMI088_gyroSelfTestPass (BMI088_Handle_t *bmi)
Check the status of the most recent Gyro self test.
uint8_t BMI088_checkGyroHealth (BMI088_Handle_t *bmi)
static float BMI088_getGyroScale (BMI088_Handle_t *bmi, bool range_up, bool range_down)
bool BMI088_readGyro (BMI088_Handle_t *bmi)
Blocking function to read the most recent Data Sample from the gyro.
bool BMI088_readAccel (BMI088_Handle_t *bmi)
Blocking function to read the acceleration values form the device.
Detailed Description
BMI088 IMU driver.
Author
Adam Busch (busch.nosp@m.8@pu.nosp@m.rdue..nosp@m.edu)
Irving Wang (irvin.nosp@m.gw@p.nosp@m.urdue.nosp@m..edu)
Definition in file bmi088.c.
Function Documentation
BMI088_checkGyroHealth()
uint8_t BMI088_checkGyroHealth (BMI088_Handle_t * bmi)
Definition at line 105 of file bmi088.c.
References BMI088_GYRO_SELFTEST_ADDR, PHAL_SPI_readByte(), and BMI088_Handle_t::spi.
BMI088_getGyroScale()
static float BMI088_getGyroScale (BMI088_Handle_t * bmi, bool range_up, bool range_down) inline static
Definition at line 114 of file bmi088.c.
References BMI088_GYRO_RANGE_ADDR, DEG_TO_RAD, BMI088_Handle_t::gyro_range, GYRO_RANGE_1000, GYRO_RANGE_125, GYRO_RANGE_2000, GYRO_RANGE_250, GYRO_RANGE_500, PHAL_SPI_writeByte(), and BMI088_Handle_t::spi.
Referenced by BMI088_readGyro().
BMI088_gyroOK()
bool BMI088_gyroOK (BMI088_Handle_t * bmi)
Do self test of gyroscope.
Parameters
bmi
Returns
true gyro is OK
false not good
Definition at line 66 of file bmi088.c.
References BMI088_gyroSelfTestComplete(), BMI088_gyroSelfTestPass(), and BMI088_gyroSelfTestStart().
BMI088_gyroSelfTestComplete()
bool BMI088_gyroSelfTestComplete (BMI088_Handle_t * bmi)
Check the status of the most recent Gyro self test.
Returns
true Self test passed, gyro data is good
false Self test failed, gyro data bad or no test was conduced
Definition at line 85 of file bmi088.c.
References BMI088_GYRO_SELFTEST_ADDR, BMI088_selectGyro(), PHAL_SPI_readByte(), PHAL_writeGPIO(), and BMI088_Handle_t::spi.
Referenced by BMI088_gyroOK(), and BMI088_init().
BMI088_gyroSelfTestPass()
bool BMI088_gyroSelfTestPass (BMI088_Handle_t * bmi)
Check the status of the most recent Gyro self test.
Returns
true Self test passed, gyro data is good
false Self test failed, gyro data bad or no test was conduced
Definition at line 92 of file bmi088.c.
References BMI088_GYRO_SELFTEST_ADDR, BMI088_selectGyro(), PHAL_SPI_readByte(), PHAL_writeGPIO(), and BMI088_Handle_t::spi.
Referenced by BMI088_gyroOK(), and BMI088_init().
BMI088_gyroSelfTestStart()
bool BMI088_gyroSelfTestStart (BMI088_Handle_t * bmi)
Start the gyro self test.
Returns
true
false
Definition at line 78 of file bmi088.c.
References BMI088_GYRO_SELFTEST_ADDR, BMI088_selectGyro(), PHAL_SPI_writeByte(), PHAL_writeGPIO(), and BMI088_Handle_t::spi.
Referenced by BMI088_gyroOK(), and BMI088_init().
BMI088_init()
bool BMI088_init (BMI088_Handle_t * bmi)
Parameters
bmi
Returns
true
false
Definition at line 21 of file bmi088.c.
References BMI088_GYRO_BANDWIDTH_ADDR, BMI088_GYRO_CHIP_ID, BMI088_GYRO_CHIP_ID_ADDR, BMI088_GYRO_RANGE_ADDR, BMI088_gyroSelfTestComplete(), BMI088_gyroSelfTestPass(), BMI088_gyroSelfTestStart(), BMI088_selectGyro(), BMI088_Handle_t::gyro_datarate, BMI088_Handle_t::gyro_range, BMI088_Handle_t::isAccelReady, PHAL_SPI_readByte(), PHAL_SPI_writeByte(), PHAL_writeGPIO(), and BMI088_Handle_t::spi.
BMI088_initAccel()
bool BMI088_initAccel (BMI088_Handle_t * bmi)
Setup the accelerometer, must be done 50ms or longer after POR.
Parameters
bmi
Returns
true ACCEL responded sucessfully
false not good
Definition at line 51 of file bmi088.c.
References BMI088_Handle_t::accel_bwp, BMI088_Handle_t::accel_odr, BMI088_Handle_t::accel_range, BMI088_ACC_CHIP_ID_ADDR, BMI088_ACC_CONFIG_ADDR, BMI088_ACC_PWR_CONF_ADDR, BMI088_ACC_RANGE_ADDR, BMI088_selectAccel(), BMI088_Handle_t::isAccelReady, PHAL_SPI_readByte(), PHAL_SPI_writeByte(), and BMI088_Handle_t::spi.
BMI088_readAccel()
bool BMI088_readAccel (BMI088_Handle_t * bmi)
Blocking function to read the acceleration values form the device.
Parameters
bmi
Returns
true
false
Definition at line 190 of file bmi088.c.
References BMI088_Handle_t::accel_range, IMU_data_t::accel_x, IMU_data_t::accel_y, IMU_data_t::accel_z, BMI088_ACC_RATE_X_LSB_ADDR, BMI088_selectAccel(), BMI088_Handle_t::bmi_rx_buffer, BMI088_Handle_t::bmi_tx_buffer, BMI088_Handle_t::data, G_TO_M_S, PHAL_SPI_busy(), PHAL_SPI_transfer_noDMA(), PHAL_writeGPIO(), rx_buffer, and BMI088_Handle_t::spi.
BMI088_readGyro()
bool BMI088_readGyro (BMI088_Handle_t * bmi)
Blocking function to read the most recent Data Sample from the gyro.
Returns
true Successful data Tx/Rx
false Unsuccessful data Tx/Rx
Definition at line 155 of file bmi088.c.
References ABS, BMI088_getGyroScale(), BMI088_GYRO_RATE_X_LSB_ADDR, BMI088_selectGyro(), BMI088_Handle_t::bmi_rx_buffer, BMI088_Handle_t::bmi_tx_buffer, BMI088_Handle_t::data, BMI088_Handle_t::enableDynamicRange, IMU_data_t::gyro_x, IMU_data_t::gyro_y, IMU_data_t::gyro_z, MAX, PHAL_SPI_busy(), PHAL_SPI_transfer_noDMA(), PHAL_writeGPIO(), rx_buffer, and BMI088_Handle_t::spi.
BMI088_selectAccel()
static void BMI088_selectAccel (BMI088_Handle_t * bmi) inline static
Definition at line 229 of file bmi088.c.
References SPI_InitConfig_t::nss_gpio_pin, SPI_InitConfig_t::nss_gpio_port, PHAL_writeGPIO(), and BMI088_Handle_t::spi.
Referenced by BMI088_initAccel(), BMI088_readAccel(), and BMI088_wakeAccel().
BMI088_selectGyro()
static void BMI088_selectGyro (BMI088_Handle_t * bmi) inline static
Definition at line 220 of file bmi088.c.
References SPI_InitConfig_t::nss_gpio_pin, SPI_InitConfig_t::nss_gpio_port, PHAL_writeGPIO(), and BMI088_Handle_t::spi.
Referenced by BMI088_gyroSelfTestComplete(), BMI088_gyroSelfTestPass(), BMI088_gyroSelfTestStart(), BMI088_init(), and BMI088_readGyro().
BMI088_wakeAccel()
void BMI088_wakeAccel (BMI088_Handle_t * bmi)
Definition at line 44 of file bmi088.c.
References BMI088_ACC_PWR_CONF_ADDR, BMI088_ACC_PWR_CTRL_ADDR, BMI088_ACC_PWR_CTRL_NORMAL, BMI088_selectAccel(), PHAL_SPI_writeByte(), and BMI088_Handle_t::spi.