PER Firmware: source/bootloader/bootloader.c File Reference
bootloader.c File Reference
CAN Bootloader:
#include "bootloader.h"
#include "common/phal/crc.h"
#include "common/phal/flash.h"
#include "common/phal/gpio.h"
Macros
#define BL_ADDRESS_CRC_CRC ((BL_ADDRESS_CRC) + 0)
#define BL_ADDRESS_CRC_ADDR ((BL_ADDRESS_CRC) + 4)
#define BL_ADDRESS_CRC_SIZE ((BL_ADDRESS_CRC) + 8)
#define BUFFER_SIZE 128
#define NODE_CASE_BL_RESPONSE(app_id, resp_func)
#define NODE_BL_CMD_CALLBACK(callback_name, can_msg_name, node_id)
Functions
static void BL_JumptoApplication (void)
void BL_checkAndBoot (void)
static int BL_processCommand_Start (uint32_t size)
static int BL_memcpy_buffer (uint32_t addr_dst, uint32_t addr_src, uint32_t size)
static int BL_setCRCConfig (uint32_t crc, uint32_t addr, uint32_t size)
void bitstream_data_CALLBACK (CanParsedData_t *msg_data_a)
static int BL_processCommand_CRC (uint32_t crc_app, uint32_t dst_addr)
static void BL_processCommand_Reset (uint32_t data)
static void BL_processCommand_Jump (uint32_t data)
void BL_processCommand (BLCmd_t cmd, uint32_t data)
bool BL_flashStarted (void)
void BL_sendStatusMessage (uint8_t cmd, uint32_t data)
void main_module_bl_cmd_CALLBACK (CanParsedData_t *msg_data_a)
void dashboard_bl_cmd_CALLBACK (CanParsedData_t *msg_data_a)
void torquevector_bl_cmd_CALLBACK (CanParsedData_t *msg_data_a)
void a_box_bl_cmd_CALLBACK (CanParsedData_t *msg_data_a)
void pdu_bl_cmd_CALLBACK (CanParsedData_t *msg_data_a)
void l4_testing_bl_cmd_CALLBACK (CanParsedData_t *msg_data_a)
void f4_testing_bl_cmd_CALLBACK (CanParsedData_t *msg_data_a)
void f7_testing_bl_cmd_CALLBACK (CanParsedData_t *msg_data_a)
void daq_bl_cmd_CALLBACK (CanParsedData_t *msg_data_a)
Variables
static bool bl_unlock = false
static volatile uint32_t firmware_size_total = 0
static uint32_t buffer [128]
static uint32_t buffer_index = 0
char __isr_vector_start
char _eboot_flash
char _estack
Detailed Description
CAN Bootloader:
Author
Eileen Yoon (eyn@p.nosp@m.urdu.nosp@m.e.edu)
Double bank flash buffer + CRC
Download/Upload firmware over buffered CAN TP
Load/store backup firmware
Version
0.1
Date
2024-11-24
Copyright
Copyright (c) 2024
Definition in file bootloader.c.
Macro Definition Documentation
BL_ADDRESS_CRC_ADDR
#define BL_ADDRESS_CRC_ADDR ((BL_ADDRESS_CRC) + 4)
Definition at line 82 of file bootloader.c.
Referenced by BL_checkAndBoot(), and BL_setCRCConfig().
BL_ADDRESS_CRC_CRC
#define BL_ADDRESS_CRC_CRC ((BL_ADDRESS_CRC) + 0)
Definition at line 81 of file bootloader.c.
Referenced by BL_checkAndBoot(), and BL_setCRCConfig().
BL_ADDRESS_CRC_SIZE
#define BL_ADDRESS_CRC_SIZE ((BL_ADDRESS_CRC) + 8)
Definition at line 83 of file bootloader.c.
Referenced by BL_checkAndBoot(), and BL_setCRCConfig().
BUFFER_SIZE
#define BUFFER_SIZE 128
Definition at line 89 of file bootloader.c.
Referenced by bitstream_data_CALLBACK().
NODE_BL_CMD_CALLBACK
#define NODE_BL_CMD_CALLBACK (callback_name, can_msg_name, node_id)
Value:
    void callback_name(CanParsedData_t* msg_data_a) { \
        if (APP_ID != node_id) \
            return; \
        BL_processCommand((BLCmd_t)msg_data_a->can_msg_name.cmd, msg_data_a->can_msg_name.data); \
    }
Definition at line 333 of file bootloader.c.
NODE_CASE_BL_RESPONSE
#define NODE_CASE_BL_RESPONSE (app_id, resp_func)
Value:
    case app_id: \
        resp_func(cmd, data); \
        break;
Definition at line 311 of file bootloader.c.
Referenced by BL_sendStatusMessage().
Function Documentation
a_box_bl_cmd_CALLBACK()
void a_box_bl_cmd_CALLBACK (CanParsedData_t * msg_data_a)
Definition at line 343 of file bootloader.c.
bitstream_data_CALLBACK()
void bitstream_data_CALLBACK (CanParsedData_t * msg_data_a)
Definition at line 208 of file bootloader.c.
References BL_sendStatusMessage(), BLERROR_FLASH, BLSTAT_INVALID, buffer, buffer_index, BUFFER_SIZE, firmware_size_total, FLASH_OK, and PHAL_flashWriteU32_Buffered().
BL_checkAndBoot()
void BL_checkAndBoot (void)
Definition at line 131 of file bootloader.c.
References addr, BL_ADDRESS_CRC_ADDR, BL_ADDRESS_CRC_CRC, BL_ADDRESS_CRC_SIZE, BL_JumptoApplication(), PHAL_CRC32_Calculate(), and PHAL_flashReadU32().
Referenced by main().
BL_flashStarted()
bool BL_flashStarted (void)
Definition at line 304 of file bootloader.c.
References bl_unlock.
Referenced by main().
BL_JumptoApplication()
static void BL_JumptoApplication (void) static
Definition at line 98 of file bootloader.c.
References _eboot_flash, and _estack.
Referenced by BL_checkAndBoot(), and BL_processCommand_Jump().
BL_memcpy_buffer()
static int BL_memcpy_buffer (uint32_t addr_dst, uint32_t addr_src, uint32_t size) static
Definition at line 164 of file bootloader.c.
References FLASH_OK, PHAL_flashErase(), and PHAL_flashWriteU32().
Referenced by BL_processCommand_CRC(), and BL_processCommand_Jump().
BL_processCommand()
void BL_processCommand (BLCmd_t cmd, uint32_t data)
Definition at line 280 of file bootloader.c.
References BL_processCommand_CRC(), BL_processCommand_Jump(), BL_processCommand_Reset(), BL_processCommand_Start(), BL_sendStatusMessage(), BLCMD_CRC, BLCMD_CRC_BACKUP, BLCMD_JUMP, BLCMD_RST, BLCMD_START, and BLSTAT_UNKNOWN_CMD.
BL_processCommand_CRC()
static int BL_processCommand_CRC (uint32_t crc_app, uint32_t dst_addr) static
Definition at line 234 of file bootloader.c.
References BL_memcpy_buffer(), BL_sendStatusMessage(), BL_setCRCConfig(), BLERROR_FLASH, BLERROR_SIZE, BLSTAT_INVALID, BLSTAT_INVALID_CRC, BLSTAT_VALID, firmware_size_total, and PHAL_CRC32_Calculate().
Referenced by BL_processCommand().
BL_processCommand_Jump()
static void BL_processCommand_Jump (uint32_t data) static
Definition at line 270 of file bootloader.c.
References BL_JumptoApplication(), BL_memcpy_buffer(), and bl_unlock.
Referenced by BL_processCommand().
BL_processCommand_Reset()
static void BL_processCommand_Reset (uint32_t data) static
Definition at line 266 of file bootloader.c.
References Bootloader_ResetForFirmwareDownload().
Referenced by BL_processCommand().
BL_processCommand_Start()
static int BL_processCommand_Start (uint32_t size) static
Definition at line 143 of file bootloader.c.
References BL_sendStatusMessage(), bl_unlock, BLERROR_FLASH, BLERROR_SIZE, BLSTAT_INVALID, BLSTAT_VALID, buffer_index, firmware_size_total, FLASH_OK, and PHAL_flashErase().
Referenced by BL_processCommand().
BL_sendStatusMessage()
void BL_sendStatusMessage (uint8_t cmd, uint32_t data)
Definition at line 316 of file bootloader.c.
References APP_A_BOX, APP_DAQ, APP_DASHBOARD, APP_F4_TESTING, APP_F7_TESTING, APP_MAIN_MODULE, APP_PDU, APP_TORQUEVECTOR, and NODE_CASE_BL_RESPONSE.
Referenced by bitstream_data_CALLBACK(), BL_processCommand(), BL_processCommand_CRC(), and BL_processCommand_Start().
BL_setCRCConfig()
static int BL_setCRCConfig (uint32_t crc, uint32_t addr, uint32_t size) static
Definition at line 177 of file bootloader.c.
References addr, BL_ADDRESS_CRC_ADDR, BL_ADDRESS_CRC_CRC, BL_ADDRESS_CRC_SIZE, bl_unlock, FLASH_OK, PHAL_flashErase(), and PHAL_flashWriteU32().
Referenced by BL_processCommand_CRC().
daq_bl_cmd_CALLBACK()
void daq_bl_cmd_CALLBACK (CanParsedData_t * msg_data_a)
Definition at line 348 of file bootloader.c.
dashboard_bl_cmd_CALLBACK()
void dashboard_bl_cmd_CALLBACK (CanParsedData_t * msg_data_a)
Definition at line 341 of file bootloader.c.
f4_testing_bl_cmd_CALLBACK()
void f4_testing_bl_cmd_CALLBACK (CanParsedData_t * msg_data_a)
Definition at line 346 of file bootloader.c.
f7_testing_bl_cmd_CALLBACK()
void f7_testing_bl_cmd_CALLBACK (CanParsedData_t * msg_data_a)
Definition at line 347 of file bootloader.c.
l4_testing_bl_cmd_CALLBACK()
void l4_testing_bl_cmd_CALLBACK (CanParsedData_t * msg_data_a)
Definition at line 345 of file bootloader.c.
main_module_bl_cmd_CALLBACK()
void main_module_bl_cmd_CALLBACK (CanParsedData_t * msg_data_a)
Definition at line 340 of file bootloader.c.
pdu_bl_cmd_CALLBACK()
void pdu_bl_cmd_CALLBACK (CanParsedData_t * msg_data_a)
Definition at line 344 of file bootloader.c.
torquevector_bl_cmd_CALLBACK()
void torquevector_bl_cmd_CALLBACK (CanParsedData_t * msg_data_a)
Definition at line 342 of file bootloader.c.
Variable Documentation
__isr_vector_start
char __isr_vector_start extern
_eboot_flash
char _eboot_flash extern
Referenced by BL_JumptoApplication().
_estack
char _estack extern
Referenced by BL_JumptoApplication().
bl_unlock
bool bl_unlock = false static
Definition at line 85 of file bootloader.c.
Referenced by BL_flashStarted(), BL_processCommand_Jump(), BL_processCommand_Start(), and BL_setCRCConfig().
buffer
uint32_t buffer[128] static
Definition at line 90 of file bootloader.c.
Referenced by bitstream_data_CALLBACK(), snprintf(), and sprintf().
buffer_index
uint32_t buffer_index = 0 static
Definition at line 91 of file bootloader.c.
Referenced by bitstream_data_CALLBACK(), and BL_processCommand_Start().
firmware_size_total
volatile uint32_t firmware_size_total = 0 static
Definition at line 86 of file bootloader.c.
Referenced by bitstream_data_CALLBACK(), BL_processCommand_CRC(), and BL_processCommand_Start().