PER Firmware: common/bootloader/bootloader_common.h File Reference
bootloader_common.h File Reference
Common bootloader functions for all firmware components. Useful for entering the bootloader to download new firmware.
#include "inttypes.h"
#include "stm32l4xx.h"
Data Structures
struct BootlaoderSharedMemory_t
Macros
#define BOOTLOADER_SHARED_MEMORY_MAGIC (0xABCDBEEF)
Enumerations
enum BLCmd_t {
BLCMD_START = 0x1 , BLCMD_CRC = 0x3 , BLCMD_CRC_BACKUP = 0x2 , BLCMD_JUMP = 0x4 ,
BLCMD_RST = 0x5
}
enum ResetReason_t {
RESET_REASON_INVALID , RESET_REASON_BUTTON , RESET_REASON_DOWNLOAD_FW , RESET_REASON_APP_WATCHDOG ,
RESET_REASON_POR , RESET_REASON_BAD_FIRMWARE
}
Functions
void Bootloader_ConfirmApplicationLaunch ()
int Bootloader_ResetForFirmwareDownload ()
int Bootloader_ResetForWatchdog ()
Variables
BootlaoderSharedMemory_t bootloader_shared_memory
Detailed Description
Common bootloader functions for all firmware components. Useful for entering the bootloader to download new firmware.
Author
Adam Busch (busch.nosp@m.8@pu.nosp@m.rdue..nosp@m.edu)
Version
0.1
Date
2022-03-10
Copyright
Copyright (c) 2022
Definition in file bootloader_common.h.
Macro Definition Documentation
BOOTLOADER_SHARED_MEMORY_MAGIC
#define BOOTLOADER_SHARED_MEMORY_MAGIC (0xABCDBEEF)
Definition at line 24 of file bootloader_common.h.
Referenced by Bootloader_ResetForFirmwareDownload(), and Bootloader_ResetForWatchdog().
Enumeration Type Documentation
BLCmd_t
enum BLCmd_t
Enumerator
BLCMD_START
BLCMD_CRC
BLCMD_CRC_BACKUP
BLCMD_JUMP
BLCMD_RST
Definition at line 26 of file bootloader_common.h.
ResetReason_t
enum ResetReason_t
Enumerator
RESET_REASON_INVALID
RESET_REASON_BUTTON
RESET_REASON_DOWNLOAD_FW
RESET_REASON_APP_WATCHDOG
RESET_REASON_POR
RESET_REASON_BAD_FIRMWARE
Definition at line 34 of file bootloader_common.h.
Function Documentation
Bootloader_ConfirmApplicationLaunch()
void Bootloader_ConfirmApplicationLaunch () inline
Definition at line 51 of file bootloader_common.h.
References bootloader_shared_memory, BootlaoderSharedMemory_t::reset_reason, and RESET_REASON_BUTTON.
Referenced by main().
Bootloader_ResetForFirmwareDownload()
int Bootloader_ResetForFirmwareDownload ()
Definition at line 18 of file bootlaoder_common.c.
References bootloader_shared_memory, BOOTLOADER_SHARED_MEMORY_MAGIC, BootlaoderSharedMemory_t::magic_word, BootlaoderSharedMemory_t::reset_count, BootlaoderSharedMemory_t::reset_reason, and RESET_REASON_DOWNLOAD_FW.
Referenced by BL_processCommand_Reset(), l4_testing_bl_cmd_CALLBACK(), and pdu_bl_cmd_CALLBACK().
Bootloader_ResetForWatchdog()
int Bootloader_ResetForWatchdog ()
Definition at line 25 of file bootlaoder_common.c.
References bootloader_shared_memory, BOOTLOADER_SHARED_MEMORY_MAGIC, BootlaoderSharedMemory_t::magic_word, BootlaoderSharedMemory_t::reset_count, BootlaoderSharedMemory_t::reset_reason, and RESET_REASON_APP_WATCHDOG.
Variable Documentation
bootloader_shared_memory
BootlaoderSharedMemory_t bootloader_shared_memory extern
Definition at line 15 of file bootlaoder_common.c.
Referenced by Bootloader_ConfirmApplicationLaunch(), Bootloader_ResetForFirmwareDownload(), and Bootloader_ResetForWatchdog().