PER Firmware: common/bootloader/bootlaoder_common.c File Reference
bootlaoder_common.c File Reference
#include "bootloader_common.h"
Functions
int Bootloader_ResetForFirmwareDownload ()
int Bootloader_ResetForWatchdog ()
Variables
BootlaoderSharedMemory_t bootloader_shared_memory
Detailed Description
Author
Adam Busch (busch.nosp@m.8@pu.nosp@m.rdue..nosp@m.edu)
Version
0.1
Date
2022-03-31
Copyright
Copyright (c) 2022
Definition in file bootlaoder_common.c.
Function Documentation
Bootloader_ResetForFirmwareDownload()
int Bootloader_ResetForFirmwareDownload ()
Definition at line 18 of file bootlaoder_common.c.
References bootloader_shared_memory, BOOTLOADER_SHARED_MEMORY_MAGIC, BootlaoderSharedMemory_t::magic_word, BootlaoderSharedMemory_t::reset_count, BootlaoderSharedMemory_t::reset_reason, and RESET_REASON_DOWNLOAD_FW.
Referenced by BL_processCommand_Reset(), l4_testing_bl_cmd_CALLBACK(), and pdu_bl_cmd_CALLBACK().
Bootloader_ResetForWatchdog()
int Bootloader_ResetForWatchdog ()
Definition at line 25 of file bootlaoder_common.c.
References bootloader_shared_memory, BOOTLOADER_SHARED_MEMORY_MAGIC, BootlaoderSharedMemory_t::magic_word, BootlaoderSharedMemory_t::reset_count, BootlaoderSharedMemory_t::reset_reason, and RESET_REASON_APP_WATCHDOG.
Variable Documentation
bootloader_shared_memory
BootlaoderSharedMemory_t bootloader_shared_memory
Initial value:
= {
    0}
Definition at line 15 of file bootlaoder_common.c.
Referenced by Bootloader_ConfirmApplicationLaunch(), Bootloader_ResetForFirmwareDownload(), and Bootloader_ResetForWatchdog().