PER Firmware: source/bootloader/bootloader/bootloader.h File Reference
bootloader.h File Reference
#include "can_parse.h"
#include "common/bootloader/bootloader_common.h"
#include "inttypes.h"
#include "node_defs.h"
#include "stdbool.h"
Enumerations
enum BLStatus_t { BLSTAT_VALID = 0 , BLSTAT_INVALID = 1 , BLSTAT_INVALID_CRC = 2 , BLSTAT_UNKNOWN_CMD = 3 }
enum BLError_t {
BLERROR_CRC_FAIL = 0 , BLERROR_LOCKED = 1 , BLERROR_LOW_ADDR = 2 , BLERROR_ADDR_BOUND = 3 ,
BLERROR_FLASH = 4 , BLERROR_SIZE = 5
}
Functions
void BL_checkAndBoot (void)
void BL_processCommand (BLCmd_t cmd, uint32_t data)
void BL_sendStatusMessage (uint8_t cmd, uint32_t data)
bool BL_flashStarted (void)
Enumeration Type Documentation
BLError_t
enum BLError_t
Enumerator
BLERROR_CRC_FAIL
BLERROR_LOCKED
BLERROR_LOW_ADDR
BLERROR_ADDR_BOUND
BLERROR_FLASH
BLERROR_SIZE
Definition at line 27 of file bootloader.h.
BLStatus_t
enum BLStatus_t
Enumerator
BLSTAT_VALID
BLSTAT_INVALID
BLSTAT_INVALID_CRC
BLSTAT_UNKNOWN_CMD
Definition at line 20 of file bootloader.h.
Function Documentation
BL_checkAndBoot()
void BL_checkAndBoot (void)
Definition at line 131 of file bootloader.c.
References addr, BL_ADDRESS_CRC_ADDR, BL_ADDRESS_CRC_CRC, BL_ADDRESS_CRC_SIZE, BL_JumptoApplication(), PHAL_CRC32_Calculate(), and PHAL_flashReadU32().
Referenced by main().
BL_flashStarted()
bool BL_flashStarted (void)
Definition at line 304 of file bootloader.c.
References bl_unlock.
Referenced by main().
BL_processCommand()
void BL_processCommand (BLCmd_t cmd, uint32_t data)
Definition at line 280 of file bootloader.c.
References BL_processCommand_CRC(), BL_processCommand_Jump(), BL_processCommand_Reset(), BL_processCommand_Start(), BL_sendStatusMessage(), BLCMD_CRC, BLCMD_CRC_BACKUP, BLCMD_JUMP, BLCMD_RST, BLCMD_START, and BLSTAT_UNKNOWN_CMD.
BL_sendStatusMessage()
void BL_sendStatusMessage (uint8_t cmd, uint32_t data)
Definition at line 316 of file bootloader.c.
References APP_A_BOX, APP_DAQ, APP_DASHBOARD, APP_F4_TESTING, APP_F7_TESTING, APP_MAIN_MODULE, APP_PDU, APP_TORQUEVECTOR, and NODE_CASE_BL_RESPONSE.
Referenced by bitstream_data_CALLBACK(), BL_processCommand(), BL_processCommand_CRC(), and BL_processCommand_Start().