PER Firmware: source/bootloader/main.c File Reference
main.c File Reference
#include "common/bootloader/bootloader_common.h"
#include "common/phal/can.h"
#include "common/phal/gpio.h"
#include "common/phal/rcc.h"
#include "bootloader.h"
#include "can_parse.h"
#include "node_defs.h"
Macros
#define TargetCoreClockrateHz 16000000
#define BOOTLOADER_INITIAL_TIMEOUT 3000
#define CAN_TX_BLOCK_TIMEOUT (30 * 16000)
Functions
void HardFault_Handler ()
void canTxSendToBack (CanMsgTypeDef_t *msg)
static void send_pending_can (void)
static void BL_CANPoll (void)
int main (void)
void CAN1_RX0_IRQHandler ()
void SysTick_Handler (void)
Variables
GPIOInitConfig_t gpio_config []
uint32_t APB1ClockRateHz
uint32_t APB2ClockRateHz
uint32_t AHBClockRateHz
uint32_t PLLClockRateHz
ClockRateConfig_t clock_config
q_handle_t q_tx_can
q_handle_t q_rx_can
static volatile uint32_t bootloader_ms = 0
Macro Definition Documentation
BOOTLOADER_INITIAL_TIMEOUT
#define BOOTLOADER_INITIAL_TIMEOUT 3000
Definition at line 40 of file main.c.
Referenced by main().
CAN_TX_BLOCK_TIMEOUT
#define CAN_TX_BLOCK_TIMEOUT (30 * 16000)
Definition at line 41 of file main.c.
Referenced by send_pending_can().
TargetCoreClockrateHz
#define TargetCoreClockrateHz 16000000
Definition at line 22 of file main.c.
Function Documentation
BL_CANPoll()
static void BL_CANPoll (void) static
Definition at line 85 of file main.c.
References canRxUpdate(), q_rx_can, qIsEmpty(), and send_pending_can().
Referenced by main().
CAN1_RX0_IRQHandler()
void CAN1_RX0_IRQHandler ()
Definition at line 109 of file main.c.
References q_rx_can, and qSendToBack().
canTxSendToBack()
void canTxSendToBack (CanMsgTypeDef_t * msg)
Definition at line 105 of file main.c.
References q_tx_can, and qSendToBack().
HardFault_Handler()
void HardFault_Handler (void)
Definition at line 149 of file main.c.
main()
int main (void)
Definition at line 44 of file main.c.
References BL_CANPoll(), BL_checkAndBoot(), BL_flashStarted(), BOOTLOADER_INITIAL_TIMEOUT, bootloader_ms, clock_config, gpio_config, HardFault_Handler(), initCANParse(), PHAL_configureClockRates(), PHAL_initCAN(), PHAL_initGPIO(), PHAL_trimHSI(), q_rx_can, q_tx_can, and qConstruct().
send_pending_can()
static void send_pending_can (void) static
Definition at line 93 of file main.c.
References CAN_TX_BLOCK_TIMEOUT, PHAL_txCANMessage(), PHAL_txMailboxFree(), q_tx_can, qReceive(), and SUCCESS_G.
Referenced by BL_CANPoll().
SysTick_Handler()
void SysTick_Handler (void)
Definition at line 145 of file main.c.
References bootloader_ms.
Variable Documentation
AHBClockRateHz
uint32_t AHBClockRateHz extern
Definition at line 17 of file rcc.c.
APB1ClockRateHz
uint32_t APB1ClockRateHz extern
Definition at line 15 of file rcc.c.
APB2ClockRateHz
uint32_t APB2ClockRateHz extern
Definition at line 16 of file rcc.c.
bootloader_ms
volatile uint32_t bootloader_ms = 0 static
Definition at line 42 of file main.c.
Referenced by main(), and SysTick_Handler().
clock_config
ClockRateConfig_t clock_config
Initial value:
= {
    .clock_source           = CLOCK_SOURCE_HSE,
    .use_pll                = false,
    .system_clock_target_hz = 16000000 ,
    .ahb_clock_target_hz    = ( 16000000 / 1),
    .apb1_clock_target_hz   = ( 16000000 / (1)),
    .apb2_clock_target_hz   = ( 16000000 / (1)),
}
Definition at line 23 of file main.c.
gpio_config
GPIOInitConfig_t gpio_config[]
Initial value:
= {
    GPIO_INIT_CANRX_PA11 ,
    GPIO_INIT_CANTX_PA12 ,
}
Definition at line 12 of file main.c.
PLLClockRateHz
uint32_t PLLClockRateHz extern
Definition at line 18 of file rcc.c.
q_rx_can
q_handle_t q_rx_can
Definition at line 38 of file main.c.
Referenced by BL_CANPoll(), CAN1_RX0_IRQHandler(), can_rx_irq_handler(), and main().
q_tx_can
q_handle_t q_tx_can
Definition at line 37 of file main.c.
Referenced by canTxSendToBack(), main(), and send_pending_can().