PER Firmware: source/dashboard/lcd/pages/calibration.h File Reference
calibration.h File Reference
Calibration page implementation.
Macros
#define CALIBRATION_STRING "calibration"
#define CALIBRATION_THROTTLE1 "thr1"
#define CALIBRATION_THROTTLE2 "thr2"
#define CALIBRATION_BRAKE1 "brk1"
#define CALIBRATION_BRAKE2 "brk2"
#define CALIBRATION_BRAKE_PRS1 "brkprs1"
#define CALIBRATION_BRAKE_PRS2 "brkprs2"
#define CALIBRATION_STATUS "status"
Functions
void calibration_telemetry_update ()
Updates the LCD display with current pedal telemetry data when on CALIBRATION page.
Detailed Description
Calibration page implementation.
Author
Irving Wang (irvin.nosp@m.gw@p.nosp@m.urdue.nosp@m..edu)
Definition in file calibration.h.
Macro Definition Documentation
CALIBRATION_BRAKE1
#define CALIBRATION_BRAKE1 "brk1"
Definition at line 16 of file calibration.h.
Referenced by calibration_telemetry_update().
CALIBRATION_BRAKE2
#define CALIBRATION_BRAKE2 "brk2"
Definition at line 17 of file calibration.h.
Referenced by calibration_telemetry_update().
CALIBRATION_BRAKE_PRS1
#define CALIBRATION_BRAKE_PRS1 "brkprs1"
Definition at line 18 of file calibration.h.
Referenced by calibration_telemetry_update().
CALIBRATION_BRAKE_PRS2
#define CALIBRATION_BRAKE_PRS2 "brkprs2"
Definition at line 19 of file calibration.h.
Referenced by calibration_telemetry_update().
CALIBRATION_STATUS
#define CALIBRATION_STATUS "status"
Definition at line 20 of file calibration.h.
Referenced by calibration_telemetry_update().
CALIBRATION_STRING
#define CALIBRATION_STRING "calibration"
Definition at line 11 of file calibration.h.
CALIBRATION_THROTTLE1
#define CALIBRATION_THROTTLE1 "thr1"
Definition at line 14 of file calibration.h.
Referenced by calibration_telemetry_update().
CALIBRATION_THROTTLE2
#define CALIBRATION_THROTTLE2 "thr2"
Definition at line 15 of file calibration.h.
Referenced by calibration_telemetry_update().
Function Documentation
calibration_telemetry_update()
void calibration_telemetry_update ()
Updates the LCD display with current pedal telemetry data when on CALIBRATION page.
Updates brake and throttle bars, raw ADC values, deviation percentages, and status indicators for brake and throttle pedals. Also displays fault statuses if detected.
Note
Only executes when current page is PAGE_CALIBRATION
Definition at line 23 of file calibration.c.
References raw_adc_values_t::b1, raw_adc_values_t::b2, raw_adc_values_t::brake1_pressure, raw_adc_values_t::brake2_pressure, CALIBRATION_BRAKE1, CALIBRATION_BRAKE2, CALIBRATION_BRAKE_PRS1, CALIBRATION_BRAKE_PRS2, CALIBRATION_STATUS, CALIBRATION_THROTTLE1, CALIBRATION_THROTTLE2, GREEN, is_latched(), NXT_setFontColor(), NXT_setText(), NXT_setTextFormatted(), raw_adc_values, RED, raw_adc_values_t::t1, and raw_adc_values_t::t2.