PER Firmware: common/can_library/can_common.h File Reference
can_common.h File Reference
Common functions and data structures used in every node in the CAN library.
#include <stdint.h>
#include "common/freertos/freertos.h"
#include "common/phal/can.h"
#include "common/can_library/generated/can_router.h"
Data Structures
struct can_peripheral_stats_t
struct can_stats_t
Macros
#define CAN_TX_BACKPRESSURE_MS (2)
#define CAN_TX_QUEUE_LENGTH (64)
#define CAN_RX_QUEUE_LENGTH (64)
#define CAN_TX_MAILBOX_CNT (3)
#define CAN_TX_TIMEOUT_MS (15)
#define CAN_TX_BLOCK_TIMEOUT (30 * 16000)
#define CAN_MAILBOX_HIGH_PRIO 0
#define CAN_MAILBOX_MED_PRIO 1
#define CAN_MAILBOX_LOW_PRIO 2
#define CAN_EFF_FLAG 0x80000000U /* EFF/SFF is set in the MSB */
#define CAN_RTR_FLAG 0x40000000U /* remote transmission request */
#define CAN_ERR_FLAG 0x20000000U /* error message frame */
#define CAN_SFF_MASK 0x000007FFU /* standard frame format (SFF) */
#define CAN_EFF_MASK 0x1FFFFFFFU /* extended frame format (EFF) */
#define CAN_ERR_MASK 0x1FFFFFFFU /* omit EFF, RTR, ERR flags */
#define CAN1_IDX 0
#define CAN2_IDX 1
#define CAN3_IDX 2
#define GET_PERIPH_IDX(bus)
#define NUM_CAN_PERIPHERALS_MAX 2
Functions
void CAN_enqueue_tx (CanMsgTypeDef_t *msg)
void CAN_tx_update ()
void CAN_rx_update ()
bool CAN_library_init ()
void CAN_handle_irq (CAN_TypeDef *bus, uint8_t fifo)
Variables
can_stats_t can_stats
volatile uint32_t last_can_rx_time_ms
QueueHandle_t q_rx_can
Detailed Description
Common functions and data structures used in every node in the CAN library.
Author
Irving Wang (irvin.nosp@m.gw@p.nosp@m.urdue.nosp@m..edu)
Ronak Jain (jain7.nosp@m.17@p.nosp@m.urdue.nosp@m..edu)
Definition in file can_common.h.
Macro Definition Documentation
CAN1_IDX
#define CAN1_IDX 0
Definition at line 47 of file can_common.h.
CAN2_IDX
#define CAN2_IDX 1
Definition at line 50 of file can_common.h.
CAN3_IDX
#define CAN3_IDX 2
Definition at line 53 of file can_common.h.
CAN_EFF_FLAG
#define CAN_EFF_FLAG 0x80000000U /* EFF/SFF is set in the MSB */
Definition at line 37 of file can_common.h.
Referenced by can_rx_irq_handler().
CAN_EFF_MASK
#define CAN_EFF_MASK 0x1FFFFFFFU /* extended frame format (EFF) */
Definition at line 43 of file can_common.h.
CAN_ERR_FLAG
#define CAN_ERR_FLAG 0x20000000U /* error message frame */
Definition at line 39 of file can_common.h.
CAN_ERR_MASK
#define CAN_ERR_MASK 0x1FFFFFFFU /* omit EFF, RTR, ERR flags */
Definition at line 44 of file can_common.h.
CAN_MAILBOX_HIGH_PRIO
#define CAN_MAILBOX_HIGH_PRIO 0
Definition at line 32 of file can_common.h.
CAN_MAILBOX_LOW_PRIO
#define CAN_MAILBOX_LOW_PRIO 2
Definition at line 34 of file can_common.h.
CAN_MAILBOX_MED_PRIO
#define CAN_MAILBOX_MED_PRIO 1
Definition at line 33 of file can_common.h.
CAN_RTR_FLAG
#define CAN_RTR_FLAG 0x40000000U /* remote transmission request */
Definition at line 38 of file can_common.h.
CAN_RX_QUEUE_LENGTH
#define CAN_RX_QUEUE_LENGTH (64)
Definition at line 26 of file can_common.h.
CAN_SFF_MASK
#define CAN_SFF_MASK 0x000007FFU /* standard frame format (SFF) */
Definition at line 42 of file can_common.h.
CAN_TX_BACKPRESSURE_MS
#define CAN_TX_BACKPRESSURE_MS (2)
Definition at line 24 of file can_common.h.
CAN_TX_BLOCK_TIMEOUT
#define CAN_TX_BLOCK_TIMEOUT (30 * 16000)
Definition at line 30 of file can_common.h.
CAN_TX_MAILBOX_CNT
#define CAN_TX_MAILBOX_CNT (3)
Definition at line 28 of file can_common.h.
CAN_TX_QUEUE_LENGTH
#define CAN_TX_QUEUE_LENGTH (64)
Definition at line 25 of file can_common.h.
CAN_TX_TIMEOUT_MS
#define CAN_TX_TIMEOUT_MS (15)
Definition at line 29 of file can_common.h.
GET_PERIPH_IDX
#define GET_PERIPH_IDX (bus)
Value:
((bus == CAN1) ? CAN1_IDX : CAN2_IDX)
Definition at line 61 of file can_common.h.
Referenced by CAN_rx_update().
NUM_CAN_PERIPHERALS_MAX
#define NUM_CAN_PERIPHERALS_MAX 2
Definition at line 67 of file can_common.h.
Function Documentation
CAN_enqueue_tx()
void CAN_enqueue_tx (CanMsgTypeDef_t * msg)
CAN_handle_irq()
void CAN_handle_irq (CAN_TypeDef * bus, uint8_t fifo)
Referenced by CAN1_RX0_IRQHandler().
CAN_library_init()
bool CAN_library_init ()
Referenced by main(), and main().
CAN_rx_update()
void CAN_rx_update ()
Definition at line 20 of file can_common.c.
References CanMsgTypeDef_t::Bus, CanMsgTypeDef_t::Data, CanMsgTypeDef_t::DLC, CanMsgTypeDef_t::ExtId, GET_PERIPH_IDX, CanMsgTypeDef_t::IDE, last_can_rx_time_ms, q_rx_can, and CanMsgTypeDef_t::StdId.
Referenced by main(), and main().
CAN_tx_update()
void CAN_tx_update ()
Referenced by main(), and main().
Variable Documentation
can_stats
can_stats_t can_stats extern
Definition at line 15 of file can_common.c.
last_can_rx_time_ms
volatile uint32_t last_can_rx_time_ms extern
Definition at line 16 of file can_common.c.
Referenced by CAN_rx_update(), and heartbeat_task().
q_rx_can
QueueHandle_t q_rx_can extern
Referenced by CAN_rx_update().