PER Firmware: source/g4_testing/canpiler.c File Reference
canpiler.c File Reference
#include "g4_testing.h"
#include <string.h>
#include "common/can_library/generated/DASHBOARD.h"
#include "common/phal/adc.h"
#include "common/phal/can.h"
#include "common/phal/dma.h"
#include "common/phal/gpio.h"
#include "common/phal/rcc.h"
#include "common/freertos/freertos.h"
#include "main.h"
#include "common/can_library/faults_common.h"
Macros
#define TargetCoreClockrateHz 16000000
Functions
void HardFault_Handler ()
void can_worker ()
DEFINE_TASK (fault_library_periodic, 10, osPriorityNormal, 1024)
DEFINE_TASK (can_worker, 0, osPriorityLow, 1024)
int main ()
Variables
GPIOInitConfig_t gpio_config []
ClockRateConfig_t clock_config
uint32_t APB1ClockRateHz
uint32_t APB2ClockRateHz
uint32_t AHBClockRateHz
uint32_t PLLClockRateHz
Macro Definition Documentation
TargetCoreClockrateHz
#define TargetCoreClockrateHz 16000000
Definition at line 21 of file canpiler.c.
Function Documentation
can_worker()
void can_worker ()
Definition at line 40 of file canpiler.c.
References CAN_rx_update(), and CAN_tx_update().
Referenced by main().
DEFINE_TASK() [1/2]
DEFINE_TASK (can_worker , 0 , osPriorityLow , 1024)
DEFINE_TASK() [2/2]
DEFINE_TASK (fault_library_periodic , 10 , osPriorityNormal , 1024)
HardFault_Handler()
void HardFault_Handler (void)
Definition at line 76 of file canpiler.c.
Referenced by main().
main()
int main (void)
Definition at line 48 of file canpiler.c.
References CAN_library_init(), can_worker(), clock_config, fault_library_periodic(), gpio_config, HardFault_Handler(), PHAL_configureClockRates(), PHAL_FDCAN_init(), PHAL_initGPIO(), and START_TASK.
Variable Documentation
AHBClockRateHz
uint32_t AHBClockRateHz extern
Definition at line 17 of file rcc.c.
APB1ClockRateHz
uint32_t APB1ClockRateHz extern
Definition at line 15 of file rcc.c.
APB2ClockRateHz
uint32_t APB2ClockRateHz extern
Definition at line 16 of file rcc.c.
clock_config
ClockRateConfig_t clock_config
Initial value:
= {
    .clock_source              = CLOCK_SOURCE_HSI,
    .use_pll                   = false,
    .vco_output_rate_target_hz = 16000000,
    .system_clock_target_hz    = 16000000 ,
    .ahb_clock_target_hz       = ( 16000000 / 1),
    .apb1_clock_target_hz      = ( 16000000 / (1)),
    .apb2_clock_target_hz      = ( 16000000 / (1)),
}
Definition at line 22 of file canpiler.c.
Referenced by main().
gpio_config
GPIOInitConfig_t gpio_config[]
Initial value:
= {
    GPIO_INIT_FDCAN2RX_PB12,
    GPIO_INIT_FDCAN2TX_PB13
}
Definition at line 16 of file canpiler.c.
Referenced by main().
PLLClockRateHz
uint32_t PLLClockRateHz extern
Definition at line 18 of file rcc.c.