PER Firmware: linker.BusLinker Class Reference
linker.BusLinker Class Reference
Public Member Functions
__init__ (self, str bus_name)
add_message (self, Message msg)
link (self)
Data Fields
bus_name = bus_name
int next_avail_id = 1
DefaultDict[int, List[Message]] msgs_by_prio = defaultdict(list)
DefaultDict[int, Set[int]] overrides_by_prio = defaultdict(set)
Set[int] all_used_ids = set()
int all_used_ids = 1
Protected Member Functions
_validate_overrides (self)
_link_priority_group (self, int priority)
Detailed Description
Definition at line 12 of file linker.py.
Constructor & Destructor Documentation
__init__()
linker.BusLinker.__init__ (self, str bus_name)
Definition at line 13 of file linker.py.
Member Function Documentation
_link_priority_group()
linker.BusLinker._link_priority_group (self, int priority) protected
Pass 2: Assign IDs to dynamic messages in this priority group.
Respects the 'Water Level' (next_avail_id) and skips reserved overrides.
Definition at line 62 of file linker.py.
References linker.BusLinker.msgs_by_prio, linker.BusLinker.next_avail_id, and linker.BusLinker.overrides_by_prio.
Referenced by linker.BusLinker.link().
_validate_overrides()
linker.BusLinker._validate_overrides (self) protected
Pass 1: Validate that overrides respect priority monotonicity.
An override in Priority 0 (e.g. 0x10) must be < an override in Priority 1 (e.g. 0x20).
Definition at line 39 of file linker.py.
References linker.BusLinker.overrides_by_prio.
Referenced by linker.BusLinker.link().
add_message()
linker.BusLinker.add_message (self, Message msg)
Definition at line 20 of file linker.py.
References linker.BusLinker.all_used_ids, linker.BusLinker.msgs_by_prio, and linker.BusLinker.overrides_by_prio.
link()
linker.BusLinker.link (self)
Execute the two-pass linking algorithm
Definition at line 29 of file linker.py.
References linker.BusLinker._link_priority_group(), linker.BusLinker._validate_overrides(), and linker.BusLinker.msgs_by_prio.
Field Documentation
all_used_ids [1/2]
Set[int] linker.BusLinker.all_used_ids = set()
Definition at line 18 of file linker.py.
Referenced by linker.BusLinker.add_message().
all_used_ids [2/2]
int linker.BusLinker.all_used_ids = 1
Definition at line 90 of file linker.py.
Referenced by linker.BusLinker.add_message().
bus_name
linker.BusLinker.bus_name = bus_name
Definition at line 14 of file linker.py.
msgs_by_prio
DefaultDict[int, List[Message]] linker.BusLinker.msgs_by_prio = defaultdict(list)
Definition at line 16 of file linker.py.
Referenced by linker.BusLinker._link_priority_group(), linker.BusLinker.add_message(), and linker.BusLinker.link().
next_avail_id
int linker.BusLinker.next_avail_id = 1
Definition at line 15 of file linker.py.
Referenced by linker.BusLinker._link_priority_group().
overrides_by_prio
DefaultDict[int, Set[int]] linker.BusLinker.overrides_by_prio = defaultdict(set)
Definition at line 17 of file linker.py.
Referenced by linker.BusLinker._link_priority_group(), linker.BusLinker._validate_overrides(), and linker.BusLinker.add_message().
The documentation for this class was generated from the following file:
common/can_library/canpiler/linker.py