PER Firmware: bootloader_commands.BootloaderCommand Class Reference
bootloader_commands.BootloaderCommand Class Reference
Public Member Functions
None __init__ (self, application_name, can_db)
can.Message firmware_size_msg (self, fw_size)
can.Message firmware_data_msg (self, double_word)
can.Message firmware_crc_msg (self, crc)
can.Message firmware_rst_msg (self)
decode_msg (self, can.Message msg)
Data Fields
TX_MSG = can_db.get_message_by_name(f"{application_name}_bl_cmd")
RX_MSG = can_db.get_message_by_name(f"{application_name}_bl_resp")
DATA_MSG = can_db.get_message_by_name(f"bitstream_data")
Static Public Attributes
list APP_IDs
dict TX_CMD
dict RX_CMD
dict BL_ERROR
Detailed Description
Definition at line 5 of file bootloader_commands.py.
Constructor & Destructor Documentation
__init__()
None bootloader_commands.BootloaderCommand.__init__ (self, application_name, can_db)
Definition at line 45 of file bootloader_commands.py.
References bootloader_commands.BootloaderCommand.APP_IDs.
Member Function Documentation
decode_msg()
bootloader_commands.BootloaderCommand.decode_msg (self, can.Message msg)
Definition at line 71 of file bootloader_commands.py.
References bootloader_commands.BootloaderCommand.RX_MSG.
firmware_crc_msg()
can.Message bootloader_commands.BootloaderCommand.firmware_crc_msg (self, crc)
Definition at line 63 of file bootloader_commands.py.
References bootloader_commands.BootloaderCommand.TX_CMD, and bootloader_commands.BootloaderCommand.TX_MSG.
firmware_data_msg()
can.Message bootloader_commands.BootloaderCommand.firmware_data_msg (self, double_word)
Definition at line 59 of file bootloader_commands.py.
References bootloader_commands.BootloaderCommand.DATA_MSG.
firmware_rst_msg()
can.Message bootloader_commands.BootloaderCommand.firmware_rst_msg (self)
Definition at line 67 of file bootloader_commands.py.
References bootloader_commands.BootloaderCommand.TX_CMD, and bootloader_commands.BootloaderCommand.TX_MSG.
firmware_size_msg()
can.Message bootloader_commands.BootloaderCommand.firmware_size_msg (self, fw_size)
Definition at line 55 of file bootloader_commands.py.
References bootloader_commands.BootloaderCommand.TX_CMD, and bootloader_commands.BootloaderCommand.TX_MSG.
Field Documentation
APP_IDs
bootloader_commands.BootloaderCommand.APP_IDs static
Initial value:
=  [
        "main_module",
        "dashboard",
        "torquevector",
        "a_box",
        "pdu",
        "l4_testing",
        "f4_testing",
        "f7_testing",
    ]
Definition at line 7 of file bootloader_commands.py.
Referenced by bootloader_commands.BootloaderCommand.__init__().
BL_ERROR
dict bootloader_commands.BootloaderCommand.BL_ERROR static
Initial value:
=  {
        0 : "BLERROR_CRC_FAIL",
        1 : "BLERROR_LOCKED",
        2 : "BLERROR_LOW_ADDR",
        3 : "BLERROR_ADDR_BOUND",
        4 : "BLERROR_FLASH",
    }
Definition at line 37 of file bootloader_commands.py.
DATA_MSG
bootloader_commands.BootloaderCommand.DATA_MSG = can_db.get_message_by_name(f"bitstream_data")
Definition at line 53 of file bootloader_commands.py.
Referenced by bootloader_commands.BootloaderCommand.firmware_data_msg().
RX_CMD
dict bootloader_commands.BootloaderCommand.RX_CMD static
Initial value:
=  {
        "BLSTAT_INVALID": 0,     # Invalid operation
        "BLSTAT_BOOT": 1,        # Bootloader boot alert
        "BLSTAT_WAIT": 2,        # Waiting to get BLCMD
        "BLSTAT_METDATA_RX": 3,  # Progress update for bootloader download
        "BLSTAT_PROGRESS": 4,    # Progress update for bootloader download
        "BLSTAT_DONE": 5,        # Completed the application download with CRC pass
        "BLSTAT_JUMP_TO_APP": 6, # About to jump to application
        "BLSTAT_INVAID_APP": 7,  # Did not attempt to boot because the starting address was invalid
        "BLSTAT_UNKNOWN_CMD": 8  # Incorrect CAN command message format
    }
Definition at line 25 of file bootloader_commands.py.
RX_MSG
bootloader_commands.BootloaderCommand.RX_MSG = can_db.get_message_by_name(f"{application_name}_bl_resp")
Definition at line 52 of file bootloader_commands.py.
Referenced by bootloader_commands.BootloaderCommand.decode_msg().
TX_CMD
dict bootloader_commands.BootloaderCommand.TX_CMD static
Initial value:
=  {
        "BLCMD_START": 0x1,   # Request to start firmware download
        "BLCMD_FW_DATA": 0x2, # Firmware data message
        "BLCMD_CRC": 0x3,     # Final CRC-32b check of firmware
        "BLCMD_RST": 0x5      # Request for reset (from app)
    }
Definition at line 18 of file bootloader_commands.py.
Referenced by bootloader_commands.BootloaderCommand.firmware_crc_msg(), bootloader_commands.BootloaderCommand.firmware_rst_msg(), and bootloader_commands.BootloaderCommand.firmware_size_msg().
TX_MSG
bootloader_commands.BootloaderCommand.TX_MSG = can_db.get_message_by_name(f"{application_name}_bl_cmd")
Definition at line 51 of file bootloader_commands.py.
Referenced by bootloader_commands.BootloaderCommand.firmware_crc_msg(), bootloader_commands.BootloaderCommand.firmware_rst_msg(), and bootloader_commands.BootloaderCommand.firmware_size_msg().
The documentation for this class was generated from the following file:
common/bootloader/bootloader_commands.py