PER Firmware: parser.Bus Class Reference
parser.Bus Class Reference
Public Member Functions
str macro_name (self)
Data Fields
name
Static Public Attributes
List tx_messages = field(default_factory=list)
List rx_messages = field(default_factory=list)
bool accept_all_messages = False
Detailed Description
Definition at line 150 of file parser.py.
Member Function Documentation
macro_name()
str parser.Bus.macro_name (self)
Definition at line 158 of file parser.py.
Field Documentation
accept_all_messages
bool parser.Bus.accept_all_messages = False static
Definition at line 155 of file parser.py.
name
parser.Bus.name
Definition at line 159 of file parser.py.
rx_messages
List parser.Bus.rx_messages = field(default_factory=list) static
Definition at line 154 of file parser.py.
Referenced by can_process.CANRxThread.get_all_signals(), can_process.CANRxThread.get_signal(), and can_process.CANRxThread.run().
tx_messages
List parser.Bus.tx_messages = field(default_factory=list) static
Definition at line 153 of file parser.py.
The documentation for this class was generated from the following file:
common/can_library/canpiler/parser.py