PER Firmware: common/phal_G4/spi/spi.c File Reference
spi.c File Reference
G4 SPI.
#include "common/phal_G4/spi/spi.h"
Functions
static void handleTxComplete (DMA_TypeDef *dma_periph, uint8_t channel)
bool PHAL_SPI_init (SPI_InitConfig_t *cfg)
Initilize SPI peripheral with the configuired structure.
bool PHAL_SPI_transfer_noDMA (SPI_InitConfig_t *spi, const uint8_t *out_data, uint32_t txlen, uint32_t rxlen, uint8_t *in_data)
SPI handle.
bool PHAL_SPI_transfer (SPI_InitConfig_t *spi, const uint8_t *out_data, const uint32_t data_len, uint8_t *in_data)
bool PHAL_SPI_busy (SPI_InitConfig_t *cfg)
Check for current SPI transaction to complete.
void PHAL_SPI_ForceReset (SPI_InitConfig_t *spi)
void DMA1_Channel3_IRQHandler (void)
void DMA1_Channel5_IRQHandler (void)
void DMA2_Channel3_IRQHandler (void)
uint8_t PHAL_SPI_readByte (SPI_InitConfig_t *spi, uint8_t address, bool skipDummy)
Blocking function to read a single byte from a SPI device. Useful for Initilization functions that just need to read a single byte in a blocking function.
uint8_t PHAL_SPI_writeByte (SPI_InitConfig_t *spi, uint8_t address, uint8_t writeDat)
Blocking function to write a single byte to a SPI device. Useful for Initilization functions that just need to write a single byte in a blocking function.
Variables
uint32_t APB2ClockRateHz
uint32_t APB1ClockRateHz
static volatile SPI_InitConfig_t * dma1_active_tx [8] = {0}
static volatile SPI_InitConfig_t * dma2_active_tx [8] = {0}
static uint16_t trash_can
static uint16_t zero
Detailed Description
G4 SPI.
Author
Ronak Jain
Version
0.1
Definition in file spi.c.
Function Documentation
DMA1_Channel3_IRQHandler()
void DMA1_Channel3_IRQHandler (void)
Definition at line 305 of file spi.c.
References handleTxComplete().
DMA1_Channel5_IRQHandler()
void DMA1_Channel5_IRQHandler (void)
Definition at line 309 of file spi.c.
References handleTxComplete().
DMA2_Channel3_IRQHandler()
void DMA2_Channel3_IRQHandler (void)
Definition at line 313 of file spi.c.
References handleTxComplete().
handleTxComplete()
static void handleTxComplete (DMA_TypeDef * dma_periph, uint8_t channel) static
Definition at line 245 of file spi.c.
References SPI_InitConfig_t::_busy, SPI_InitConfig_t::_direct_mode_error, SPI_InitConfig_t::_error, SPI_InitConfig_t::_fifo_overrun, dma_init_t::channel_idx, dma1_active_tx, dma2_active_tx, SPI_InitConfig_t::nss_gpio_pin, SPI_InitConfig_t::nss_gpio_port, SPI_InitConfig_t::nss_sw, dma_init_t::periph, SPI_InitConfig_t::periph, PHAL_stopTxfer(), PHAL_writeGPIO(), SPI_InitConfig_t::rx_dma_cfg, and SPI_InitConfig_t::tx_dma_cfg.
PHAL_SPI_busy()
bool PHAL_SPI_busy (SPI_InitConfig_t * cfg)
Check for current SPI transaction to complete.
Parameters
cfg Spi config
Returns
true
false
Definition at line 222 of file spi.c.
References SPI_InitConfig_t::_busy.
PHAL_SPI_ForceReset()
void PHAL_SPI_ForceReset (SPI_InitConfig_t * spi)
Definition at line 226 of file spi.c.
References SPI_InitConfig_t::periph.
PHAL_SPI_init()
bool PHAL_SPI_init (SPI_InitConfig_t * handle)
Initilize SPI peripheral with the configuired structure.
Parameters
handle SPI handle to configure.
Returns
true
false
Definition at line 22 of file spi.c.
References SPI_InitConfig_t::_busy, SPI_InitConfig_t::_direct_mode_error, SPI_InitConfig_t::_error, SPI_InitConfig_t::_fifo_overrun, APB1ClockRateHz, APB2ClockRateHz, CLAMP, SPI_InitConfig_t::cpha, SPI_InitConfig_t::cpol, SPI_InitConfig_t::data_len, SPI_InitConfig_t::data_rate, LOG2_DOWN(), SPI_InitConfig_t::mode, SPI_InitConfig_t::nss_gpio_pin, SPI_InitConfig_t::nss_gpio_port, SPI_InitConfig_t::nss_sw, SPI_InitConfig_t::periph, PHAL_initDMA(), PHAL_writeGPIO(), SPI_InitConfig_t::rx_dma_cfg, SPI_MODE_MASTER, SPI_InitConfig_t::tx_dma_cfg, and zero.
PHAL_SPI_readByte()
uint8_t PHAL_SPI_readByte (SPI_InitConfig_t * spi, uint8_t address, bool skipDummy)
Blocking function to read a single byte from a SPI device. Useful for Initilization functions that just need to read a single byte in a blocking function.
Parameters
spi Spi handle
address Address of data to read
skipDummy Return the 3rd byte read instead of the 2nd byte
Definition at line 317 of file spi.c.
References PHAL_SPI_busy(), PHAL_SPI_transfer(), PHAL_SPI_transfer_noDMA(), and SPI_InitConfig_t::rx_dma_cfg.
PHAL_SPI_transfer()
bool PHAL_SPI_transfer (SPI_InitConfig_t * spi, const uint8_t * out_data, const uint32_t data_len, uint8_t * in_data)
Definition at line 162 of file spi.c.
References SPI_InitConfig_t::_busy, dma_init_t::channel_idx, dma1_active_tx, dma2_active_tx, dma_init_t::mem_inc, SPI_InitConfig_t::mode, SPI_InitConfig_t::nss_gpio_pin, SPI_InitConfig_t::nss_gpio_port, SPI_InitConfig_t::nss_sw, dma_init_t::periph, SPI_InitConfig_t::periph, PHAL_DMA_setMemAddress(), PHAL_DMA_setTxferLength(), PHAL_reEnable(), PHAL_SPI_busy(), PHAL_writeGPIO(), SPI_InitConfig_t::rx_dma_cfg, SPI_MODE_MASTER, trash_can, SPI_InitConfig_t::tx_dma_cfg, and zero.
PHAL_SPI_transfer_noDMA()
bool PHAL_SPI_transfer_noDMA (SPI_InitConfig_t * spi, const uint8_t * out_data, uint32_t txlen, uint32_t rxlen, uint8_t * in_data)
SPI handle.
Parameters
spi SPI handle
out_data Address of data buffer to put on MOSI line
txlen Number of SPI Packets to Send
rxlen Number of SPI Packets to Receive
in_data Address of data buffer to put data coming in MISO line
Returns
true Successfully completed non-DMA SPI transaction
false Unable to complete non-DMA SPI transaction
Definition at line 97 of file spi.c.
References SPI_InitConfig_t::_busy, SPI_InitConfig_t::mode, SPI_InitConfig_t::nss_gpio_pin, SPI_InitConfig_t::nss_gpio_port, SPI_InitConfig_t::nss_sw, SPI_InitConfig_t::periph, PHAL_SPI_busy(), PHAL_writeGPIO(), and SPI_MODE_MASTER.
PHAL_SPI_writeByte()
uint8_t PHAL_SPI_writeByte (SPI_InitConfig_t * spi, uint8_t address, uint8_t writeDat)
Blocking function to write a single byte to a SPI device. Useful for Initilization functions that just need to write a single byte in a blocking function.
Parameters
spi Spi handle
address Address of data to read
writeDat Data to write to address
Definition at line 334 of file spi.c.
References PHAL_SPI_busy(), PHAL_SPI_transfer(), PHAL_SPI_transfer_noDMA(), and SPI_InitConfig_t::tx_dma_cfg.
Variable Documentation
APB1ClockRateHz
uint32_t APB1ClockRateHz extern
Definition at line 15 of file rcc.c.
APB2ClockRateHz
uint32_t APB2ClockRateHz extern
Definition at line 16 of file rcc.c.
dma1_active_tx
volatile SPI_InitConfig_t* dma1_active_tx[8] = {0} static
Definition at line 14 of file spi.c.
Referenced by handleTxComplete(), and PHAL_SPI_transfer().
dma2_active_tx
volatile SPI_InitConfig_t* dma2_active_tx[8] = {0} static
Definition at line 15 of file spi.c.
Referenced by handleTxComplete(), and PHAL_SPI_transfer().
trash_can
uint16_t trash_can static
Definition at line 17 of file spi.c.
zero
uint16_t zero static
Definition at line 18 of file spi.c.