PER Firmware: common/common_defs/common_defs.h File Reference
common_defs.h File Reference
Common defs for the entire firmware repository. Dont let this get too out of control please.
#include <stdint.h>
Macros
#define MIN(x, y)
#define MAX(x, y)
#define CLAMP(x, min, max)
#define ABS(x)
#define PI (3.14159f)
#define DEG_TO_RAD (PI / 180.0f)
#define G_TO_M_S (9.80665f)
#define HSI_TRIM_TORQUE_VECTOR 15
#define HSI_TRIM_MAIN_MODULE 15
#define HSI_TRIM_PDU 16
#define HSI_TRIM_DASHBOARD 15
#define HSI_TRIM_DAQ 17
#define HSI_TRIM_A_BOX 16
Functions
static int32_t min_i (int32_t x, int32_t y)
static float min_f (float x, float y)
static int32_t max_i (int32_t x, int32_t y)
static float max_f (float x, float y)
static int32_t clamp_i (int32_t x, int32_t min, int32_t max)
static float clamp_f (float x, float min, float max)
static int32_t abs_i (int32_t x)
static float abs_f (float x)
static uint32_t LOG2_DOWN (uint32_t x)
static uint32_t LOG2_UP (uint32_t x)
static uint32_t ROUNDDOWN (uint32_t a, uint32_t n)
static uint32_t ROUNDUP (uint32_t a, uint32_t n)
Variables
static constexpr uint32_t CONN_LED_TIMEOUT_MS = 1000
static constexpr uint32_t PREFLIGHT_DURATION_MS = 1500
static constexpr uint32_t HEARTBEAT_PERIOD_MS = 100
Detailed Description
Common defs for the entire firmware repository. Dont let this get too out of control please.
Author
Adam Busch (busch.nosp@m.8@pu.nosp@m.rdue..nosp@m.edu)
Version
0.1
Date
2022-01-26
Copyright
Copyright (c) 2022
Definition in file common_defs.h.
Macro Definition Documentation
ABS
#define ABS (x)
Value:
_Generic((x), float: abs_f, double: abs_f, default: abs_i)(x)
Definition at line 44 of file common_defs.h.
Referenced by BMI088_readGyro(), calibrationTelemetryUpdate(), and pedalsPeriodic().
CLAMP
#define CLAMP (x, min, max)
Value:
    _Generic((x), \
    float: clamp_f, \
    double: clamp_f, \
    default: clamp_i \
)((x), (min), (max))
Definition at line 36 of file common_defs.h.
Referenced by cooling_driver_request_CALLBACK(), pedalsPeriodic(), and PHAL_SPI_init().
DEG_TO_RAD
#define DEG_TO_RAD (PI / 180.0f)
Definition at line 69 of file common_defs.h.
Referenced by BMI088_getGyroScale().
G_TO_M_S
#define G_TO_M_S (9.80665f)
Definition at line 70 of file common_defs.h.
Referenced by BMI088_readAccel().
HSI_TRIM_A_BOX
#define HSI_TRIM_A_BOX 16
Definition at line 78 of file common_defs.h.
HSI_TRIM_DAQ
#define HSI_TRIM_DAQ 17
Definition at line 77 of file common_defs.h.
HSI_TRIM_DASHBOARD
#define HSI_TRIM_DASHBOARD 15
Definition at line 76 of file common_defs.h.
HSI_TRIM_MAIN_MODULE
#define HSI_TRIM_MAIN_MODULE 15
Definition at line 74 of file common_defs.h.
HSI_TRIM_PDU
#define HSI_TRIM_PDU 16
Definition at line 75 of file common_defs.h.
Referenced by main().
HSI_TRIM_TORQUE_VECTOR
#define HSI_TRIM_TORQUE_VECTOR 15
Definition at line 73 of file common_defs.h.
MAX
#define MAX (x, y)
Value:
_Generic((x), float: max_f, double: max_f, default: max_i)((x), (y))
Definition at line 24 of file common_defs.h.
Referenced by BMI088_readGyro().
MIN
#define MIN (x, y)
Value:
_Generic((x), float: min_f, double: min_f, default: min_i)((x), (y))
Definition at line 20 of file common_defs.h.
PI
#define PI (3.14159f)
Definition at line 66 of file common_defs.h.
Function Documentation
abs_f()
static float abs_f (float x) inline static
Definition at line 43 of file common_defs.h.
abs_i()
static int32_t abs_i (int32_t x) inline static
Definition at line 42 of file common_defs.h.
clamp_f()
static float clamp_f (float x, float min, float max) inline static
Definition at line 31 of file common_defs.h.
clamp_i()
static int32_t clamp_i (int32_t x, int32_t min, int32_t max) inline static
Definition at line 26 of file common_defs.h.
LOG2_DOWN()
static uint32_t LOG2_DOWN (uint32_t x) inline static
Definition at line 47 of file common_defs.h.
Referenced by LOG2_UP(), and PHAL_SPI_init().
LOG2_UP()
static uint32_t LOG2_UP (uint32_t x) inline static
Definition at line 52 of file common_defs.h.
References LOG2_DOWN().
max_f()
static float max_f (float x, float y) inline static
Definition at line 23 of file common_defs.h.
max_i()
static int32_t max_i (int32_t x, int32_t y) inline static
Definition at line 22 of file common_defs.h.
min_f()
static float min_f (float x, float y) inline static
Definition at line 19 of file common_defs.h.
min_i()
static int32_t min_i (int32_t x, int32_t y) inline static
Definition at line 18 of file common_defs.h.
ROUNDDOWN()
static uint32_t ROUNDDOWN (uint32_t a, uint32_t n) inline static
Definition at line 56 of file common_defs.h.
Referenced by PHAL_initUSART(), and ROUNDUP().
ROUNDUP()
static uint32_t ROUNDUP (uint32_t a, uint32_t n) inline static
Definition at line 61 of file common_defs.h.
References ROUNDDOWN().
Referenced by mapMem(), and PHAL_initUSART().
Variable Documentation
CONN_LED_TIMEOUT_MS
uint32_t CONN_LED_TIMEOUT_MS = 1000 static constexpr
Definition at line 80 of file common_defs.h.
Referenced by heartbeat_task().
HEARTBEAT_PERIOD_MS
uint32_t HEARTBEAT_PERIOD_MS = 100 static constexpr
Definition at line 82 of file common_defs.h.
PREFLIGHT_DURATION_MS
uint32_t PREFLIGHT_DURATION_MS = 1500 static constexpr
Definition at line 81 of file common_defs.h.
Referenced by heartbeat_task().