PER Firmware: common/phal_F4_F7/usart/usart.c File Reference
usart.c File Reference
#include "common/phal_F4_F7/usart/usart.h"
#include "common/common_defs/common_defs.h"
Data Structures
struct usart_active_transfer_t
Enumerations
enum usart_dma_mode_t { USART_DMA_TX , USART_DMA_RX }
Functions
bool PHAL_initUSART (usart_init_t *handle, const uint32_t fck)
Initialize a USART Peripheral with desired settings.
void PHAL_usartTxBl (usart_init_t *handle, uint8_t *data, uint32_t len)
TX using no DMA (blocks until complete)
void PHAL_usartRxBl (usart_init_t *handle, uint8_t *data, uint32_t len)
RX using no DMA (blocks until complete)
bool PHAL_usartTxDma (usart_init_t *handle, uint16_t *data, uint32_t len)
Starts a tx using dma, use PHAL_usartTxDmaComplete to ensure the previous transmission is complete.
volatile bool PHAL_usartTxBusy (usart_init_t *handle)
Returns whether USART peripheral is currently transmitting data.
bool PHAL_usartRxDma (usart_init_t *handle, uint16_t *data, uint32_t len, bool cont)
Starts an rx using dma of a specific length.
bool PHAL_disableContinousRxDMA (usart_init_t *handle)
Disables the Continous RX that was previously used.
bool PHAL_usartRxBusy (usart_init_t *handle)
Returns whether USART peripheral is currently receiving data.
static void handleUsartIRQ (USART_TypeDef *handle, uint8_t idx)
static void handleDMAxComplete (uint8_t idx, uint32_t irq, uint8_t dma_type)
Handle DMA interrupts.
__WEAK void usart_recieve_complete_callback (usart_init_t *handle)
Callback function called immediately after reception of a USART RX message Uses USART IDLE line interrupt.
Variables
volatile usart_active_transfer_t active_uarts [TOTAL_NUM_UART]
Detailed Description
Author
Aditya Anand (anand.nosp@m.89@p.nosp@m.urdue.nosp@m..edu) - Redesign of L4 UART HAL by Dawson Moore (moore.nosp@m.800@.nosp@m.purdu.nosp@m.e.ed.nosp@m.u)
Version
0.1
Date
2024-1-4
Copyright
Copyright (c) 2024
Definition in file usart.c.
Enumeration Type Documentation
usart_dma_mode_t
enum usart_dma_mode_t
Enumerator
USART_DMA_TX
USART is transmitting over DMA.
USART_DMA_RX
USART is recieving over DMA.
Definition at line 19 of file usart.c.
Function Documentation
handleDMAxComplete()
static void handleDMAxComplete (uint8_t idx, uint32_t irq, uint8_t dma_type) static
Handle DMA interrupts.
Definition at line 549 of file usart.c.
References usart_active_transfer_t::_tx_busy, usart_active_transfer_t::active_handle, active_uarts, usart_rx_errors_t::dma_direct_mode_error, usart_tx_errors_t::dma_direct_mode_error, usart_rx_errors_t::dma_fifo_overrun, usart_tx_errors_t::dma_fifo_overrun, usart_rx_errors_t::dma_transfer_error, usart_tx_errors_t::dma_transfer_error, dma_init_t::periph, PHAL_stopTxfer(), usart_init_t::rx_dma_cfg, usart_init_t::rx_errors, dma_init_t::stream_idx, usart_init_t::tx_dma_cfg, usart_init_t::tx_errors, and USART_DMA_TX.
Referenced by DMA1_Channel1_IRQHandler(), DMA1_Channel2_IRQHandler(), DMA1_Channel3_IRQHandler(), DMA1_Channel4_IRQHandler(), DMA1_Channel5_IRQHandler(), DMA1_Channel7_IRQHandler(), DMA2_Channel6_IRQHandler(), and DMA2_Channel7_IRQHandler().
handleUsartIRQ()
static void handleUsartIRQ (USART_TypeDef * handle, uint8_t idx) static
Definition at line 398 of file usart.c.
References usart_active_transfer_t::_rx_busy, usart_active_transfer_t::active_handle, active_uarts, usart_rx_errors_t::framing_error, usart_rx_errors_t::noise_detected, usart_rx_errors_t::overrun, usart_rx_errors_t::parity_error, usart_init_t::periph, PHAL_DMA_setTxferLength(), PHAL_reEnable(), PHAL_stopTxfer(), usart_init_t::rx_errors, usart_active_transfer_t::rxfer_size, and usart_recieve_complete_callback().
Referenced by LPUART1_IRQHandler(), USART1_IRQHandler(), USART2_IRQHandler(), and USART3_IRQHandler().
PHAL_disableContinousRxDMA()
bool PHAL_disableContinousRxDMA (usart_init_t * handle)
Disables the Continous RX that was previously used.
Parameters
handle The handle for the usart configuration
Definition at line 337 of file usart.c.
References usart_active_transfer_t::_rx_busy, usart_active_transfer_t::active_handle, active_uarts, usart_active_transfer_t::cont_rx, usart_init_t::periph, and usart_init_t::usart_active_num.
PHAL_initUSART()
bool PHAL_initUSART (usart_init_t * handle, const uint32_t fck)
Initialize a USART Peripheral with desired settings.
Parameters
handle Handle containing settings for USART peripheral
fck Clock rate going to USART peripheral (APBx bus)
Returns
true Successfully initialized USART peripheral
false Failed to initialize USART peripheral
Definition at line 34 of file usart.c.
References usart_active_transfer_t::active_handle, active_uarts, usart_init_t::address, usart_init_t::baud_rate, usart_init_t::obsample, OV_16, OV_8, usart_init_t::ovsample, usart_init_t::parity, usart_init_t::periph, PHAL_initDMA(), PT_NONE, ROUNDDOWN(), ROUNDUP(), usart_init_t::rx_dma_cfg, usart_init_t::stop_bits, usart_init_t::tx_dma_cfg, usart_init_t::usart_active_num, usart_init_t::wake_addr, and usart_init_t::word_length.
Referenced by main(), and main().
PHAL_usartRxBl()
void PHAL_usartRxBl (usart_init_t * handle, uint8_t * data, uint32_t len)
RX using no DMA (blocks until complete)
Parameters
handle The handle for the usart configuration
data The address of the data to receive
len Number of u8s expected to receive. Will block if not received.
Definition at line 182 of file usart.c.
References usart_init_t::periph.
PHAL_usartRxBusy()
bool PHAL_usartRxBusy (usart_init_t * handle)
Returns whether USART peripheral is currently receiving data.
Parameters
handle Handle of USART peripheral check
Returns
true USART peripheral is currently receiving a message
false USART peripheal is not currently receiving a message
Definition at line 394 of file usart.c.
References usart_active_transfer_t::_rx_busy, active_uarts, and usart_init_t::usart_active_num.
PHAL_usartRxDma()
bool PHAL_usartRxDma (usart_init_t * handle, uint16_t * data, uint32_t len, bool cont)
Starts an rx using dma of a specific length.
Parameters
handle The handle for the usart configuration
data The address to put the received data, ensure a cast to (uint16_t *), even if 8 bits
len Number of units of data, depending on the configured word length
cont Enable Continous RX using the idle line interrupt (only need to call this function once, and HAL will keep recieving messages of the same length)
Definition at line 277 of file usart.c.
References usart_active_transfer_t::active_handle, active_uarts, usart_active_transfer_t::cont_rx, usart_init_t::periph, PHAL_DMA_setMemAddress(), usart_init_t::rx_dma_cfg, usart_active_transfer_t::rxfer_size, and usart_init_t::usart_active_num.
PHAL_usartTxBl()
void PHAL_usartTxBl (usart_init_t * handle, uint8_t * data, uint32_t len)
TX using no DMA (blocks until complete)
Parameters
handle The handle for the usart configuration
data The address of the data to send
len Number of u8s
Definition at line 150 of file usart.c.
References usart_init_t::periph.
PHAL_usartTxBusy()
volatile bool PHAL_usartTxBusy (usart_init_t * handle)
Returns whether USART peripheral is currently transmitting data.
Parameters
handle Handle of USART peripheral to check
Returns
true USART peripheral is currently sending a message
false USART peripheal is not currently sending a message
Definition at line 273 of file usart.c.
References usart_active_transfer_t::_tx_busy, active_uarts, and usart_init_t::usart_active_num.
Referenced by lcd_tx_cmd().
PHAL_usartTxDma()
bool PHAL_usartTxDma (usart_init_t * handle, uint16_t * data, uint32_t len)
Starts a tx using dma, use PHAL_usartTxDmaComplete to ensure the previous transmission is complete.
Parameters
handle The handle for the usart configuration
data The address of the data to send, ensure a cast to (uint16_t *), even if 8 bits
len Number of units of data, depending on the configured word length
Definition at line 207 of file usart.c.
References usart_active_transfer_t::_tx_busy, usart_active_transfer_t::active_handle, active_uarts, usart_init_t::periph, PHAL_DMA_setMemAddress(), PHAL_DMA_setTxferLength(), PHAL_startTxfer(), usart_init_t::tx_dma_cfg, and usart_init_t::usart_active_num.
Referenced by lcd_tx_cmd(), and usartTXTest().
usart_recieve_complete_callback()
__WEAK void usart_recieve_complete_callback (usart_init_t * handle)
Callback function called immediately after reception of a USART RX message Uses USART IDLE line interrupt.
NOTE: this is executed during an interrupt handler call, so keep code in this function light
Parameters
handle Handle of USART peripheral that just recieved a message
Definition at line 724 of file usart.c.
Referenced by handleUsartIRQ().
Variable Documentation
active_uarts
volatile usart_active_transfer_t active_uarts[TOTAL_NUM_UART]
Definition at line 32 of file usart.c.
Referenced by handleDMAxComplete(), handleDMAxComplete(), handleUsartIRQ(), handleUsartIRQ(), PHAL_disableContinousRxDMA(), PHAL_initUSART(), PHAL_usartRxBusy(), PHAL_usartRxDma(), PHAL_usartRxDma(), PHAL_usartTxBusy(), PHAL_usartTxDma(), and PHAL_usartTxDma().