PER Firmware: common/phal_G4/fdcan/fdcan.c File Reference
fdcan.c File Reference
G4 FDCAN.
#include "common/phal_G4/fdcan/fdcan.h"
#include "common/phal_G4/fdcan/fdcan_priv.h"
Functions
static uint32_t PHAL_FDCAN_get_ram_base (FDCAN_GlobalTypeDef *fdcan)
static int PHAL_FDCAN_makeNBTP (uint32_t ker_hz, uint32_t baud_bps, uint32_t *nbtp_out)
static void PHAL_FDCAN_setExtendedFilter (FDCAN_GlobalTypeDef *fdcan, uint32_t num_xid, uint32_t *xid_list)
static void PHAL_FDCAN_setStandardFilter (FDCAN_GlobalTypeDef *fdcan, uint32_t num_sid, uint32_t *sid_list)
void PHAL_FDCAN_setFilters (FDCAN_GlobalTypeDef *fdcan, uint32_t *sid_list, uint32_t num_sid, uint32_t *xid_list, uint32_t num_xid)
bool PHAL_FDCAN_init (FDCAN_GlobalTypeDef *fdcan, bool test_mode, uint32_t bit_rate)
bool PHAL_FDCAN_txFifoFree (FDCAN_GlobalTypeDef *fdcan)
void PHAL_FDCAN_send (CanMsgTypeDef_t *msg)
static uint8_t dlc_to_len (uint8_t dlc)
static int PHAL_FDCAN_getRxMessage (FDCAN_GlobalTypeDef *fdcan, CanMsgTypeDef_t *m)
void PHAL_FDCAN_RX_IRQHandler (FDCAN_GlobalTypeDef *fdcan)
void PHAL_FDCAN_rxCallback (CanMsgTypeDef_t *msg)
void FDCAN1_IT0_IRQHandler (void)
void FDCAN2_IT0_IRQHandler (void)
void FDCAN3_IT0_IRQHandler (void)
Detailed Description
G4 FDCAN.
Author
Eileen Yoon
Version
0.1
Date
2025-08-11
Copyright
Copyright (c) 2025
Definition in file fdcan.c.
Function Documentation
dlc_to_len()
static uint8_t dlc_to_len (uint8_t dlc) inline static
Definition at line 273 of file fdcan.c.
Referenced by PHAL_FDCAN_getRxMessage().
FDCAN1_IT0_IRQHandler()
void FDCAN1_IT0_IRQHandler (void)
Definition at line 364 of file fdcan.c.
References PHAL_FDCAN_RX_IRQHandler().
FDCAN2_IT0_IRQHandler()
void FDCAN2_IT0_IRQHandler (void)
Definition at line 368 of file fdcan.c.
References PHAL_FDCAN_RX_IRQHandler().
FDCAN3_IT0_IRQHandler()
void FDCAN3_IT0_IRQHandler (void)
Definition at line 372 of file fdcan.c.
References PHAL_FDCAN_RX_IRQHandler().
PHAL_FDCAN_get_ram_base()
static uint32_t PHAL_FDCAN_get_ram_base (FDCAN_GlobalTypeDef * fdcan) static
Definition at line 16 of file fdcan.c.
References SRAMCAN_SIZE.
Referenced by PHAL_FDCAN_getRxMessage(), PHAL_FDCAN_send(), PHAL_FDCAN_setExtendedFilter(), and PHAL_FDCAN_setStandardFilter().
PHAL_FDCAN_getRxMessage()
static int PHAL_FDCAN_getRxMessage (FDCAN_GlobalTypeDef * fdcan, CanMsgTypeDef_t * m) static
Definition at line 279 of file fdcan.c.
References CanMsgTypeDef_t::Bus, CanMsgTypeDef_t::Data, CanMsgTypeDef_t::DLC, dlc_to_len(), CanMsgTypeDef_t::ExtId, CanMsgTypeDef_t::IDE, PHAL_FDCAN_get_ram_base(), SRAMCAN_RF0_SIZE, SRAMCAN_RF0SA, and CanMsgTypeDef_t::StdId.
Referenced by PHAL_FDCAN_RX_IRQHandler().
PHAL_FDCAN_init()
bool PHAL_FDCAN_init (FDCAN_GlobalTypeDef * fdcan, bool test_mode, uint32_t bit_rate)
< Accept in Rx FIFO 0
< Accept in Rx FIFO 0
< Accept in Rx FIFO 0
< Accept in Rx FIFO 0
Definition at line 146 of file fdcan.c.
References FDCAN_ACCEPT_IN_RX_FIFO0, PHAL_FDCAN_makeNBTP(), and RCC_FDCANCLKSOURCE_PCLK1.
Referenced by main(), and main().
PHAL_FDCAN_makeNBTP()
static int PHAL_FDCAN_makeNBTP (uint32_t ker_hz, uint32_t baud_bps, uint32_t * nbtp_out) static
Definition at line 30 of file fdcan.c.
Referenced by PHAL_FDCAN_init().
PHAL_FDCAN_RX_IRQHandler()
void PHAL_FDCAN_RX_IRQHandler (FDCAN_GlobalTypeDef * fdcan)
Definition at line 339 of file fdcan.c.
References PHAL_FDCAN_getRxMessage(), and PHAL_FDCAN_rxCallback().
Referenced by FDCAN1_IT0_IRQHandler(), FDCAN2_IT0_IRQHandler(), and FDCAN3_IT0_IRQHandler().
PHAL_FDCAN_rxCallback()
void PHAL_FDCAN_rxCallback (CanMsgTypeDef_t * msg)
Definition at line 360 of file fdcan.c.
Referenced by PHAL_FDCAN_RX_IRQHandler().
PHAL_FDCAN_send()
void PHAL_FDCAN_send (CanMsgTypeDef_t * msg)
Definition at line 219 of file fdcan.c.
References PHAL_FDCAN_get_ram_base(), SRAMCAN_TFQ_SIZE, and SRAMCAN_TFQSA.
Referenced by PHAL_FDCAN_testExtended().
PHAL_FDCAN_setExtendedFilter()
static void PHAL_FDCAN_setExtendedFilter (FDCAN_GlobalTypeDef * fdcan, uint32_t num_xid, uint32_t * xid_list) static
Definition at line 84 of file fdcan.c.
References MAX_NUM_XID_FILTER, PHAL_FDCAN_get_ram_base(), and SRAMCAN_FLESA.
Referenced by PHAL_FDCAN_setFilters().
PHAL_FDCAN_setFilters()
void PHAL_FDCAN_setFilters (FDCAN_GlobalTypeDef * fdcan, uint32_t * sid_list, uint32_t num_sid, uint32_t * xid_list, uint32_t num_xid)
< Reject
< Reject
< Accept in Rx FIFO 0
< Accept in Rx FIFO 0
Definition at line 126 of file fdcan.c.
References FDCAN_ACCEPT_IN_RX_FIFO0, FDCAN_REJECT, PHAL_FDCAN_setExtendedFilter(), and PHAL_FDCAN_setStandardFilter().
Referenced by main().
PHAL_FDCAN_setStandardFilter()
static void PHAL_FDCAN_setStandardFilter (FDCAN_GlobalTypeDef * fdcan, uint32_t num_sid, uint32_t * sid_list) static
Definition at line 107 of file fdcan.c.
References MAX_NUM_SID_FILTER, PHAL_FDCAN_get_ram_base(), and SRAMCAN_FLSSA.
Referenced by PHAL_FDCAN_setFilters().
PHAL_FDCAN_txFifoFree()
bool PHAL_FDCAN_txFifoFree (FDCAN_GlobalTypeDef * fdcan)
Definition at line 214 of file fdcan.c.