PER Firmware: common/phal_F4_F7/spi/spi.c File Reference
spi.c File Reference
PER Serial Peripheral Interface Device driver for STM32F4 and STM32F7.
#include "common/phal_F4_F7/spi/spi.h"
Functions
static void handleTxComplete ()
Handle TCIF interrupt signaling end of TX transaction.
bool PHAL_SPI_init (SPI_InitConfig_t *cfg)
Initilize SPI peripheral with the configuired structure.
bool PHAL_SPI_transfer_noDMA (SPI_InitConfig_t *spi, const uint8_t *out_data, uint32_t txlen, uint32_t rxlen, uint8_t *in_data)
SPI handle.
bool PHAL_SPI_transfer (SPI_InitConfig_t *spi, const uint8_t *out_data, const uint32_t data_len, const uint8_t *in_data)
Transfer data_len bytes from out_data to SPI device and place MISO data in in_data This function just starts the DMA transfer,.
bool PHAL_SPI_busy (SPI_InitConfig_t *cfg)
Check for current SPI transaction to complete.
void PHAL_SPI_ForceReset (SPI_InitConfig_t *spi)
void DMA2_Stream3_IRQHandler ()
uint8_t PHAL_SPI_readByte (SPI_InitConfig_t *spi, uint8_t address, bool skipDummy)
Blocking function to read a single byte from a SPI device. Useful for Initilization functions that just need to read a single byte in a blocking function.
uint8_t PHAL_SPI_writeByte (SPI_InitConfig_t *spi, uint8_t address, uint8_t writeDat)
Blocking function to write a single byte to a SPI device. Useful for Initilization functions that just need to write a single byte in a blocking function.
Variables
uint32_t APB2ClockRateHz
uint32_t APB1ClockRateHz
static volatile SPI_InitConfig_t * active_transfer = NULL
static uint16_t trash_can
Used as an address for DMA to dump data into.
static uint16_t zero
Used as a constant zero during transmissions.
Detailed Description
PER Serial Peripheral Interface Device driver for STM32F4 and STM32F7.
Author
Aditya Anand (anand.nosp@m.89@p.nosp@m.urdue.nosp@m..edu) - Port of L4 HAL by Adam Busch (busch.nosp@m.8@pu.nosp@m.rdue..nosp@m.edu)
Version
0.1
Date
2023-12-4
Copyright
Copyright (c) 2021
Definition in file spi.c.
Function Documentation
DMA2_Stream3_IRQHandler()
void DMA2_Stream3_IRQHandler ()
Definition at line 417 of file spi.c.
References handleTxComplete().
handleTxComplete()
static void handleTxComplete () static
Handle TCIF interrupt signaling end of TX transaction.
Definition at line 238 of file spi.c.
References SPI_InitConfig_t::_busy, SPI_InitConfig_t::_direct_mode_error, SPI_InitConfig_t::_error, SPI_InitConfig_t::_fifo_overrun, active_transfer, dma_init_t::mem_inc, SPI_InitConfig_t::nss_gpio_pin, SPI_InitConfig_t::nss_gpio_port, SPI_InitConfig_t::nss_sw, dma_init_t::periph, SPI_InitConfig_t::periph, PHAL_stopTxfer(), PHAL_writeGPIO(), SPI_InitConfig_t::rx_dma_cfg, dma_init_t::stream, dma_init_t::stream_idx, and SPI_InitConfig_t::tx_dma_cfg.
Referenced by DMA1_Channel3_IRQHandler(), DMA1_Channel5_IRQHandler(), DMA2_Channel3_IRQHandler(), and DMA2_Stream3_IRQHandler().
PHAL_SPI_busy()
bool PHAL_SPI_busy (SPI_InitConfig_t * cfg)
Check for current SPI transaction to complete.
Parameters
cfg Spi config
Returns
true
false
Definition at line 215 of file spi.c.
References SPI_InitConfig_t::_busy, active_transfer, and SPI_InitConfig_t::periph.
Referenced by BMI088_readAccel(), BMI088_readGyro(), LED_control(), PHAL_SPI_readByte(), PHAL_SPI_transfer(), PHAL_SPI_transfer(), PHAL_SPI_transfer_noDMA(), PHAL_SPI_writeByte(), readMem(), readPage(), and writePage().
PHAL_SPI_ForceReset()
void PHAL_SPI_ForceReset (SPI_InitConfig_t * spi)
Definition at line 224 of file spi.c.
References SPI_InitConfig_t::periph.
PHAL_SPI_init()
bool PHAL_SPI_init (SPI_InitConfig_t * handle)
Initilize SPI peripheral with the configuired structure.
Parameters
handle SPI handle to configure.
Returns
true
false
Definition at line 22 of file spi.c.
References SPI_InitConfig_t::_busy, SPI_InitConfig_t::_direct_mode_error, SPI_InitConfig_t::_error, SPI_InitConfig_t::_fifo_overrun, APB1ClockRateHz, APB2ClockRateHz, CLAMP, SPI_InitConfig_t::data_len, SPI_InitConfig_t::data_rate, LOG2_DOWN(), SPI_InitConfig_t::nss_gpio_pin, SPI_InitConfig_t::nss_gpio_port, SPI_InitConfig_t::periph, PHAL_initDMA(), PHAL_writeGPIO(), SPI_InitConfig_t::rx_dma_cfg, SPI_InitConfig_t::tx_dma_cfg, and zero.
Referenced by main(), main(), and preflightChecks().
PHAL_SPI_readByte()
uint8_t PHAL_SPI_readByte (SPI_InitConfig_t * spi, uint8_t address, bool skipDummy)
Blocking function to read a single byte from a SPI device. Useful for Initilization functions that just need to read a single byte in a blocking function.
Parameters
spi Spi handle
address Address of data to read
skipDummy Return the 3rd byte read instead of the 2nd byte
Definition at line 421 of file spi.c.
References PHAL_SPI_busy(), PHAL_SPI_transfer(), PHAL_SPI_transfer_noDMA(), and SPI_InitConfig_t::rx_dma_cfg.
Referenced by BMI088_checkGyroHealth(), BMI088_gyroSelfTestComplete(), BMI088_gyroSelfTestPass(), BMI088_init(), and BMI088_initAccel().
PHAL_SPI_transfer()
bool PHAL_SPI_transfer (SPI_InitConfig_t * spi, const uint8_t * out_data, const uint32_t data_len, const uint8_t * in_data)
Transfer data_len bytes from out_data to SPI device and place MISO data in in_data This function just starts the DMA transfer,.
Parameters
spi SPI handle
out_data Address of data buffer to put on MOSI line
data_len Number of SPI packets to send
in_data Address of data buffer to put data coming in MISO line
Returns
true Able to start DMA transaction
false Unable to start DMA transaction
Definition at line 153 of file spi.c.
References SPI_InitConfig_t::_busy, active_transfer, SPI_InitConfig_t::nss_gpio_pin, SPI_InitConfig_t::nss_gpio_port, SPI_InitConfig_t::nss_sw, SPI_InitConfig_t::periph, PHAL_DMA_setMemAddress(), PHAL_DMA_setTxferLength(), PHAL_reEnable(), PHAL_SPI_busy(), PHAL_writeGPIO(), SPI_InitConfig_t::rx_dma_cfg, dma_init_t::stream, trash_can, SPI_InitConfig_t::tx_dma_cfg, and zero.
Referenced by LED_control(), PHAL_SPI_readByte(), PHAL_SPI_writeByte(), readPage(), and writePage().
PHAL_SPI_transfer_noDMA()
bool PHAL_SPI_transfer_noDMA (SPI_InitConfig_t * spi, const uint8_t * out_data, uint32_t txlen, uint32_t rxlen, uint8_t * in_data)
SPI handle.
Parameters
spi SPI handle
out_data Address of data buffer to put on MOSI line
txlen Number of SPI Packets to Send
rxlen Number of SPI Packets to Receive
in_data Address of data buffer to put data coming in MISO line
Returns
true Successfully completed non-DMA SPI transaction
false Unable to complete non-DMA SPI transaction
Definition at line 87 of file spi.c.
References SPI_InitConfig_t::_busy, active_transfer, SPI_InitConfig_t::nss_gpio_pin, SPI_InitConfig_t::nss_gpio_port, SPI_InitConfig_t::nss_sw, SPI_InitConfig_t::periph, PHAL_SPI_busy(), and PHAL_writeGPIO().
Referenced by adbms6380_read(), adbms_connect(), adbms_read_therms(), adbms_write_rega(), adbms_write_regb(), BMI088_readAccel(), BMI088_readGyro(), PHAL_SPI_readByte(), and PHAL_SPI_writeByte().
PHAL_SPI_writeByte()
uint8_t PHAL_SPI_writeByte (SPI_InitConfig_t * spi, uint8_t address, uint8_t writeDat)
Blocking function to write a single byte to a SPI device. Useful for Initilization functions that just need to write a single byte in a blocking function.
Parameters
spi Spi handle
address Address of data to read
writeDat Data to write to address
Definition at line 440 of file spi.c.
References PHAL_SPI_busy(), PHAL_SPI_transfer(), PHAL_SPI_transfer_noDMA(), and SPI_InitConfig_t::tx_dma_cfg.
Referenced by BMI088_getGyroScale(), BMI088_gyroSelfTestStart(), BMI088_init(), BMI088_initAccel(), and BMI088_wakeAccel().
Variable Documentation
active_transfer
volatile SPI_InitConfig_t* active_transfer = NULL static
Definition at line 15 of file spi.c.
Referenced by DMA1_Channel2_IRQHandler(), DMA1_Channel3_IRQHandler(), DMA2_Channel1_IRQHandler(), DMA2_Channel2_IRQHandler(), handleTxComplete(), PHAL_SPI_busy(), PHAL_SPI_transfer(), and PHAL_SPI_transfer_noDMA().
APB1ClockRateHz
uint32_t APB1ClockRateHz extern
Definition at line 15 of file rcc.c.
Referenced by PHAL_SPI_init().
APB2ClockRateHz
uint32_t APB2ClockRateHz extern
Definition at line 16 of file rcc.c.
Referenced by PHAL_SPI_init().
trash_can
uint16_t trash_can static
Used as an address for DMA to dump data into.
Definition at line 17 of file spi.c.
Referenced by PHAL_SPI_transfer(), and PHAL_SPI_transfer().
zero
uint16_t zero static
Used as a constant zero during transmissions.
Definition at line 18 of file spi.c.
Referenced by PHAL_SPI_init(), PHAL_SPI_transfer(), and PHAL_SPI_transfer().