PER Firmware: common/phal_L4/spi/spi.c File Reference
spi.c File Reference
PER Serial Peripheral Interface Device driver for STM32L4.
#include "common/phal_L4/spi/spi.h"
Functions
bool PHAL_SPI_init (SPI_InitConfig_t *cfg)
Initilize SPI peripheral with the configuired structure.
bool PHAL_SPI_transfer_noDMA (SPI_InitConfig_t *spi, const uint8_t *out_data, uint32_t txlen, uint32_t rxlen, uint8_t *in_data)
SPI handle.
bool PHAL_SPI_transfer (SPI_InitConfig_t *spi, const uint8_t *out_data, const uint32_t data_len, const uint8_t *in_data)
Transfer data_len bytes from out_data to SPI device and place MISO data in in_data This function just starts the DMA transfer,.
bool PHAL_SPI_busy (SPI_InitConfig_t *cfg)
Check for current SPI transaction to complete.
void DMA1_Channel3_IRQHandler ()
void DMA2_Channel2_IRQHandler ()
void DMA1_Channel2_IRQHandler ()
SPI1 Rx DMA Transfer Complete interrupt.
void DMA2_Channel1_IRQHandler ()
uint8_t PHAL_SPI_readByte (SPI_InitConfig_t *spi, uint8_t address, bool skipDummy)
SPI1 Rx DMA Transfer Complete interrupt.
uint8_t PHAL_SPI_writeByte (SPI_InitConfig_t *spi, uint8_t address, uint8_t writeDat)
Blocking function to write a single byte to a SPI device. Useful for Initilization functions that just need to write a single byte in a blocking function.
Variables
uint32_t APB2ClockRateHz
uint32_t APB1ClockRateHz
static volatile SPI_InitConfig_t * active_transfer = NULL
static uint16_t trash_can
static uint16_t zero
Detailed Description
PER Serial Peripheral Interface Device driver for STM32L4.
Author
Adam Busch (busch.nosp@m.8@pu.nosp@m.rdue..nosp@m.edu)
Version
0.1
Date
2022-01-22
Copyright
Copyright (c) 2021
Definition in file spi.c.
Function Documentation
DMA1_Channel2_IRQHandler()
void DMA1_Channel2_IRQHandler (void)
SPI1 Rx DMA Transfer Complete interrupt.
Definition at line 249 of file spi.c.
References SPI_InitConfig_t::_busy, SPI_InitConfig_t::_error, active_transfer, dma_init_t::channel, dma_init_t::mem_inc, SPI_InitConfig_t::nss_gpio_pin, SPI_InitConfig_t::nss_gpio_port, SPI_InitConfig_t::nss_sw, PHAL_stopTxfer(), PHAL_writeGPIO(), SPI_InitConfig_t::rx_dma_cfg, and SPI_InitConfig_t::tx_dma_cfg.
DMA1_Channel3_IRQHandler()
void DMA1_Channel3_IRQHandler (void)
Definition at line 201 of file spi.c.
References SPI_InitConfig_t::_error, and active_transfer.
DMA2_Channel1_IRQHandler()
void DMA2_Channel1_IRQHandler ()
Definition at line 282 of file spi.c.
References SPI_InitConfig_t::_busy, SPI_InitConfig_t::_error, active_transfer, dma_init_t::channel, dma_init_t::mem_inc, SPI_InitConfig_t::nss_gpio_pin, SPI_InitConfig_t::nss_gpio_port, SPI_InitConfig_t::nss_sw, PHAL_stopTxfer(), PHAL_writeGPIO(), SPI_InitConfig_t::rx_dma_cfg, and SPI_InitConfig_t::tx_dma_cfg.
DMA2_Channel2_IRQHandler()
void DMA2_Channel2_IRQHandler ()
Definition at line 215 of file spi.c.
References SPI_InitConfig_t::_error, and active_transfer.
PHAL_SPI_busy()
bool PHAL_SPI_busy (SPI_InitConfig_t * cfg)
Check for current SPI transaction to complete.
Parameters
cfg Spi config
Returns
true
false
Definition at line 192 of file spi.c.
References SPI_InitConfig_t::_busy, active_transfer, and SPI_InitConfig_t::periph.
PHAL_SPI_init()
bool PHAL_SPI_init (SPI_InitConfig_t * handle)
Initilize SPI peripheral with the configuired structure.
Parameters
handle SPI handle to configure.
Returns
true
false
Definition at line 20 of file spi.c.
References SPI_InitConfig_t::_busy, SPI_InitConfig_t::_error, APB1ClockRateHz, APB2ClockRateHz, CLAMP, SPI_InitConfig_t::data_len, SPI_InitConfig_t::data_rate, LOG2_DOWN(), SPI_InitConfig_t::nss_gpio_pin, SPI_InitConfig_t::nss_gpio_port, SPI_InitConfig_t::periph, PHAL_initDMA(), PHAL_writeGPIO(), SPI_InitConfig_t::rx_dma_cfg, SPI_InitConfig_t::tx_dma_cfg, and zero.
PHAL_SPI_readByte()
uint8_t PHAL_SPI_readByte (SPI_InitConfig_t * spi, uint8_t address, bool skipDummy)
SPI1 Rx DMA Transfer Complete interrupt.
Blocking function to read a single byte from a SPI device. Useful for Initilization functions that just need to read a single byte in a blocking function.
Definition at line 354 of file spi.c.
References PHAL_SPI_busy(), PHAL_SPI_transfer(), PHAL_SPI_transfer_noDMA(), and SPI_InitConfig_t::rx_dma_cfg.
PHAL_SPI_transfer()
bool PHAL_SPI_transfer (SPI_InitConfig_t * spi, const uint8_t * out_data, const uint32_t data_len, const uint8_t * in_data)
Transfer data_len bytes from out_data to SPI device and place MISO data in in_data This function just starts the DMA transfer,.
Parameters
spi SPI handle
out_data Address of data buffer to put on MOSI line
data_len Number of SPI packets to send
in_data Address of data buffer to put data coming in MISO line
Returns
true Able to start DMA transaction
false Unable to start DMA transaction
Definition at line 131 of file spi.c.
References SPI_InitConfig_t::_busy, active_transfer, dma_init_t::channel, SPI_InitConfig_t::nss_gpio_pin, SPI_InitConfig_t::nss_gpio_port, SPI_InitConfig_t::nss_sw, SPI_InitConfig_t::periph, PHAL_DMA_setMemAddress(), PHAL_DMA_setTxferLength(), PHAL_SPI_busy(), PHAL_startTxfer(), PHAL_writeGPIO(), SPI_InitConfig_t::rx_dma_cfg, trash_can, SPI_InitConfig_t::tx_dma_cfg, and zero.
PHAL_SPI_transfer_noDMA()
bool PHAL_SPI_transfer_noDMA (SPI_InitConfig_t * spi, const uint8_t * out_data, uint32_t txlen, uint32_t rxlen, uint8_t * in_data)
SPI handle.
Parameters
spi SPI handle
out_data Address of data buffer to put on MOSI line
txlen Number of SPI Packets to Send
rxlen Number of SPI Packets to Receive
in_data Address of data buffer to put data coming in MISO line
Returns
true Successfully completed non-DMA SPI transaction
false Unable to complete non-DMA SPI transaction
Definition at line 75 of file spi.c.
References SPI_InitConfig_t::_busy, active_transfer, SPI_InitConfig_t::nss_gpio_pin, SPI_InitConfig_t::nss_gpio_port, SPI_InitConfig_t::nss_sw, SPI_InitConfig_t::periph, PHAL_SPI_busy(), and PHAL_writeGPIO().
PHAL_SPI_writeByte()
uint8_t PHAL_SPI_writeByte (SPI_InitConfig_t * spi, uint8_t address, uint8_t writeDat)
Blocking function to write a single byte to a SPI device. Useful for Initilization functions that just need to write a single byte in a blocking function.
Parameters
spi Spi handle
address Address of data to read
writeDat Data to write to address
Definition at line 371 of file spi.c.
References PHAL_SPI_busy(), PHAL_SPI_transfer(), PHAL_SPI_transfer_noDMA(), and SPI_InitConfig_t::tx_dma_cfg.
Variable Documentation
active_transfer
volatile SPI_InitConfig_t* active_transfer = NULL static
Definition at line 15 of file spi.c.
APB1ClockRateHz
uint32_t APB1ClockRateHz extern
Definition at line 15 of file rcc.c.
Referenced by PHAL_configureAPB1Clock().
APB2ClockRateHz
uint32_t APB2ClockRateHz extern
Definition at line 16 of file rcc.c.
Referenced by PHAL_configureAPB2Clock().
trash_can
uint16_t trash_can static
Definition at line 17 of file spi.c.
zero
uint16_t zero static
Definition at line 18 of file spi.c.