PER Firmware: source/pdu/cooling/cooling.c File Reference
cooling.c File Reference
#include "cooling.h"
#include "auto_switch.h"
#include "common/bangbang/bangbang.h"
#include "fan_control.h"
#include "led.h"
Functions
static void calculate_cooling_periodic ()
static void set_pump1_on ()
static void set_pump1_off ()
static void set_fan1_on ()
static void set_fan1_off ()
static void set_pump2_on ()
static void set_pump2_off ()
static void set_fan2_on ()
static void set_fan2_off ()
void coolingInit ()
Initializes cooling_request struct values to 0.
void update_cooling_periodic ()
Periodic function that sets switches and fan speeds based off of values in the cooling_request struct.
void cooling_driver_request_CALLBACK (can_data_t *p_can_data)
Callback function for cooling_driver_request message sent from dashboard, updates values in cooling_request struct based off signal values.
Variables
volatile cooling_request_t cr
static bool batt_fan_autospeed
static bool motor_fan_autospeed
bangbang_t batt_pump_controller = { .upper_bound = 30 , .lower_bound = (30 - 2), .on_func = set_pump1_on, .off_func = set_pump1_off, .min_switch_interval = 1000 , .last_switch_ms = 0, .is_on = false }
bangbang_t batt_fan_controller = { .upper_bound = 30 , .lower_bound = (30 - 2), .on_func = set_fan1_on, .off_func = set_fan1_off, .min_switch_interval = 1000 , .last_switch_ms = 0, .is_on = false }
bangbang_t motor_pump_controller = { .upper_bound = 60 , .lower_bound = (60 - 5), .on_func = set_pump2_on, .off_func = set_pump2_off, .min_switch_interval = 1000 , .last_switch_ms = 0, .is_on = false }
bangbang_t motor_fan_controller = { .upper_bound = 100 , .lower_bound = (100 - 5), .on_func = set_fan2_on, .off_func = set_fan2_off, .min_switch_interval = 1000 , .last_switch_ms = 0, .is_on = false }
Detailed Description
Author
Nicolas Vera (nvera.nosp@m.pae@.nosp@m.purdu.nosp@m.e.ed.nosp@m.u)
Version
0.1
Date
2024-2-29
Copyright
Copyright (c) 2024
Definition in file cooling.c.
Function Documentation
calculate_cooling_periodic()
static void calculate_cooling_periodic () static
Definition at line 114 of file cooling.c.
References bangbang_update(), can_data, cr, cooling_request_t::fan1_speed, cooling_request_t::fan1_status, cooling_request_t::fan2_speed, cooling_request_t::fan2_status, cooling_request_t::fan3_speed, cooling_request_t::fan3_status, cooling_request_t::fan4_speed, cooling_request_t::fan4_status, bangbang_t::last_switch_ms, MAX, MOTOR_COOLING_ENABLE_TEMP, motor_fan_controller, motor_pump_controller, set_fan2_off(), and set_pump2_off().
Referenced by update_cooling_periodic().
cooling_driver_request_CALLBACK()
void cooling_driver_request_CALLBACK (can_data_t * p_can_data)
Callback function for cooling_driver_request message sent from dashboard, updates values in cooling_request struct based off signal values.
Parameters
*msg_data_a CAN msg data
Returns
Definition at line 220 of file cooling.c.
References batt_fan_autospeed, can_data, CLAMP, cr, cooling_request_t::fan1_speed, cooling_request_t::fan2_speed, cooling_request_t::fan3_speed, cooling_request_t::fan4_speed, and motor_fan_autospeed.
coolingInit()
void coolingInit ()
Initializes cooling_request struct values to 0.
Parameters
return
Definition at line 61 of file cooling.c.
References batt_fan_autospeed, cr, cooling_request_t::fan1_speed, cooling_request_t::fan1_status, cooling_request_t::fan2_speed, cooling_request_t::fan2_status, cooling_request_t::fan3_speed, cooling_request_t::fan3_status, cooling_request_t::fan4_speed, cooling_request_t::fan4_status, cooling_request_t::hxfan_status, motor_fan_autospeed, cooling_request_t::pump1_status, and cooling_request_t::pump2_status.
Referenced by main().
set_fan1_off()
static void set_fan1_off () static
Definition at line 191 of file cooling.c.
References batt_fan_autospeed, cr, cooling_request_t::fan1_speed, and cooling_request_t::fan1_status.
set_fan1_on()
static void set_fan1_on () static
Definition at line 184 of file cooling.c.
References batt_fan_autospeed, cr, cooling_request_t::fan1_speed, and cooling_request_t::fan1_status.
set_fan2_off()
static void set_fan2_off () static
Definition at line 213 of file cooling.c.
References cr, cooling_request_t::fan2_speed, cooling_request_t::fan2_status, and motor_fan_autospeed.
Referenced by calculate_cooling_periodic().
set_fan2_on()
static void set_fan2_on () static
Definition at line 206 of file cooling.c.
References cr, cooling_request_t::fan2_speed, cooling_request_t::fan2_status, and motor_fan_autospeed.
set_pump1_off()
static void set_pump1_off () static
Definition at line 180 of file cooling.c.
References cr, and cooling_request_t::pump1_status.
set_pump1_on()
static void set_pump1_on () static
Definition at line 176 of file cooling.c.
References cr, and cooling_request_t::pump1_status.
set_pump2_off()
static void set_pump2_off () static
Definition at line 202 of file cooling.c.
References cr, and cooling_request_t::pump2_status.
Referenced by calculate_cooling_periodic().
set_pump2_on()
static void set_pump2_on () static
Definition at line 198 of file cooling.c.
References cr, and cooling_request_t::pump2_status.
update_cooling_periodic()
void update_cooling_periodic ()
Periodic function that sets switches and fan speeds based off of values in the cooling_request struct.
Parameters
return
Definition at line 77 of file cooling.c.
References calculate_cooling_periodic(), cr, cooling_request_t::fan1_speed, cooling_request_t::fan1_status, cooling_request_t::fan2_speed, cooling_request_t::fan2_status, cooling_request_t::fan3_speed, cooling_request_t::fan3_status, cooling_request_t::fan4_speed, cooling_request_t::fan4_status, cooling_request_t::hxfan_status, cooling_request_t::pump1_status, cooling_request_t::pump2_status, setFan1Speed(), setFan2Speed(), setFan3Speed(), setFan4Speed(), setSwitch(), SW_FAN_1, SW_FAN_2, SW_FAN_3, SW_FAN_4, SW_HXFAN, SW_PUMP_1, and SW_PUMP_2.
Referenced by main().
Variable Documentation
batt_fan_autospeed
bool batt_fan_autospeed static
Definition at line 30 of file cooling.c.
Referenced by cooling_driver_request_CALLBACK(), coolingInit(), set_fan1_off(), and set_fan1_on().
batt_fan_controller
bangbang_t batt_fan_controller = { .upper_bound = 30 , .lower_bound = (30 - 2), .on_func = set_fan1_on, .off_func = set_fan1_off, .min_switch_interval = 1000 , .last_switch_ms = 0, .is_on = false }
Definition at line 45 of file cooling.c.
batt_pump_controller
bangbang_t batt_pump_controller = { .upper_bound = 30 , .lower_bound = (30 - 2), .on_func = set_pump1_on, .off_func = set_pump1_off, .min_switch_interval = 1000 , .last_switch_ms = 0, .is_on = false }
Definition at line 38 of file cooling.c.
cr
volatile cooling_request_t cr
Definition at line 18 of file cooling.c.
Referenced by calculate_cooling_periodic(), cooling_driver_request_CALLBACK(), coolingInit(), set_fan1_off(), set_fan1_on(), set_fan2_off(), set_fan2_on(), set_pump1_off(), set_pump1_on(), set_pump2_off(), set_pump2_on(), and update_cooling_periodic().
motor_fan_autospeed
bool motor_fan_autospeed static
Definition at line 31 of file cooling.c.
Referenced by cooling_driver_request_CALLBACK(), coolingInit(), set_fan2_off(), and set_fan2_on().
motor_fan_controller
bangbang_t motor_fan_controller = { .upper_bound = 100 , .lower_bound = (100 - 5), .on_func = set_fan2_on, .off_func = set_fan2_off, .min_switch_interval = 1000 , .last_switch_ms = 0, .is_on = false }
Definition at line 59 of file cooling.c.
Referenced by calculate_cooling_periodic().
motor_pump_controller
bangbang_t motor_pump_controller = { .upper_bound = 60 , .lower_bound = (60 - 5), .on_func = set_pump2_on, .off_func = set_pump2_off, .min_switch_interval = 1000 , .last_switch_ms = 0, .is_on = false }
Definition at line 52 of file cooling.c.
Referenced by calculate_cooling_periodic().