PER Firmware: source/pdu/cooling/cooling.h File Reference
cooling.h File Reference
#include "common/can_library/generated/PDU.h"
Data Structures
struct cooling_request_t
Macros
#define GPS_SPEED_MOVING 2
#define MOTOR_COOLING_ENABLE_TEMP 60
#define MOTOR_COOLING_MAX_TEMP 100
#define BATT_COOLING_ENABLE_TEMP 30
Functions
void coolingInit ()
Initializes cooling_request struct values to 0.
void update_cooling_periodic ()
Periodic function that sets switches and fan speeds based off of values in the cooling_request struct.
void cooling_driver_request_CALLBACK (can_data_t *p_can_data)
Callback function for cooling_driver_request message sent from dashboard, updates values in cooling_request struct based off signal values.
Detailed Description
Author
Nicolas Vera (nvera.nosp@m.pae@.nosp@m.purdu.nosp@m.e.ed.nosp@m.u)
Version
0.1
Date
2024-2-29
Copyright
Copyright (c) 2024
Definition in file cooling.h.
Macro Definition Documentation
BATT_COOLING_ENABLE_TEMP
#define BATT_COOLING_ENABLE_TEMP 30
Definition at line 19 of file cooling.h.
Referenced by calculate_cooling_periodic().
GPS_SPEED_MOVING
#define GPS_SPEED_MOVING 2
Definition at line 16 of file cooling.h.
Referenced by calculate_cooling_periodic().
MOTOR_COOLING_ENABLE_TEMP
#define MOTOR_COOLING_ENABLE_TEMP 60
Definition at line 17 of file cooling.h.
Referenced by calculate_cooling_periodic().
MOTOR_COOLING_MAX_TEMP
#define MOTOR_COOLING_MAX_TEMP 100
Definition at line 18 of file cooling.h.
Referenced by calculate_cooling_periodic().
Function Documentation
cooling_driver_request_CALLBACK()
void cooling_driver_request_CALLBACK (can_data_t * p_can_data)
Callback function for cooling_driver_request message sent from dashboard, updates values in cooling_request struct based off signal values.
Parameters
*msg_data_a CAN msg data
Returns
Definition at line 93 of file cooling.c.
References can_data, CLAMP, cr, cooling_request_t::fan1_speed, and cooling_request_t::fan2_speed.
coolingInit()
void coolingInit ()
Initializes cooling_request struct values to 0.
Parameters
return
Definition at line 20 of file cooling.c.
References cooling_request_t::aux_status, cr, cooling_request_t::fan1_speed, cooling_request_t::fan1_status, cooling_request_t::fan2_speed, cooling_request_t::fan2_status, cooling_request_t::pump1_status, and cooling_request_t::pump2_status.
Referenced by preflightChecks().
update_cooling_periodic()
void update_cooling_periodic ()
Periodic function that sets switches and fan speeds based off of values in the cooling_request struct.
Parameters
return
Definition at line 30 of file cooling.c.
References cooling_request_t::aux_status, calculate_cooling_periodic(), cr, cooling_request_t::fan1_speed, cooling_request_t::fan1_status, cooling_request_t::fan2_speed, cooling_request_t::fan2_status, cooling_request_t::pump1_status, cooling_request_t::pump2_status, setFan1Speed(), setFan2Speed(), setSwitch(), SW_AUX, SW_FAN_1, SW_FAN_2, SW_PUMP_1, and SW_PUMP_2.
Referenced by main().