PER Firmware: common/phal_F4_F7/crc/crc.c File Reference
crc.c File Reference
Hardware CRC32 w/ software fallback.
#include "crc.h"
Functions
void PHAL_CRC32_Reset (void)
void PHAL_CRC32_Init (void)
uint32_t PHAL_CRC32_Calculate (uint32_t *data, uint32_t count)
static uint32_t update_crc (uint32_t crc, uint32_t data)
uint32_t PHAL_CRC32_CalculateSW (uint32_t *data, uint32_t count)
Variables
static const uint32_t crc32b_LUT [16]
Detailed Description
Hardware CRC32 w/ software fallback.
Author
Eileen Yoon (eyn@p.nosp@m.urdu.nosp@m.e.edu)
Version
0.1
Date
2024-11-25
Copyright
Copyright (c) 2024
Definition in file crc.c.
Function Documentation
PHAL_CRC32_Calculate()
uint32_t PHAL_CRC32_Calculate (uint32_t * data, uint32_t count)
Definition at line 32 of file crc.c.
References PHAL_CRC32_Reset().
Referenced by BL_checkAndBoot(), and BL_processCommand_CRC().
PHAL_CRC32_CalculateSW()
uint32_t PHAL_CRC32_CalculateSW (uint32_t * data, uint32_t count)
Definition at line 77 of file crc.c.
References update_crc().
PHAL_CRC32_Init()
void PHAL_CRC32_Init (void)
Definition at line 28 of file crc.c.
References PHAL_CRC32_Reset().
PHAL_CRC32_Reset()
void PHAL_CRC32_Reset (void)
Definition at line 14 of file crc.c.
Referenced by PHAL_CRC32_Calculate(), and PHAL_CRC32_Init().
update_crc()
static uint32_t update_crc (uint32_t crc, uint32_t data) inline static
Definition at line 61 of file crc.c.
Referenced by PHAL_CRC32_CalculateSW().
Variable Documentation
crc32b_LUT
const uint32_t crc32b_LUT[16] static
Initial value:
= {
    0x00000000,
    0x04C11DB7,
    0x09823B6E,
    0x0D4326D9,
    0x130476DC,
    0x17C56B6B,
    0x1A864DB2,
    0x1E475005,
    0x2608EDB8,
    0x22C9F00F,
    0x2F8AD6D6,
    0x2B4BCB61,
    0x350C9B64,
    0x31CD86D3,
    0x3C8EA00A,
    0x384FBDBD,
}
Definition at line 42 of file crc.c.