PER Firmware: source/daq/daq_hub/daq_rtc_config.h File Reference
daq_rtc_config.h File Reference
#include "common/phal/can.h"
#include "common/phal/rtc.h"
Functions
void rtc_config_cb (CanMsgTypeDef_t *)
static void parse_gps_time (const CanMsgTypeDef_t *msg, RTC_timestamp_t *gps_rtc_time)
Function Documentation
parse_gps_time()
static void parse_gps_time (const CanMsgTypeDef_t * msg, RTC_timestamp_t * gps_rtc_time) static
rtc_config_cb()
void rtc_config_cb (CanMsgTypeDef_t * msg)
Definition at line 8 of file daq_rtc_config.c.
References daq_hub, HardFault_Handler(), parse_gps_time(), PHAL_configureRTC(), daq_hub_t::rtc_config_state, and RTC_SYNC_COMPLETE.
Referenced by can_rx_irq_handler().