PER Firmware: source/daq/daq_hub/daq_hub.h File Reference
daq_hub.h File Reference
Data acquisition from CAN to:
#include <assert.h>
#include <stdint.h>
#include "common/freertos/freertos.h"
#include "common/phal/can.h"
#include "daq_eth.h"
#include "daq_sd.h"
#include "daq_rtc_config.h"
#include "ff.h"
#include "sdio.h"
#include "spmc.h"
Data Structures
struct daq_hub_t
Typedefs
typedef uint32_t canid_t
typedef uint8_t busid_t
Functions
void daq_hub_init (void)
void daq_create_threads (void)
void uds_receive_periodic (void)
void daq_shutdown_hook (void)
Variables
daq_hub_t daq_hub
Detailed Description
Data acquisition from CAN to:
Author
Luke Oxley (lcoxl.nosp@m.ey@p.nosp@m.urdue.nosp@m..edu)
SD Card
Ethernet
USB (maybe)
Version
0.1
Date
2024-02-08
Copyright
Copyright (c) 2024
Definition in file daq_hub.h.
Typedef Documentation
busid_t
typedef uint8_t busid_t
Definition at line 30 of file daq_hub.h.
canid_t
typedef uint32_t canid_t
Definition at line 29 of file daq_hub.h.
Function Documentation
daq_create_threads()
void daq_create_threads (void)
Definition at line 69 of file daq_hub.c.
References can_send_periodic(), createThread, daq_heartbeat(), eth_update_periodic(), and sd_update_periodic().
Referenced by main().
daq_hub_init()
void daq_hub_init (void)
Definition at line 39 of file daq_hub.c.
References daq_hub_t::bcan_rx_overflow, daq_hub_t::can1_rx_overflow, daq_hub, daq_hub_t::eth_error_ct, ETH_ERROR_NONE, daq_hub_t::eth_last_err, daq_hub_t::eth_last_err_res, daq_hub_t::eth_last_error_time, ETH_LINK_IDLE, daq_hub_t::eth_state, ETH_TCP_IDLE, daq_hub_t::eth_tcp_state, daq_hub_t::last_file_ms, daq_hub_t::last_write_ms, daq_hub_t::log_enable_sw, daq_hub_t::log_enable_tcp, daq_hub_t::rtc_config_state, RTC_SYNC_PENDING, daq_hub_t::sd_error_ct, SD_ERROR_NONE, daq_hub_t::sd_last_err, daq_hub_t::sd_last_err_res, daq_hub_t::sd_last_error_time, daq_hub_t::sd_rx_overflow, daq_hub_t::sd_state, SD_STATE_IDLE, daq_hub_t::sd_task_handle, and daq_hub_t::tcp_tx_overflow.
Referenced by main().
daq_shutdown_hook()
void daq_shutdown_hook (void)
Definition at line 92 of file daq_hub.c.
References CONNECTION_LED_PIN, ERROR_LED_PIN, ETH_RST_PIN, ETH_RST_PORT, GPIO_CLEAR_BIT, HEARTBEAT_LED_PIN, PHAL_deinitCAN(), PHAL_writeGPIO(), SD_ACTIVITY_LED_PIN, SD_DETECT_LED_PIN, SD_DETECT_LED_PORT, SD_ERROR_LED_PIN, and sd_shutdown().
Referenced by shutdown().
uds_receive_periodic()
void uds_receive_periodic (void)
Variable Documentation
daq_hub
daq_hub_t daq_hub extern
Definition at line 28 of file daq_hub.c.