PER Firmware: source/daq/daq_hub/daq_spi.h File Reference
daq_spi.h File Reference
Functions
void daq_spi_register_callbacks (void)
Function Documentation
daq_spi_register_callbacks()
void daq_spi_register_callbacks (void)
Definition at line 131 of file daq_spi.c.
References crit_enter(), crit_exit(), cs_desel(), cs_sel(), ETH_CS_PIN, ETH_CS_PORT, PHAL_writeGPIO(), reg_wizchip_cris_cbfunc(), reg_wizchip_cs_cbfunc(), reg_wizchip_spi_cbfunc(), reg_wizchip_spiburst_cbfunc(), spi_rb(), spi_rb_burst(), spi_wb(), and spi_wb_burst().
Referenced by main().