PER Firmware: source/daq/daq_hub/daq_hub.c File Reference
daq_hub.c File Reference
Data acquisition from CAN to:
#include "daq_hub.h"
#include <string.h>
#include "common/phal/gpio.h"
#include "daq_can.h"
#include "daq_eth.h"
#include "daq_sd.h"
#include "daq_rtc_config.h"
#include "main.h"
#include "common/can_library/generated/DAQ.h"
Macros
#define GPIO_CLEAR_BIT(PIN)
Functions
static void daq_heartbeat (void)
static void can_send_periodic (void)
defineThreadStack (daq_heartbeat, 500, osPriorityNormal, 128)
defineThreadStack (sd_update_periodic, 100, osPriorityNormal, 4096)
defineThreadStack (eth_update_periodic, 50, osPriorityNormal, 4096)
defineThreadStack (can_send_periodic, 50, osPriorityNormal, 128)
void daq_hub_init (void)
void daq_create_threads (void)
void uds_frame_send (uint64_t data)
void uds_receive_periodic (void)
void daq_shutdown_hook (void)
Variables
daq_hub_t daq_hub
Detailed Description
Data acquisition from CAN to:
Author
Luke Oxley (lcoxl.nosp@m.ey@p.nosp@m.urdue.nosp@m..edu) Eileen Yoon (eyn@p.nosp@m.urdu.nosp@m.e.edu)
SD Card
Ethernet
USB (maybe)
Version
0.1
Date
2024-02-08
Copyright
Copyright (c) 2024
Definition in file daq_hub.c.
Macro Definition Documentation
GPIO_CLEAR_BIT
#define GPIO_CLEAR_BIT (PIN)
Value:
((1 << ((1 << 4) | (PIN))))
Definition at line 119 of file daq_hub.c.
Referenced by daq_shutdown_hook().
Function Documentation
can_send_periodic()
static void can_send_periodic (void) static
Definition at line 86 of file daq_hub.c.
References CAN_rx_update(), and CAN_tx_update().
Referenced by daq_create_threads().
daq_create_threads()
void daq_create_threads (void)
Definition at line 70 of file daq_hub.c.
References can_send_periodic(), createThread, daq_heartbeat(), and sd_update_periodic().
Referenced by main().
daq_heartbeat()
static void daq_heartbeat (void) static
Definition at line 78 of file daq_hub.c.
References daq_hub_t::bcan_rx_overflow, CAN1_IDX, daq_hub_t::can1_rx_overflow, can_stats_t::can_peripheral_stats, can_stats, daq_hub, HEARTBEAT_LED_PIN, HEARTBEAT_LED_PORT, PHAL_toggleGPIO(), can_stats_t::rx_of, can_peripheral_stats_t::rx_overrun, daq_hub_t::sd_rx_overflow, daq_hub_t::tcp_tx_overflow, can_peripheral_stats_t::tx_fail, and can_peripheral_stats_t::tx_of.
Referenced by daq_create_threads().
daq_hub_init()
void daq_hub_init (void)
Definition at line 41 of file daq_hub.c.
References daq_hub_t::bcan_rx_overflow, daq_hub_t::can1_rx_overflow, daq_hub, daq_hub_t::eth_error_ct, ETH_ERROR_NONE, daq_hub_t::eth_last_err, daq_hub_t::eth_last_err_res, daq_hub_t::eth_last_error_time, ETH_LINK_IDLE, daq_hub_t::eth_state, ETH_TCP_IDLE, daq_hub_t::eth_tcp_state, daq_hub_t::last_file_ms, daq_hub_t::last_write_ms, daq_hub_t::log_enable_sw, daq_hub_t::log_enable_tcp, daq_hub_t::rtc_config_state, RTC_SYNC_PENDING, daq_hub_t::sd_error_ct, SD_ERROR_NONE, daq_hub_t::sd_last_err, daq_hub_t::sd_last_err_res, daq_hub_t::sd_last_error_time, daq_hub_t::sd_rx_overflow, daq_hub_t::sd_state, SD_STATE_IDLE, and daq_hub_t::tcp_tx_overflow.
Referenced by main().
daq_shutdown_hook()
void daq_shutdown_hook (void)
Definition at line 121 of file daq_hub.c.
References CONNECTION_LED_PIN, ERROR_LED_PIN, ETH_RST_PIN, ETH_RST_PORT, GPIO_CLEAR_BIT, HEARTBEAT_LED_PIN, PHAL_deinitCAN(), PHAL_writeGPIO(), SD_ACTIVITY_LED_PIN, SD_DETECT_LED_PIN, SD_DETECT_LED_PORT, SD_ERROR_LED_PIN, and sd_shutdown().
Referenced by shutdown().
defineThreadStack() [1/4]
defineThreadStack (can_send_periodic , 50 , osPriorityNormal , 128)
defineThreadStack() [2/4]
defineThreadStack (daq_heartbeat , 500 , osPriorityNormal , 128)
defineThreadStack() [3/4]
defineThreadStack (eth_update_periodic , 50 , osPriorityNormal , 4096)
defineThreadStack() [4/4]
defineThreadStack (sd_update_periodic , 100 , osPriorityNormal , 4096)
uds_frame_send()
void uds_frame_send (uint64_t data)
Definition at line 91 of file daq_hub.c.
References BUS_ID_CAN1, CAN_EFF_FLAG, DAQ_FRAME_UDP_TX, timestamped_frame_t::data, getTick, and timestamped_frame_t::msg_id.
uds_receive_periodic()
void uds_receive_periodic (void)
Pull UDS CAN frames out of UDS queue added during CAN1/CAN2 ISR and process them in non-interrupt context
Definition at line 107 of file daq_hub.c.
References timestamped_frame_t::data, and q_can1_rx.
Variable Documentation
daq_hub
daq_hub_t daq_hub
Definition at line 28 of file daq_hub.c.
Referenced by _eth_handle_error(), _eth_tcp_send_frame_raw(), _sd_write_periodic(), can_rx_irq_handler(), daq_heartbeat(), daq_hub_init(), daq_request_sd_mount(), eth_reset_error(), eth_tcp_receive_periodic(), eth_tcp_send_periodic(), eth_tcp_update(), eth_udp_send_periodic(), eth_update_periodic(), rtc_config_cb(), sd_create_new_file(), sd_file_sync(), sd_handle_error(), sd_reset_error(), sd_shutdown(), and sd_update_periodic().