PER Firmware: source/daq/daq_hub/daq_spi.c File Reference
daq_spi.c File Reference
#include "daq_spi.h"
#include "common/phal/spi.h"
#include "main.h"
#include "w5500/wizchip_conf.h"
Functions
static void cs_sel (void)
static void cs_desel (void)
static uint8_t spi_rb (uint32_t addr)
static void spi_wb (uint32_t addr, uint8_t b)
static void spi_rb_burst (uint32_t addr, uint8_t *pBuf, uint16_t len)
static void spi_wb_burst (uint32_t addr, uint8_t *pBuf, uint16_t len)
static void crit_enter (void)
static void crit_exit (void)
static void PHAL_SPI_transfer_noDMA_DAQW5500Only (SPI_InitConfig_t *spi, uint32_t addr, const uint8_t *tx_data, uint32_t txlen, uint32_t rxlen, uint8_t *rx_data)
void daq_spi_register_callbacks (void)
Variables
SPI_InitConfig_t eth_spi_config
Function Documentation
crit_enter()
static void crit_enter (void) static
Definition at line 121 of file daq_spi.c.
References HardFault_Handler(), and spi1_lock.
Referenced by daq_spi_register_callbacks().
crit_exit()
static void crit_exit (void) static
Definition at line 127 of file daq_spi.c.
References spi1_lock.
Referenced by daq_spi_register_callbacks().
cs_desel()
static void cs_desel (void) static
Definition at line 35 of file daq_spi.c.
References ETH_CS_PIN, ETH_CS_PORT, eth_spi_config, SPI_InitConfig_t::periph, and PHAL_writeGPIO().
Referenced by daq_spi_register_callbacks(), and reg_wizchip_cs_cbfunc().
cs_sel()
static void cs_sel (void) static
Definition at line 30 of file daq_spi.c.
References ETH_CS_PIN, ETH_CS_PORT, eth_spi_config, SPI_InitConfig_t::periph, and PHAL_writeGPIO().
Referenced by daq_spi_register_callbacks(), and reg_wizchip_cs_cbfunc().
daq_spi_register_callbacks()
void daq_spi_register_callbacks (void)
Definition at line 131 of file daq_spi.c.
References crit_enter(), crit_exit(), cs_desel(), cs_sel(), ETH_CS_PIN, ETH_CS_PORT, PHAL_writeGPIO(), reg_wizchip_cris_cbfunc(), reg_wizchip_cs_cbfunc(), reg_wizchip_spi_cbfunc(), reg_wizchip_spiburst_cbfunc(), spi_rb(), spi_rb_burst(), spi_wb(), and spi_wb_burst().
Referenced by main().
PHAL_SPI_transfer_noDMA_DAQW5500Only()
static void PHAL_SPI_transfer_noDMA_DAQW5500Only (SPI_InitConfig_t * spi, uint32_t addr, const uint8_t * tx_data, uint32_t txlen, uint32_t rxlen, uint8_t * rx_data) static
Definition at line 41 of file daq_spi.c.
References addr, and SPI_InitConfig_t::periph.
Referenced by spi_rb(), spi_rb_burst(), spi_wb(), and spi_wb_burst().
spi_rb()
static uint8_t spi_rb (uint32_t addr) static
Definition at line 101 of file daq_spi.c.
References addr, eth_spi_config, and PHAL_SPI_transfer_noDMA_DAQW5500Only().
Referenced by daq_spi_register_callbacks(), reg_wizchip_spi_cbfunc(), and reg_wizchip_spiburst_cbfunc().
spi_rb_burst()
static void spi_rb_burst (uint32_t addr, uint8_t * pBuf, uint16_t len) static
Definition at line 111 of file daq_spi.c.
References addr, eth_spi_config, and PHAL_SPI_transfer_noDMA_DAQW5500Only().
Referenced by daq_spi_register_callbacks().
spi_wb()
static void spi_wb (uint32_t addr, uint8_t b) static
Definition at line 107 of file daq_spi.c.
References addr, eth_spi_config, and PHAL_SPI_transfer_noDMA_DAQW5500Only().
Referenced by daq_spi_register_callbacks(), reg_wizchip_spi_cbfunc(), and reg_wizchip_spiburst_cbfunc().
spi_wb_burst()
static void spi_wb_burst (uint32_t addr, uint8_t * pBuf, uint16_t len) static
Definition at line 116 of file daq_spi.c.
References addr, eth_spi_config, and PHAL_SPI_transfer_noDMA_DAQW5500Only().
Referenced by daq_spi_register_callbacks().
Variable Documentation
eth_spi_config
SPI_InitConfig_t eth_spi_config extern
Definition at line 76 of file main.c.
Referenced by cs_desel(), cs_sel(), main(), spi_rb(), spi_rb_burst(), spi_wb(), and spi_wb_burst().