PER Firmware: source/daq/daq_hub/daq_can.h File Reference
daq_can.h File Reference
#include <stdint.h>
#include "common/phal/can.h"
#include "common/can_library/can_common.h"
Macros
#define BUS_ID_CAN1 0
#define BUS_ID_CAN2 1
#define CAN_BUS_COUNT 2
Functions
void initCANParse ()
void canTxSendToBack (CanMsgTypeDef_t *msg)
void CAN_tx_update (void)
Variables
can_stats_t can_stats
Macro Definition Documentation
BUS_ID_CAN1
#define BUS_ID_CAN1 0
Definition at line 10 of file daq_can.h.
Referenced by can_rx_irq_handler().
BUS_ID_CAN2
#define BUS_ID_CAN2 1
Definition at line 11 of file daq_can.h.
Referenced by can_rx_irq_handler().
CAN_BUS_COUNT
#define CAN_BUS_COUNT 2
Definition at line 13 of file daq_can.h.
Function Documentation
CAN_tx_update()
void CAN_tx_update (void)
Referenced by background_can_update(), can_send_periodic(), can_worker_task(), can_worker_thread(), and main().
canTxSendToBack()
void canTxSendToBack (CanMsgTypeDef_t * msg)
Definition at line 105 of file main.c.
initCANParse()
void initCANParse ()
Definition at line 21 of file daq_can.c.
References initCANParseBase().
Referenced by main().
Variable Documentation
can_stats
can_stats_t can_stats extern
Definition at line 16 of file can_common.c.
Referenced by daq_heartbeat(), heatBeatLED(), and initCANParseBase().