PER Firmware: source/daq/daq_hub/daq_sd.c File Reference
daq_sd.c File Reference
#include "daq_sd.h"
#include "common/phal/gpio.h"
#include "common/phal/rtc.h"
#include "daq_hub.h"
#include "ff.h"
#include "main.h"
Macros
#define sd_write_periodic()
Functions
static FRESULT sd_create_new_file (void)
static void sd_file_sync (void)
static void _sd_write_periodic (bool bypass)
static void sd_handle_error (sd_error_t sd_error, FRESULT result)
static void sd_reset_error (void)
bool daq_request_sd_mount (void)
void sd_shutdown (void)
void sd_update_periodic (void)
Macro Definition Documentation
sd_write_periodic
#define sd_write_periodic ()
Value:
_sd_write_periodic(false)
Definition at line 15 of file daq_sd.c.
Referenced by sd_update_periodic().
Function Documentation
_sd_write_periodic()
static void _sd_write_periodic (bool bypass) static
Definition at line 78 of file daq_sd.c.
References b_rx_can, bCommitRead(), bGetItemCount(), bGetTailForRead(), daq_hub, f_write(), FR_OK, getTick, daq_hub_t::last_write_ms, daq_hub_t::log_fp, PHAL_writeGPIO(), RX_TAIL_SD, SD_ACTIVITY_LED_PIN, SD_ACTIVITY_LED_PORT, SD_ERROR_WRITE, sd_file_sync(), sd_handle_error(), SD_MAX_WRITE_COUNT, daq_hub_t::sd_rx_overflow, daq_hub_t::sd_state, and SD_STATE_ACTIVE.
daq_request_sd_mount()
bool daq_request_sd_mount (void)
Definition at line 17 of file daq_sd.c.
References daq_hub, daq_hub_t::sd_state, SD_STATE_ACTIVE, and SD_STATE_MOUNTED.
sd_create_new_file()
static FRESULT sd_create_new_file (void) static
Definition at line 45 of file daq_sd.c.
References daq_hub, debug_printf(), f_open(), FA_OPEN_APPEND, FA_READ, FA_WRITE, FR_OK, getTick, daq_hub_t::last_file_ms, daq_hub_t::log_fp, PHAL_getTimeRTC(), SD_ERROR_FOPEN, sd_handle_error(), and sprintf().
Referenced by sd_update_periodic().
sd_file_sync()
static void sd_file_sync (void) inline static
Definition at line 71 of file daq_sd.c.
References daq_hub, f_sync(), FR_OK, daq_hub_t::log_fp, SD_ERROR_SYNC, and sd_handle_error().
Referenced by _sd_write_periodic(), and sd_shutdown().
sd_handle_error()
static void sd_handle_error (sd_error_t sd_error, FRESULT result) static
Definition at line 21 of file daq_sd.c.
References daq_hub, debug_printf(), getTick, PHAL_writeGPIO(), daq_hub_t::sd_error_ct, SD_ERROR_LED_PIN, SD_ERROR_LED_PORT, daq_hub_t::sd_last_err, daq_hub_t::sd_last_err_res, and daq_hub_t::sd_last_error_time.
Referenced by _sd_write_periodic(), sd_create_new_file(), sd_file_sync(), and sd_update_periodic().
sd_reset_error()
static void sd_reset_error (void) static
Definition at line 30 of file daq_sd.c.
References daq_hub, getTick, PHAL_writeGPIO(), SD_ERROR_LED_PIN, SD_ERROR_LED_PORT, SD_ERROR_NONE, SD_ERROR_RETRY_MS, daq_hub_t::sd_last_err, daq_hub_t::sd_last_err_res, daq_hub_t::sd_last_error_time, daq_hub_t::sd_state, and SD_STATE_IDLE.
Referenced by sd_update_periodic().
sd_shutdown()
void sd_shutdown (void)
Definition at line 114 of file daq_sd.c.
References b_rx_can, bDeactivateTail(), daq_hub, f_close(), f_mount(), daq_hub_t::log_fp, PHAL_writeGPIO(), RX_TAIL_SD, SD_ACTIVITY_LED_PIN, SD_ACTIVITY_LED_PORT, SD_DeInit(), SD_DETECT_LED_PIN, SD_DETECT_LED_PORT, SD_ERROR_LED_PIN, SD_ERROR_LED_PORT, sd_file_sync(), daq_hub_t::sd_state, SD_STATE_ACTIVE, SD_STATE_IDLE, and SD_STATE_MOUNTED.
Referenced by daq_shutdown_hook(), and sd_update_periodic().
sd_update_periodic()
void sd_update_periodic (void)
Definition at line 134 of file daq_sd.c.
References b_rx_can, bActivateTail(), daq_hub, debug_printf(), f_mount(), daq_hub_t::fat_fs, FR_OK, getTick, daq_hub_t::last_file_ms, daq_hub_t::last_write_ms, LOG_ENABLE_PIN, LOG_ENABLE_PORT, daq_hub_t::log_enable_sw, daq_hub_t::log_start_ms, PHAL_readGPIO(), PHAL_writeGPIO(), RX_TAIL_SD, sd_create_new_file(), SD_Detect(), SD_DETECT_LED_PIN, SD_DETECT_LED_PORT, SD_ERROR_MOUNT, sd_handle_error(), SD_NEW_FILE_PERIOD_MS, SD_PRESENT, sd_reset_error(), sd_shutdown(), daq_hub_t::sd_state, SD_STATE_ACTIVE, SD_STATE_IDLE, SD_STATE_MOUNTED, SD_WRITE_PERIOD_MS, and sd_write_periodic.
Referenced by daq_create_threads().