PER Firmware: source/daq/daq_hub/daq_eth.c File Reference
daq_eth.c File Reference
W5500 Ethernet.
#include <string.h>
#include "common/phal/can.h"
#include "common/phal/gpio.h"
#include "daq_can.h"
#include "daq_hub.h"
#include "main.h"
#include "w5500/socket.h"
#include "w5500/wizchip_conf.h"
#include "common/can_library/generated/DAQ.h"
Data Structures
struct eth_config_t
Macros
#define eth_handle_error(err, res)
Functions
static int8_t eth_init (void)
static int8_t eth_get_link_up (void)
static int8_t eth_udp_init (void)
static void eth_udp_send_periodic (void)
static void eth_tcp_receive_periodic (void)
static void eth_tcp_update (void)
static void eth_tcp_send_periodic (void)
static void eth_reset_error (void)
static void _eth_handle_error (eth_error_t err, int32_t reason)
void eth_update_periodic (void)
static void eth_udp_send_frame (timestamped_frame_t *frame)
static int8_t eth_init_tcp (void)
static void conv_tcp_frame_to_can_msg (timestamped_frame_t *tcp_frame, CanMsgTypeDef_t *can_msg)
static void eth_tcp_relay_can_frame (timestamped_frame_t *frame)
static void eth_tcp_send_frame (timestamped_frame_t *frame)
static void _eth_tcp_send_frame_raw (timestamped_frame_t *frame)
Variables
eth_config_t eth_config
Detailed Description
W5500 Ethernet.
Author
Luke Oxley (lcoxl.nosp@m.ey@p.nosp@m.urdue.nosp@m..edu) Eileen Yoon (eyn@p.nosp@m.urdu.nosp@m.e.edu)
Version
0.1
Date
2025-02-25
Copyright
Copyright (c) 2025
Definition in file daq_eth.c.
Macro Definition Documentation
eth_handle_error
#define eth_handle_error (err, res)
Value:
_eth_handle_error(err, res)
Definition at line 34 of file daq_eth.c.
Referenced by _eth_tcp_send_frame_raw(), eth_init(), eth_init_tcp(), eth_udp_init(), and eth_udp_send_periodic().
Function Documentation
_eth_handle_error()
static void _eth_handle_error (eth_error_t err, int32_t reason) static
Definition at line 106 of file daq_eth.c.
References daq_hub, debug_printf(), ERROR_LED_PIN, ERROR_LED_PORT, daq_hub_t::eth_error_ct, daq_hub_t::eth_last_err, daq_hub_t::eth_last_err_res, daq_hub_t::eth_last_error_time, getTick, and PHAL_writeGPIO().
_eth_tcp_send_frame_raw()
static void _eth_tcp_send_frame_raw (timestamped_frame_t * frame) static
Definition at line 354 of file daq_eth.c.
References DAQ_FRAME_TCP_TX, daq_hub, eth_config, ETH_ERROR_TCP_SEND, eth_handle_error, ETH_TCP_ESTABLISHED, daq_hub_t::eth_tcp_state, timestamped_frame_t::frame_type, send(), and eth_config_t::tcp_sock.
Referenced by eth_tcp_send_periodic().
conv_tcp_frame_to_can_msg()
static void conv_tcp_frame_to_can_msg (timestamped_frame_t * tcp_frame, CanMsgTypeDef_t * can_msg) static
Definition at line 283 of file daq_eth.c.
References CanMsgTypeDef_t::Bus, timestamped_frame_t::bus_id, BUS_ID_CAN1, CAN_EFF_FLAG, CAN_EFF_MASK, CAN_SFF_MASK, CanMsgTypeDef_t::Data, timestamped_frame_t::data, CanMsgTypeDef_t::DLC, timestamped_frame_t::dlc, CanMsgTypeDef_t::ExtId, CanMsgTypeDef_t::IDE, timestamped_frame_t::msg_id, and CanMsgTypeDef_t::StdId.
Referenced by eth_tcp_relay_can_frame().
eth_get_link_up()
static int8_t eth_get_link_up (void) static
Definition at line 174 of file daq_eth.c.
References getPHYCFGR, and PHY_LINK_ON.
Referenced by eth_update_periodic().
eth_init()
static int8_t eth_init (void) static
Definition at line 143 of file daq_eth.c.
References eth_config, ETH_ERROR_INIT, ETH_ERROR_NONE, ETH_ERROR_VERS, eth_handle_error, ETH_PHY_RESET_PERIOD_MS, ETH_PHY_VERSION_ID, ETH_RST_PIN, ETH_RST_PORT, getVERSIONR, eth_config_t::net_info, PHAL_writeGPIO(), wizchip_init(), and wizchip_setnetinfo().
Referenced by eth_update_periodic().
eth_init_tcp()
static int8_t eth_init_tcp (void) static
Definition at line 226 of file daq_eth.c.
References close(), CS_SET_IOMODE, ctlsocket(), eth_config, ETH_ERROR_NONE, ETH_ERROR_TCP_LISTEN, ETH_ERROR_TCP_SOCK, eth_handle_error, listen(), SOCK_IO_NONBLOCK, SOCK_OK, SOCK_STREAM, socket(), eth_config_t::tcp_port, and eth_config_t::tcp_sock.
Referenced by eth_tcp_update().
eth_reset_error()
static void eth_reset_error (void) static
Definition at line 115 of file daq_eth.c.
References CONNECTION_LED_PIN, CONNECTION_LED_PORT, daq_hub, ERROR_LED_PIN, ERROR_LED_PORT, ETH_ERROR_NONE, ETH_ERROR_RETRY_MS, daq_hub_t::eth_last_err, daq_hub_t::eth_last_err_res, daq_hub_t::eth_last_error_time, ETH_LINK_FAIL, ETH_LINK_IDLE, ETH_LINK_UP, daq_hub_t::eth_state, ETH_TCP_ESTABLISHED, ETH_TCP_FAIL, ETH_TCP_IDLE, daq_hub_t::eth_tcp_state, getTick, PHAL_toggleGPIO(), and PHAL_writeGPIO().
Referenced by eth_update_periodic().
eth_tcp_receive_periodic()
static void eth_tcp_receive_periodic (void) static
Definition at line 315 of file daq_eth.c.
References DAQ_FRAME_TCP2CAN, daq_hub, eth_config, ETH_TCP_ESTABLISHED, ETH_TCP_IDLE, eth_tcp_relay_can_frame(), daq_hub_t::eth_tcp_state, timestamped_frame_t::frame_type, recv(), SOCKERR_SOCKSTATUS, tcp_rx_buf, TCP_RX_ITEM_COUNT, and eth_config_t::tcp_sock.
Referenced by eth_tcp_update().
eth_tcp_relay_can_frame()
static void eth_tcp_relay_can_frame (timestamped_frame_t * frame) static
Definition at line 300 of file daq_eth.c.
References CAN_enqueue_tx(), and conv_tcp_frame_to_can_msg().
Referenced by eth_tcp_receive_periodic().
eth_tcp_send_frame()
static void eth_tcp_send_frame (timestamped_frame_t * frame) static
Definition at line 344 of file daq_eth.c.
References daq_hub, ETH_TCP_ESTABLISHED, daq_hub_t::eth_tcp_state, q_tcp_tx, and daq_hub_t::tcp_tx_overflow.
Referenced by uds_frame_send().
eth_tcp_send_periodic()
static void eth_tcp_send_periodic (void) static
Definition at line 365 of file daq_eth.c.
References _eth_tcp_send_frame_raw(), daq_hub, ETH_TCP_ESTABLISHED, daq_hub_t::eth_tcp_state, and q_tcp_tx.
Referenced by eth_tcp_update().
eth_tcp_update()
static void eth_tcp_update (void) static
Definition at line 250 of file daq_eth.c.
References close(), daq_hub, debug_printf(), eth_config, ETH_ERROR_NONE, eth_init_tcp(), ETH_LINK_UP, daq_hub_t::eth_state, ETH_TCP_ESTABLISHED, ETH_TCP_FAIL, ETH_TCP_IDLE, ETH_TCP_LISTEN, eth_tcp_receive_periodic(), eth_tcp_send_periodic(), daq_hub_t::eth_tcp_state, getSn_SR, SOCK_CLOSE_WAIT, SOCK_ESTABLISHED, and eth_config_t::tcp_sock.
Referenced by eth_update_periodic().
eth_udp_init()
static int8_t eth_udp_init (void) static
Definition at line 179 of file daq_eth.c.
References eth_config, ETH_ERROR_NONE, ETH_ERROR_UDP_SOCK, eth_handle_error, SOCK_DGRAM, socket(), eth_config_t::udp_bc_port, and eth_config_t::udp_bc_sock.
Referenced by eth_update_periodic().
eth_udp_send_frame()
static void eth_udp_send_frame (timestamped_frame_t * frame) static
Definition at line 215 of file daq_eth.c.
References b_rx_can, bCommitWrite(), bGetHeadForWrite(), and DAQ_FRAME_UDP_TX.
eth_udp_send_periodic()
static void eth_udp_send_periodic (void) static
Definition at line 193 of file daq_eth.c.
References b_rx_can, bCommitRead(), bGetTailForRead(), daq_hub, eth_config, ETH_ERROR_UDP_SEND, eth_handle_error, ETH_LINK_UP, daq_hub_t::eth_state, RX_TAIL_UDP, sendto(), eth_config_t::udp_bc_addr, eth_config_t::udp_bc_port, eth_config_t::udp_bc_sock, and UDP_MAX_WRITE_COUNT.
Referenced by eth_update_periodic().
eth_update_periodic()
void eth_update_periodic (void)
Definition at line 60 of file daq_eth.c.
References b_rx_can, bActivateTail(), bDeactivateTail(), CONNECTION_LED_PIN, CONNECTION_LED_PORT, daq_hub, debug_printf(), ETH_ERROR_NONE, eth_get_link_up(), eth_init(), ETH_LINK_DOWN, ETH_LINK_FAIL, ETH_LINK_IDLE, ETH_LINK_STARTING, ETH_LINK_UP, eth_reset_error(), daq_hub_t::eth_state, eth_tcp_update(), eth_udp_init(), eth_udp_send_periodic(), mDelay, PHAL_writeGPIO(), and RX_TAIL_UDP.
Variable Documentation
eth_config
eth_config_t eth_config
Initial value:
= {
    .net_info = {
        .mac = {0x00, 0x08, 0xdc, 0xab, 0xcd, 0xef},
        .ip  = {192, 168, 10, 41},
        .sn  = {255, 255, 255, 0},
        .gw  = {192, 168, 10, 1},
    },
    .udp_bc_addr = {192, 168, 10, 255},
    .udp_bc_port = 5005,
    .udp_bc_sock = 0 ,
    .tcp_port    = 5005,
    .tcp_sock    = 1 ,
}
Definition at line 46 of file daq_eth.c.
Referenced by _eth_tcp_send_frame_raw(), eth_init(), eth_init_tcp(), eth_tcp_receive_periodic(), eth_tcp_update(), eth_udp_init(), and eth_udp_send_periodic().