PER Firmware: common/daq/daq_base.h File Reference
daq_base.h File Reference
Embedded DAQ protocol meant to communicate with a PC dashboard over CAN.
#include <string.h>
#include "common/phal_L4/can/can.h"
#include "common/phal_L4/gpio/gpio.h"
#include "common/phal_L4/eeprom_spi/eeprom_spi.h"
#include "common/queue/queue.h"
Data Structures
struct daq_variable_t
Macros
#define DAQ_EEPROM_ENABLE
#define DAQ_CMD_LENGTH 3
#define DAQ_CMD_MASK 0b111
#define DAQ_ID_LENGTH 5
#define DAQ_ID_MASK 0b11111
#define DAQ_BANK_LENGTH 4
#define DAQ_BANK_MASK 0xF
#define DAQ_PIN_LENGTH 4
#define DAQ_PIN_MASK 0xF
#define DAQ_PIN_VAL_LENGTH 2
#define DAQ_PIN_VAL_ERROR 0x2
Typedefs
typedef void(* read_func_ptr_t) (void *arg)
typedef void(* write_func_ptr_t) (void *arg)
Enumerations
enum Daq_Cmd_t {
DAQ_CMD_READ = 0 , DAQ_CMD_WRITE = 1 , DAQ_CMD_LOAD = 2 , DAQ_CMD_SAVE = 3 ,
DAQ_CMD_PUB_START = 4 , DAQ_CMD_PUB_STOP = 5 , DAQ_CMD_READ_PIN = 6
}
enum Daq_Rply_t {
DAQ_RPLY_READ = 0 , DAQ_RPLY_SAVE = 1 , DAQ_RPLY_READ_ERROR = 2 , DAQ_RPLY_WRITE_ERROR = 3 ,
DAQ_RPLY_SAVE_ERROR = 4 , DAQ_RPLY_LOAD_ERROR = 5 , DAQ_RPLY_PUB = 6 , DAQ_RPLY_READ_PIN = 7
}
Functions
bool daqInitBase (q_handle_t *tx_a, uint8_t num_variables, CAN_TypeDef *hcan, uint32_t ext_id, daq_variable_t *tracked_vars_)
Call after linking read and write functions / addresses If the eeprom is enabled, configures the eeprom to contain the variables and loads default values if applicable.
void daqPeriodicBase ()
Call periodically at DAQ_UPDATE_PERIOD Processes pending eeprom save commands and publishes live variables.
void daq_command_callback (CanMsgTypeDef_t *msg_header_a)
Callback for receiving a daq message, automatically called by can_parse.c.
Detailed Description
Embedded DAQ protocol meant to communicate with a PC dashboard over CAN.
Author
Luke Oxley (lcoxl.nosp@m.ey@p.nosp@m.urdue.nosp@m..edu)
Version
0.1
Date
2021-10-06
Copyright
Copyright (c) 2021
Definition in file daq_base.h.
Macro Definition Documentation
DAQ_BANK_LENGTH
#define DAQ_BANK_LENGTH 4
Definition at line 63 of file daq_base.h.
Referenced by daq_command_callback(), and readPin().
DAQ_BANK_MASK
#define DAQ_BANK_MASK 0xF
Definition at line 64 of file daq_base.h.
Referenced by daq_command_callback(), and readPin().
DAQ_CMD_LENGTH
#define DAQ_CMD_LENGTH 3
Definition at line 34 of file daq_base.h.
Referenced by daq_command_callback(), daqPeriodicBase(), readPin(), readVar(), and writeVar().
DAQ_CMD_MASK
#define DAQ_CMD_MASK 0b111
Definition at line 35 of file daq_base.h.
Referenced by daq_command_callback().
DAQ_EEPROM_ENABLE
#define DAQ_EEPROM_ENABLE
Definition at line 24 of file daq_base.h.
DAQ_ID_LENGTH
#define DAQ_ID_LENGTH 5
Definition at line 60 of file daq_base.h.
Referenced by daq_command_callback(), daqPeriodicBase(), loadFile(), pubVarStart(), readVar(), saveFile(), and writeVar().
DAQ_ID_MASK
#define DAQ_ID_MASK 0b11111
Definition at line 61 of file daq_base.h.
Referenced by daq_command_callback().
DAQ_PIN_LENGTH
#define DAQ_PIN_LENGTH 4
Definition at line 65 of file daq_base.h.
Referenced by daq_command_callback(), and readPin().
DAQ_PIN_MASK
#define DAQ_PIN_MASK 0xF
Definition at line 66 of file daq_base.h.
Referenced by daq_command_callback(), and readPin().
DAQ_PIN_VAL_ERROR
#define DAQ_PIN_VAL_ERROR 0x2
Definition at line 69 of file daq_base.h.
Referenced by readPin().
DAQ_PIN_VAL_LENGTH
#define DAQ_PIN_VAL_LENGTH 2
Definition at line 68 of file daq_base.h.
Referenced by readPin().
Typedef Documentation
read_func_ptr_t
typedef void(* read_func_ptr_t) (void *arg)
Definition at line 30 of file daq_base.h.
write_func_ptr_t
typedef void(* write_func_ptr_t) (void *arg)
Definition at line 31 of file daq_base.h.
Enumeration Type Documentation
Daq_Cmd_t
enum Daq_Cmd_t
Enumerator
DAQ_CMD_READ
DAQ_CMD_WRITE
DAQ_CMD_LOAD
DAQ_CMD_SAVE
DAQ_CMD_PUB_START
DAQ_CMD_PUB_STOP
DAQ_CMD_READ_PIN
Definition at line 37 of file daq_base.h.
Daq_Rply_t
enum Daq_Rply_t
Enumerator
DAQ_RPLY_READ
DAQ_RPLY_SAVE
DAQ_RPLY_READ_ERROR
DAQ_RPLY_WRITE_ERROR
DAQ_RPLY_SAVE_ERROR
DAQ_RPLY_LOAD_ERROR
DAQ_RPLY_PUB
DAQ_RPLY_READ_PIN
Definition at line 48 of file daq_base.h.
Function Documentation
daq_command_callback()
void daq_command_callback (CanMsgTypeDef_t * msg_header_a)
Callback for receiving a daq message, automatically called by can_parse.c.
Parameters
msg_header_a Rx CAN message
process daq request 3 bit command type: read, write, load, save, start pub, stop pub followed by 5 bit var id write is followed by variable data, length pre-specified for each var id publish is followed by publish rate (in Hz)
Definition at line 266 of file daq_base.c.
References daq_rx_frame_reader_t::curr_bit, DAQ_BANK_LENGTH, DAQ_BANK_MASK, DAQ_CMD_LENGTH, DAQ_CMD_LOAD, DAQ_CMD_MASK, DAQ_CMD_PUB_START, DAQ_CMD_PUB_STOP, DAQ_CMD_READ, DAQ_CMD_READ_PIN, DAQ_CMD_SAVE, DAQ_CMD_WRITE, DAQ_ID_LENGTH, DAQ_ID_MASK, DAQ_PIN_LENGTH, DAQ_PIN_MASK, CanMsgTypeDef_t::Data, CanMsgTypeDef_t::DLC, flushDaqFrame(), loadFile(), pubVarStart(), pubVarStop(), daq_rx_frame_reader_t::raw_data_a, readPin(), readVar(), saveFile(), and writeVar().
Referenced by daq_command_TEST_NODE_TEST_CALLBACK().
daqInitBase()
bool daqInitBase (q_handle_t * tx_a, uint8_t num_variables, CAN_TypeDef * hcan, uint32_t ext_id, daq_variable_t * tracked_vars_)
Call after linking read and write functions / addresses If the eeprom is enabled, configures the eeprom to contain the variables and loads default values if applicable.
Parameters
tx_a Address of the tx CAN buffer to send responses to
Returns
Returns false if the operation was successful
Definition at line 50 of file daq_base.c.
References ext_id, num_vars, q_tx_can_a, and tracked_vars.
Referenced by daqInit().
daqPeriodicBase()
void daqPeriodicBase ()
Call periodically at DAQ_UPDATE_PERIOD Processes pending eeprom save commands and publishes live variables.
Definition at line 315 of file daq_base.c.
References appendDataToFrame(), daq_tx_frame_writer_t::curr_bit, DAQ_CMD_LENGTH, DAQ_ID_LENGTH, DAQ_RPLY_PUB, daq_tick, flushDaqFrame(), num_vars, daq_variable_t::read_func_a, tracked_vars, and v_memcpy().
Referenced by daqPeriodic().