PER Firmware: source/daq/main.c File Reference
main.c File Reference
#include "main.h"
#include "buffer.h"
#include "common/can_library/generated/DAQ.h"
#include "common/freertos/freertos.h"
#include "common/phal/can.h"
#include "common/phal/gpio.h"
#include "common/phal/rcc.h"
#include "common/phal/rtc.h"
#include "common/phal/spi.h"
#include "common/phal/usart.h"
#include "daq_can.h"
#include "daq_hub.h"
#include "daq_spi.h"
Macros
#define TargetCoreClockrateHz 168000000
Functions
static void _iodev_write (usart_init_t *handle, char *buffer, int size)
int debug_printf (const char *fmt,...)
defineStaticQueue (q_tcp_tx, timestamped_frame_t, 32)
defineStaticQueue (q_can1_rx, timestamped_frame_t, 2048)
defineStaticSemaphore (spi1_lock)
static void configure_interrupts (void)
bool can_parse_error_status (uint32_t err, timestamped_frame_t *frame)
void shutdown (void)
Disables high power consumption devices If file open, flushes it to the sd card Then unmounts sd card.
int main ()
static void can_rx_irq_handler (CAN_TypeDef *can_h)
void CAN1_RX0_IRQHandler ()
void CAN2_RX0_IRQHandler ()
void CAN1_SCE_IRQHandler ()
void EXTI15_10_IRQHandler ()
void HardFault_Handler ()
Variables
GPIOInitConfig_t gpio_config []
uint32_t APB1ClockRateHz
uint32_t APB2ClockRateHz
uint32_t AHBClockRateHz
uint32_t PLLClockRateHz
ClockRateConfig_t clock_config
dma_init_t spi_rx_dma_config = SPI1_RXDMA_CONT_CONFIG(NULL, 2)
dma_init_t spi_tx_dma_config = SPI1_TXDMA_CONT_CONFIG(NULL, 1)
SPI_InitConfig_t eth_spi_config
RTC_timestamp_t start_time
dma_init_t usart_tx_dma_config = USART6_TXDMA_CONT_CONFIG(NULL, 1)
dma_init_t usart_rx_dma_config = USART6_RXDMA_CONT_CONFIG(NULL, 2)
usart_init_t lte_usart_config
daq_hub_t daq_hub
volatile timestamped_frame_t can_rx_buffer [2048]
b_tail_t tails [RX_TAIL_COUNT]
b_handle_t b_rx_can
timestamped_frame_t tcp_rx_buf [100]
volatile uint32_t error_irq_cnt = 0
Macro Definition Documentation
TargetCoreClockrateHz
#define TargetCoreClockrateHz 168000000
Definition at line 62 of file main.c.
Function Documentation
_iodev_write()
static void _iodev_write (usart_init_t * handle, char * buffer, int size) inline static
Definition at line 114 of file main.c.
CAN1_RX0_IRQHandler()
void CAN1_RX0_IRQHandler ()
Definition at line 263 of file main.c.
References can_rx_irq_handler().
CAN1_SCE_IRQHandler()
void CAN1_SCE_IRQHandler ()
Definition at line 275 of file main.c.
References b_rx_can, bCommitWrite(), bGetHeadForWrite(), can_parse_error_status(), error_irq_cnt, and getTick.
CAN2_RX0_IRQHandler()
void CAN2_RX0_IRQHandler ()
Definition at line 267 of file main.c.
References can_rx_irq_handler().
can_parse_error_status()
bool can_parse_error_status (uint32_t err, timestamped_frame_t * frame)
Definition at line 294 of file main.c.
References timestamped_frame_t::bus_id, CAN_ERR_ACK, CAN_ERR_BUSOFF, CAN_ERR_CRTL, CAN_ERR_CRTL_RX_PASSIVE, CAN_ERR_CRTL_RX_WARNING, CAN_ERR_CRTL_TX_PASSIVE, CAN_ERR_CRTL_TX_WARNING, CAN_ERR_CRTL_UNSPEC, CAN_ERR_DLC, CAN_ERR_FLAG, CAN_ERR_LOSTARB_UNSPEC, CAN_ERR_PROT, CAN_ERR_PROT_BIT0, CAN_ERR_PROT_BIT1, CAN_ERR_PROT_FORM, CAN_ERR_PROT_LOC_CRC_SEQ, CAN_ERR_PROT_LOC_UNSPEC, CAN_ERR_PROT_STUFF, CAN_ERR_PROT_UNSPEC, CAN_ERR_TRX_UNSPEC, timestamped_frame_t::data, timestamped_frame_t::dlc, and timestamped_frame_t::msg_id.
Referenced by CAN1_SCE_IRQHandler().
can_rx_irq_handler()
static void can_rx_irq_handler (CAN_TypeDef * can_h) static
Definition at line 203 of file main.c.
References b_rx_can, daq_hub_t::bcan_rx_overflow, bCommitWrite(), bGetHeadForWrite(), BUS_ID_CAN1, BUS_ID_CAN2, CAN_EFF_FLAG, DAQ_FRAME_CAN_RX, daq_hub, getTick, q_rx_can, qSendToBack(), and rtc_config_cb().
Referenced by CAN1_RX0_IRQHandler(), and CAN2_RX0_IRQHandler().
configure_interrupts()
static void configure_interrupts (void) static
Definition at line 184 of file main.c.
Referenced by main().
debug_printf()
int debug_printf (const char * fmt, ...)
Definition at line 114 of file main.c.
Referenced by _eth_handle_error(), eth_tcp_update(), eth_update_periodic(), sd_create_new_file(), sd_handle_error(), and sd_update_periodic().
defineStaticQueue() [1/2]
defineStaticQueue (q_can1_rx , timestamped_frame_t , 2048)
defineStaticQueue() [2/2]
defineStaticQueue (q_tcp_tx , timestamped_frame_t , 32)
defineStaticSemaphore()
defineStaticSemaphore (spi1_lock)
EXTI15_10_IRQHandler()
void EXTI15_10_IRQHandler ()
Definition at line 374 of file main.c.
References shutdown().
HardFault_Handler()
void HardFault_Handler (void)
Definition at line 381 of file main.c.
References ERROR_LED_PIN, ERROR_LED_PORT, and PHAL_writeGPIO().
main()
int main (void)
Definition at line 137 of file main.c.
References APB2ClockRateHz, b_rx_can, bConstruct(), can_rx_buffer, clock_config, configure_interrupts(), createStaticQueue, createStaticSemaphore, DAQ_CAN1_RX_COUNT, daq_create_threads(), daq_hub_init(), daq_spi_register_callbacks(), ETH_RST_PIN, ETH_RST_PORT, eth_spi_config, gpio_config, HardFault_Handler(), log_yellow, lte_usart_config, PHAL_configureClockRates(), PHAL_configureRTC(), PHAL_initCAN(), PHAL_initGPIO(), PHAL_initUSART(), PHAL_SPI_init(), PHAL_writeGPIO(), q_can1_rx, q_tcp_tx, spi1_lock, start_time, and TCP_TX_ITEM_COUNT.
shutdown()
void shutdown (void)
Disables high power consumption devices If file open, flushes it to the sd card Then unmounts sd card.
Definition at line 362 of file main.c.
References daq_shutdown_hook(), getTick, PHAL_readGPIO(), PWR_LOSS_PIN, and PWR_LOSS_PORT.
Referenced by EXTI15_10_IRQHandler().
Variable Documentation
AHBClockRateHz
uint32_t AHBClockRateHz extern
Definition at line 17 of file rcc.c.
APB1ClockRateHz
uint32_t APB1ClockRateHz extern
Definition at line 15 of file rcc.c.
APB2ClockRateHz
uint32_t APB2ClockRateHz extern
Definition at line 16 of file rcc.c.
b_rx_can
b_handle_t b_rx_can
Initial value:
= {
    .buffer    = (volatile uint8_t*)can_rx_buffer,
    .tails     = tails,
    .num_tails = RX_TAIL_COUNT,
}
Definition at line 121 of file main.c.
Referenced by CAN1_SCE_IRQHandler(), can_rx_irq_handler(), and main().
can_rx_buffer
volatile timestamped_frame_t can_rx_buffer[2048]
Definition at line 119 of file main.c.
Referenced by main().
clock_config
ClockRateConfig_t clock_config
Initial value:
= {
    .clock_source              = CLOCK_SOURCE_HSE,
    .use_pll                   = true,
    .pll_src                   = PLL_SRC_HSE,
    .vco_output_rate_target_hz = 336000000,
    .system_clock_target_hz    = 168000000,
    .ahb_clock_target_hz       = (168000000 / 1),
    .apb1_clock_target_hz      = (168000000 / 4),
    .apb2_clock_target_hz      = (168000000 / 4),
}
Definition at line 63 of file main.c.
daq_hub
daq_hub_t daq_hub extern
Definition at line 28 of file daq_hub.c.
Referenced by _eth_handle_error(), _eth_tcp_send_frame_raw(), _sd_write_periodic(), can_rx_irq_handler(), daq_heartbeat(), daq_hub_init(), daq_request_sd_mount(), eth_reset_error(), eth_tcp_receive_periodic(), eth_tcp_send_frame(), eth_tcp_send_periodic(), eth_tcp_update(), eth_udp_send_periodic(), eth_update_periodic(), rtc_config_cb(), sd_create_new_file(), sd_file_sync(), sd_handle_error(), sd_reset_error(), sd_shutdown(), and sd_update_periodic().
error_irq_cnt
volatile uint32_t error_irq_cnt = 0
Definition at line 273 of file main.c.
Referenced by CAN1_SCE_IRQHandler().
eth_spi_config
SPI_InitConfig_t eth_spi_config
Initial value:
= {
    .data_len      = 8,
    .nss_sw        = false,
    .nss_gpio_port = GPIOA,
    .nss_gpio_pin  = 4,
    .rx_dma_cfg    = &spi_rx_dma_config,
    .tx_dma_cfg    = &spi_tx_dma_config,
    .periph        = SPI1,
}
Definition at line 77 of file main.c.
Referenced by cs_desel(), cs_sel(), main(), spi_rb(), spi_rb_burst(), spi_wb(), and spi_wb_burst().
gpio_config
GPIOInitConfig_t gpio_config[]
Definition at line 16 of file main.c.
lte_usart_config
usart_init_t lte_usart_config
Initial value:
= {
     .baud_rate        = 115200,
     .word_length      = WORD_8,
     .stop_bits        = SB_ONE,
     .parity           = PT_NONE,
     .hw_flow_ctl      = HW_DISABLE,
     .ovsample         = OV_16,
     .obsample         = OB_DISABLE,
     .periph           = USART6,
     .wake_addr        = false,
     .usart_active_num = USART6_ACTIVE_IDX,
     .tx_dma_cfg       = &usart_tx_dma_config,
     .rx_dma_cfg       = &usart_rx_dma_config}
Definition at line 101 of file main.c.
Referenced by main().
PLLClockRateHz
uint32_t PLLClockRateHz extern
Definition at line 18 of file rcc.c.
spi_rx_dma_config
dma_init_t spi_rx_dma_config = SPI1_RXDMA_CONT_CONFIG(NULL, 2)
Definition at line 75 of file main.c.
spi_tx_dma_config
dma_init_t spi_tx_dma_config = SPI1_TXDMA_CONT_CONFIG(NULL, 1)
Definition at line 76 of file main.c.
start_time
RTC_timestamp_t start_time
Initial value:
=
    {
        .date = {.month_bcd = RTC_MONTH_UNKNOWN,
                 .weekday   = RTC_WEEKDAY_UNKNOWN,
                 .day_bcd   = 0x00,
                 .year_bcd  = 0x00},
        .time = {.hours_bcd   = 0x00,
                 .minutes_bcd = 0x00,
                 .seconds_bcd = 0x00,
                 .time_format = RTC_FORMAT_24_HOUR},
}
Definition at line 87 of file main.c.
Referenced by main().
tails
b_tail_t tails[RX_TAIL_COUNT]
Definition at line 120 of file main.c.
tcp_rx_buf
timestamped_frame_t tcp_rx_buf[100]
Definition at line 127 of file main.c.
Referenced by eth_tcp_receive_periodic().
usart_rx_dma_config
dma_init_t usart_rx_dma_config = USART6_RXDMA_CONT_CONFIG(NULL, 2)
Definition at line 100 of file main.c.
Referenced by main().
usart_tx_dma_config
dma_init_t usart_tx_dma_config = USART6_TXDMA_CONT_CONFIG(NULL, 1)
Definition at line 99 of file main.c.
Referenced by main().