PER Firmware: common/daq/daq_base.c File Reference
daq_base.c File Reference
#include "common/daq/daq_base.h"
Data Structures
struct daq_tx_frame_writer_t
struct daq_rx_frame_reader_t
Functions
static bool readVar (uint8_t var_id, daq_tx_frame_writer_t *tx_msg)
static bool writeVar (uint8_t var_id, daq_rx_frame_reader_t *rx_msg, daq_tx_frame_writer_t *tx_msg)
static bool saveFile (daq_rx_frame_reader_t *rx_msg, daq_tx_frame_writer_t *tx_msg)
static bool loadFile (daq_rx_frame_reader_t *rx_msg, daq_tx_frame_writer_t *tx_msg)
static bool pubVarStart (uint8_t var_id, daq_rx_frame_reader_t *rx_msg)
static bool pubVarStop (uint8_t var_id)
static bool appendDataToFrame (daq_tx_frame_writer_t *tx_msg, uint64_t data, uint8_t bit_length)
static void flushDaqFrame (daq_tx_frame_writer_t *tx_msg)
static void sendDaqFrame (daq_tx_frame_writer_t tx_frame)
static void daqeQueuePop ()
static void daqeQueuePush ()
static void v_memcpy (volatile void *dest, volatile void *src, size_t len)
bool daqInitBase (q_handle_t *tx_a, uint8_t num_variables_, CAN_TypeDef *hcan, uint32_t ext_id_, daq_variable_t *tracked_vars_)
Call after linking read and write functions / addresses If the eeprom is enabled, configures the eeprom to contain the variables and loads default values if applicable.
static bool readPin (uint8_t bank_pin, daq_tx_frame_writer_t *tx_msg)
void daq_command_callback (CanMsgTypeDef_t *msg_header_a)
Callback for receiving a daq message, automatically called by can_parse.c.
void daqPeriodicBase ()
Call periodically at DAQ_UPDATE_PERIOD Processes pending eeprom save commands and publishes live variables.
Variables
static q_handle_t * q_tx_can_a
static uint8_t num_vars
static uint32_t ext_id
static CAN_TypeDef * can
static daq_variable_t * tracked_vars
static uint32_t daq_tick = 0
Function Documentation
appendDataToFrame()
static bool appendDataToFrame (daq_tx_frame_writer_t * tx_msg, uint64_t data, uint8_t bit_length) static
Definition at line 359 of file daq_base.c.
References daq_tx_frame_writer_t::curr_bit, flushDaqFrame(), and daq_tx_frame_writer_t::raw_data.
Referenced by daqPeriodicBase(), readPin(), readVar(), and writeVar().
daq_command_callback()
void daq_command_callback (CanMsgTypeDef_t * msg_header_a)
Callback for receiving a daq message, automatically called by can_parse.c.
process daq request 3 bit command type: read, write, load, save, start pub, stop pub followed by 5 bit var id write is followed by variable data, length pre-specified for each var id publish is followed by publish rate (in Hz)
Definition at line 266 of file daq_base.c.
References daq_rx_frame_reader_t::curr_bit, DAQ_BANK_LENGTH, DAQ_BANK_MASK, DAQ_CMD_LENGTH, DAQ_CMD_LOAD, DAQ_CMD_MASK, DAQ_CMD_PUB_START, DAQ_CMD_PUB_STOP, DAQ_CMD_READ, DAQ_CMD_READ_PIN, DAQ_CMD_SAVE, DAQ_CMD_WRITE, DAQ_ID_LENGTH, DAQ_ID_MASK, DAQ_PIN_LENGTH, DAQ_PIN_MASK, CanMsgTypeDef_t::Data, CanMsgTypeDef_t::DLC, flushDaqFrame(), loadFile(), pubVarStart(), pubVarStop(), daq_rx_frame_reader_t::raw_data_a, readPin(), readVar(), saveFile(), and writeVar().
Referenced by daq_command_TEST_NODE_TEST_CALLBACK().
daqeQueuePop()
static void daqeQueuePop () static
daqeQueuePush()
static void daqeQueuePush () static
daqInitBase()
bool daqInitBase (q_handle_t * tx_a, uint8_t num_variables, CAN_TypeDef * hcan, uint32_t ext_id, daq_variable_t * tracked_vars_)
Call after linking read and write functions / addresses If the eeprom is enabled, configures the eeprom to contain the variables and loads default values if applicable.
Parameters
tx_a Address of the tx CAN buffer to send responses to
Returns
Returns false if the operation was successful
Definition at line 50 of file daq_base.c.
References ext_id, num_vars, q_tx_can_a, and tracked_vars.
Referenced by daqInit().
daqPeriodicBase()
void daqPeriodicBase ()
Call periodically at DAQ_UPDATE_PERIOD Processes pending eeprom save commands and publishes live variables.
Definition at line 315 of file daq_base.c.
References appendDataToFrame(), daq_tx_frame_writer_t::curr_bit, DAQ_CMD_LENGTH, DAQ_ID_LENGTH, DAQ_RPLY_PUB, daq_tick, flushDaqFrame(), num_vars, daq_variable_t::read_func_a, tracked_vars, and v_memcpy().
Referenced by daqPeriodic().
flushDaqFrame()
static void flushDaqFrame (daq_tx_frame_writer_t * tx_msg) static
Definition at line 379 of file daq_base.c.
References daq_tx_frame_writer_t::curr_bit, daq_tx_frame_writer_t::raw_data, and sendDaqFrame().
Referenced by appendDataToFrame(), daq_command_callback(), daqPeriodicBase(), readPin(), and readVar().
loadFile()
static bool loadFile (daq_rx_frame_reader_t * rx_msg, daq_tx_frame_writer_t * tx_msg) static
Definition at line 206 of file daq_base.c.
References daq_rx_frame_reader_t::curr_bit, DAQ_ID_LENGTH, NAME_LEN, daq_rx_frame_reader_t::raw_data_a, and requestLoad().
Referenced by daq_command_callback().
pubVarStart()
static bool pubVarStart (uint8_t var_id, daq_rx_frame_reader_t * rx_msg) static
Definition at line 241 of file daq_base.c.
References daq_rx_frame_reader_t::curr_bit, DAQ_ID_LENGTH, daq_variable_t::pub_period, daq_rx_frame_reader_t::raw_data_a, and tracked_vars.
Referenced by daq_command_callback().
pubVarStop()
static bool pubVarStop (uint8_t var_id) static
Definition at line 252 of file daq_base.c.
References daq_variable_t::pub_period, and tracked_vars.
Referenced by daq_command_callback().
readPin()
static bool readPin (uint8_t bank_pin, daq_tx_frame_writer_t * tx_msg) static
Definition at line 77 of file daq_base.c.
References appendDataToFrame(), daq_tx_frame_writer_t::curr_bit, DAQ_BANK_LENGTH, DAQ_BANK_MASK, DAQ_CMD_LENGTH, DAQ_PIN_LENGTH, DAQ_PIN_MASK, DAQ_PIN_VAL_ERROR, DAQ_PIN_VAL_LENGTH, DAQ_RPLY_READ_PIN, flushDaqFrame(), and PHAL_readGPIO().
Referenced by daq_command_callback().
readVar()
static bool readVar (uint8_t var_id, daq_tx_frame_writer_t * tx_msg) static
Definition at line 137 of file daq_base.c.
References appendDataToFrame(), daq_tx_frame_writer_t::curr_bit, DAQ_CMD_LENGTH, DAQ_ID_LENGTH, DAQ_RPLY_READ, DAQ_RPLY_READ_ERROR, flushDaqFrame(), daq_variable_t::read_func_a, tracked_vars, and v_memcpy().
Referenced by daq_command_callback().
saveFile()
static bool saveFile (daq_rx_frame_reader_t * rx_msg, daq_tx_frame_writer_t * tx_msg) static
Definition at line 223 of file daq_base.c.
References daq_rx_frame_reader_t::curr_bit, DAQ_ID_LENGTH, NAME_LEN, daq_rx_frame_reader_t::raw_data_a, and requestFlush().
Referenced by daq_command_callback().
sendDaqFrame()
static void sendDaqFrame (daq_tx_frame_writer_t tx_frame) static
Definition at line 393 of file daq_base.c.
References can, daq_tx_frame_writer_t::curr_bit, daq_tx_frame_writer_t::data, ext_id, q_tx_can_a, qSendToBack(), and v_memcpy().
Referenced by flushDaqFrame().
v_memcpy()
static void v_memcpy (volatile void * dest, volatile void * src, size_t len) static
Definition at line 403 of file daq_base.c.
Referenced by daqPeriodicBase(), readVar(), sendDaqFrame(), and writeVar().
writeVar()
static bool writeVar (uint8_t var_id, daq_rx_frame_reader_t * rx_msg, daq_tx_frame_writer_t * tx_msg) static
Definition at line 174 of file daq_base.c.
References appendDataToFrame(), daq_variable_t::bit_length, daq_rx_frame_reader_t::curr_bit, DAQ_CMD_LENGTH, DAQ_ID_LENGTH, DAQ_RPLY_WRITE_ERROR, daq_rx_frame_reader_t::raw_data_a, tracked_vars, v_memcpy(), and daq_variable_t::write_func_a.
Referenced by daq_command_callback().
Variable Documentation
can
CAN_TypeDef* can static
Definition at line 47 of file daq_base.c.
Referenced by sendDaqFrame().
daq_tick
uint32_t daq_tick = 0 static
Definition at line 312 of file daq_base.c.
Referenced by daqPeriodicBase().
ext_id
uint32_t ext_id static
Definition at line 46 of file daq_base.c.
Referenced by daqInitBase(), and sendDaqFrame().
num_vars
uint8_t num_vars static
Definition at line 45 of file daq_base.c.
Referenced by daqInitBase(), and daqPeriodicBase().
q_tx_can_a
q_handle_t* q_tx_can_a static
Definition at line 44 of file daq_base.c.
Referenced by daqInitBase(), and sendDaqFrame().
tracked_vars
daq_variable_t* tracked_vars static
Definition at line 48 of file daq_base.c.
Referenced by daqInitBase(), daqPeriodicBase(), pubVarStart(), pubVarStop(), readVar(), and writeVar().