PER Firmware: source/dashboard/main.c File Reference
main.c File Reference
"Dashboard" node source code
#include "common/can_library/faults_common.h"
#include "common/common_defs/common_defs.h"
#include "common/phal/adc.h"
#include "common/phal/can.h"
#include "common/phal/dma.h"
#include "common/phal/gpio.h"
#include "common/phal/rcc.h"
#include "common/phal/usart.h"
#include "common/freertos/freertos.h"
#include "common/can_library/generated/DASHBOARD.h"
#include "lcd.h"
#include "main.h"
#include "nextion.h"
#include "pedals.h"
Functions
void preflight_animation (void)
void heartbeat_led ()
Updates system LED indicators and CAN stats.
void lcd_tx_cmd ()
Called periodically to send commands to the Nextion LCD display via USART.
void config_button_irqs ()
void service_button_inputs ()
Processes dashboard button flags and triggers corresponding actions.
void send_version ()
void HardFault_Handler ()
ALLOCATE_STRBUF (lcd_tx_buf, 1024)
void preflight_task ()
void can_worker_task ()
defineThreadStack (preflight_task, 10, osPriorityRealtime, 1024)
defineThreadStack (pedalsPeriodic, FILT_THROTTLE_BRAKE_PERIOD_MS, osPriorityHigh, 512)
defineThreadStack (can_worker_task, 20, osPriorityNormal, 512)
defineThreadStack (updateFaultDisplay, 500, osPriorityLow, 256)
defineThreadStack (heartbeat_led, 500, osPriorityLow, 128)
defineThreadStack (service_button_inputs, 50, osPriorityLow, 1024)
defineThreadStack (send_version, DASH_VERSION_PERIOD_MS, osPriorityLow, 256)
defineThreadStack (updateTelemetryPages, 200, osPriorityLow, 1024)
defineThreadStack (sendTVParameters, DASHBOARD_VCU_PARAMETERS_PERIOD_MS, osPriorityLow, 256)
int main (void)
void EXTI9_5_IRQHandler ()
void EXTI15_10_IRQHandler ()
Variables
GPIOInitConfig_t gpio_config []
volatile raw_adc_values_t raw_adc_values
ADCInitConfig_t adc_config
ADCChannelConfig_t adc_channel_config []
dma_init_t adc_dma_config = ADC1_DMA_CONT_CONFIG((uint32_t)&raw_adc_values, sizeof(raw_adc_values) / sizeof(raw_adc_values.t1), 0b01)
dma_init_t usart_tx_dma_config = USART1_TXDMA_CONT_CONFIG(NULL, 1)
dma_init_t usart_rx_dma_config = USART1_RXDMA_CONT_CONFIG(NULL, 2)
usart_init_t lcd
static constexpr uint32_t TargetCoreClockrateHz = 16000000
ClockRateConfig_t clock_config
uint32_t APB1ClockRateHz
uint32_t APB2ClockRateHz
uint32_t AHBClockRateHz
uint32_t PLLClockRateHz
page_t curr_page
volatile dashboard_input_state_t input_state = {0}
Detailed Description
"Dashboard" node source code
Author
Irving Wang (irvin.nosp@m.gw@p.nosp@m.urdue.nosp@m..edu)
Luke Oxley (lcoxl.nosp@m.ey@p.nosp@m.urdue.nosp@m..edu)
Chris Mcgalliard (cpmcg.nosp@m.alli.nosp@m.ard@g.nosp@m.mail.nosp@m..com)
Definition in file main.c.
Function Documentation
ALLOCATE_STRBUF()
ALLOCATE_STRBUF (lcd_tx_buf , 1024)
can_worker_task()
void can_worker_task ()
Definition at line 233 of file main.c.
References CAN_rx_update(), CAN_tx_update(), and lcd_tx_cmd().
Referenced by preflight_task().
config_button_irqs()
void config_button_irqs ()
Definition at line 409 of file main.c.
Referenced by main().
defineThreadStack() [1/9]
defineThreadStack (can_worker_task , 20 , osPriorityNormal , 512)
defineThreadStack() [2/9]
defineThreadStack (heartbeat_led , 500 , osPriorityLow , 128)
defineThreadStack() [3/9]
defineThreadStack (pedalsPeriodic , FILT_THROTTLE_BRAKE_PERIOD_MS , osPriorityHigh , 512)
defineThreadStack() [4/9]
defineThreadStack (preflight_task , 10 , osPriorityRealtime , 1024)
defineThreadStack() [5/9]
defineThreadStack (send_version , DASH_VERSION_PERIOD_MS , osPriorityLow , 256)
defineThreadStack() [6/9]
defineThreadStack (sendTVParameters , DASHBOARD_VCU_PARAMETERS_PERIOD_MS , osPriorityLow , 256)
defineThreadStack() [7/9]
defineThreadStack (service_button_inputs , 50 , osPriorityLow , 1024)
defineThreadStack() [8/9]
defineThreadStack (updateFaultDisplay , 500 , osPriorityLow , 256)
defineThreadStack() [9/9]
defineThreadStack (updateTelemetryPages , 200 , osPriorityLow , 1024)
EXTI15_10_IRQHandler()
void EXTI15_10_IRQHandler ()
Definition at line 353 of file main.c.
References input_state, dashboard_input_state_t::select_button, and dashboard_input_state_t::start_button.
EXTI9_5_IRQHandler()
void EXTI9_5_IRQHandler ()
Definition at line 327 of file main.c.
References dashboard_input_state_t::down_button, input_state, dashboard_input_state_t::left_button, dashboard_input_state_t::right_button, and dashboard_input_state_t::up_button.
HardFault_Handler()
void HardFault_Handler (void) extern
Definition at line 447 of file main.c.
References ERROR_LED_GPIO_Port, and ERROR_LED_Pin.
heartbeat_led()
void heartbeat_led ()
Updates system LED indicators and CAN stats.
Controls heartbeat, connection, precharge, IMD and BMS status LEDs. Handles periodic CAN statistics transmission.
Definition at line 292 of file main.c.
References BMS_LED_GPIO_Port, BMS_LED_Pin, can_data, CONN_LED_GPIO_Port, CONN_LED_MS_THRESH, CONN_LED_Pin, HEART_LED_GPIO_Port, HEART_LED_Pin, IMD_LED_GPIO_Port, IMD_LED_Pin, last_can_rx_time_ms, PHAL_toggleGPIO(), PHAL_writeGPIO(), PRCHG_LED_GPIO_Port, and PRCHG_LED_Pin.
Referenced by preflight_task().
lcd_tx_cmd()
void lcd_tx_cmd ()
Called periodically to send commands to the Nextion LCD display via USART.
Definition at line 439 of file main.c.
References strbuf_t::data, lcd, lcd_tx_buf, strbuf_t::length, PHAL_usartTxBusy(), PHAL_usartTxDma(), and strbuf_clear().
Referenced by can_worker_task(), and updatePage().
main()
int main (void)
Definition at line 156 of file main.c.
References adc_channel_config, adc_config, adc_dma_config, APB2ClockRateHz, BMS_LED_GPIO_Port, BMS_LED_Pin, CAN_library_init(), clock_config, config_button_irqs(), CONN_LED_GPIO_Port, CONN_LED_Pin, createThread, ERROR_LED_GPIO_Port, ERROR_LED_Pin, gpio_config, HardFault_Handler(), HEART_LED_GPIO_Port, HEART_LED_Pin, IMD_LED_GPIO_Port, IMD_LED_Pin, initLCD(), lcd, PHAL_configureClockRates(), PHAL_FDCAN_init(), PHAL_initADC(), PHAL_initDMA(), PHAL_initGPIO(), PHAL_initUSART(), PHAL_startADC(), PHAL_startTxfer(), PHAL_writeGPIO(), PRCHG_LED_GPIO_Port, PRCHG_LED_Pin, and preflight_task().
preflight_animation()
void preflight_animation (void)
Definition at line 243 of file main.c.
References BMS_LED_GPIO_Port, BMS_LED_Pin, CONN_LED_GPIO_Port, CONN_LED_Pin, ERROR_LED_GPIO_Port, ERROR_LED_Pin, HEART_LED_GPIO_Port, HEART_LED_Pin, IMD_LED_GPIO_Port, IMD_LED_Pin, PHAL_writeGPIO(), PRCHG_LED_GPIO_Port, and PRCHG_LED_Pin.
Referenced by main(), and preflight_task().
preflight_task()
void preflight_task ()
Definition at line 203 of file main.c.
References can_worker_task(), CONN_LED_GPIO_Port, CONN_LED_Pin, counter, createThread, ERROR_LED_GPIO_Port, ERROR_LED_Pin, HEART_LED_GPIO_Port, HEART_LED_Pin, heartbeat_led(), pedalsPeriodic(), PHAL_writeGPIO(), preflight_animation(), send_version(), sendTVParameters(), service_button_inputs(), updateFaultDisplay(), and updateTelemetryPages().
Referenced by main().
send_version()
void send_version ()
Definition at line 280 of file main.c.
Referenced by preflight_task().
service_button_inputs()
void service_button_inputs ()
Processes dashboard button flags and triggers corresponding actions.
Meant to be called periodically.
Definition at line 372 of file main.c.
References advancePage(), backPage(), dashboard_input_state_t::down_button, input_state, dashboard_input_state_t::left_button, moveDown(), moveUp(), dashboard_input_state_t::right_button, dashboard_input_state_t::select_button, selectItem(), dashboard_input_state_t::start_button, dashboard_input_state_t::up_button, dashboard_input_state_t::update_page, and updatePage().
Referenced by preflight_task().
Variable Documentation
adc_channel_config
ADCChannelConfig_t adc_channel_config[]
Initial value:
= {
    {.channel = (8), .rank = 1, .sampling_time = ADC_CHN_SMP_CYCLES_480},
    {.channel = (7), .rank = 2, .sampling_time = ADC_CHN_SMP_CYCLES_480},
    {.channel = (9), .rank = 3, .sampling_time = ADC_CHN_SMP_CYCLES_480},
    {.channel = (1), .rank = 4, .sampling_time = ADC_CHN_SMP_CYCLES_480},
    {.channel = (2), .rank = 5, .sampling_time = ADC_CHN_SMP_CYCLES_480},
    {.channel = (3), .rank = 6, .sampling_time = ADC_CHN_SMP_CYCLES_480}
}
Definition at line 76 of file main.c.
Referenced by main(), and main().
adc_config
ADCInitConfig_t adc_config
Initial value:
= {
    .prescaler      = ADC_CLK_PRESC_2,
    .resolution     = ADC_RES_12_BIT,
    .data_align     = ADC_DATA_ALIGN_RIGHT,
    .cont_conv_mode = true,
    .dma_mode       = ADC_DMA_CIRCULAR,
    .periph         = ADC1,
}
Definition at line 67 of file main.c.
Referenced by main(), and main().
adc_dma_config
dma_init_t adc_dma_config = ADC1_DMA_CONT_CONFIG((uint32_t)&raw_adc_values, sizeof(raw_adc_values) / sizeof(raw_adc_values.t1), 0b01)
Definition at line 85 of file main.c.
Referenced by main(), and main().
AHBClockRateHz
uint32_t AHBClockRateHz extern
Definition at line 17 of file rcc.c.
APB1ClockRateHz
uint32_t APB1ClockRateHz extern
Definition at line 15 of file rcc.c.
APB2ClockRateHz
uint32_t APB2ClockRateHz extern
Definition at line 16 of file rcc.c.
clock_config
ClockRateConfig_t clock_config
Initial value:
= {
    .clock_source           = CLOCK_SOURCE_HSI,
    .use_pll                = false,
    .system_clock_target_hz = TargetCoreClockrateHz,
    .ahb_clock_target_hz    = (TargetCoreClockrateHz / 1),
    .apb1_clock_target_hz   = (TargetCoreClockrateHz / (1)),
    .apb2_clock_target_hz   = (TargetCoreClockrateHz / (1)),
}
Definition at line 107 of file main.c.
curr_page
page_t curr_page extern
Definition at line 16 of file lcd.c.
Referenced by advancePage(), backPage(), calibrationTelemetryUpdate(), coolant_out_CALLBACK(), errorPageSelect(), faultTelemetryUpdate(), initLCD(), moveDown(), moveUp(), raceTelemetryUpdate(), sdcTelemetryUpdate(), selectItem(), updatePage(), and updateTelemetryPages().
gpio_config
GPIOInitConfig_t gpio_config[]
Definition at line 28 of file main.c.
input_state
volatile dashboard_input_state_t input_state = {0}
Definition at line 124 of file main.c.
Referenced by EXTI15_10_IRQHandler(), EXTI9_5_IRQHandler(), and service_button_inputs().
lcd
usart_init_t lcd
Initial value:
= {
    .baud_rate        = (115200),
    .word_length      = WORD_8,
    .stop_bits        = SB_ONE,
    .parity           = PT_NONE,
    .hw_flow_ctl      = HW_DISABLE,
    .ovsample         = OV_16,
    .obsample         = OB_DISABLE,
    .periph           = USART1,
    .wake_addr        = false,
    .usart_active_num = USART1_ACTIVE_IDX,
    .tx_dma_cfg       = &usart_tx_dma_config,
    .rx_dma_cfg       = &usart_rx_dma_config,
}
Definition at line 91 of file main.c.
Referenced by lcd_tx_cmd(), and main().
PLLClockRateHz
uint32_t PLLClockRateHz extern
Definition at line 18 of file rcc.c.
raw_adc_values
volatile raw_adc_values_t raw_adc_values
Definition at line 64 of file main.c.
Referenced by calibrationTelemetryUpdate(), pedalsPeriodic(), and shockpot_thread().
TargetCoreClockrateHz
uint32_t TargetCoreClockrateHz = 16000000 static constexpr
Definition at line 106 of file main.c.
usart_rx_dma_config
dma_init_t usart_rx_dma_config = USART1_RXDMA_CONT_CONFIG(NULL, 2)
Definition at line 89 of file main.c.
usart_tx_dma_config
dma_init_t usart_tx_dma_config = USART1_TXDMA_CONT_CONFIG(NULL, 1)
Definition at line 88 of file main.c.