PER Firmware: source/driveline/main.c File Reference
main.c File Reference
"Driveline" node source code
#include "common/can_library/generated/DRIVELINE.h"
#include "common/phal/can.h"
#include "common/phal/gpio.h"
#include "common/phal/rcc.h"
#include "common/phal/adc.h"
#include "common/phal/dma.h"
#include "common/freertos/freertos.h"
#include "pin_defs.h"
#include "config.h"
Data Structures
struct raw_adc_values_t
Functions
void HardFault_Handler ()
void shockpot_thread ()
defineThreadStack (shockpot_thread, 100, osPriorityNormal, 512)
int main (void)
Variables
GPIOInitConfig_t gpio_config []
static constexpr uint32_t TargetCoreClockrateHz = 16000000
ClockRateConfig_t clock_config
ADCInitConfig_t adc_config
ADCChannelConfig_t adc_channel_config []
volatile raw_adc_values_t raw_adc_values
dma_init_t adc_dma_config = ADC1_DMA_CONT_CONFIG((uint32_t)&raw_adc_values, sizeof(raw_adc_values) / sizeof(uint16_t), 0b01)
uint32_t APB1ClockRateHz
uint32_t APB2ClockRateHz
uint32_t AHBClockRateHz
uint32_t PLLClockRateHz
Detailed Description
"Driveline" node source code
Author
Irving Wang (irvin.nosp@m.gw@p.nosp@m.urdue.nosp@m..edu)
Definition in file main.c.
Function Documentation
defineThreadStack()
defineThreadStack (shockpot_thread , 100 , osPriorityNormal , 512)
HardFault_Handler()
void HardFault_Handler (void) extern
Definition at line 125 of file main.c.
References ERROR_LED_PIN, and ERROR_LED_PORT.
main()
int main (void)
Definition at line 77 of file main.c.
References adc_channel_config, adc_config, adc_dma_config, clock_config, createThread, gpio_config, HardFault_Handler(), PHAL_configureClockRates(), PHAL_FDCAN_init(), PHAL_initADC(), PHAL_initDMA(), PHAL_initGPIO(), PHAL_startADC(), PHAL_startTxfer(), and shockpot_thread().
shockpot_thread()
void shockpot_thread ()
Definition at line 112 of file main.c.
References raw_adc_values, raw_adc_values_t::shock_l, and raw_adc_values_t::shock_r.
Referenced by main().
Variable Documentation
adc_channel_config
ADCChannelConfig_t adc_channel_config[]
Initial value:
= {
    {.channel = (4) , .rank = 1, .sampling_time = ADC_CHN_SMP_CYCLES_480},
    {.channel = (10) , .rank = 2, .sampling_time = ADC_CHN_SMP_CYCLES_480},
}
Definition at line 51 of file main.c.
adc_config
ADCInitConfig_t adc_config
Initial value:
= {
    .prescaler      = ADC_CLK_PRESC_2,
    .resolution     = ADC_RES_12_BIT,
    .data_align     = ADC_DATA_ALIGN_RIGHT,
    .cont_conv_mode = true,
    .dma_mode       = ADC_DMA_CIRCULAR,
    .periph         = ADC1,
}
Definition at line 43 of file main.c.
adc_dma_config
dma_init_t adc_dma_config = ADC1_DMA_CONT_CONFIG((uint32_t)&raw_adc_values, sizeof(raw_adc_values) / sizeof(uint16_t), 0b01)
Definition at line 64 of file main.c.
AHBClockRateHz
uint32_t AHBClockRateHz extern
Definition at line 17 of file rcc.c.
APB1ClockRateHz
uint32_t APB1ClockRateHz extern
Definition at line 15 of file rcc.c.
APB2ClockRateHz
uint32_t APB2ClockRateHz extern
Definition at line 16 of file rcc.c.
clock_config
ClockRateConfig_t clock_config
Initial value:
= {
    .clock_source           = CLOCK_SOURCE_HSI,
    .use_pll                = false,
    .system_clock_target_hz = TargetCoreClockrateHz,
    .ahb_clock_target_hz    = (TargetCoreClockrateHz / 1),
    .apb1_clock_target_hz   = (TargetCoreClockrateHz / (1)),
    .apb2_clock_target_hz   = (TargetCoreClockrateHz / (1)),
}
Definition at line 33 of file main.c.
gpio_config
GPIOInitConfig_t gpio_config[]
Initial value:
= {
    GPIO_INIT_OUTPUT( (GPIOB) , (0) , GPIO_OUTPUT_LOW_SPEED),
    GPIO_INIT_OUTPUT( (GPIOB) , (2) , GPIO_OUTPUT_LOW_SPEED),
    GPIO_INIT_FDCAN2RX_PB12,
    GPIO_INIT_FDCAN2TX_PB13
}
Definition at line 22 of file main.c.
PLLClockRateHz
uint32_t PLLClockRateHz extern
Definition at line 18 of file rcc.c.
raw_adc_values
volatile raw_adc_values_t raw_adc_values
Definition at line 63 of file main.c.
TargetCoreClockrateHz
uint32_t TargetCoreClockrateHz = 16000000 static constexpr
Definition at line 32 of file main.c.