PER Firmware: source/f4_testing/canpiler.c File Reference
canpiler.c File Reference
#include "f4_testing.h"
#include "common/can_library/generated/PDU.h"
#include "common/phal/adc.h"
#include "common/phal/can.h"
#include "common/phal/dma.h"
#include "common/phal/gpio.h"
#include "common/phal/rcc.h"
#include "common/freertos/freertos.h"
Macros
#define TargetCoreClockrateHz 16'000'000
Functions
void HardFault_Handler ()
void can_worker ()
void send_periodic ()
DEFINE_TASK (send_periodic, 10, osPriorityNormal, 1024)
DEFINE_TASK (can_worker, 0, osPriorityLow, 1024)
int main ()
void CAN1_RX0_IRQHandler ()
void cooling_driver_request_CALLBACK (can_data_t *can_data)
Callback function for cooling_driver_request message sent from dashboard, updates values in cooling_request struct based off signal values.
Variables
GPIOInitConfig_t gpio_config []
ClockRateConfig_t clock_config
uint32_t APB1ClockRateHz
uint32_t APB2ClockRateHz
uint32_t AHBClockRateHz
uint32_t PLLClockRateHz
Macro Definition Documentation
TargetCoreClockrateHz
#define TargetCoreClockrateHz 16'000'000
Definition at line 18 of file canpiler.c.
Function Documentation
CAN1_RX0_IRQHandler()
void CAN1_RX0_IRQHandler ()
Definition at line 76 of file canpiler.c.
References CAN_handle_irq().
can_worker()
void can_worker ()
Definition at line 36 of file canpiler.c.
References CAN_rx_update(), and CAN_tx_update().
Referenced by main().
cooling_driver_request_CALLBACK()
void cooling_driver_request_CALLBACK (can_data_t * p_can_data)
Callback function for cooling_driver_request message sent from dashboard, updates values in cooling_request struct based off signal values.
Parameters
*msg_data_a CAN msg data
Returns
Definition at line 81 of file canpiler.c.
References can_data.
DEFINE_TASK() [1/2]
DEFINE_TASK (can_worker , 0 , osPriorityLow , 1024)
DEFINE_TASK() [2/2]
DEFINE_TASK (send_periodic , 10 , osPriorityNormal , 1024)
HardFault_Handler()
void HardFault_Handler (void)
Definition at line 85 of file canpiler.c.
Referenced by main().
main()
int main (void)
Definition at line 48 of file canpiler.c.
References CAN_library_init(), can_worker(), clock_config, gpio_config, HardFault_Handler(), PHAL_configureClockRates(), PHAL_initCAN(), PHAL_initGPIO(), send_periodic(), and START_TASK.
send_periodic()
void send_periodic ()
Definition at line 41 of file canpiler.c.
Referenced by main().
Variable Documentation
AHBClockRateHz
uint32_t AHBClockRateHz extern
Definition at line 17 of file rcc.c.
APB1ClockRateHz
uint32_t APB1ClockRateHz extern
Definition at line 15 of file rcc.c.
APB2ClockRateHz
uint32_t APB2ClockRateHz extern
Definition at line 16 of file rcc.c.
clock_config
ClockRateConfig_t clock_config
Initial value:
= {
    .clock_source              = CLOCK_SOURCE_HSI,
    .use_pll                   = false,
    .vco_output_rate_target_hz = 160'000'000,
    .system_clock_target_hz    = 16'000'000 ,
    .ahb_clock_target_hz       = ( 16'000'000 / 1),
    .apb1_clock_target_hz      = ( 16'000'000 / (1)),
    .apb2_clock_target_hz      = ( 16'000'000 / (1)),
}
Definition at line 19 of file canpiler.c.
Referenced by main().
gpio_config
GPIOInitConfig_t gpio_config[]
Initial value:
= {
    GPIO_INIT_CANRX_PD0,
    GPIO_INIT_CANTX_PD1
}
Definition at line 12 of file canpiler.c.
Referenced by main().
PLLClockRateHz
uint32_t PLLClockRateHz extern
Definition at line 18 of file rcc.c.