PER Firmware: source/pdu/fan_control/fan_control.c File Reference
fan_control.c File Reference
#include "fan_control.h"
#include "common/phal_F4_F7/pwm/pwm.h"
Functions
bool fanControlInit ()
void setFan1Speed (uint8_t fan_speed)
void setFan2Speed (uint8_t fan_speed)
Function Documentation
fanControlInit()
bool fanControlInit ()
Definition at line 4 of file fan_control.c.
References FAN_PWM_TIM, PHAL_initPWM(), and PWM_FREQUENCY_HZ.
Referenced by preflightChecks().
setFan1Speed()
void setFan1Speed (uint8_t fan_speed)
Definition at line 8 of file fan_control.c.
References FAN_PWM_TIM, and PHAL_PWMsetPercent().
Referenced by update_cooling_periodic().
setFan2Speed()
void setFan2Speed (uint8_t fan_speed)
Definition at line 12 of file fan_control.c.
References FAN_PWM_TIM, and PHAL_PWMsetPercent().
Referenced by update_cooling_periodic().