PER Firmware: source/dashboard/lcd/pages/faults.c File Reference
faults.c File Reference
Faults page implementation.
#include "faults.h"
#include "menu_system.h"
Functions
void fault_view_refresh ()
void fault_view_moveUp ()
void fault_view_moveDown ()
void fault_view_select ()
void fault_telemetry_update ()
Variables
menu_element_t fault_view_elements []
menu_page_t fault_view_page
Detailed Description
Faults page implementation.
Author
Irving Wang (irvin.nosp@m.gw@p.nosp@m.urdue.nosp@m..edu)
Definition in file faults.c.
Function Documentation
fault_telemetry_update()
void fault_telemetry_update (void)
Definition at line 81 of file faults.c.
fault_view_moveDown()
void fault_view_moveDown ()
Definition at line 73 of file faults.c.
References fault_view_page, and MS_moveDown().
fault_view_moveUp()
void fault_view_moveUp ()
Definition at line 69 of file faults.c.
References fault_view_page, and MS_moveUp().
fault_view_refresh()
void fault_view_refresh ()
Definition at line 65 of file faults.c.
References fault_view_page, and MS_refreshPage().
fault_view_select()
void fault_view_select ()
Definition at line 77 of file faults.c.
References fault_view_page, and MS_select().
Variable Documentation
fault_view_elements
menu_element_t fault_view_elements[]
Definition at line 15 of file faults.c.
fault_view_page
menu_page_t fault_view_page
Initial value:
= {
    .elements            = fault_view_elements,
    .num_elements        = sizeof(fault_view_elements) / sizeof(fault_view_elements[0]),
    .current_index       = 0,
    .is_element_selected = false
}
Definition at line 58 of file faults.c.
Referenced by fault_view_moveDown(), fault_view_moveUp(), fault_view_refresh(), and fault_view_select().