PER Firmware: source/dashboard/lcd/pages/faults.h File Reference
faults.h File Reference
Faults page implementation.
Macros
#define FAULT_STRING "fault"
#define FAULT1_BUTTON "ERROR1"
#define FAULT2_BUTTON "ERROR2"
#define FAULT3_BUTTON "ERROR3"
#define FAULT4_BUTTON "ERROR4"
#define FAULT5_BUTTON "ERROR5"
#define FAULT6_BUTTON "ERROR6"
#define FAULT7_BUTTON "ERROR7"
#define FAULT8_BUTTON "ERROR8"
#define FAULT1_TXT "ERROR1"
#define FAULT2_TXT "ERROR2"
#define FAULT3_TXT "ERROR3"
#define FAULT4_TXT "ERROR4"
#define FAULT5_TXT "ERROR5"
#define FAULT6_TXT "ERROR6"
#define FAULT7_TXT "ERROR7"
#define FAULT8_TXT "ERROR8"
#define FAULT_NONE_STRING "NONE\0"
Functions
void faults_update (void)
void faults_move_up (void)
void faults_move_down (void)
void faults_select (void)
void faults_telemetry_update (void)
Detailed Description
Faults page implementation.
Author
Irving Wang (irvin.nosp@m.gw@p.nosp@m.urdue.nosp@m..edu)
Definition in file faults.h.
Macro Definition Documentation
FAULT1_BUTTON
#define FAULT1_BUTTON "ERROR1"
Definition at line 14 of file faults.h.
FAULT1_TXT
#define FAULT1_TXT "ERROR1"
Definition at line 22 of file faults.h.
FAULT2_BUTTON
#define FAULT2_BUTTON "ERROR2"
Definition at line 15 of file faults.h.
FAULT2_TXT
#define FAULT2_TXT "ERROR2"
Definition at line 23 of file faults.h.
FAULT3_BUTTON
#define FAULT3_BUTTON "ERROR3"
Definition at line 16 of file faults.h.
FAULT3_TXT
#define FAULT3_TXT "ERROR3"
Definition at line 24 of file faults.h.
FAULT4_BUTTON
#define FAULT4_BUTTON "ERROR4"
Definition at line 17 of file faults.h.
FAULT4_TXT
#define FAULT4_TXT "ERROR4"
Definition at line 25 of file faults.h.
FAULT5_BUTTON
#define FAULT5_BUTTON "ERROR5"
Definition at line 18 of file faults.h.
FAULT5_TXT
#define FAULT5_TXT "ERROR5"
Definition at line 26 of file faults.h.
FAULT6_BUTTON
#define FAULT6_BUTTON "ERROR6"
Definition at line 19 of file faults.h.
FAULT6_TXT
#define FAULT6_TXT "ERROR6"
Definition at line 27 of file faults.h.
FAULT7_BUTTON
#define FAULT7_BUTTON "ERROR7"
Definition at line 20 of file faults.h.
FAULT7_TXT
#define FAULT7_TXT "ERROR7"
Definition at line 28 of file faults.h.
FAULT8_BUTTON
#define FAULT8_BUTTON "ERROR8"
Definition at line 21 of file faults.h.
FAULT8_TXT
#define FAULT8_TXT "ERROR8"
Definition at line 29 of file faults.h.
FAULT_NONE_STRING
#define FAULT_NONE_STRING "NONE\0"
Definition at line 30 of file faults.h.
FAULT_STRING
#define FAULT_STRING "fault"
Definition at line 11 of file faults.h.
Function Documentation
faults_move_down()
void faults_move_down (void)
Definition at line 73 of file faults.c.
References faults_page, and MS_moveDown().
faults_move_up()
void faults_move_up (void)
Definition at line 69 of file faults.c.
References faults_page, and MS_moveUp().
faults_select()
void faults_select (void)
Definition at line 77 of file faults.c.
References faults_page, and MS_select().
faults_telemetry_update()
void faults_telemetry_update (void)
Definition at line 81 of file faults.c.
faults_update()
void faults_update (void)
Definition at line 65 of file faults.c.
References faults_page, and MS_refreshPage().