PER Firmware: common/can_library/faults_common.h File Reference
faults_common.h File Reference
Event-based FIDR system.
#include <stdint.h>
#include "common/can_library/generated/can_types.h"
Data Structures
struct fault_t
Enumerations
enum fault_priority_t : uint8_t { FAULT_PRIO_WARNING , FAULT_PRIO_ERROR , FAULT_PRIO_FATAL , NUM_FAULT_PRIOS }
enum fault_state_t : uint8_t { FAULT_STATE_OK = 0 , FAULT_STATE_PENDING = 1 , FAULT_STATE_LATCHED = 2 , FAULT_STATE_RECOVERING = 3 }
Functions
void update_fault (fault_id_t idx, uint16_t value)
bool is_latched (fault_id_t idx)
void fault_library_periodic ()
bool is_warning_latched ()
bool is_error_latched ()
bool is_fatal_latched ()
bool is_curr_mcu_latched ()
bool is_other_mcus_latched ()
bool is_any_latched ()
Detailed Description
Event-based FIDR system.
Author
Irving Wang (irvin.nosp@m.gw@p.nosp@m.urdue.nosp@m..edu)
Definition in file faults_common.h.
Enumeration Type Documentation
fault_priority_t
enum fault_priority_t : uint8_t
Enumerator
FAULT_PRIO_WARNING
FAULT_PRIO_ERROR
FAULT_PRIO_FATAL
NUM_FAULT_PRIOS
Definition at line 14 of file faults_common.h.
fault_state_t
enum fault_state_t : uint8_t
Enumerator
FAULT_STATE_OK
FAULT_STATE_PENDING
FAULT_STATE_LATCHED
FAULT_STATE_RECOVERING
Definition at line 21 of file faults_common.h.
Function Documentation
fault_library_periodic()
void fault_library_periodic ()
Referenced by main(), main(), and preflight_task().
is_any_latched()
bool is_any_latched ()
is_curr_mcu_latched()
bool is_curr_mcu_latched ()
is_error_latched()
bool is_error_latched ()
is_fatal_latched()
bool is_fatal_latched ()
Referenced by fsm_periodic().
is_latched()
bool is_latched (fault_id_t idx)
Referenced by clearFault(), fsm_periodic(), heartbeat_led(), is_precharge_complete(), is_TSMS_closed(), pedalsPeriodic(), sdcTelemetryUpdate(), and set_faultIndicator().
is_other_mcus_latched()
bool is_other_mcus_latched ()
is_warning_latched()
bool is_warning_latched ()
update_fault()
void update_fault (fault_id_t idx, uint16_t value)
Referenced by checkSwitchFaults(), fsm_periodic(), pedalsPeriodic(), send_iv_readings(), and update_SDC().