PER Firmware: common/phal_G4/fdcan/fdcan.h File Reference
fdcan.h File Reference
#include "common/phal_G4/phal_G4.h"
Data Structures
struct CanMsgTypeDef_t
Macros
#define MAX_NUM_XID_FILTER (8)
#define MAX_NUM_SID_FILTER (28)
#define AF_NUM_FDCAN2 (9)
#define AF_NUM_FDCAN13 (11)
#define GPIO_INIT_FDCAN1RX_PA11
#define GPIO_INIT_FDCAN1TX_PA12
#define GPIO_INIT_FDCAN1RX_PB8
#define GPIO_INIT_FDCAN1TX_PB9
#define GPIO_INIT_FDCAN2RX_PB12
#define GPIO_INIT_FDCAN2TX_PB13
#define GPIO_INIT_FDCAN2RX_PB5
#define GPIO_INIT_FDCAN2TX_PB6
#define GPIO_INIT_FDCAN3RX_PA8
#define GPIO_INIT_FDCAN3TX_PB4
#define GPIO_INIT_FDCAN3TX_PA15
#define GPIO_INIT_FDCAN3TX_PB3
Functions
bool PHAL_FDCAN_init (FDCAN_GlobalTypeDef *fdcan, bool test_mode, uint32_t bit_rate)
void PHAL_FDCAN_setFilters (FDCAN_GlobalTypeDef *fdcan, uint32_t *sid_list, uint32_t num_sid, uint32_t *xid_list, uint32_t num_xid)
void PHAL_FDCAN_send (CanMsgTypeDef_t *msg)
bool PHAL_FDCAN_txFifoFree (FDCAN_GlobalTypeDef *fdcan)
void PHAL_FDCAN_rxCallback (CanMsgTypeDef_t *msg)
Macro Definition Documentation
AF_NUM_FDCAN13
#define AF_NUM_FDCAN13 (11)
Definition at line 30 of file fdcan.h.
AF_NUM_FDCAN2
#define AF_NUM_FDCAN2 (9)
Definition at line 29 of file fdcan.h.
GPIO_INIT_FDCAN1RX_PA11
#define GPIO_INIT_FDCAN1RX_PA11
Value:
    GPIO_INIT_AF(GPIOA, \
                 11, \
                 AF_NUM_FDCAN13, \
                 GPIO_OUTPUT_ULTRA_SPEED, \
                 GPIO_OUTPUT_OPEN_DRAIN, \
                 GPIO_INPUT_OPEN_DRAIN)
Definition at line 33 of file fdcan.h.
GPIO_INIT_FDCAN1RX_PB8
#define GPIO_INIT_FDCAN1RX_PB8
Value:
    GPIO_INIT_AF(GPIOB, \
                 8, \
                 AF_NUM_FDCAN13, \
                 GPIO_OUTPUT_ULTRA_SPEED, \
                 GPIO_OUTPUT_OPEN_DRAIN, \
                 GPIO_INPUT_OPEN_DRAIN)
Definition at line 47 of file fdcan.h.
GPIO_INIT_FDCAN1TX_PA12
#define GPIO_INIT_FDCAN1TX_PA12
Value:
    GPIO_INIT_AF(GPIOA, \
                 12, \
                 AF_NUM_FDCAN13, \
                 GPIO_OUTPUT_ULTRA_SPEED, \
                 GPIO_OUTPUT_PUSH_PULL, \
                 GPIO_INPUT_OPEN_DRAIN)
Definition at line 40 of file fdcan.h.
GPIO_INIT_FDCAN1TX_PB9
#define GPIO_INIT_FDCAN1TX_PB9
Value:
    GPIO_INIT_AF(GPIOB, \
                 9, \
                 AF_NUM_FDCAN13, \
                 GPIO_OUTPUT_ULTRA_SPEED, \
                 GPIO_OUTPUT_PUSH_PULL, \
                 GPIO_INPUT_OPEN_DRAIN)
Definition at line 54 of file fdcan.h.
GPIO_INIT_FDCAN2RX_PB12
#define GPIO_INIT_FDCAN2RX_PB12
Value:
    GPIO_INIT_AF(GPIOB, \
                 12, \
                 AF_NUM_FDCAN2, \
                 GPIO_OUTPUT_ULTRA_SPEED, \
                 GPIO_OUTPUT_OPEN_DRAIN, \
                 GPIO_INPUT_OPEN_DRAIN)
Definition at line 63 of file fdcan.h.
GPIO_INIT_FDCAN2RX_PB5
#define GPIO_INIT_FDCAN2RX_PB5
Value:
    GPIO_INIT_AF(GPIOB, \
                 5, \
                 AF_NUM_FDCAN2, \
                 GPIO_OUTPUT_ULTRA_SPEED, \
                 GPIO_OUTPUT_OPEN_DRAIN, \
                 GPIO_INPUT_OPEN_DRAIN)
Definition at line 77 of file fdcan.h.
GPIO_INIT_FDCAN2TX_PB13
#define GPIO_INIT_FDCAN2TX_PB13
Value:
    GPIO_INIT_AF(GPIOB, \
                 13, \
                 AF_NUM_FDCAN2, \
                 GPIO_OUTPUT_ULTRA_SPEED, \
                 GPIO_OUTPUT_PUSH_PULL, \
                 GPIO_INPUT_OPEN_DRAIN)
Definition at line 70 of file fdcan.h.
GPIO_INIT_FDCAN2TX_PB6
#define GPIO_INIT_FDCAN2TX_PB6
Value:
    GPIO_INIT_AF(GPIOB, \
                 6, \
                 AF_NUM_FDCAN2, \
                 GPIO_OUTPUT_ULTRA_SPEED, \
                 GPIO_OUTPUT_PUSH_PULL, \
                 GPIO_INPUT_OPEN_DRAIN)
Definition at line 84 of file fdcan.h.
GPIO_INIT_FDCAN3RX_PA8
#define GPIO_INIT_FDCAN3RX_PA8
Value:
    GPIO_INIT_AF(GPIOA, \
                 8, \
                 AF_NUM_FDCAN13, \
                 GPIO_OUTPUT_ULTRA_SPEED, \
                 GPIO_OUTPUT_OPEN_DRAIN, \
                 GPIO_INPUT_OPEN_DRAIN)
Definition at line 93 of file fdcan.h.
GPIO_INIT_FDCAN3TX_PA15
#define GPIO_INIT_FDCAN3TX_PA15
Value:
    GPIO_INIT_AF(GPIOA, \
                 15, \
                 AF_NUM_FDCAN13, \
                 GPIO_OUTPUT_ULTRA_SPEED, \
                 GPIO_OUTPUT_OPEN_DRAIN, \
                 GPIO_INPUT_OPEN_DRAIN)
Definition at line 107 of file fdcan.h.
GPIO_INIT_FDCAN3TX_PB3
#define GPIO_INIT_FDCAN3TX_PB3
Value:
    GPIO_INIT_AF(GPIOB, \
                 3, \
                 AF_NUM_FDCAN13, \
                 GPIO_OUTPUT_ULTRA_SPEED, \
                 GPIO_OUTPUT_PUSH_PULL, \
                 GPIO_INPUT_OPEN_DRAIN)
Definition at line 114 of file fdcan.h.
GPIO_INIT_FDCAN3TX_PB4
#define GPIO_INIT_FDCAN3TX_PB4
Value:
    GPIO_INIT_AF(GPIOB, \
                 4, \
                 AF_NUM_FDCAN13, \
                 GPIO_OUTPUT_ULTRA_SPEED, \
                 GPIO_OUTPUT_PUSH_PULL, \
                 GPIO_INPUT_OPEN_DRAIN)
Definition at line 100 of file fdcan.h.
MAX_NUM_SID_FILTER
#define MAX_NUM_SID_FILTER (28)
Definition at line 27 of file fdcan.h.
Referenced by PHAL_FDCAN_setStandardFilter().
MAX_NUM_XID_FILTER
#define MAX_NUM_XID_FILTER (8)
Definition at line 26 of file fdcan.h.
Referenced by PHAL_FDCAN_setExtendedFilter().
Function Documentation
PHAL_FDCAN_init()
bool PHAL_FDCAN_init (FDCAN_GlobalTypeDef * fdcan, bool test_mode, uint32_t bit_rate)
< Accept in Rx FIFO 0
< Accept in Rx FIFO 0
< Accept in Rx FIFO 0
< Accept in Rx FIFO 0
Definition at line 146 of file fdcan.c.
References FDCAN_ACCEPT_IN_RX_FIFO0, PHAL_FDCAN_makeNBTP(), and RCC_FDCANCLKSOURCE_PCLK1.
Referenced by main(), and main().
PHAL_FDCAN_rxCallback()
void PHAL_FDCAN_rxCallback (CanMsgTypeDef_t * msg) extern
Definition at line 125 of file fdcan.c.
Referenced by PHAL_FDCAN_RX_IRQHandler().
PHAL_FDCAN_send()
void PHAL_FDCAN_send (CanMsgTypeDef_t * msg)
Definition at line 219 of file fdcan.c.
References PHAL_FDCAN_get_ram_base(), SRAMCAN_TFQ_SIZE, and SRAMCAN_TFQSA.
Referenced by PHAL_FDCAN_testExtended().
PHAL_FDCAN_setFilters()
void PHAL_FDCAN_setFilters (FDCAN_GlobalTypeDef * fdcan, uint32_t * sid_list, uint32_t num_sid, uint32_t * xid_list, uint32_t num_xid)
< Reject
< Reject
< Accept in Rx FIFO 0
< Accept in Rx FIFO 0
Definition at line 126 of file fdcan.c.
References FDCAN_ACCEPT_IN_RX_FIFO0, FDCAN_REJECT, PHAL_FDCAN_setExtendedFilter(), and PHAL_FDCAN_setStandardFilter().
Referenced by main().
PHAL_FDCAN_txFifoFree()
bool PHAL_FDCAN_txFifoFree (FDCAN_GlobalTypeDef * fdcan)
Definition at line 214 of file fdcan.c.