PER Firmware: source/daq/fatfs/ff.c File Reference
ff.c File Reference
#include "ff.h"
#include <string.h>
#include "diskio.h"
Macros
#define MAX_DIR 0x200000 /* Max size of FAT directory */
#define MAX_DIR_EX 0x10000000 /* Max size of exFAT directory */
#define MAX_FAT12 0xFF5 /* Max FAT12 clusters (differs from specs, but right for real DOS/Windows behavior) */
#define MAX_FAT16 0xFFF5 /* Max FAT16 clusters (differs from specs, but right for real DOS/Windows behavior) */
#define MAX_FAT32 0x0FFFFFF5 /* Max FAT32 clusters (not specified, practical limit) */
#define MAX_EXFAT 0x7FFFFFFD /* Max exFAT clusters (differs from specs, implementation limit) */
#define IsUpper(c)
#define IsLower(c)
#define IsDigit(c)
#define IsSeparator(c)
#define IsTerminator(c)
#define IsSurrogate(c)
#define IsSurrogateH(c)
#define IsSurrogateL(c)
#define FA_SEEKEND 0x20 /* Seek to end of the file on file open */
#define FA_MODIFIED 0x40 /* File has been modified */
#define FA_DIRTY 0x80 /* FIL.buf[] needs to be written-back */
#define AM_VOL 0x08 /* Volume label */
#define AM_LFN 0x0F /* LFN entry */
#define AM_MASK 0x3F /* Mask of defined bits in FAT */
#define AM_MASKX 0x37 /* Mask of defined bits in exFAT */
#define NSFLAG 11 /* Index of the name status byte */
#define NS_LOSS 0x01 /* Out of 8.3 format */
#define NS_LFN 0x02 /* Force to create LFN entry */
#define NS_LAST 0x04 /* Last segment */
#define NS_BODY 0x08 /* Lower case flag (body) */
#define NS_EXT 0x10 /* Lower case flag (ext) */
#define NS_DOT 0x20 /* Dot entry */
#define NS_NOLFN 0x40 /* Do not find LFN */
#define NS_NONAME 0x80 /* Not followed */
#define ET_BITMAP 0x81 /* Allocation bitmap */
#define ET_UPCASE 0x82 /* Up-case table */
#define ET_VLABEL 0x83 /* Volume label */
#define ET_FILEDIR 0x85 /* File and directory */
#define ET_STREAM 0xC0 /* Stream extension */
#define ET_FILENAME 0xC1 /* Name extension */
#define BS_JmpBoot 0 /* x86 jump instruction (3-byte) */
#define BS_OEMName 3 /* OEM name (8-byte) */
#define BPB_BytsPerSec 11 /* Sector size [byte] (WORD) */
#define BPB_SecPerClus 13 /* Cluster size [sector] (BYTE) */
#define BPB_RsvdSecCnt 14 /* Size of reserved area [sector] (WORD) */
#define BPB_NumFATs 16 /* Number of FATs (BYTE) */
#define BPB_RootEntCnt 17 /* Size of root directory area for FAT [entry] (WORD) */
#define BPB_TotSec16 19 /* Volume size (16-bit) [sector] (WORD) */
#define BPB_Media 21 /* Media descriptor byte (BYTE) */
#define BPB_FATSz16 22 /* FAT size (16-bit) [sector] (WORD) */
#define BPB_SecPerTrk 24 /* Number of sectors per track for int13h [sector] (WORD) */
#define BPB_NumHeads 26 /* Number of heads for int13h (WORD) */
#define BPB_HiddSec 28 /* Volume offset from top of the drive (DWORD) */
#define BPB_TotSec32 32 /* Volume size (32-bit) [sector] (DWORD) */
#define BS_DrvNum 36 /* Physical drive number for int13h (BYTE) */
#define BS_NTres 37 /* WindowsNT error flag (BYTE) */
#define BS_BootSig 38 /* Extended boot signature (BYTE) */
#define BS_VolID 39 /* Volume serial number (DWORD) */
#define BS_VolLab 43 /* Volume label string (8-byte) */
#define BS_FilSysType 54 /* Filesystem type string (8-byte) */
#define BS_BootCode 62 /* Boot code (448-byte) */
#define BS_55AA 510 /* Signature word (WORD) */
#define BPB_FATSz32 36 /* FAT32: FAT size [sector] (DWORD) */
#define BPB_ExtFlags32 40 /* FAT32: Extended flags (WORD) */
#define BPB_FSVer32 42 /* FAT32: Filesystem version (WORD) */
#define BPB_RootClus32 44 /* FAT32: Root directory cluster (DWORD) */
#define BPB_FSInfo32 48 /* FAT32: Offset of FSINFO sector (WORD) */
#define BPB_BkBootSec32 50 /* FAT32: Offset of backup boot sector (WORD) */
#define BS_DrvNum32 64 /* FAT32: Physical drive number for int13h (BYTE) */
#define BS_NTres32 65 /* FAT32: Error flag (BYTE) */
#define BS_BootSig32 66 /* FAT32: Extended boot signature (BYTE) */
#define BS_VolID32 67 /* FAT32: Volume serial number (DWORD) */
#define BS_VolLab32 71 /* FAT32: Volume label string (8-byte) */
#define BS_FilSysType32 82 /* FAT32: Filesystem type string (8-byte) */
#define BS_BootCode32 90 /* FAT32: Boot code (420-byte) */
#define BPB_ZeroedEx 11 /* exFAT: MBZ field (53-byte) */
#define BPB_VolOfsEx 64 /* exFAT: Volume offset from top of the drive [sector] (QWORD) */
#define BPB_TotSecEx 72 /* exFAT: Volume size [sector] (QWORD) */
#define BPB_FatOfsEx 80 /* exFAT: FAT offset from top of the volume [sector] (DWORD) */
#define BPB_FatSzEx 84 /* exFAT: FAT size [sector] (DWORD) */
#define BPB_DataOfsEx 88 /* exFAT: Data offset from top of the volume [sector] (DWORD) */
#define BPB_NumClusEx 92 /* exFAT: Number of clusters (DWORD) */
#define BPB_RootClusEx 96 /* exFAT: Root directory start cluster (DWORD) */
#define BPB_VolIDEx 100 /* exFAT: Volume serial number (DWORD) */
#define BPB_FSVerEx 104 /* exFAT: Filesystem version (WORD) */
#define BPB_VolFlagEx 106 /* exFAT: Volume flags (WORD) */
#define BPB_BytsPerSecEx 108 /* exFAT: Log2 of sector size in unit of byte (BYTE) */
#define BPB_SecPerClusEx 109 /* exFAT: Log2 of cluster size in unit of sector (BYTE) */
#define BPB_NumFATsEx 110 /* exFAT: Number of FATs (BYTE) */
#define BPB_DrvNumEx 111 /* exFAT: Physical drive number for int13h (BYTE) */
#define BPB_PercInUseEx 112 /* exFAT: Percent in use (BYTE) */
#define BPB_RsvdEx 113 /* exFAT: Reserved (7-byte) */
#define BS_BootCodeEx 120 /* exFAT: Boot code (390-byte) */
#define DIR_Name 0 /* Short file name (11-byte) */
#define DIR_Attr 11 /* Attribute (BYTE) */
#define DIR_NTres 12 /* Lower case flag (BYTE) */
#define DIR_CrtTime10 13 /* Created time sub-second (BYTE) */
#define DIR_CrtTime 14 /* Created time (DWORD) */
#define DIR_LstAccDate 18 /* Last accessed date (WORD) */
#define DIR_FstClusHI 20 /* Higher 16-bit of first cluster (WORD) */
#define DIR_ModTime 22 /* Modified time (DWORD) */
#define DIR_FstClusLO 26 /* Lower 16-bit of first cluster (WORD) */
#define DIR_FileSize 28 /* File size (DWORD) */
#define LDIR_Ord 0 /* LFN: LFN order and LLE flag (BYTE) */
#define LDIR_Attr 11 /* LFN: LFN attribute (BYTE) */
#define LDIR_Type 12 /* LFN: Entry type (BYTE) */
#define LDIR_Chksum 13 /* LFN: Checksum of the SFN (BYTE) */
#define LDIR_FstClusLO 26 /* LFN: MBZ field (WORD) */
#define XDIR_Type 0 /* exFAT: Type of exFAT directory entry (BYTE) */
#define XDIR_NumLabel 1 /* exFAT: Number of volume label characters (BYTE) */
#define XDIR_Label 2 /* exFAT: Volume label (11-WORD) */
#define XDIR_CaseSum 4 /* exFAT: Sum of case conversion table (DWORD) */
#define XDIR_NumSec 1 /* exFAT: Number of secondary entries (BYTE) */
#define XDIR_SetSum 2 /* exFAT: Sum of the set of directory entries (WORD) */
#define XDIR_Attr 4 /* exFAT: File attribute (WORD) */
#define XDIR_CrtTime 8 /* exFAT: Created time (DWORD) */
#define XDIR_ModTime 12 /* exFAT: Modified time (DWORD) */
#define XDIR_AccTime 16 /* exFAT: Last accessed time (DWORD) */
#define XDIR_CrtTime10 20 /* exFAT: Created time subsecond (BYTE) */
#define XDIR_ModTime10 21 /* exFAT: Modified time subsecond (BYTE) */
#define XDIR_CrtTZ 22 /* exFAT: Created timezone (BYTE) */
#define XDIR_ModTZ 23 /* exFAT: Modified timezone (BYTE) */
#define XDIR_AccTZ 24 /* exFAT: Last accessed timezone (BYTE) */
#define XDIR_GenFlags 33 /* exFAT: General secondary flags (BYTE) */
#define XDIR_NumName 35 /* exFAT: Number of file name characters (BYTE) */
#define XDIR_NameHash 36 /* exFAT: Hash of file name (WORD) */
#define XDIR_ValidFileSize 40 /* exFAT: Valid file size (QWORD) */
#define XDIR_FstClus 52 /* exFAT: First cluster of the file data (DWORD) */
#define XDIR_FileSize 56 /* exFAT: File/Directory size (QWORD) */
#define SZDIRE 32 /* Size of a directory entry */
#define DDEM 0xE5 /* Deleted directory entry mark set to DIR_Name[0] */
#define RDDEM 0x05 /* Replacement of the character collides with DDEM */
#define LLEF 0x40 /* Last long entry flag in LDIR_Ord */
#define FSI_LeadSig 0 /* FAT32 FSI: Leading signature (DWORD) */
#define FSI_StrucSig 484 /* FAT32 FSI: Structure signature (DWORD) */
#define FSI_Free_Count 488 /* FAT32 FSI: Number of free clusters (DWORD) */
#define FSI_Nxt_Free 492 /* FAT32 FSI: Last allocated cluster (DWORD) */
#define MBR_Table 446 /* MBR: Offset of partition table in the MBR */
#define SZ_PTE 16 /* MBR: Size of a partition table entry */
#define PTE_Boot 0 /* MBR PTE: Boot indicator */
#define PTE_StHead 1 /* MBR PTE: Start head */
#define PTE_StSec 2 /* MBR PTE: Start sector */
#define PTE_StCyl 3 /* MBR PTE: Start cylinder */
#define PTE_System 4 /* MBR PTE: System ID */
#define PTE_EdHead 5 /* MBR PTE: End head */
#define PTE_EdSec 6 /* MBR PTE: End sector */
#define PTE_EdCyl 7 /* MBR PTE: End cylinder */
#define PTE_StLba 8 /* MBR PTE: Start in LBA */
#define PTE_SizLba 12 /* MBR PTE: Size in LBA */
#define GPTH_Sign 0 /* GPT HDR: Signature (8-byte) */
#define GPTH_Rev 8 /* GPT HDR: Revision (DWORD) */
#define GPTH_Size 12 /* GPT HDR: Header size (DWORD) */
#define GPTH_Bcc 16 /* GPT HDR: Header BCC (DWORD) */
#define GPTH_CurLba 24 /* GPT HDR: This header LBA (QWORD) */
#define GPTH_BakLba 32 /* GPT HDR: Another header LBA (QWORD) */
#define GPTH_FstLba 40 /* GPT HDR: First LBA for partition data (QWORD) */
#define GPTH_LstLba 48 /* GPT HDR: Last LBA for partition data (QWORD) */
#define GPTH_DskGuid 56 /* GPT HDR: Disk GUID (16-byte) */
#define GPTH_PtOfs 72 /* GPT HDR: Partition table LBA (QWORD) */
#define GPTH_PtNum 80 /* GPT HDR: Number of table entries (DWORD) */
#define GPTH_PteSize 84 /* GPT HDR: Size of table entry (DWORD) */
#define GPTH_PtBcc 88 /* GPT HDR: Partition table BCC (DWORD) */
#define SZ_GPTE 128 /* GPT PTE: Size of partition table entry */
#define GPTE_PtGuid 0 /* GPT PTE: Partition type GUID (16-byte) */
#define GPTE_UpGuid 16 /* GPT PTE: Partition unique GUID (16-byte) */
#define GPTE_FstLba 32 /* GPT PTE: First LBA of partition (QWORD) */
#define GPTE_LstLba 40 /* GPT PTE: Last LBA of partition (QWORD) */
#define GPTE_Flags 48 /* GPT PTE: Partition flags (QWORD) */
#define GPTE_Name 56 /* GPT PTE: Partition name */
#define ABORT(fs, res)
#define LEAVE_FF(fs, res)
#define LD2PD(vol)
#define LD2PT(vol)
#define SS(fs)
#define GET_FATTIME()
#define TBL_CT437 {0x80, 0x9A, 0x45, 0x41, 0x8E, 0x41, 0x8F, 0x80, 0x45, 0x45, 0x45, 0x49, 0x49, 0x49, 0x8E, 0x8F, 0x90, 0x92, 0x92, 0x4F, 0x99, 0x4F, 0x55, 0x55, 0x59, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0x41, 0x49, 0x4F, 0x55, 0xA5, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF, 0xE0, 0xE1, 0xE2, 0xE3, 0xE4, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9, 0xEA, 0xEB, 0xEC, 0xED, 0xEE, 0xEF, 0xF0, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFB, 0xFC, 0xFD, 0xFE, 0xFF}
#define TBL_CT720 {0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0xA0, 0xA1, 0xA2, 0xA3, 0xA4, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF, 0xE0, 0xE1, 0xE2, 0xE3, 0xE4, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9, 0xEA, 0xEB, 0xEC, 0xED, 0xEE, 0xEF, 0xF0, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFB, 0xFC, 0xFD, 0xFE, 0xFF}
#define TBL_CT737 {0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F, 0x90, 0x92, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F, 0x90, 0x91, 0xAA, 0x92, 0x93, 0x94, 0x95, 0x96, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF, 0x97, 0xEA, 0xEB, 0xEC, 0xE4, 0xED, 0xEE, 0xEF, 0xF5, 0xF0, 0xEA, 0xEB, 0xEC, 0xED, 0xEE, 0xEF, 0xF0, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFB, 0xFC, 0xFD, 0xFE, 0xFF}
#define TBL_CT771 {0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xDB, 0xDC, 0xDC, 0xDE, 0xDE, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0xF0, 0xF0, 0xF2, 0xF2, 0xF4, 0xF4, 0xF6, 0xF6, 0xF8, 0xF8, 0xFA, 0xFA, 0xFC, 0xFC, 0xFE, 0xFF}
#define TBL_CT775 {0x80, 0x9A, 0x91, 0xA0, 0x8E, 0x95, 0x8F, 0x80, 0xAD, 0xED, 0x8A, 0x8A, 0xA1, 0x8D, 0x8E, 0x8F, 0x90, 0x92, 0x92, 0xE2, 0x99, 0x95, 0x96, 0x97, 0x97, 0x99, 0x9A, 0x9D, 0x9C, 0x9D, 0x9E, 0x9F, 0xA0, 0xA1, 0xE0, 0xA3, 0xA3, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xB5, 0xB6, 0xB7, 0xB8, 0xBD, 0xBE, 0xC6, 0xC7, 0xA5, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF, 0xE0, 0xE1, 0xE2, 0xE3, 0xE5, 0xE5, 0xE6, 0xE3, 0xE8, 0xE8, 0xEA, 0xEA, 0xEE, 0xED, 0xEE, 0xEF, 0xF0, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFB, 0xFC, 0xFD, 0xFE, 0xFF}
#define TBL_CT850 {0x43, 0x55, 0x45, 0x41, 0x41, 0x41, 0x41, 0x43, 0x45, 0x45, 0x45, 0x49, 0x49, 0x49, 0x41, 0x41, 0x45, 0x92, 0x92, 0x4F, 0x4F, 0x4F, 0x55, 0x55, 0x59, 0x4F, 0x55, 0x4F, 0x9C, 0x4F, 0x9E, 0x9F, 0x41, 0x49, 0x4F, 0x55, 0xA5, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0x41, 0x41, 0x41, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0x41, 0x41, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD1, 0xD1, 0x45, 0x45, 0x45, 0x49, 0x49, 0x49, 0x49, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0x49, 0xDF, 0x4F, 0xE1, 0x4F, 0x4F, 0x4F, 0x4F, 0xE6, 0xE8, 0xE8, 0x55, 0x55, 0x55, 0x59, 0x59, 0xEE, 0xEF, 0xF0, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFB, 0xFC, 0xFD, 0xFE, 0xFF}
#define TBL_CT852 {0x80, 0x9A, 0x90, 0xB6, 0x8E, 0xDE, 0x8F, 0x80, 0x9D, 0xD3, 0x8A, 0x8A, 0xD7, 0x8D, 0x8E, 0x8F, 0x90, 0x91, 0x91, 0xE2, 0x99, 0x95, 0x95, 0x97, 0x97, 0x99, 0x9A, 0x9B, 0x9B, 0x9D, 0x9E, 0xAC, 0xB5, 0xD6, 0xE0, 0xE9, 0xA4, 0xA4, 0xA6, 0xA6, 0xA8, 0xA8, 0xAA, 0x8D, 0xAC, 0xB8, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBD, 0xBF, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC6, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD1, 0xD1, 0xD2, 0xD3, 0xD2, 0xD5, 0xD6, 0xD7, 0xB7, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF, 0xE0, 0xE1, 0xE2, 0xE3, 0xE3, 0xD5, 0xE6, 0xE6, 0xE8, 0xE9, 0xE8, 0xEB, 0xED, 0xED, 0xDD, 0xEF, 0xF0, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xEB, 0xFC, 0xFC, 0xFE, 0xFF}
#define TBL_CT855 {0x81, 0x81, 0x83, 0x83, 0x85, 0x85, 0x87, 0x87, 0x89, 0x89, 0x8B, 0x8B, 0x8D, 0x8D, 0x8F, 0x8F, 0x91, 0x91, 0x93, 0x93, 0x95, 0x95, 0x97, 0x97, 0x99, 0x99, 0x9B, 0x9B, 0x9D, 0x9D, 0x9F, 0x9F, 0xA1, 0xA1, 0xA3, 0xA3, 0xA5, 0xA5, 0xA7, 0xA7, 0xA9, 0xA9, 0xAB, 0xAB, 0xAD, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB6, 0xB6, 0xB8, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBE, 0xBE, 0xBF, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC7, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD1, 0xD1, 0xD3, 0xD3, 0xD5, 0xD5, 0xD7, 0xD7, 0xDD, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xE0, 0xDF, 0xE0, 0xE2, 0xE2, 0xE4, 0xE4, 0xE6, 0xE6, 0xE8, 0xE8, 0xEA, 0xEA, 0xEC, 0xEC, 0xEE, 0xEE, 0xEF, 0xF0, 0xF2, 0xF2, 0xF4, 0xF4, 0xF6, 0xF6, 0xF8, 0xF8, 0xFA, 0xFA, 0xFC, 0xFC, 0xFD, 0xFE, 0xFF}
#define TBL_CT857 {0x80, 0x9A, 0x90, 0xB6, 0x8E, 0xB7, 0x8F, 0x80, 0xD2, 0xD3, 0xD4, 0xD8, 0xD7, 0x49, 0x8E, 0x8F, 0x90, 0x92, 0x92, 0xE2, 0x99, 0xE3, 0xEA, 0xEB, 0x98, 0x99, 0x9A, 0x9D, 0x9C, 0x9D, 0x9E, 0x9E, 0xB5, 0xD6, 0xE0, 0xE9, 0xA5, 0xA5, 0xA6, 0xA6, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC7, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0x49, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF, 0xE0, 0xE1, 0xE2, 0xE3, 0xE5, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9, 0xEA, 0xEB, 0xDE, 0xED, 0xEE, 0xEF, 0xF0, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFB, 0xFC, 0xFD, 0xFE, 0xFF}
#define TBL_CT860 {0x80, 0x9A, 0x90, 0x8F, 0x8E, 0x91, 0x86, 0x80, 0x89, 0x89, 0x92, 0x8B, 0x8C, 0x98, 0x8E, 0x8F, 0x90, 0x91, 0x92, 0x8C, 0x99, 0xA9, 0x96, 0x9D, 0x98, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0x86, 0x8B, 0x9F, 0x96, 0xA5, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF, 0xE0, 0xE1, 0xE2, 0xE3, 0xE4, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9, 0xEA, 0xEB, 0xEC, 0xED, 0xEE, 0xEF, 0xF0, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFB, 0xFC, 0xFD, 0xFE, 0xFF}
#define TBL_CT861 {0x80, 0x9A, 0x90, 0x41, 0x8E, 0x41, 0x8F, 0x80, 0x45, 0x45, 0x45, 0x8B, 0x8B, 0x8D, 0x8E, 0x8F, 0x90, 0x92, 0x92, 0x4F, 0x99, 0x8D, 0x55, 0x97, 0x97, 0x99, 0x9A, 0x9D, 0x9C, 0x9D, 0x9E, 0x9F, 0xA4, 0xA5, 0xA6, 0xA7, 0xA4, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF, 0xE0, 0xE1, 0xE2, 0xE3, 0xE4, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9, 0xEA, 0xEB, 0xEC, 0xED, 0xEE, 0xEF, 0xF0, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFB, 0xFC, 0xFD, 0xFE, 0xFF}
#define TBL_CT862 {0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0x41, 0x49, 0x4F, 0x55, 0xA5, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF, 0xE0, 0xE1, 0xE2, 0xE3, 0xE4, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9, 0xEA, 0xEB, 0xEC, 0xED, 0xEE, 0xEF, 0xF0, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFB, 0xFC, 0xFD, 0xFE, 0xFF}
#define TBL_CT863 {0x43, 0x55, 0x45, 0x41, 0x41, 0x41, 0x86, 0x43, 0x45, 0x45, 0x45, 0x49, 0x49, 0x8D, 0x41, 0x8F, 0x45, 0x45, 0x45, 0x4F, 0x45, 0x49, 0x55, 0x55, 0x98, 0x4F, 0x55, 0x9B, 0x9C, 0x55, 0x55, 0x9F, 0xA0, 0xA1, 0x4F, 0x55, 0xA4, 0xA5, 0xA6, 0xA7, 0x49, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF, 0xE0, 0xE1, 0xE2, 0xE3, 0xE4, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9, 0xEA, 0xEB, 0xEC, 0xED, 0xEE, 0xEF, 0xF0, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFB, 0xFC, 0xFD, 0xFE, 0xFF}
#define TBL_CT864 {0x80, 0x9A, 0x45, 0x41, 0x8E, 0x41, 0x8F, 0x80, 0x45, 0x45, 0x45, 0x49, 0x49, 0x49, 0x8E, 0x8F, 0x90, 0x92, 0x92, 0x4F, 0x99, 0x4F, 0x55, 0x55, 0x59, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0x41, 0x49, 0x4F, 0x55, 0xA5, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF, 0xE0, 0xE1, 0xE2, 0xE3, 0xE4, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9, 0xEA, 0xEB, 0xEC, 0xED, 0xEE, 0xEF, 0xF0, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFB, 0xFC, 0xFD, 0xFE, 0xFF}
#define TBL_CT865 {0x80, 0x9A, 0x90, 0x41, 0x8E, 0x41, 0x8F, 0x80, 0x45, 0x45, 0x45, 0x49, 0x49, 0x49, 0x8E, 0x8F, 0x90, 0x92, 0x92, 0x4F, 0x99, 0x4F, 0x55, 0x55, 0x59, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0x41, 0x49, 0x4F, 0x55, 0xA5, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF, 0xE0, 0xE1, 0xE2, 0xE3, 0xE4, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9, 0xEA, 0xEB, 0xEC, 0xED, 0xEE, 0xEF, 0xF0, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFB, 0xFC, 0xFD, 0xFE, 0xFF}
#define TBL_CT866 {0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0xF0, 0xF0, 0xF2, 0xF2, 0xF4, 0xF4, 0xF6, 0xF6, 0xF8, 0xF9, 0xFA, 0xFB, 0xFC, 0xFD, 0xFE, 0xFF}
#define TBL_CT869 {0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0x86, 0x9C, 0x8D, 0x8F, 0x90, 0x91, 0x90, 0x92, 0x95, 0xA4, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xA4, 0xA5, 0xA6, 0xD9, 0xDA, 0xDB, 0xDC, 0xA7, 0xA8, 0xDF, 0xA9, 0xAA, 0xAC, 0xAD, 0xB5, 0xB6, 0xB7, 0xB8, 0xBD, 0xBE, 0xC6, 0xC7, 0xCF, 0xCF, 0xD0, 0xEF, 0xF0, 0xF1, 0xD1, 0xD2, 0xD3, 0xF5, 0xD4, 0xF7, 0xF8, 0xF9, 0xD5, 0x96, 0x95, 0x98, 0xFE, 0xFF}
#define TBL_DC932 {0x81, 0x9F, 0xE0, 0xFC, 0x40, 0x7E, 0x80, 0xFC, 0x00, 0x00}
#define TBL_DC936 {0x81, 0xFE, 0x00, 0x00, 0x40, 0x7E, 0x80, 0xFE, 0x00, 0x00}
#define TBL_DC949 {0x81, 0xFE, 0x00, 0x00, 0x41, 0x5A, 0x61, 0x7A, 0x81, 0xFE}
#define TBL_DC950 {0x81, 0xFE, 0x00, 0x00, 0x40, 0x7E, 0xA1, 0xFE, 0x00, 0x00}
#define MERGE_2STR(a, b)
#define MKCVTBL(hd, cp)
#define MAXDIRB(nc)
#define DEF_NAMBUF WCHAR lbuf[FF_MAX_LFN + 1]; /* LFN working buffer */
#define INIT_NAMBUF(fs)
#define FREE_NAMBUF()
#define LEAVE_MKFS(res)
#define CODEPAGE FF_CODE_PAGE
#define DIR_READ_FILE(dp)
#define DIR_READ_LABEL(dp)
Functions
static WORD ld_word (const BYTE *ptr)
static DWORD ld_dword (const BYTE *ptr)
static void st_word (BYTE *ptr, WORD val)
static void st_dword (BYTE *ptr, DWORD val)
static int dbc_1st (BYTE c)
static int dbc_2nd (BYTE c)
static DWORD tchar2uni (const TCHAR **str)
static UINT put_utf (DWORD chr, TCHAR *buf, UINT szb)
static int lock_volume (FATFS *fs, int syslock)
static void unlock_volume (FATFS *fs, FRESULT res)
static FRESULT sync_window (FATFS *fs)
static FRESULT move_window (FATFS *fs, LBA_t sect)
static FRESULT sync_fs (FATFS *fs)
static LBA_t clst2sect (FATFS *fs, DWORD clst)
static DWORD get_fat (FFOBJID *obj, DWORD clst)
static FRESULT put_fat (FATFS *fs, DWORD clst, DWORD val)
static FRESULT remove_chain (FFOBJID *obj, DWORD clst, DWORD pclst)
static DWORD create_chain (FFOBJID *obj, DWORD clst)
static FRESULT dir_clear (FATFS *fs, DWORD clst)
static FRESULT dir_sdi (DIR *dp, DWORD ofs)
static FRESULT dir_next (DIR *dp, int stretch)
static FRESULT dir_alloc (DIR *dp, UINT n_ent)
static DWORD ld_clust (FATFS *fs, const BYTE *dir)
static void st_clust (FATFS *fs, BYTE *dir, DWORD cl)
static int cmp_lfn (const WCHAR *lfnbuf, BYTE *dir)
static int pick_lfn (WCHAR *lfnbuf, BYTE *dir)
static void put_lfn (const WCHAR *lfn, BYTE *dir, BYTE ord, BYTE sum)
static void gen_numname (BYTE *dst, const BYTE *src, const WCHAR *lfn, UINT seq)
static BYTE sum_sfn (const BYTE *dir)
static FRESULT dir_read (DIR *dp, int vol)
static FRESULT dir_find (DIR *dp)
static FRESULT dir_register (DIR *dp)
static FRESULT dir_remove (DIR *dp)
static void get_fileinfo (DIR *dp, FILINFO *fno)
static FRESULT create_name (DIR *dp, const TCHAR **path)
static FRESULT follow_path (DIR *dp, const TCHAR *path)
static int get_ldnumber (const TCHAR **path)
static UINT check_fs (FATFS *fs, LBA_t sect)
static UINT find_volume (FATFS *fs, UINT part)
static FRESULT mount_volume (const TCHAR **path, FATFS **rfs, BYTE mode)
static FRESULT validate (FFOBJID *obj, FATFS **rfs)
FRESULT f_mount (FATFS *fs, const TCHAR *path, BYTE opt)
FRESULT f_open (FIL *fp, const TCHAR *path, BYTE mode)
FRESULT f_read (FIL *fp, void *buff, UINT btr, UINT *br)
FRESULT f_write (FIL *fp, const void *buff, UINT btw, UINT *bw)
FRESULT f_sync (FIL *fp)
FRESULT f_close (FIL *fp)
FRESULT f_lseek (FIL *fp, FSIZE_t ofs)
FRESULT f_opendir (DIR *dp, const TCHAR *path)
FRESULT f_closedir (DIR *dp)
FRESULT f_readdir (DIR *dp, FILINFO *fno)
FRESULT f_stat (const TCHAR *path, FILINFO *fno)
FRESULT f_getfree (const TCHAR *path, DWORD *nclst, FATFS **fatfs)
FRESULT f_truncate (FIL *fp)
FRESULT f_unlink (const TCHAR *path)
FRESULT f_mkdir (const TCHAR *path)
FRESULT f_rename (const TCHAR *path_old, const TCHAR *path_new)
Variables
static FATFS * FatFs [1]
static WORD Fsid
static const char *const VolumeStr [1] = { "SD" }
static const BYTE LfnOfs [] = {1, 3, 5, 7, 9, 14, 16, 18, 20, 22, 24, 28, 30}
static const BYTE ExCvt [] = {0x80, 0x9A, 0x45, 0x41, 0x8E, 0x41, 0x8F, 0x80, 0x45, 0x45, 0x45, 0x49, 0x49, 0x49, 0x8E, 0x8F, 0x90, 0x92, 0x92, 0x4F, 0x99, 0x4F, 0x55, 0x55, 0x59, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0x41, 0x49, 0x4F, 0x55, 0xA5, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF, 0xE0, 0xE1, 0xE2, 0xE3, 0xE4, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9, 0xEA, 0xEB, 0xEC, 0xED, 0xEE, 0xEF, 0xF0, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFB, 0xFC, 0xFD, 0xFE, 0xFF}
Macro Definition Documentation
ABORT
#define ABORT (fs, res)
Value:
    { \
        fp->err = (BYTE)(res); \
        LEAVE_FF(fs, res); \
    }
Definition at line 226 of file ff.c.
Referenced by f_lseek(), f_read(), f_truncate(), and f_write().
AM_LFN
#define AM_LFN 0x0F /* LFN entry */
Definition at line 62 of file ff.c.
Referenced by dir_find(), dir_read(), and put_lfn().
AM_MASK
#define AM_MASK 0x3F /* Mask of defined bits in FAT */
Definition at line 63 of file ff.c.
Referenced by dir_find(), dir_read(), and get_fileinfo().
AM_MASKX
#define AM_MASKX 0x37 /* Mask of defined bits in exFAT */
Definition at line 64 of file ff.c.
Referenced by get_fileinfo().
AM_VOL
#define AM_VOL 0x08 /* Volume label */
Definition at line 61 of file ff.c.
Referenced by dir_find(), and dir_read().
BPB_BkBootSec32
#define BPB_BkBootSec32 50 /* FAT32: Offset of backup boot sector (WORD) */
Definition at line 116 of file ff.c.
BPB_BytsPerSec
#define BPB_BytsPerSec 11 /* Sector size [byte] (WORD) */
Definition at line 90 of file ff.c.
Referenced by check_fs(), and mount_volume().
BPB_BytsPerSecEx
#define BPB_BytsPerSecEx 108 /* exFAT: Log2 of sector size in unit of byte (BYTE) */
Definition at line 136 of file ff.c.
Referenced by mount_volume().
BPB_DataOfsEx
#define BPB_DataOfsEx 88 /* exFAT: Data offset from top of the volume [sector] (DWORD) */
Definition at line 130 of file ff.c.
Referenced by mount_volume().
BPB_DrvNumEx
#define BPB_DrvNumEx 111 /* exFAT: Physical drive number for int13h (BYTE) */
Definition at line 139 of file ff.c.
BPB_ExtFlags32
#define BPB_ExtFlags32 40 /* FAT32: Extended flags (WORD) */
Definition at line 112 of file ff.c.
BPB_FatOfsEx
#define BPB_FatOfsEx 80 /* exFAT: FAT offset from top of the volume [sector] (DWORD) */
Definition at line 128 of file ff.c.
Referenced by mount_volume().
BPB_FATSz16
#define BPB_FATSz16 22 /* FAT size (16-bit) [sector] (WORD) */
Definition at line 97 of file ff.c.
Referenced by check_fs(), and mount_volume().
BPB_FATSz32
#define BPB_FATSz32 36 /* FAT32: FAT size [sector] (DWORD) */
Definition at line 111 of file ff.c.
Referenced by mount_volume().
BPB_FatSzEx
#define BPB_FatSzEx 84 /* exFAT: FAT size [sector] (DWORD) */
Definition at line 129 of file ff.c.
Referenced by mount_volume().
BPB_FSInfo32
#define BPB_FSInfo32 48 /* FAT32: Offset of FSINFO sector (WORD) */
Definition at line 115 of file ff.c.
Referenced by mount_volume().
BPB_FSVer32
#define BPB_FSVer32 42 /* FAT32: Filesystem version (WORD) */
Definition at line 113 of file ff.c.
Referenced by mount_volume().
BPB_FSVerEx
#define BPB_FSVerEx 104 /* exFAT: Filesystem version (WORD) */
Definition at line 134 of file ff.c.
Referenced by mount_volume().
BPB_HiddSec
#define BPB_HiddSec 28 /* Volume offset from top of the drive (DWORD) */
Definition at line 100 of file ff.c.
BPB_Media
#define BPB_Media 21 /* Media descriptor byte (BYTE) */
Definition at line 96 of file ff.c.
BPB_NumClusEx
#define BPB_NumClusEx 92 /* exFAT: Number of clusters (DWORD) */
Definition at line 131 of file ff.c.
Referenced by mount_volume().
BPB_NumFATs
#define BPB_NumFATs 16 /* Number of FATs (BYTE) */
Definition at line 93 of file ff.c.
Referenced by check_fs(), and mount_volume().
BPB_NumFATsEx
#define BPB_NumFATsEx 110 /* exFAT: Number of FATs (BYTE) */
Definition at line 138 of file ff.c.
Referenced by mount_volume().
BPB_NumHeads
#define BPB_NumHeads 26 /* Number of heads for int13h (WORD) */
Definition at line 99 of file ff.c.
BPB_PercInUseEx
#define BPB_PercInUseEx 112 /* exFAT: Percent in use (BYTE) */
Definition at line 140 of file ff.c.
BPB_RootClus32
#define BPB_RootClus32 44 /* FAT32: Root directory cluster (DWORD) */
Definition at line 114 of file ff.c.
Referenced by mount_volume().
BPB_RootClusEx
#define BPB_RootClusEx 96 /* exFAT: Root directory start cluster (DWORD) */
Definition at line 132 of file ff.c.
Referenced by mount_volume().
BPB_RootEntCnt
#define BPB_RootEntCnt 17 /* Size of root directory area for FAT [entry] (WORD) */
Definition at line 94 of file ff.c.
Referenced by check_fs(), and mount_volume().
BPB_RsvdEx
#define BPB_RsvdEx 113 /* exFAT: Reserved (7-byte) */
Definition at line 141 of file ff.c.
BPB_RsvdSecCnt
#define BPB_RsvdSecCnt 14 /* Size of reserved area [sector] (WORD) */
Definition at line 92 of file ff.c.
Referenced by check_fs(), and mount_volume().
BPB_SecPerClus
#define BPB_SecPerClus 13 /* Cluster size [sector] (BYTE) */
Definition at line 91 of file ff.c.
Referenced by check_fs(), and mount_volume().
BPB_SecPerClusEx
#define BPB_SecPerClusEx 109 /* exFAT: Log2 of cluster size in unit of sector (BYTE) */
Definition at line 137 of file ff.c.
Referenced by mount_volume().
BPB_SecPerTrk
#define BPB_SecPerTrk 24 /* Number of sectors per track for int13h [sector] (WORD) */
Definition at line 98 of file ff.c.
BPB_TotSec16
#define BPB_TotSec16 19 /* Volume size (16-bit) [sector] (WORD) */
Definition at line 95 of file ff.c.
Referenced by check_fs(), and mount_volume().
BPB_TotSec32
#define BPB_TotSec32 32 /* Volume size (32-bit) [sector] (DWORD) */
Definition at line 101 of file ff.c.
Referenced by check_fs(), and mount_volume().
BPB_TotSecEx
#define BPB_TotSecEx 72 /* exFAT: Volume size [sector] (QWORD) */
Definition at line 127 of file ff.c.
Referenced by mount_volume().
BPB_VolFlagEx
#define BPB_VolFlagEx 106 /* exFAT: Volume flags (WORD) */
Definition at line 135 of file ff.c.
BPB_VolIDEx
#define BPB_VolIDEx 100 /* exFAT: Volume serial number (DWORD) */
Definition at line 133 of file ff.c.
BPB_VolOfsEx
#define BPB_VolOfsEx 64 /* exFAT: Volume offset from top of the drive [sector] (QWORD) */
Definition at line 126 of file ff.c.
BPB_ZeroedEx
#define BPB_ZeroedEx 11 /* exFAT: MBZ field (53-byte) */
Definition at line 125 of file ff.c.
Referenced by mount_volume().
BS_55AA
#define BS_55AA 510 /* Signature word (WORD) */
Definition at line 109 of file ff.c.
Referenced by check_fs(), mount_volume(), and sync_fs().
BS_BootCode
#define BS_BootCode 62 /* Boot code (448-byte) */
Definition at line 108 of file ff.c.
BS_BootCode32
#define BS_BootCode32 90 /* FAT32: Boot code (420-byte) */
Definition at line 123 of file ff.c.
BS_BootCodeEx
#define BS_BootCodeEx 120 /* exFAT: Boot code (390-byte) */
Definition at line 142 of file ff.c.
BS_BootSig
#define BS_BootSig 38 /* Extended boot signature (BYTE) */
Definition at line 104 of file ff.c.
BS_BootSig32
#define BS_BootSig32 66 /* FAT32: Extended boot signature (BYTE) */
Definition at line 119 of file ff.c.
BS_DrvNum
#define BS_DrvNum 36 /* Physical drive number for int13h (BYTE) */
Definition at line 102 of file ff.c.
BS_DrvNum32
#define BS_DrvNum32 64 /* FAT32: Physical drive number for int13h (BYTE) */
Definition at line 117 of file ff.c.
BS_FilSysType
#define BS_FilSysType 54 /* Filesystem type string (8-byte) */
Definition at line 107 of file ff.c.
BS_FilSysType32
#define BS_FilSysType32 82 /* FAT32: Filesystem type string (8-byte) */
Definition at line 122 of file ff.c.
Referenced by check_fs().
BS_JmpBoot
#define BS_JmpBoot 0 /* x86 jump instruction (3-byte) */
Definition at line 88 of file ff.c.
Referenced by check_fs().
BS_NTres
#define BS_NTres 37 /* WindowsNT error flag (BYTE) */
Definition at line 103 of file ff.c.
BS_NTres32
#define BS_NTres32 65 /* FAT32: Error flag (BYTE) */
Definition at line 118 of file ff.c.
BS_OEMName
#define BS_OEMName 3 /* OEM name (8-byte) */
Definition at line 89 of file ff.c.
BS_VolID
#define BS_VolID 39 /* Volume serial number (DWORD) */
Definition at line 105 of file ff.c.
BS_VolID32
#define BS_VolID32 67 /* FAT32: Volume serial number (DWORD) */
Definition at line 120 of file ff.c.
BS_VolLab
#define BS_VolLab 43 /* Volume label string (8-byte) */
Definition at line 106 of file ff.c.
BS_VolLab32
#define BS_VolLab32 71 /* FAT32: Volume label string (8-byte) */
Definition at line 121 of file ff.c.
CODEPAGE
#define CODEPAGE FF_CODE_PAGE
Definition at line 507 of file ff.c.
Referenced by create_name(), get_fileinfo(), put_utf(), and tchar2uni().
DDEM
#define DDEM 0xE5 /* Deleted directory entry mark set to DIR_Name[0] */
Definition at line 182 of file ff.c.
Referenced by create_name(), dir_alloc(), dir_find(), dir_read(), dir_remove(), and get_fileinfo().
DEF_NAMBUF
#define DEF_NAMBUF WCHAR lbuf[FF_MAX_LFN + 1]; /* LFN working buffer */
Definition at line 430 of file ff.c.
Referenced by f_mkdir(), f_open(), f_opendir(), f_readdir(), f_rename(), f_stat(), f_sync(), and f_unlink().
DIR_Attr
#define DIR_Attr 11 /* Attribute (BYTE) */
Definition at line 145 of file ff.c.
Referenced by dir_find(), dir_read(), f_mkdir(), f_open(), f_rename(), f_sync(), and get_fileinfo().
DIR_CrtTime
#define DIR_CrtTime 14 /* Created time (DWORD) */
Definition at line 148 of file ff.c.
Referenced by f_open().
DIR_CrtTime10
#define DIR_CrtTime10 13 /* Created time sub-second (BYTE) */
Definition at line 147 of file ff.c.
DIR_FileSize
#define DIR_FileSize 28 /* File size (DWORD) */
Definition at line 153 of file ff.c.
Referenced by f_open(), f_sync(), and get_fileinfo().
DIR_FstClusHI
#define DIR_FstClusHI 20 /* Higher 16-bit of first cluster (WORD) */
Definition at line 150 of file ff.c.
Referenced by ld_clust(), and st_clust().
DIR_FstClusLO
#define DIR_FstClusLO 26 /* Lower 16-bit of first cluster (WORD) */
Definition at line 152 of file ff.c.
Referenced by ld_clust(), and st_clust().
DIR_LstAccDate
#define DIR_LstAccDate 18 /* Last accessed date (WORD) */
Definition at line 149 of file ff.c.
Referenced by f_sync().
DIR_ModTime
#define DIR_ModTime 22 /* Modified time (DWORD) */
Definition at line 151 of file ff.c.
Referenced by f_mkdir(), f_open(), f_sync(), and get_fileinfo().
DIR_Name
#define DIR_Name 0 /* Short file name (11-byte) */
Definition at line 144 of file ff.c.
Referenced by dir_alloc(), dir_find(), dir_read(), dir_register(), dir_remove(), and f_mkdir().
DIR_NTres
#define DIR_NTres 12 /* Lower case flag (BYTE) */
Definition at line 146 of file ff.c.
Referenced by dir_register(), and get_fileinfo().
DIR_READ_FILE
#define DIR_READ_FILE (dp)
Value:
dir_read(dp, 0)
Definition at line 2232 of file ff.c.
Referenced by dir_find(), f_readdir(), and f_unlink().
DIR_READ_LABEL
#define DIR_READ_LABEL (dp)
Value:
dir_read(dp, 1)
Definition at line 2233 of file ff.c.
ET_BITMAP
#define ET_BITMAP 0x81 /* Allocation bitmap */
Definition at line 78 of file ff.c.
Referenced by mount_volume().
ET_FILEDIR
#define ET_FILEDIR 0x85 /* File and directory */
Definition at line 81 of file ff.c.
Referenced by dir_read().
ET_FILENAME
#define ET_FILENAME 0xC1 /* Name extension */
Definition at line 83 of file ff.c.
ET_STREAM
#define ET_STREAM 0xC0 /* Stream extension */
Definition at line 82 of file ff.c.
ET_UPCASE
#define ET_UPCASE 0x82 /* Up-case table */
Definition at line 79 of file ff.c.
ET_VLABEL
#define ET_VLABEL 0x83 /* Volume label */
Definition at line 80 of file ff.c.
Referenced by dir_read().
FA_DIRTY
#define FA_DIRTY 0x80 /* FIL.buf[] needs to be written-back */
Definition at line 58 of file ff.c.
Referenced by f_lseek(), f_read(), f_sync(), f_truncate(), and f_write().
FA_MODIFIED
#define FA_MODIFIED 0x40 /* File has been modified */
Definition at line 57 of file ff.c.
Referenced by f_lseek(), f_open(), f_sync(), f_truncate(), and f_write().
FA_SEEKEND
#define FA_SEEKEND 0x20 /* Seek to end of the file on file open */
Definition at line 56 of file ff.c.
Referenced by f_open().
FREE_NAMBUF
#define FREE_NAMBUF ()
Definition at line 433 of file ff.c.
Referenced by f_mkdir(), f_open(), f_opendir(), f_readdir(), f_rename(), f_stat(), f_sync(), and f_unlink().
FSI_Free_Count
#define FSI_Free_Count 488 /* FAT32 FSI: Number of free clusters (DWORD) */
Definition at line 188 of file ff.c.
Referenced by mount_volume(), and sync_fs().
FSI_LeadSig
#define FSI_LeadSig 0 /* FAT32 FSI: Leading signature (DWORD) */
Definition at line 186 of file ff.c.
Referenced by mount_volume(), and sync_fs().
FSI_Nxt_Free
#define FSI_Nxt_Free 492 /* FAT32 FSI: Last allocated cluster (DWORD) */
Definition at line 189 of file ff.c.
Referenced by mount_volume(), and sync_fs().
FSI_StrucSig
#define FSI_StrucSig 484 /* FAT32 FSI: Structure signature (DWORD) */
Definition at line 187 of file ff.c.
Referenced by mount_volume(), and sync_fs().
GET_FATTIME
#define GET_FATTIME ()
Value:
get_fattime()
Definition at line 272 of file ff.c.
Referenced by f_mkdir(), f_open(), and f_sync().
GPTE_Flags
#define GPTE_Flags 48 /* GPT PTE: Partition flags (QWORD) */
Definition at line 222 of file ff.c.
GPTE_FstLba
#define GPTE_FstLba 32 /* GPT PTE: First LBA of partition (QWORD) */
Definition at line 220 of file ff.c.
Referenced by find_volume().
GPTE_LstLba
#define GPTE_LstLba 40 /* GPT PTE: Last LBA of partition (QWORD) */
Definition at line 221 of file ff.c.
GPTE_Name
#define GPTE_Name 56 /* GPT PTE: Partition name */
Definition at line 223 of file ff.c.
GPTE_PtGuid
#define GPTE_PtGuid 0 /* GPT PTE: Partition type GUID (16-byte) */
Definition at line 218 of file ff.c.
Referenced by find_volume().
GPTE_UpGuid
#define GPTE_UpGuid 16 /* GPT PTE: Partition unique GUID (16-byte) */
Definition at line 219 of file ff.c.
GPTH_BakLba
#define GPTH_BakLba 32 /* GPT HDR: Another header LBA (QWORD) */
Definition at line 209 of file ff.c.
GPTH_Bcc
#define GPTH_Bcc 16 /* GPT HDR: Header BCC (DWORD) */
Definition at line 207 of file ff.c.
GPTH_CurLba
#define GPTH_CurLba 24 /* GPT HDR: This header LBA (QWORD) */
Definition at line 208 of file ff.c.
GPTH_DskGuid
#define GPTH_DskGuid 56 /* GPT HDR: Disk GUID (16-byte) */
Definition at line 212 of file ff.c.
GPTH_FstLba
#define GPTH_FstLba 40 /* GPT HDR: First LBA for partition data (QWORD) */
Definition at line 210 of file ff.c.
GPTH_LstLba
#define GPTH_LstLba 48 /* GPT HDR: Last LBA for partition data (QWORD) */
Definition at line 211 of file ff.c.
GPTH_PtBcc
#define GPTH_PtBcc 88 /* GPT HDR: Partition table BCC (DWORD) */
Definition at line 216 of file ff.c.
GPTH_PteSize
#define GPTH_PteSize 84 /* GPT HDR: Size of table entry (DWORD) */
Definition at line 215 of file ff.c.
GPTH_PtNum
#define GPTH_PtNum 80 /* GPT HDR: Number of table entries (DWORD) */
Definition at line 214 of file ff.c.
Referenced by find_volume().
GPTH_PtOfs
#define GPTH_PtOfs 72 /* GPT HDR: Partition table LBA (QWORD) */
Definition at line 213 of file ff.c.
Referenced by find_volume().
GPTH_Rev
#define GPTH_Rev 8 /* GPT HDR: Revision (DWORD) */
Definition at line 205 of file ff.c.
GPTH_Sign
#define GPTH_Sign 0 /* GPT HDR: Signature (8-byte) */
Definition at line 204 of file ff.c.
GPTH_Size
#define GPTH_Size 12 /* GPT HDR: Header size (DWORD) */
Definition at line 206 of file ff.c.
INIT_NAMBUF
#define INIT_NAMBUF (fs)
Value:
    { (fs)->lfnbuf = lbuf; }
Definition at line 431 of file ff.c.
Referenced by f_mkdir(), f_open(), f_opendir(), f_readdir(), f_rename(), f_stat(), f_sync(), and f_unlink().
IsDigit
#define IsDigit (c)
Value:
((c) >= '0' && (c) <= '9')
Definition at line 48 of file ff.c.
Referenced by get_ldnumber().
IsLower
#define IsLower (c)
Value:
((c) >= 'a' && (c) <= 'z')
Definition at line 47 of file ff.c.
Referenced by create_name(), and get_ldnumber().
IsSeparator
#define IsSeparator (c)
Value:
((c) == '/' || (c) == '\\')
Definition at line 49 of file ff.c.
Referenced by create_name(), and follow_path().
IsSurrogate
#define IsSurrogate (c)
Value:
((c) >= 0xD800 && (c) <= 0xDFFF)
Definition at line 51 of file ff.c.
Referenced by get_fileinfo(), put_utf(), and tchar2uni().
IsSurrogateH
#define IsSurrogateH (c)
Value:
((c) >= 0xD800 && (c) <= 0xDBFF)
Definition at line 52 of file ff.c.
Referenced by put_utf(), and tchar2uni().
IsSurrogateL
#define IsSurrogateL (c)
Value:
((c) >= 0xDC00 && (c) <= 0xDFFF)
Definition at line 53 of file ff.c.
Referenced by put_utf(), and tchar2uni().
IsTerminator
#define IsTerminator (c)
Value:
((UINT)(c) < (FF_USE_LFN ? ' ' : '!'))
Definition at line 50 of file ff.c.
Referenced by create_name(), follow_path(), and get_ldnumber().
IsUpper
#define IsUpper (c)
Value:
((c) >= 'A' && (c) <= 'Z')
Definition at line 46 of file ff.c.
Referenced by create_name(), and get_fileinfo().
LD2PD
#define LD2PD (vol)
Value:
(BYTE)(vol) /* Each logical drive is associated with the same physical drive number */
Definition at line 251 of file ff.c.
Referenced by f_mount().
LD2PT
#define LD2PT (vol)
Value:
0 /* Auto partition search */
Definition at line 252 of file ff.c.
Referenced by mount_volume().
LDIR_Attr
#define LDIR_Attr 11 /* LFN: LFN attribute (BYTE) */
Definition at line 155 of file ff.c.
Referenced by put_lfn().
LDIR_Chksum
#define LDIR_Chksum 13 /* LFN: Checksum of the SFN (BYTE) */
Definition at line 157 of file ff.c.
Referenced by dir_find(), dir_read(), and put_lfn().
LDIR_FstClusLO
#define LDIR_FstClusLO 26 /* LFN: MBZ field (WORD) */
Definition at line 158 of file ff.c.
Referenced by cmp_lfn(), pick_lfn(), and put_lfn().
LDIR_Ord
#define LDIR_Ord 0 /* LFN: LFN order and LLE flag (BYTE) */
Definition at line 154 of file ff.c.
Referenced by cmp_lfn(), pick_lfn(), and put_lfn().
LDIR_Type
#define LDIR_Type 12 /* LFN: Entry type (BYTE) */
Definition at line 156 of file ff.c.
Referenced by put_lfn().
LEAVE_FF
#define LEAVE_FF (fs, res)
Value:
    { \
        unlock_volume(fs, res); \
        return res; \
    }
Definition at line 237 of file ff.c.
Referenced by f_getfree(), f_lseek(), f_mkdir(), f_mount(), f_open(), f_opendir(), f_read(), f_readdir(), f_rename(), f_stat(), f_sync(), f_truncate(), f_unlink(), and f_write().
LEAVE_MKFS
#define LEAVE_MKFS (res)
Value:
return res
Definition at line 435 of file ff.c.
LLEF
#define LLEF 0x40 /* Last long entry flag in LDIR_Ord */
Definition at line 184 of file ff.c.
Referenced by cmp_lfn(), dir_find(), dir_read(), pick_lfn(), and put_lfn().
MAX_DIR
#define MAX_DIR 0x200000 /* Max size of FAT directory */
Definition at line 38 of file ff.c.
Referenced by dir_next(), and dir_sdi().
MAX_DIR_EX
#define MAX_DIR_EX 0x10000000 /* Max size of exFAT directory */
Definition at line 39 of file ff.c.
Referenced by dir_next(), and dir_sdi().
MAX_EXFAT
#define MAX_EXFAT 0x7FFFFFFD /* Max exFAT clusters (differs from specs, implementation limit) */
Definition at line 43 of file ff.c.
Referenced by mount_volume().
MAX_FAT12
#define MAX_FAT12 0xFF5 /* Max FAT12 clusters (differs from specs, but right for real DOS/Windows behavior) */
Definition at line 40 of file ff.c.
Referenced by mount_volume().
MAX_FAT16
#define MAX_FAT16 0xFFF5 /* Max FAT16 clusters (differs from specs, but right for real DOS/Windows behavior) */
Definition at line 41 of file ff.c.
Referenced by mount_volume().
MAX_FAT32
#define MAX_FAT32 0x0FFFFFF5 /* Max FAT32 clusters (not specified, practical limit) */
Definition at line 42 of file ff.c.
Referenced by mount_volume().
MAXDIRB
#define MAXDIRB (nc)
Value:
((nc + 44U) / 15 * SZDIRE) /* exFAT: Size of directory entry block scratchpad buffer needed for the name length */
Definition at line 406 of file ff.c.
Referenced by get_fileinfo().
MBR_Table
#define MBR_Table 446 /* MBR: Offset of partition table in the MBR */
Definition at line 191 of file ff.c.
Referenced by find_volume().
MERGE_2STR
#define MERGE_2STR (a, b)
Value:
a##b
Definition at line 336 of file ff.c.
MKCVTBL
#define MKCVTBL (hd, cp)
Value:
MERGE_2STR(hd, cp)
Definition at line 337 of file ff.c.
NS_BODY
#define NS_BODY 0x08 /* Lower case flag (body) */
Definition at line 71 of file ff.c.
Referenced by create_name(), dir_register(), and get_fileinfo().
NS_DOT
#define NS_DOT 0x20 /* Dot entry */
Definition at line 73 of file ff.c.
Referenced by create_name(), dir_register(), f_mkdir(), f_rename(), f_unlink(), and follow_path().
NS_EXT
#define NS_EXT 0x10 /* Lower case flag (ext) */
Definition at line 72 of file ff.c.
Referenced by create_name(), dir_register(), and get_fileinfo().
NS_LAST
#define NS_LAST 0x04 /* Last segment */
Definition at line 70 of file ff.c.
Referenced by create_name(), and follow_path().
NS_LFN
#define NS_LFN 0x02 /* Force to create LFN entry */
Definition at line 69 of file ff.c.
Referenced by create_name(), and dir_register().
NS_LOSS
#define NS_LOSS 0x01 /* Out of 8.3 format */
Definition at line 68 of file ff.c.
Referenced by create_name(), dir_find(), and dir_register().
NS_NOLFN
#define NS_NOLFN 0x40 /* Do not find LFN */
Definition at line 74 of file ff.c.
Referenced by dir_find(), and dir_register().
NS_NONAME
#define NS_NONAME 0x80 /* Not followed */
Definition at line 75 of file ff.c.
Referenced by dir_register(), f_open(), f_opendir(), f_rename(), f_stat(), f_unlink(), and follow_path().
NSFLAG
#define NSFLAG 11 /* Index of the name status byte */
Definition at line 67 of file ff.c.
Referenced by create_name(), dir_find(), dir_register(), f_mkdir(), f_open(), f_opendir(), f_rename(), f_stat(), f_unlink(), and follow_path().
PTE_Boot
#define PTE_Boot 0 /* MBR PTE: Boot indicator */
Definition at line 193 of file ff.c.
PTE_EdCyl
#define PTE_EdCyl 7 /* MBR PTE: End cylinder */
Definition at line 200 of file ff.c.
PTE_EdHead
#define PTE_EdHead 5 /* MBR PTE: End head */
Definition at line 198 of file ff.c.
PTE_EdSec
#define PTE_EdSec 6 /* MBR PTE: End sector */
Definition at line 199 of file ff.c.
PTE_SizLba
#define PTE_SizLba 12 /* MBR PTE: Size in LBA */
Definition at line 202 of file ff.c.
PTE_StCyl
#define PTE_StCyl 3 /* MBR PTE: Start cylinder */
Definition at line 196 of file ff.c.
PTE_StHead
#define PTE_StHead 1 /* MBR PTE: Start head */
Definition at line 194 of file ff.c.
PTE_StLba
#define PTE_StLba 8 /* MBR PTE: Start in LBA */
Definition at line 201 of file ff.c.
Referenced by find_volume().
PTE_StSec
#define PTE_StSec 2 /* MBR PTE: Start sector */
Definition at line 195 of file ff.c.
PTE_System
#define PTE_System 4 /* MBR PTE: System ID */
Definition at line 197 of file ff.c.
Referenced by find_volume().
RDDEM
#define RDDEM 0x05 /* Replacement of the character collides with DDEM */
Definition at line 183 of file ff.c.
Referenced by create_name(), and get_fileinfo().
SS
#define SS (fs)
Value:
((UINT)FF_MAX_SS) /* Fixed sector size */
Definition at line 260 of file ff.c.
Referenced by dir_clear(), dir_next(), dir_register(), dir_sdi(), f_getfree(), f_lseek(), f_mkdir(), f_open(), f_read(), f_write(), find_volume(), follow_path(), get_fat(), mount_volume(), and put_fat().
SZ_GPTE
#define SZ_GPTE 128 /* GPT PTE: Size of partition table entry */
Definition at line 217 of file ff.c.
Referenced by find_volume().
SZ_PTE
#define SZ_PTE 16 /* MBR: Size of a partition table entry */
Definition at line 192 of file ff.c.
Referenced by find_volume().
SZDIRE
#define SZDIRE 32 /* Size of a directory entry */
Definition at line 181 of file ff.c.
Referenced by dir_find(), dir_next(), dir_register(), dir_sdi(), f_mkdir(), f_rename(), get_fileinfo(), and mount_volume().
TBL_CT437
#define TBL_CT437 {0x80, 0x9A, 0x45, 0x41, 0x8E, 0x41, 0x8F, 0x80, 0x45, 0x45, 0x45, 0x49, 0x49, 0x49, 0x8E, 0x8F, 0x90, 0x92, 0x92, 0x4F, 0x99, 0x4F, 0x55, 0x55, 0x59, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0x41, 0x49, 0x4F, 0x55, 0xA5, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF, 0xE0, 0xE1, 0xE2, 0xE3, 0xE4, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9, 0xEA, 0xEB, 0xEC, 0xED, 0xEE, 0xEF, 0xF0, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFB, 0xFC, 0xFD, 0xFE, 0xFF}
Definition at line 289 of file ff.c.
TBL_CT720
#define TBL_CT720 {0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0xA0, 0xA1, 0xA2, 0xA3, 0xA4, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF, 0xE0, 0xE1, 0xE2, 0xE3, 0xE4, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9, 0xEA, 0xEB, 0xEC, 0xED, 0xEE, 0xEF, 0xF0, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFB, 0xFC, 0xFD, 0xFE, 0xFF}
Definition at line 291 of file ff.c.
TBL_CT737
#define TBL_CT737 {0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F, 0x90, 0x92, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F, 0x90, 0x91, 0xAA, 0x92, 0x93, 0x94, 0x95, 0x96, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF, 0x97, 0xEA, 0xEB, 0xEC, 0xE4, 0xED, 0xEE, 0xEF, 0xF5, 0xF0, 0xEA, 0xEB, 0xEC, 0xED, 0xEE, 0xEF, 0xF0, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFB, 0xFC, 0xFD, 0xFE, 0xFF}
Definition at line 293 of file ff.c.
TBL_CT771
#define TBL_CT771 {0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xDB, 0xDC, 0xDC, 0xDE, 0xDE, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0xF0, 0xF0, 0xF2, 0xF2, 0xF4, 0xF4, 0xF6, 0xF6, 0xF8, 0xF8, 0xFA, 0xFA, 0xFC, 0xFC, 0xFE, 0xFF}
Definition at line 295 of file ff.c.
TBL_CT775
#define TBL_CT775 {0x80, 0x9A, 0x91, 0xA0, 0x8E, 0x95, 0x8F, 0x80, 0xAD, 0xED, 0x8A, 0x8A, 0xA1, 0x8D, 0x8E, 0x8F, 0x90, 0x92, 0x92, 0xE2, 0x99, 0x95, 0x96, 0x97, 0x97, 0x99, 0x9A, 0x9D, 0x9C, 0x9D, 0x9E, 0x9F, 0xA0, 0xA1, 0xE0, 0xA3, 0xA3, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xB5, 0xB6, 0xB7, 0xB8, 0xBD, 0xBE, 0xC6, 0xC7, 0xA5, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF, 0xE0, 0xE1, 0xE2, 0xE3, 0xE5, 0xE5, 0xE6, 0xE3, 0xE8, 0xE8, 0xEA, 0xEA, 0xEE, 0xED, 0xEE, 0xEF, 0xF0, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFB, 0xFC, 0xFD, 0xFE, 0xFF}
Definition at line 297 of file ff.c.
TBL_CT850
#define TBL_CT850 {0x43, 0x55, 0x45, 0x41, 0x41, 0x41, 0x41, 0x43, 0x45, 0x45, 0x45, 0x49, 0x49, 0x49, 0x41, 0x41, 0x45, 0x92, 0x92, 0x4F, 0x4F, 0x4F, 0x55, 0x55, 0x59, 0x4F, 0x55, 0x4F, 0x9C, 0x4F, 0x9E, 0x9F, 0x41, 0x49, 0x4F, 0x55, 0xA5, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0x41, 0x41, 0x41, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0x41, 0x41, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD1, 0xD1, 0x45, 0x45, 0x45, 0x49, 0x49, 0x49, 0x49, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0x49, 0xDF, 0x4F, 0xE1, 0x4F, 0x4F, 0x4F, 0x4F, 0xE6, 0xE8, 0xE8, 0x55, 0x55, 0x55, 0x59, 0x59, 0xEE, 0xEF, 0xF0, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFB, 0xFC, 0xFD, 0xFE, 0xFF}
Definition at line 299 of file ff.c.
TBL_CT852
#define TBL_CT852 {0x80, 0x9A, 0x90, 0xB6, 0x8E, 0xDE, 0x8F, 0x80, 0x9D, 0xD3, 0x8A, 0x8A, 0xD7, 0x8D, 0x8E, 0x8F, 0x90, 0x91, 0x91, 0xE2, 0x99, 0x95, 0x95, 0x97, 0x97, 0x99, 0x9A, 0x9B, 0x9B, 0x9D, 0x9E, 0xAC, 0xB5, 0xD6, 0xE0, 0xE9, 0xA4, 0xA4, 0xA6, 0xA6, 0xA8, 0xA8, 0xAA, 0x8D, 0xAC, 0xB8, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBD, 0xBF, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC6, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD1, 0xD1, 0xD2, 0xD3, 0xD2, 0xD5, 0xD6, 0xD7, 0xB7, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF, 0xE0, 0xE1, 0xE2, 0xE3, 0xE3, 0xD5, 0xE6, 0xE6, 0xE8, 0xE9, 0xE8, 0xEB, 0xED, 0xED, 0xDD, 0xEF, 0xF0, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xEB, 0xFC, 0xFC, 0xFE, 0xFF}
Definition at line 301 of file ff.c.
TBL_CT855
#define TBL_CT855 {0x81, 0x81, 0x83, 0x83, 0x85, 0x85, 0x87, 0x87, 0x89, 0x89, 0x8B, 0x8B, 0x8D, 0x8D, 0x8F, 0x8F, 0x91, 0x91, 0x93, 0x93, 0x95, 0x95, 0x97, 0x97, 0x99, 0x99, 0x9B, 0x9B, 0x9D, 0x9D, 0x9F, 0x9F, 0xA1, 0xA1, 0xA3, 0xA3, 0xA5, 0xA5, 0xA7, 0xA7, 0xA9, 0xA9, 0xAB, 0xAB, 0xAD, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB6, 0xB6, 0xB8, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBE, 0xBE, 0xBF, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC7, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD1, 0xD1, 0xD3, 0xD3, 0xD5, 0xD5, 0xD7, 0xD7, 0xDD, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xE0, 0xDF, 0xE0, 0xE2, 0xE2, 0xE4, 0xE4, 0xE6, 0xE6, 0xE8, 0xE8, 0xEA, 0xEA, 0xEC, 0xEC, 0xEE, 0xEE, 0xEF, 0xF0, 0xF2, 0xF2, 0xF4, 0xF4, 0xF6, 0xF6, 0xF8, 0xF8, 0xFA, 0xFA, 0xFC, 0xFC, 0xFD, 0xFE, 0xFF}
Definition at line 303 of file ff.c.
TBL_CT857
#define TBL_CT857 {0x80, 0x9A, 0x90, 0xB6, 0x8E, 0xB7, 0x8F, 0x80, 0xD2, 0xD3, 0xD4, 0xD8, 0xD7, 0x49, 0x8E, 0x8F, 0x90, 0x92, 0x92, 0xE2, 0x99, 0xE3, 0xEA, 0xEB, 0x98, 0x99, 0x9A, 0x9D, 0x9C, 0x9D, 0x9E, 0x9E, 0xB5, 0xD6, 0xE0, 0xE9, 0xA5, 0xA5, 0xA6, 0xA6, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC7, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0x49, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF, 0xE0, 0xE1, 0xE2, 0xE3, 0xE5, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9, 0xEA, 0xEB, 0xDE, 0xED, 0xEE, 0xEF, 0xF0, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFB, 0xFC, 0xFD, 0xFE, 0xFF}
Definition at line 305 of file ff.c.
TBL_CT860
#define TBL_CT860 {0x80, 0x9A, 0x90, 0x8F, 0x8E, 0x91, 0x86, 0x80, 0x89, 0x89, 0x92, 0x8B, 0x8C, 0x98, 0x8E, 0x8F, 0x90, 0x91, 0x92, 0x8C, 0x99, 0xA9, 0x96, 0x9D, 0x98, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0x86, 0x8B, 0x9F, 0x96, 0xA5, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF, 0xE0, 0xE1, 0xE2, 0xE3, 0xE4, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9, 0xEA, 0xEB, 0xEC, 0xED, 0xEE, 0xEF, 0xF0, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFB, 0xFC, 0xFD, 0xFE, 0xFF}
Definition at line 307 of file ff.c.
TBL_CT861
#define TBL_CT861 {0x80, 0x9A, 0x90, 0x41, 0x8E, 0x41, 0x8F, 0x80, 0x45, 0x45, 0x45, 0x8B, 0x8B, 0x8D, 0x8E, 0x8F, 0x90, 0x92, 0x92, 0x4F, 0x99, 0x8D, 0x55, 0x97, 0x97, 0x99, 0x9A, 0x9D, 0x9C, 0x9D, 0x9E, 0x9F, 0xA4, 0xA5, 0xA6, 0xA7, 0xA4, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF, 0xE0, 0xE1, 0xE2, 0xE3, 0xE4, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9, 0xEA, 0xEB, 0xEC, 0xED, 0xEE, 0xEF, 0xF0, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFB, 0xFC, 0xFD, 0xFE, 0xFF}
Definition at line 309 of file ff.c.
TBL_CT862
#define TBL_CT862 {0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0x41, 0x49, 0x4F, 0x55, 0xA5, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF, 0xE0, 0xE1, 0xE2, 0xE3, 0xE4, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9, 0xEA, 0xEB, 0xEC, 0xED, 0xEE, 0xEF, 0xF0, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFB, 0xFC, 0xFD, 0xFE, 0xFF}
Definition at line 311 of file ff.c.
TBL_CT863
#define TBL_CT863 {0x43, 0x55, 0x45, 0x41, 0x41, 0x41, 0x86, 0x43, 0x45, 0x45, 0x45, 0x49, 0x49, 0x8D, 0x41, 0x8F, 0x45, 0x45, 0x45, 0x4F, 0x45, 0x49, 0x55, 0x55, 0x98, 0x4F, 0x55, 0x9B, 0x9C, 0x55, 0x55, 0x9F, 0xA0, 0xA1, 0x4F, 0x55, 0xA4, 0xA5, 0xA6, 0xA7, 0x49, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF, 0xE0, 0xE1, 0xE2, 0xE3, 0xE4, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9, 0xEA, 0xEB, 0xEC, 0xED, 0xEE, 0xEF, 0xF0, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFB, 0xFC, 0xFD, 0xFE, 0xFF}
Definition at line 313 of file ff.c.
TBL_CT864
#define TBL_CT864 {0x80, 0x9A, 0x45, 0x41, 0x8E, 0x41, 0x8F, 0x80, 0x45, 0x45, 0x45, 0x49, 0x49, 0x49, 0x8E, 0x8F, 0x90, 0x92, 0x92, 0x4F, 0x99, 0x4F, 0x55, 0x55, 0x59, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0x41, 0x49, 0x4F, 0x55, 0xA5, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF, 0xE0, 0xE1, 0xE2, 0xE3, 0xE4, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9, 0xEA, 0xEB, 0xEC, 0xED, 0xEE, 0xEF, 0xF0, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFB, 0xFC, 0xFD, 0xFE, 0xFF}
Definition at line 315 of file ff.c.
TBL_CT865
#define TBL_CT865 {0x80, 0x9A, 0x90, 0x41, 0x8E, 0x41, 0x8F, 0x80, 0x45, 0x45, 0x45, 0x49, 0x49, 0x49, 0x8E, 0x8F, 0x90, 0x92, 0x92, 0x4F, 0x99, 0x4F, 0x55, 0x55, 0x59, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0x41, 0x49, 0x4F, 0x55, 0xA5, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF, 0xE0, 0xE1, 0xE2, 0xE3, 0xE4, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9, 0xEA, 0xEB, 0xEC, 0xED, 0xEE, 0xEF, 0xF0, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFB, 0xFC, 0xFD, 0xFE, 0xFF}
Definition at line 317 of file ff.c.
TBL_CT866
#define TBL_CT866 {0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0xF0, 0xF0, 0xF2, 0xF2, 0xF4, 0xF4, 0xF6, 0xF6, 0xF8, 0xF9, 0xFA, 0xFB, 0xFC, 0xFD, 0xFE, 0xFF}
Definition at line 319 of file ff.c.
TBL_CT869
#define TBL_CT869 {0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0x86, 0x9C, 0x8D, 0x8F, 0x90, 0x91, 0x90, 0x92, 0x95, 0xA4, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xA4, 0xA5, 0xA6, 0xD9, 0xDA, 0xDB, 0xDC, 0xA7, 0xA8, 0xDF, 0xA9, 0xAA, 0xAC, 0xAD, 0xB5, 0xB6, 0xB7, 0xB8, 0xBD, 0xBE, 0xC6, 0xC7, 0xCF, 0xCF, 0xD0, 0xEF, 0xF0, 0xF1, 0xD1, 0xD2, 0xD3, 0xF5, 0xD4, 0xF7, 0xF8, 0xF9, 0xD5, 0x96, 0x95, 0x98, 0xFE, 0xFF}
Definition at line 321 of file ff.c.
TBL_DC932
#define TBL_DC932 {0x81, 0x9F, 0xE0, 0xFC, 0x40, 0x7E, 0x80, 0xFC, 0x00, 0x00}
Definition at line 326 of file ff.c.
TBL_DC936
#define TBL_DC936 {0x81, 0xFE, 0x00, 0x00, 0x40, 0x7E, 0x80, 0xFE, 0x00, 0x00}
Definition at line 328 of file ff.c.
TBL_DC949
#define TBL_DC949 {0x81, 0xFE, 0x00, 0x00, 0x41, 0x5A, 0x61, 0x7A, 0x81, 0xFE}
Definition at line 330 of file ff.c.
TBL_DC950
#define TBL_DC950 {0x81, 0xFE, 0x00, 0x00, 0x40, 0x7E, 0xA1, 0xFE, 0x00, 0x00}
Definition at line 332 of file ff.c.
XDIR_AccTime
#define XDIR_AccTime 16 /* exFAT: Last accessed time (DWORD) */
Definition at line 168 of file ff.c.
Referenced by f_sync().
XDIR_AccTZ
#define XDIR_AccTZ 24 /* exFAT: Last accessed timezone (BYTE) */
Definition at line 173 of file ff.c.
XDIR_Attr
#define XDIR_Attr 4 /* exFAT: File attribute (WORD) */
Definition at line 165 of file ff.c.
Referenced by dir_read(), f_mkdir(), f_open(), f_rename(), f_sync(), and get_fileinfo().
XDIR_CaseSum
#define XDIR_CaseSum 4 /* exFAT: Sum of case conversion table (DWORD) */
Definition at line 162 of file ff.c.
XDIR_CrtTime
#define XDIR_CrtTime 8 /* exFAT: Created time (DWORD) */
Definition at line 166 of file ff.c.
Referenced by f_open().
XDIR_CrtTime10
#define XDIR_CrtTime10 20 /* exFAT: Created time subsecond (BYTE) */
Definition at line 169 of file ff.c.
XDIR_CrtTZ
#define XDIR_CrtTZ 22 /* exFAT: Created timezone (BYTE) */
Definition at line 171 of file ff.c.
XDIR_FileSize
#define XDIR_FileSize 56 /* exFAT: File/Directory size (QWORD) */
Definition at line 179 of file ff.c.
Referenced by dir_register(), f_mkdir(), f_sync(), follow_path(), and get_fileinfo().
XDIR_FstClus
#define XDIR_FstClus 52 /* exFAT: First cluster of the file data (DWORD) */
Definition at line 178 of file ff.c.
Referenced by f_mkdir(), and f_sync().
XDIR_GenFlags
#define XDIR_GenFlags 33 /* exFAT: General secondary flags (BYTE) */
Definition at line 174 of file ff.c.
Referenced by dir_register(), f_mkdir(), f_open(), f_sync(), and follow_path().
XDIR_Label
#define XDIR_Label 2 /* exFAT: Volume label (11-WORD) */
Definition at line 161 of file ff.c.
XDIR_ModTime
#define XDIR_ModTime 12 /* exFAT: Modified time (DWORD) */
Definition at line 167 of file ff.c.
Referenced by f_mkdir(), f_sync(), and get_fileinfo().
XDIR_ModTime10
#define XDIR_ModTime10 21 /* exFAT: Modified time subsecond (BYTE) */
Definition at line 170 of file ff.c.
Referenced by f_sync().
XDIR_ModTZ
#define XDIR_ModTZ 23 /* exFAT: Modified timezone (BYTE) */
Definition at line 172 of file ff.c.
XDIR_NameHash
#define XDIR_NameHash 36 /* exFAT: Hash of file name (WORD) */
Definition at line 176 of file ff.c.
Referenced by dir_find(), and f_rename().
XDIR_NumLabel
#define XDIR_NumLabel 1 /* exFAT: Number of volume label characters (BYTE) */
Definition at line 160 of file ff.c.
XDIR_NumName
#define XDIR_NumName 35 /* exFAT: Number of file name characters (BYTE) */
Definition at line 175 of file ff.c.
Referenced by dir_find(), f_rename(), and get_fileinfo().
XDIR_NumSec
#define XDIR_NumSec 1 /* exFAT: Number of secondary entries (BYTE) */
Definition at line 163 of file ff.c.
Referenced by f_rename().
XDIR_SetSum
#define XDIR_SetSum 2 /* exFAT: Sum of the set of directory entries (WORD) */
Definition at line 164 of file ff.c.
XDIR_Type
#define XDIR_Type 0 /* exFAT: Type of exFAT directory entry (BYTE) */
Definition at line 159 of file ff.c.
Referenced by dir_alloc(), and dir_remove().
XDIR_ValidFileSize
#define XDIR_ValidFileSize 40 /* exFAT: Valid file size (QWORD) */
Definition at line 177 of file ff.c.
Referenced by dir_register(), f_mkdir(), and f_sync().
Function Documentation
check_fs()
static UINT check_fs (FATFS * fs, LBA_t sect) static
Definition at line 3313 of file ff.c.
References BPB_BytsPerSec, BPB_FATSz16, BPB_NumFATs, BPB_RootEntCnt, BPB_RsvdSecCnt, BPB_SecPerClus, BPB_TotSec16, BPB_TotSec32, BS_55AA, BS_FilSysType32, BS_JmpBoot, FF_MAX_SS, FF_MIN_SS, FR_OK, ld_dword(), ld_word(), move_window(), FATFS::wflag, FATFS::win, and FATFS::winsect.
Referenced by find_volume().
clst2sect()
static LBA_t clst2sect (FATFS * fs, DWORD clst) static
Definition at line 1066 of file ff.c.
References FATFS::csize, FATFS::database, and FATFS::n_fatent.
Referenced by dir_clear(), dir_next(), dir_sdi(), f_lseek(), f_open(), f_read(), f_rename(), f_write(), mount_volume(), and remove_chain().
cmp_lfn()
static int cmp_lfn (const WCHAR * lfnbuf, BYTE * dir) static
Definition at line 1823 of file ff.c.
References FF_MAX_LFN, ff_wtoupper(), ld_word(), LDIR_FstClusLO, LDIR_Ord, LfnOfs, and LLEF.
Referenced by dir_find().
create_chain()
static DWORD create_chain (FFOBJID * obj, DWORD clst) static
Definition at line 1452 of file ff.c.
References FR_DISK_ERR, FR_INT_ERR, FR_OK, FATFS::free_clst, FFOBJID::fs, FS_EXFAT, FATFS::fs_type, FATFS::fsi_flag, get_fat(), FATFS::last_clst, FATFS::n_fatent, put_fat(), FFOBJID::sclust, and FFOBJID::stat.
Referenced by dir_next(), f_lseek(), f_mkdir(), and f_write().
create_name()
static FRESULT create_name (DIR * dp, const TCHAR ** path) static
Definition at line 2823 of file ff.c.
References CODEPAGE, dbc_1st(), dbc_2nd(), DDEM, ExCvt, FF_MAX_LFN, ff_uni2oem(), ff_wtoupper(), DIR::fn, FR_INVALID_NAME, FR_OK, FFOBJID::fs, IsLower, IsSeparator, IsTerminator, IsUpper, FATFS::lfnbuf, NS_BODY, NS_DOT, NS_EXT, NS_LAST, NS_LFN, NS_LOSS, NSFLAG, DIR::obj, RDDEM, and tchar2uni().
Referenced by follow_path().
dbc_1st()
static int dbc_1st (BYTE c) static
Definition at line 609 of file ff.c.
Referenced by create_name(), gen_numname(), get_fileinfo(), and tchar2uni().
dbc_2nd()
static int dbc_2nd (BYTE c) static
Definition at line 632 of file ff.c.
Referenced by create_name(), get_fileinfo(), and tchar2uni().
dir_alloc()
static FRESULT dir_alloc (DIR * dp, UINT n_ent) static
Definition at line 1751 of file ff.c.
References DDEM, DIR::dir, DIR_Name, dir_next(), dir_sdi(), FR_DENIED, FR_NO_FILE, FR_OK, FFOBJID::fs, FS_EXFAT, FATFS::fs_type, move_window(), DIR::obj, DIR::sect, and XDIR_Type.
Referenced by dir_register().
dir_clear()
static FRESULT dir_clear (FATFS * fs, DWORD clst) static
Definition at line 1596 of file ff.c.
References clst2sect(), FATFS::csize, disk_write(), FR_DISK_ERR, FR_OK, FATFS::pdrv, RES_OK, SS, sync_window(), FATFS::win, and FATFS::winsect.
Referenced by dir_next(), and f_mkdir().
dir_find()
static FRESULT dir_find (DIR * dp) static
Definition at line 2316 of file ff.c.
References AM_LFN, AM_MASK, AM_VOL, FFOBJID::attr, DIR::blk_ofs, cmp_lfn(), DDEM, DIR::dir, DIR_Attr, DIR_Name, dir_next(), DIR_READ_FILE, dir_sdi(), DIR::dptr, FF_MAX_LFN, ff_wtoupper(), DIR::fn, FR_NO_FILE, FR_OK, FFOBJID::fs, FS_EXFAT, FATFS::fs_type, ld_word(), LDIR_Chksum, FATFS::lfnbuf, LLEF, move_window(), NS_LOSS, NS_NOLFN, NSFLAG, DIR::obj, DIR::sect, sum_sfn(), SZDIRE, XDIR_NameHash, and XDIR_NumName.
Referenced by dir_register(), and follow_path().
dir_next()
static FRESULT dir_next (DIR * dp, int stretch) static
Definition at line 1683 of file ff.c.
References clst2sect(), DIR::clust, create_chain(), FATFS::csize, DIR::dir, dir_clear(), DIR::dptr, FF_FS_EXFAT, FR_DENIED, FR_DISK_ERR, FR_INT_ERR, FR_NO_FILE, FR_OK, FFOBJID::fs, FS_EXFAT, FATFS::fs_type, get_fat(), MAX_DIR, MAX_DIR_EX, FATFS::n_fatent, FATFS::n_rootdir, DIR::obj, DIR::sect, SS, FFOBJID::stat, SZDIRE, and FATFS::win.
Referenced by dir_alloc(), dir_find(), dir_read(), dir_register(), dir_remove(), and f_readdir().
dir_read()
static FRESULT dir_read (DIR * dp, int vol) static
Definition at line 2235 of file ff.c.
References AM_ARC, AM_LFN, AM_MASK, AM_VOL, FFOBJID::attr, DIR::blk_ofs, DDEM, DIR::dir, DIR_Attr, DIR_Name, dir_next(), DIR::dptr, ET_FILEDIR, ET_VLABEL, FF_USE_LABEL, FR_NO_FILE, FR_OK, FFOBJID::fs, FS_EXFAT, FATFS::fs_type, LDIR_Chksum, FATFS::lfnbuf, LLEF, move_window(), DIR::obj, pick_lfn(), DIR::sect, sum_sfn(), and XDIR_Attr.
dir_register()
static FRESULT dir_register (DIR * dp) static
Definition at line 2410 of file ff.c.
References DIR::blk_ofs, DIR::clust, FATFS::csize, DIR::dir, dir_alloc(), dir_find(), DIR_Name, dir_next(), DIR_NTres, dir_sdi(), DIR::dptr, DIR::fn, FR_DENIED, FR_INVALID_NAME, FR_NO_FILE, FR_OK, FFOBJID::fs, FS_EXFAT, FATFS::fs_type, gen_numname(), FATFS::lfnbuf, move_window(), NS_BODY, NS_DOT, NS_EXT, NS_LFN, NS_LOSS, NS_NOLFN, NS_NONAME, NSFLAG, DIR::obj, FFOBJID::objsize, put_lfn(), FFOBJID::sclust, DIR::sect, SS, FFOBJID::stat, sum_sfn(), SZDIRE, FATFS::wflag, XDIR_FileSize, XDIR_GenFlags, and XDIR_ValidFileSize.
Referenced by f_mkdir(), f_open(), and f_rename().
dir_remove()
static FRESULT dir_remove (DIR * dp) static
Definition at line 2523 of file ff.c.
References DIR::blk_ofs, DDEM, DIR::dir, DIR_Name, dir_next(), dir_sdi(), DIR::dptr, FF_FS_EXFAT, FR_INT_ERR, FR_NO_FILE, FR_OK, FFOBJID::fs, FS_EXFAT, FATFS::fs_type, move_window(), DIR::obj, DIR::sect, FATFS::wflag, and XDIR_Type.
Referenced by f_rename(), and f_unlink().
dir_sdi()
static FRESULT dir_sdi (DIR * dp, DWORD ofs) static
Definition at line 1635 of file ff.c.
References clst2sect(), DIR::clust, FATFS::csize, DIR::dir, FATFS::dirbase, DIR::dptr, FF_FS_EXFAT, FR_DISK_ERR, FR_INT_ERR, FR_OK, FFOBJID::fs, FS_EXFAT, FS_FAT32, FATFS::fs_type, get_fat(), MAX_DIR, MAX_DIR_EX, FATFS::n_fatent, FATFS::n_rootdir, DIR::obj, FFOBJID::sclust, DIR::sect, SS, FFOBJID::stat, SZDIRE, and FATFS::win.
Referenced by dir_alloc(), dir_find(), dir_register(), dir_remove(), f_opendir(), f_readdir(), f_unlink(), and follow_path().
f_close()
FRESULT f_close (FIL * fp)
Definition at line 4278 of file ff.c.
References f_sync(), FR_OK, FFOBJID::fs, FIL::obj, unlock_volume(), and validate().
Referenced by sd_shutdown().
f_closedir()
FRESULT f_closedir (DIR * dp)
Definition at line 4748 of file ff.c.
References FR_OK, FFOBJID::fs, DIR::obj, unlock_volume(), and validate().
f_getfree()
FRESULT f_getfree (const TCHAR * path, DWORD * nclst, FATFS ** fatfs)
Definition at line 4888 of file ff.c.
References FATFS::fatbase, FR_DISK_ERR, FR_INT_ERR, FR_OK, FATFS::free_clst, FFOBJID::fs, FS_EXFAT, FS_FAT12, FS_FAT16, FATFS::fs_type, FATFS::fsi_flag, get_fat(), ld_dword(), ld_word(), LEAVE_FF, mount_volume(), move_window(), FATFS::n_fatent, SS, and FATFS::win.
f_lseek()
FRESULT f_lseek (FIL * fp, FSIZE_t ofs)
Definition at line 4500 of file ff.c.
References ABORT, FIL::buf, clst2sect(), FIL::clust, create_chain(), CREATE_LINKMAP, FATFS::csize, disk_read(), disk_write(), FIL::err, FA_DIRTY, FA_MODIFIED, FA_WRITE, FF_FS_EXFAT, FF_FS_READONLY, FIL::flag, FIL::fptr, FR_DISK_ERR, FR_INT_ERR, FR_NOT_ENOUGH_CORE, FR_OK, FS_EXFAT, FATFS::fs_type, get_fat(), LEAVE_FF, FATFS::n_fatent, FIL::obj, FFOBJID::objsize, FATFS::pdrv, RES_OK, FFOBJID::sclust, FIL::sect, SS, and validate().
f_mkdir()
FRESULT f_mkdir (const TCHAR * path)
Definition at line 5130 of file ff.c.
References AM_DIR, create_chain(), FATFS::csize, DEF_NAMBUF, DIR::dir, DIR_Attr, dir_clear(), DIR_ModTime, DIR_Name, dir_register(), FA_WRITE, FF_FS_EXFAT, FF_FS_RPATH, DIR::fn, follow_path(), FR_DENIED, FR_DISK_ERR, FR_EXIST, FR_INT_ERR, FR_INVALID_NAME, FR_NO_FILE, FR_OK, FREE_NAMBUF, FFOBJID::fs, FS_EXFAT, FATFS::fs_type, GET_FATTIME, INIT_NAMBUF, LEAVE_FF, mount_volume(), NS_DOT, NSFLAG, DIR::obj, remove_chain(), FFOBJID::sclust, SS, st_clust(), st_dword(), sync_fs(), SZDIRE, FATFS::wflag, FATFS::win, XDIR_Attr, XDIR_FileSize, XDIR_FstClus, XDIR_GenFlags, XDIR_ModTime, and XDIR_ValidFileSize.
f_mount()
FRESULT f_mount (FATFS * fs, const TCHAR * path, BYTE opt)
Definition at line 3710 of file ff.c.
References FatFs, ff_mutex_create(), ff_mutex_delete(), FF_VOLUMES, FR_INT_ERR, FR_INVALID_DRIVE, FR_OK, FATFS::fs_type, get_ldnumber(), LD2PD, FATFS::ldrv, LEAVE_FF, mount_volume(), and FATFS::pdrv.
Referenced by sd_shutdown(), and sd_update_periodic().
f_open()
FRESULT f_open (FIL * fp, const TCHAR * path, BYTE mode)
Definition at line 3768 of file ff.c.
References AM_ARC, AM_DIR, AM_RDO, FFOBJID::attr, DIR::blk_ofs, FIL::buf, clst2sect(), FIL::clust, FATFS::csize, DEF_NAMBUF, DIR::dir, DIR_Attr, DIR_CrtTime, DIR_FileSize, DIR_ModTime, FIL::dir_ptr, dir_register(), FIL::dir_sect, disk_read(), FIL::err, FA_CREATE_ALWAYS, FA_CREATE_NEW, FA_MODIFIED, FA_OPEN_ALWAYS, FA_OPEN_APPEND, FA_READ, FA_SEEKEND, FA_WRITE, FF_FS_READONLY, FIL::flag, DIR::fn, follow_path(), FIL::fptr, FR_DENIED, FR_DISK_ERR, FR_EXIST, FR_INT_ERR, FR_INVALID_NAME, FR_INVALID_OBJECT, FR_NO_FILE, FR_OK, FR_TOO_MANY_OPEN_FILES, FREE_NAMBUF, FFOBJID::fs, FS_EXFAT, FATFS::fs_type, get_fat(), GET_FATTIME, FATFS::id, FFOBJID::id, INIT_NAMBUF, FATFS::last_clst, ld_clust(), ld_dword(), LEAVE_FF, mount_volume(), move_window(), NS_NONAME, NSFLAG, DIR::obj, FIL::obj, FFOBJID::objsize, FATFS::pdrv, remove_chain(), RES_OK, FFOBJID::sclust, FIL::sect, SS, st_clust(), st_dword(), FFOBJID::stat, FATFS::wflag, FATFS::winsect, XDIR_Attr, XDIR_CrtTime, and XDIR_GenFlags.
Referenced by sd_create_new_file().
f_opendir()
FRESULT f_opendir (DIR * dp, const TCHAR * path)
Definition at line 4683 of file ff.c.
References AM_DIR, FFOBJID::attr, DIR::blk_ofs, DEF_NAMBUF, DIR::dir, dir_sdi(), DIR::fn, follow_path(), FR_INVALID_OBJECT, FR_NO_FILE, FR_NO_PATH, FR_OK, FR_TOO_MANY_OPEN_FILES, FREE_NAMBUF, FFOBJID::fs, FS_EXFAT, FATFS::fs_type, FATFS::id, FFOBJID::id, INIT_NAMBUF, ld_clust(), LEAVE_FF, mount_volume(), NS_NONAME, NSFLAG, DIR::obj, FFOBJID::objsize, FFOBJID::sclust, and FFOBJID::stat.
f_read()
FRESULT f_read (FIL * fp, void * buff, UINT btr, UINT * br)
Definition at line 3967 of file ff.c.
References ABORT, FIL::buf, clst2sect(), FIL::clust, FATFS::csize, disk_read(), disk_write(), FIL::err, FA_DIRTY, FA_READ, FIL::flag, FIL::fptr, FR_DENIED, FR_DISK_ERR, FR_INT_ERR, FR_OK, get_fat(), LEAVE_FF, move_window(), FIL::obj, FFOBJID::objsize, FATFS::pdrv, RES_OK, FFOBJID::sclust, FIL::sect, SS, validate(), FATFS::wflag, FATFS::win, and FATFS::winsect.
f_readdir()
FRESULT f_readdir (DIR * dp, FILINFO * fno)
Definition at line 4775 of file ff.c.
References DEF_NAMBUF, dir_next(), DIR_READ_FILE, dir_sdi(), FR_NO_FILE, FR_OK, FREE_NAMBUF, get_fileinfo(), INIT_NAMBUF, LEAVE_FF, DIR::obj, and validate().
f_rename()
FRESULT f_rename (const TCHAR * path_old, const TCHAR * path_new)
Definition at line 5214 of file ff.c.
References AM_ARC, AM_DIR, clst2sect(), DEF_NAMBUF, DIR::dir, DIR_Attr, dir_register(), dir_remove(), DIR::dptr, FA_WRITE, FF_FS_EXFAT, DIR::fn, follow_path(), FR_EXIST, FR_INT_ERR, FR_INVALID_NAME, FR_NO_FILE, FR_OK, FREE_NAMBUF, FFOBJID::fs, FS_EXFAT, FATFS::fs_type, get_ldnumber(), INIT_NAMBUF, ld_clust(), ld_word(), LEAVE_FF, mount_volume(), move_window(), NS_DOT, NS_NONAME, NSFLAG, DIR::obj, FFOBJID::sclust, st_clust(), st_word(), sync_fs(), SZDIRE, FATFS::wflag, FATFS::win, XDIR_Attr, XDIR_NameHash, XDIR_NumName, and XDIR_NumSec.
f_stat()
FRESULT f_stat (const TCHAR * path, FILINFO * fno)
Definition at line 4856 of file ff.c.
References DEF_NAMBUF, DIR::fn, follow_path(), FR_INVALID_NAME, FR_OK, FREE_NAMBUF, FFOBJID::fs, get_fileinfo(), INIT_NAMBUF, LEAVE_FF, mount_volume(), NS_NONAME, NSFLAG, and DIR::obj.
f_sync()
FRESULT f_sync (FIL * fp)
Definition at line 4201 of file ff.c.
References AM_ARC, FIL::buf, FIL::clust, DEF_NAMBUF, DIR_Attr, DIR_FileSize, DIR_LstAccDate, DIR_ModTime, FIL::dir_ptr, FIL::dir_sect, disk_write(), FA_DIRTY, FA_MODIFIED, FIL::flag, FR_DISK_ERR, FR_OK, FREE_NAMBUF, FFOBJID::fs, FS_EXFAT, FATFS::fs_type, GET_FATTIME, INIT_NAMBUF, LEAVE_FF, move_window(), FIL::obj, FFOBJID::objsize, FATFS::pdrv, RES_OK, FFOBJID::sclust, FIL::sect, st_clust(), st_dword(), st_word(), FFOBJID::stat, sync_fs(), validate(), FATFS::wflag, XDIR_AccTime, XDIR_Attr, XDIR_FileSize, XDIR_FstClus, XDIR_GenFlags, XDIR_ModTime, XDIR_ModTime10, and XDIR_ValidFileSize.
Referenced by f_close(), and sd_file_sync().
f_truncate()
FRESULT f_truncate (FIL * fp)
Definition at line 4987 of file ff.c.
References ABORT, FIL::buf, FIL::clust, disk_write(), FIL::err, FA_DIRTY, FA_MODIFIED, FA_WRITE, FIL::flag, FIL::fptr, FR_DENIED, FR_DISK_ERR, FR_INT_ERR, FR_OK, get_fat(), LEAVE_FF, FIL::obj, FFOBJID::objsize, FATFS::pdrv, remove_chain(), RES_OK, FFOBJID::sclust, FIL::sect, and validate().
f_unlink()
FRESULT f_unlink (const TCHAR * path)
Definition at line 5037 of file ff.c.
References AM_DIR, AM_RDO, FFOBJID::attr, DEF_NAMBUF, DIR::dir, DIR_READ_FILE, dir_remove(), dir_sdi(), FA_WRITE, FF_FS_RPATH, DIR::fn, follow_path(), FR_DENIED, FR_INVALID_NAME, FR_NO_FILE, FR_OK, FREE_NAMBUF, FFOBJID::fs, FS_EXFAT, FATFS::fs_type, INIT_NAMBUF, ld_clust(), LEAVE_FF, mount_volume(), NS_DOT, NS_NONAME, NSFLAG, DIR::obj, FFOBJID::objsize, remove_chain(), FFOBJID::sclust, FFOBJID::stat, and sync_fs().
f_write()
FRESULT f_write (FIL * fp, const void * buff, UINT btw, UINT * bw)
Definition at line 4073 of file ff.c.
References ABORT, FIL::buf, clst2sect(), FIL::clust, create_chain(), FATFS::csize, disk_read(), disk_write(), FIL::err, FA_DIRTY, FA_MODIFIED, FA_WRITE, FF_FS_EXFAT, FIL::flag, FIL::fptr, FR_DENIED, FR_DISK_ERR, FR_INT_ERR, FR_OK, FS_EXFAT, FATFS::fs_type, LEAVE_FF, move_window(), FIL::obj, FFOBJID::objsize, FATFS::pdrv, RES_OK, FFOBJID::sclust, FIL::sect, SS, sync_window(), validate(), FATFS::wflag, FATFS::win, and FATFS::winsect.
Referenced by _sd_write_periodic().
find_volume()
static UINT find_volume (FATFS * fs, UINT part) static
Definition at line 3356 of file ff.c.
References check_fs(), FF_MULTI_PARTITION, FR_OK, GPTE_FstLba, GPTE_PtGuid, GPTH_PtNum, GPTH_PtOfs, ld_dword(), MBR_Table, move_window(), PTE_StLba, PTE_System, SS, SZ_GPTE, SZ_PTE, and FATFS::win.
Referenced by mount_volume().
follow_path()
static FRESULT follow_path (DIR * dp, const TCHAR * path) static
Definition at line 3064 of file ff.c.
References AM_DIR, FFOBJID::attr, DIR::blk_ofs, create_name(), dir_find(), dir_sdi(), DIR::dptr, FF_FS_RPATH, FF_STR_VOLUME_ID, DIR::fn, FR_NO_FILE, FR_NO_PATH, FR_OK, FFOBJID::fs, FS_EXFAT, FATFS::fs_type, IsSeparator, IsTerminator, ld_clust(), ld_dword(), NS_DOT, NS_LAST, NS_NONAME, NSFLAG, DIR::obj, FFOBJID::objsize, FFOBJID::sclust, SS, FFOBJID::stat, FATFS::win, XDIR_FileSize, and XDIR_GenFlags.
Referenced by f_mkdir(), f_open(), f_opendir(), f_rename(), f_stat(), and f_unlink().
gen_numname()
static void gen_numname (BYTE * dst, const BYTE * src, const WCHAR * lfn, UINT seq) static
Definition at line 1934 of file ff.c.
References dbc_1st().
Referenced by dir_register().
get_fat()
static DWORD get_fat (FFOBJID * obj, DWORD clst) static
Definition at line 1080 of file ff.c.
References FATFS::csize, FATFS::fatbase, FR_OK, FFOBJID::fs, FS_EXFAT, FS_FAT12, FS_FAT16, FS_FAT32, FATFS::fs_type, ld_dword(), ld_word(), move_window(), FATFS::n_fatent, FFOBJID::objsize, FFOBJID::sclust, SS, FFOBJID::stat, and FATFS::win.
Referenced by create_chain(), dir_next(), dir_sdi(), f_getfree(), f_lseek(), f_open(), f_read(), f_truncate(), and remove_chain().
get_fileinfo()
static void get_fileinfo (DIR * dp, FILINFO * fno) static
Definition at line 2569 of file ff.c.
References FILINFO::altname, AM_DIR, AM_MASK, AM_MASKX, DIR::blk_ofs, CODEPAGE, dbc_1st(), dbc_2nd(), DDEM, DIR::dir, DIR_Attr, DIR_FileSize, DIR_ModTime, DIR_NTres, FILINFO::fattrib, FILINFO::fdate, FF_LFN_BUF, FF_MAX_LFN, ff_oem2uni(), FF_SFN_BUF, FILINFO::fname, FFOBJID::fs, FS_EXFAT, FATFS::fs_type, FILINFO::fsize, FILINFO::ftime, IsSurrogate, IsUpper, ld_dword(), ld_word(), FATFS::lfnbuf, MAXDIRB, NS_BODY, NS_EXT, DIR::obj, put_utf(), RDDEM, DIR::sect, SZDIRE, XDIR_Attr, XDIR_FileSize, XDIR_ModTime, and XDIR_NumName.
Referenced by f_readdir(), and f_stat().
get_ldnumber()
static int get_ldnumber (const TCHAR ** path) static
Definition at line 3153 of file ff.c.
References FF_VOLUMES, IsDigit, IsLower, IsTerminator, and VolumeStr.
Referenced by f_mount(), f_rename(), and mount_volume().
ld_clust()
static DWORD ld_clust (FATFS * fs, const BYTE * dir) static
Definition at line 1791 of file ff.c.
References DIR_FstClusHI, DIR_FstClusLO, FS_FAT32, FATFS::fs_type, and ld_word().
Referenced by f_open(), f_opendir(), f_rename(), f_unlink(), and follow_path().
ld_dword()
static DWORD ld_dword (const BYTE * ptr) static
Definition at line 535 of file ff.c.
Referenced by check_fs(), f_getfree(), f_open(), find_volume(), follow_path(), get_fat(), get_fileinfo(), mount_volume(), and put_fat().
ld_word()
static WORD ld_word (const BYTE * ptr) static
Definition at line 526 of file ff.c.
Referenced by check_fs(), cmp_lfn(), dir_find(), f_getfree(), f_rename(), get_fat(), get_fileinfo(), ld_clust(), mount_volume(), and pick_lfn().
lock_volume()
static int lock_volume (FATFS * fs, int syslock) static
Definition at line 838 of file ff.c.
References ff_mutex_give(), ff_mutex_take(), FF_VOLUMES, and FATFS::ldrv.
Referenced by mount_volume(), and validate().
mount_volume()
static FRESULT mount_volume (const TCHAR ** path, FATFS ** rfs, BYTE mode) static
Definition at line 3412 of file ff.c.
References BPB_BytsPerSec, BPB_BytsPerSecEx, BPB_DataOfsEx, BPB_FatOfsEx, BPB_FATSz16, BPB_FATSz32, BPB_FatSzEx, BPB_FSInfo32, BPB_FSVer32, BPB_FSVerEx, BPB_NumClusEx, BPB_NumFATs, BPB_NumFATsEx, BPB_RootClus32, BPB_RootClusEx, BPB_RootEntCnt, BPB_RsvdSecCnt, BPB_SecPerClus, BPB_SecPerClusEx, BPB_TotSec16, BPB_TotSec32, BPB_TotSecEx, BPB_ZeroedEx, BS_55AA, clst2sect(), FATFS::csize, FATFS::database, FATFS::dirbase, disk_initialize(), disk_ioctl(), disk_status(), ET_BITMAP, FA_READ, FATFS::fatbase, FatFs, FF_FS_READONLY, FF_LBA64, FF_MAX_SS, FF_MIN_SS, find_volume(), FR_DISK_ERR, FR_INVALID_DRIVE, FR_NO_FILESYSTEM, FR_NOT_ENABLED, FR_NOT_READY, FR_OK, FR_TIMEOUT, FR_WRITE_PROTECTED, FATFS::free_clst, FS_EXFAT, FS_FAT12, FS_FAT16, FS_FAT32, FATFS::fs_type, FATFS::fsi_flag, FSI_Free_Count, FSI_LeadSig, FSI_Nxt_Free, FSI_StrucSig, Fsid, FATFS::fsize, get_ldnumber(), GET_SECTOR_SIZE, FATFS::id, FATFS::last_clst, LD2PT, ld_dword(), ld_word(), FATFS::lfnbuf, lock_volume(), MAX_EXFAT, MAX_FAT12, MAX_FAT16, MAX_FAT32, move_window(), FATFS::n_fatent, FATFS::n_fats, FATFS::n_rootdir, FATFS::pdrv, RES_OK, SS, STA_NOINIT, STA_PROTECT, SZDIRE, FATFS::volbase, FATFS::win, and FATFS::winsect.
Referenced by f_getfree(), f_mkdir(), f_mount(), f_open(), f_opendir(), f_rename(), f_stat(), and f_unlink().
move_window()
static FRESULT move_window (FATFS * fs, LBA_t sect) static
Definition at line 1007 of file ff.c.
References disk_read(), FR_DISK_ERR, FR_OK, FATFS::pdrv, RES_OK, sync_window(), FATFS::win, and FATFS::winsect.
Referenced by check_fs(), dir_alloc(), dir_find(), dir_read(), dir_register(), dir_remove(), f_getfree(), f_open(), f_read(), f_rename(), f_sync(), f_write(), find_volume(), get_fat(), mount_volume(), and put_fat().
pick_lfn()
static int pick_lfn (WCHAR * lfnbuf, BYTE * dir) static
Definition at line 1859 of file ff.c.
References FF_MAX_LFN, ld_word(), LDIR_FstClusLO, LDIR_Ord, LfnOfs, and LLEF.
Referenced by dir_read().
put_fat()
static FRESULT put_fat (FATFS * fs, DWORD clst, DWORD val) static
Definition at line 1159 of file ff.c.
References FATFS::fatbase, FF_FS_EXFAT, FR_INT_ERR, FR_OK, FS_EXFAT, FS_FAT12, FS_FAT16, FS_FAT32, FATFS::fs_type, ld_dword(), move_window(), SS, st_dword(), st_word(), FATFS::wflag, and FATFS::win.
Referenced by create_chain(), and remove_chain().
put_lfn()
static void put_lfn (const WCHAR * lfn, BYTE * dir, BYTE ord, BYTE sum) static
Definition at line 1898 of file ff.c.
References AM_LFN, LDIR_Attr, LDIR_Chksum, LDIR_FstClusLO, LDIR_Ord, LDIR_Type, LfnOfs, LLEF, and st_word().
Referenced by dir_register().
put_utf()
static UINT put_utf (DWORD chr, TCHAR * buf, UINT szb) static
Definition at line 739 of file ff.c.
References CODEPAGE, ff_uni2oem(), IsSurrogate, IsSurrogateH, and IsSurrogateL.
Referenced by get_fileinfo().
remove_chain()
static FRESULT remove_chain (FFOBJID * obj, DWORD clst, DWORD pclst) static
Definition at line 1351 of file ff.c.
References clst2sect(), FATFS::csize, disk_ioctl(), FF_FS_EXFAT, FR_DISK_ERR, FR_INT_ERR, FR_OK, FATFS::free_clst, FFOBJID::fs, FS_EXFAT, FATFS::fs_type, FATFS::fsi_flag, get_fat(), FATFS::n_fatent, FATFS::pdrv, put_fat(), FFOBJID::sclust, and FFOBJID::stat.
Referenced by f_mkdir(), f_open(), f_truncate(), and f_unlink().
st_clust()
static void st_clust (FATFS * fs, BYTE * dir, DWORD cl) static
Definition at line 1806 of file ff.c.
References DIR_FstClusHI, DIR_FstClusLO, FS_FAT32, FATFS::fs_type, and st_word().
Referenced by f_mkdir(), f_open(), f_rename(), and f_sync().
st_dword()
static void st_dword (BYTE * ptr, DWORD val) static
Definition at line 571 of file ff.c.
Referenced by f_mkdir(), f_open(), f_sync(), put_fat(), and sync_fs().
st_word()
static void st_word (BYTE * ptr, WORD val) static
Definition at line 564 of file ff.c.
Referenced by f_rename(), f_sync(), put_fat(), put_lfn(), st_clust(), and sync_fs().
sum_sfn()
static BYTE sum_sfn (const BYTE * dir) static
Definition at line 1991 of file ff.c.
Referenced by dir_find(), dir_read(), and dir_register().
sync_fs()
static FRESULT sync_fs (FATFS * fs) static
Definition at line 1033 of file ff.c.
References BS_55AA, CTRL_SYNC, disk_ioctl(), disk_write(), FR_DISK_ERR, FR_OK, FATFS::free_clst, FS_FAT32, FATFS::fs_type, FATFS::fsi_flag, FSI_Free_Count, FSI_LeadSig, FSI_Nxt_Free, FSI_StrucSig, FATFS::last_clst, FATFS::pdrv, RES_OK, st_dword(), st_word(), sync_window(), FATFS::volbase, FATFS::win, and FATFS::winsect.
Referenced by f_mkdir(), f_rename(), f_sync(), and f_unlink().
sync_window()
static FRESULT sync_window (FATFS * fs) static
Definition at line 987 of file ff.c.
References disk_write(), FATFS::fatbase, FR_DISK_ERR, FR_OK, FATFS::fsize, FATFS::n_fats, FATFS::pdrv, RES_OK, FATFS::wflag, FATFS::win, and FATFS::winsect.
Referenced by dir_clear(), f_write(), move_window(), and sync_fs().
tchar2uni()
static DWORD tchar2uni (const TCHAR ** str) static
Definition at line 661 of file ff.c.
References CODEPAGE, dbc_1st(), dbc_2nd(), ff_oem2uni(), IsSurrogate, IsSurrogateH, and IsSurrogateL.
Referenced by create_name().
unlock_volume()
static void unlock_volume (FATFS * fs, FRESULT res) static
Definition at line 860 of file ff.c.
References ff_mutex_give(), FF_VOLUMES, FR_INVALID_DRIVE, FR_NOT_ENABLED, FR_TIMEOUT, and FATFS::ldrv.
Referenced by f_close(), f_closedir(), and validate().
validate()
static FRESULT validate (FFOBJID * obj, FATFS ** rfs) static
Definition at line 3673 of file ff.c.
References disk_status(), FR_INVALID_OBJECT, FR_OK, FR_TIMEOUT, FFOBJID::fs, FATFS::fs_type, FATFS::id, FFOBJID::id, lock_volume(), FATFS::pdrv, STA_NOINIT, and unlock_volume().
Referenced by f_close(), f_closedir(), f_lseek(), f_read(), f_readdir(), f_sync(), f_truncate(), and f_write().
Variable Documentation
ExCvt
const BYTE ExCvt[] = {0x80, 0x9A, 0x45, 0x41, 0x8E, 0x41, 0x8F, 0x80, 0x45, 0x45, 0x45, 0x49, 0x49, 0x49, 0x8E, 0x8F, 0x90, 0x92, 0x92, 0x4F, 0x99, 0x4F, 0x55, 0x55, 0x59, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0x41, 0x49, 0x4F, 0x55, 0xA5, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF, 0xE0, 0xE1, 0xE2, 0xE3, 0xE4, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9, 0xEA, 0xEB, 0xEC, 0xED, 0xEE, 0xEF, 0xF0, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFB, 0xFC, 0xFD, 0xFE, 0xFF} static
Definition at line 508 of file ff.c.
Referenced by create_name().
FatFs
FATFS* FatFs[1] static
Definition at line 355 of file ff.c.
Referenced by f_mount(), and mount_volume().
Fsid
WORD Fsid static
Definition at line 356 of file ff.c.
Referenced by mount_volume().
LfnOfs
const BYTE LfnOfs[] = {1, 3, 5, 7, 9, 14, 16, 18, 20, 22, 24, 28, 30} static
Definition at line 405 of file ff.c.
Referenced by cmp_lfn(), pick_lfn(), and put_lfn().
VolumeStr
const char* const VolumeStr[1] = { "SD" } static
Definition at line 371 of file ff.c.
Referenced by get_ldnumber().