PER Firmware: source/daq/fatfs/ffsystem.c File Reference
ffsystem.c File Reference
#include "ff.h"
#include "common/freertos/freertos.h"
Functions
int ff_mutex_create (int vol)
void ff_mutex_delete (int vol)
int ff_mutex_take (int vol)
void ff_mutex_give (int vol)
Variables
static SemaphoreHandle_t Mutex [1+1]
static StaticSemaphore_t MutexControlBlocks [1+1]
Function Documentation
ff_mutex_create()
int ff_mutex_create (int vol)
Definition at line 45 of file ffsystem.c.
References Mutex, and MutexControlBlocks.
Referenced by f_mount().
ff_mutex_delete()
void ff_mutex_delete (int vol)
Definition at line 58 of file ffsystem.c.
References Mutex.
Referenced by f_mount().
ff_mutex_give()
void ff_mutex_give (int vol)
Definition at line 81 of file ffsystem.c.
References Mutex.
Referenced by lock_volume(), and unlock_volume().
ff_mutex_take()
int ff_mutex_take (int vol)
Definition at line 70 of file ffsystem.c.
References FF_FS_TIMEOUT, and Mutex.
Referenced by lock_volume().
Variable Documentation
Mutex
SemaphoreHandle_t Mutex[1+1] static
Definition at line 35 of file ffsystem.c.
Referenced by ff_mutex_create(), ff_mutex_delete(), ff_mutex_give(), and ff_mutex_take().
MutexControlBlocks
StaticSemaphore_t MutexControlBlocks[1+1] static
Definition at line 36 of file ffsystem.c.
Referenced by ff_mutex_create().