PER Firmware: common/gps/gps.h File Reference
gps.h File Reference
GPS driver for UBLOX NEO-M9N GPS module.
#include <stdint.h>
Data Structures
struct NAV_PVT_t
struct GPS_Handle_t
Macros
#define GPS_RX_BUF_SIZE 100
#define UBX_NAV_PVT_HEADER_B0 0xB5
#define UBX_NAV_PVT_HEADER_B1 0x62
#define UBX_NAV_PVT_CLASS 0x01
#define UBX_NAV_PVT_MSG_ID 0x07
#define GPS_VALID_DATE ((gps_valid_flags_t)0x01)
#define GPS_VALID_TIME ((gps_valid_flags_t)0x02)
#define GPS_VALID_FULLY_RESOLVED ((gps_valid_flags_t)0x04)
#define GPS_VALID_MAG ((gps_valid_flags_t)0x08)
#define GPS_FIX_TYPE_NONE ((gps_fix_type_t)0x00)
#define GPS_FIX_TYPE_DEAD_RECKONING ((gps_fix_type_t)0x01)
#define GPS_FIX_TYPE_GNSS_2D ((gps_fix_type_t)0x02)
#define GPS_FIX_TYPE_GNSS_3D ((gps_fix_type_t)0x03)
#define GPS_FIX_TYPE_GNSS_DEAD_RECKONING ((gps_fix_type_t)0x04)
#define GPS_FIX_TYPE_TIME_ONLY ((gps_fix_type_t)0x05)
#define GPS_FLAG1_GNSS_FIX_OK ((gps_flags1_t)0x01)
#define GPS_FLAG1_DIFF_SOLN ((gps_flags1_t)0x02)
#define GPS_FLAG1_PSM_MASK ((gps_flags1_t)0x1C)
#define GPS_FLAG1_PSM_OFF ((gps_flags1_t)0x00)
#define GPS_FLAG1_PSM_ENABLED ((gps_flags1_t)0x04)
#define GPS_FLAG1_PSM_ACQUIRED ((gps_flags1_t)0x08)
#define GPS_FLAG1_PSM_TRACKING ((gps_flags1_t)0x0C)
#define GPS_FLAG1_PSM_POWER_OPTIMIZED ((gps_flags1_t)0x10)
#define GPS_FLAG1_PSM_INACTIVE ((gps_flags1_t)0x14)
#define GPS_FLAG1_HEADING_VALID ((gps_flags1_t)0x20)
#define GPS_FLAG1_CARRIER_PHASE_MASK ((gps_flags1_t)0xC0)
#define GPS_FLAG1_CARRIER_PHASE_NONE ((gps_flags1_t)0x00)
#define GPS_FLAG1_CARRIER_PHASE_FLOAT ((gps_flags1_t)0x40)
#define GPS_FLAG1_CARRIER_PHASE_FIXED ((gps_flags1_t)0x80)
#define GPS_FLAGS2_CONFIRMED_AVAILABLE ((gps_flags2_t)0x20)
#define GPS_FLAGS2_CONFIRMED_DATE ((gps_flags2_t)0x40)
#define GPS_FLAGS2_CONFIRMED_TIME ((gps_flags2_t)0x80)
Typedefs
typedef uint8_t gps_valid_flags_t
typedef uint8_t gps_fix_type_t
typedef uint8_t gps_flags1_t
typedef uint8_t gps_flags2_t
Functions
static int32_t bytes_to_int32 (uint8_t b0, uint8_t b1, uint8_t b2, uint8_t b3)
static uint32_t bytes_to_uint32 (uint8_t b0, uint8_t b1, uint8_t b2, uint8_t b3)
static uint16_t bytes_to_uint16 (uint8_t b0, uint8_t b1)
static int16_t bytes_to_int16 (uint8_t b0, uint8_t b1)
static bool is_valid_header (uint8_t sync0, uint8_t sync1, uint8_t class_id, uint8_t msg_id)
bool GPS_Decode (GPS_Handle_t *gps)
Function to decode periodic GPS UBX message.
Detailed Description
GPS driver for UBLOX NEO-M9N GPS module.
Author
Irving Wang (irvin.nosp@m.gw@p.nosp@m.urdue.nosp@m..edu)
Definition in file gps.h.
Macro Definition Documentation
GPS_FIX_TYPE_DEAD_RECKONING
#define GPS_FIX_TYPE_DEAD_RECKONING ((gps_fix_type_t)0x01)
Definition at line 51 of file gps.h.
GPS_FIX_TYPE_GNSS_2D
#define GPS_FIX_TYPE_GNSS_2D ((gps_fix_type_t)0x02)
Definition at line 52 of file gps.h.
Referenced by GPS_Decode().
GPS_FIX_TYPE_GNSS_3D
#define GPS_FIX_TYPE_GNSS_3D ((gps_fix_type_t)0x03)
Definition at line 53 of file gps.h.
Referenced by GPS_Decode().
GPS_FIX_TYPE_GNSS_DEAD_RECKONING
#define GPS_FIX_TYPE_GNSS_DEAD_RECKONING ((gps_fix_type_t)0x04)
Definition at line 54 of file gps.h.
GPS_FIX_TYPE_NONE
#define GPS_FIX_TYPE_NONE ((gps_fix_type_t)0x00)
Definition at line 50 of file gps.h.
GPS_FIX_TYPE_TIME_ONLY
#define GPS_FIX_TYPE_TIME_ONLY ((gps_fix_type_t)0x05)
Definition at line 55 of file gps.h.
GPS_FLAG1_CARRIER_PHASE_FIXED
#define GPS_FLAG1_CARRIER_PHASE_FIXED ((gps_flags1_t)0x80)
Definition at line 74 of file gps.h.
GPS_FLAG1_CARRIER_PHASE_FLOAT
#define GPS_FLAG1_CARRIER_PHASE_FLOAT ((gps_flags1_t)0x40)
Definition at line 73 of file gps.h.
GPS_FLAG1_CARRIER_PHASE_MASK
#define GPS_FLAG1_CARRIER_PHASE_MASK ((gps_flags1_t)0xC0)
Definition at line 71 of file gps.h.
GPS_FLAG1_CARRIER_PHASE_NONE
#define GPS_FLAG1_CARRIER_PHASE_NONE ((gps_flags1_t)0x00)
Definition at line 72 of file gps.h.
GPS_FLAG1_DIFF_SOLN
#define GPS_FLAG1_DIFF_SOLN ((gps_flags1_t)0x02)
Definition at line 60 of file gps.h.
GPS_FLAG1_GNSS_FIX_OK
#define GPS_FLAG1_GNSS_FIX_OK ((gps_flags1_t)0x01)
Definition at line 59 of file gps.h.
GPS_FLAG1_HEADING_VALID
#define GPS_FLAG1_HEADING_VALID ((gps_flags1_t)0x20)
Definition at line 70 of file gps.h.
GPS_FLAG1_PSM_ACQUIRED
#define GPS_FLAG1_PSM_ACQUIRED ((gps_flags1_t)0x08)
Definition at line 65 of file gps.h.
GPS_FLAG1_PSM_ENABLED
#define GPS_FLAG1_PSM_ENABLED ((gps_flags1_t)0x04)
Definition at line 64 of file gps.h.
GPS_FLAG1_PSM_INACTIVE
#define GPS_FLAG1_PSM_INACTIVE ((gps_flags1_t)0x14)
Definition at line 68 of file gps.h.
GPS_FLAG1_PSM_MASK
#define GPS_FLAG1_PSM_MASK ((gps_flags1_t)0x1C)
Definition at line 62 of file gps.h.
GPS_FLAG1_PSM_OFF
#define GPS_FLAG1_PSM_OFF ((gps_flags1_t)0x00)
Definition at line 63 of file gps.h.
GPS_FLAG1_PSM_POWER_OPTIMIZED
#define GPS_FLAG1_PSM_POWER_OPTIMIZED ((gps_flags1_t)0x10)
Definition at line 67 of file gps.h.
GPS_FLAG1_PSM_TRACKING
#define GPS_FLAG1_PSM_TRACKING ((gps_flags1_t)0x0C)
Definition at line 66 of file gps.h.
GPS_FLAGS2_CONFIRMED_AVAILABLE
#define GPS_FLAGS2_CONFIRMED_AVAILABLE ((gps_flags2_t)0x20)
Definition at line 77 of file gps.h.
GPS_FLAGS2_CONFIRMED_DATE
#define GPS_FLAGS2_CONFIRMED_DATE ((gps_flags2_t)0x40)
Definition at line 78 of file gps.h.
GPS_FLAGS2_CONFIRMED_TIME
#define GPS_FLAGS2_CONFIRMED_TIME ((gps_flags2_t)0x80)
Definition at line 79 of file gps.h.
GPS_RX_BUF_SIZE
#define GPS_RX_BUF_SIZE 100
Definition at line 33 of file gps.h.
GPS_VALID_DATE
#define GPS_VALID_DATE ((gps_valid_flags_t)0x01)
Definition at line 43 of file gps.h.
Referenced by GPS_Decode().
GPS_VALID_FULLY_RESOLVED
#define GPS_VALID_FULLY_RESOLVED ((gps_valid_flags_t)0x04)
Definition at line 45 of file gps.h.
Referenced by GPS_Decode().
GPS_VALID_MAG
#define GPS_VALID_MAG ((gps_valid_flags_t)0x08)
Definition at line 46 of file gps.h.
Referenced by GPS_Decode().
GPS_VALID_TIME
#define GPS_VALID_TIME ((gps_valid_flags_t)0x02)
Definition at line 44 of file gps.h.
Referenced by GPS_Decode().
UBX_NAV_PVT_CLASS
#define UBX_NAV_PVT_CLASS 0x01
Definition at line 38 of file gps.h.
Referenced by is_valid_header().
UBX_NAV_PVT_HEADER_B0
#define UBX_NAV_PVT_HEADER_B0 0xB5
Definition at line 36 of file gps.h.
Referenced by is_valid_header().
UBX_NAV_PVT_HEADER_B1
#define UBX_NAV_PVT_HEADER_B1 0x62
Definition at line 37 of file gps.h.
Referenced by is_valid_header().
UBX_NAV_PVT_MSG_ID
#define UBX_NAV_PVT_MSG_ID 0x07
Definition at line 39 of file gps.h.
Referenced by is_valid_header().
Typedef Documentation
gps_fix_type_t
typedef uint8_t gps_fix_type_t
Definition at line 49 of file gps.h.
gps_flags1_t
typedef uint8_t gps_flags1_t
Definition at line 58 of file gps.h.
gps_flags2_t
typedef uint8_t gps_flags2_t
Definition at line 76 of file gps.h.
gps_valid_flags_t
typedef uint8_t gps_valid_flags_t
Definition at line 42 of file gps.h.
Function Documentation
bytes_to_int16()
static int16_t bytes_to_int16 (uint8_t b0, uint8_t b1) inline static
Definition at line 147 of file gps.h.
Referenced by GPS_Decode().
bytes_to_int32()
static int32_t bytes_to_int32 (uint8_t b0, uint8_t b1, uint8_t b2, uint8_t b3) inline static
Definition at line 134 of file gps.h.
Referenced by GPS_Decode().
bytes_to_uint16()
static uint16_t bytes_to_uint16 (uint8_t b0, uint8_t b1) inline static
Definition at line 143 of file gps.h.
Referenced by GPS_Decode().
bytes_to_uint32()
static uint32_t bytes_to_uint32 (uint8_t b0, uint8_t b1, uint8_t b2, uint8_t b3) inline static
Definition at line 139 of file gps.h.
Referenced by GPS_Decode().
GPS_Decode()
bool GPS_Decode (GPS_Handle_t * gps)
Function to decode periodic GPS UBX message.
Parameters
GPS Handle for GPS configuration and data
Returns
true Parsing successful
false Parsing failed
Definition at line 10 of file gps.c.
References bytes_to_int16(), bytes_to_int32(), bytes_to_uint16(), bytes_to_uint32(), GPS_Handle_t::data, NAV_PVT_t::day, NAV_PVT_t::fixType, NAV_PVT_t::flags1, NAV_PVT_t::flags2, GPS_FIX_TYPE_GNSS_2D, GPS_FIX_TYPE_GNSS_3D, GPS_Handle_t::gps_rx_buffer, GPS_VALID_DATE, GPS_VALID_FULLY_RESOLVED, GPS_VALID_MAG, GPS_VALID_TIME, NAV_PVT_t::groundSpeed, GPS_Handle_t::hasGNSSFix, NAV_PVT_t::headingMotion, NAV_PVT_t::headingVehicle, NAV_PVT_t::height, NAV_PVT_t::heightMSL, NAV_PVT_t::horizontalAccuracy, NAV_PVT_t::hour, is_valid_header(), GPS_Handle_t::isFullyResolved, GPS_Handle_t::isValidDate, GPS_Handle_t::isValidMag, GPS_Handle_t::isValidTime, NAV_PVT_t::iTOW, NAV_PVT_t::latitude, NAV_PVT_t::longitude, NAV_PVT_t::magneticAcc, NAV_PVT_t::magneticDec, NAV_PVT_t::minute, NAV_PVT_t::month, NAV_PVT_t::nano, NAV_PVT_t::numSatellites, NAV_PVT_t::positionDOP, NAV_PVT_t::reserved, rx_buffer, NAV_PVT_t::second, NAV_PVT_t::speedAccuracy, NAV_PVT_t::timeAccuracy, NAV_PVT_t::valid, NAV_PVT_t::velDown, NAV_PVT_t::velEast, NAV_PVT_t::velNorth, NAV_PVT_t::verticalAccuracy, and NAV_PVT_t::year.
is_valid_header()
static bool is_valid_header (uint8_t sync0, uint8_t sync1, uint8_t class_id, uint8_t msg_id) inline static
Definition at line 152 of file gps.h.
References UBX_NAV_PVT_CLASS, UBX_NAV_PVT_HEADER_B0, UBX_NAV_PVT_HEADER_B1, and UBX_NAV_PVT_MSG_ID.
Referenced by GPS_Decode().