PER Firmware: common/gps/gps.c File Reference
gps.c File Reference
GPS driver for UBLOX NEO-M9N GPS module.
#include "gps.h"
Functions
bool GPS_Decode (GPS_Handle_t *gps)
Function to decode periodic GPS UBX message.
Detailed Description
GPS driver for UBLOX NEO-M9N GPS module.
Author
Irving Wang (irvin.nosp@m.gw@p.nosp@m.urdue.nosp@m..edu)
Definition in file gps.c.
Function Documentation
GPS_Decode()
bool GPS_Decode (GPS_Handle_t * gps)
Function to decode periodic GPS UBX message.
Parameters
GPS Handle for GPS configuration and data
Returns
true Parsing successful
false Parsing failed
Definition at line 10 of file gps.c.
References bytes_to_int16(), bytes_to_int32(), bytes_to_uint16(), bytes_to_uint32(), GPS_Handle_t::data, NAV_PVT_t::day, NAV_PVT_t::fixType, NAV_PVT_t::flags1, NAV_PVT_t::flags2, GPS_FIX_TYPE_GNSS_2D, GPS_FIX_TYPE_GNSS_3D, GPS_Handle_t::gps_rx_buffer, GPS_VALID_DATE, GPS_VALID_FULLY_RESOLVED, GPS_VALID_MAG, GPS_VALID_TIME, NAV_PVT_t::groundSpeed, GPS_Handle_t::hasGNSSFix, NAV_PVT_t::headingMotion, NAV_PVT_t::headingVehicle, NAV_PVT_t::height, NAV_PVT_t::heightMSL, NAV_PVT_t::horizontalAccuracy, NAV_PVT_t::hour, is_valid_header(), GPS_Handle_t::isFullyResolved, GPS_Handle_t::isValidDate, GPS_Handle_t::isValidMag, GPS_Handle_t::isValidTime, NAV_PVT_t::iTOW, NAV_PVT_t::latitude, NAV_PVT_t::longitude, NAV_PVT_t::magneticAcc, NAV_PVT_t::magneticDec, NAV_PVT_t::minute, NAV_PVT_t::month, NAV_PVT_t::nano, NAV_PVT_t::numSatellites, NAV_PVT_t::positionDOP, NAV_PVT_t::reserved, rx_buffer, NAV_PVT_t::second, NAV_PVT_t::speedAccuracy, NAV_PVT_t::timeAccuracy, NAV_PVT_t::valid, NAV_PVT_t::velDown, NAV_PVT_t::velEast, NAV_PVT_t::velNorth, NAV_PVT_t::verticalAccuracy, and NAV_PVT_t::year.