PER Firmware: common/heartbeat/heartbeat.h File Reference
heartbeat.h File Reference
Shared heartbeat task implementation for status LEDs.
#include "common/phal/gpio.h"
#include "common/freertos/freertos.h"
Data Structures
struct status_leds_t
Macros
#define DEFINE_HEARTBEAT_TASK(PREFLIGHT_CALLBACK)
Macro to define a heartbeat task with predefined behavior for status LEDs.
#define START_HEARTBEAT_TASK()
Enumerations
enum heartbeat_state_t : uint8_t { HEARTBEAT_STATE_PREFLIGHT , HEARTBEAT_STATE_NORMAL }
Functions
void heartbeat_task (status_leds_t *leds)
Variables
static constexpr uint32_t PREFLIGHT_DURATION_MS = 1500
static constexpr uint32_t HEARTBEAT_PERIOD_MS = 100
static constexpr uint32_t CONN_LED_TIMEOUT_MS = 1000
Detailed Description
Shared heartbeat task implementation for status LEDs.
Author
Irving Wang (irvin.nosp@m.gw@p.nosp@m.urdue.nosp@m..edu)
Definition in file heartbeat.h.
Macro Definition Documentation
DEFINE_HEARTBEAT_TASK
#define DEFINE_HEARTBEAT_TASK (PREFLIGHT_CALLBACK)
Value:
    status_leds_t status_leds = { \
        .heartbeat_port = HEARTBEAT_LED_PORT, \
        .heartbeat_pin = HEARTBEAT_LED_PIN, \
        .connection_port = CONNECTION_LED_PORT, \
        .connection_pin = CONNECTION_LED_PIN, \
        .error_port = ERROR_LED_PORT, \
        .error_pin = ERROR_LED_PIN, \
        .preflight_callback = (PREFLIGHT_CALLBACK), \
        .state = HEARTBEAT_STATE_PREFLIGHT \
    }; \
    void heartbeat_wrapper(void) { heartbeat_task(&status_leds); }; \
    DEFINE_TASK(heartbeat_wrapper, HEARTBEAT_PERIOD_MS, osPriorityLow, STACK_512)
Macro to define a heartbeat task with predefined behavior for status LEDs.
Usage:
Ensure that the macros HEARTBEAT_LED_PORT, HEARTBEAT_LED_PIN, CONNECTION_LED_PORT, CONNECTION_LED_PIN, ERROR_LED_PORT, and ERROR_LED_PIN are defined
Init the GPIOS for the LEDs as outputs.
Call DEFINE_HEARTBEAT_TASK() in your source file to define the task.
Call START_HEARTBEAT_TASK() in your main function after initializing the kernel to start the task.
Parameters
PREFLIGHT_CALLBACK optional callback function periodically called during the preflight state.
Definition at line 47 of file heartbeat.h.
START_HEARTBEAT_TASK
#define START_HEARTBEAT_TASK ()
Value:
START_TASK(heartbeat_wrapper)
Definition at line 61 of file heartbeat.h.
Referenced by main(), and main().
Enumeration Type Documentation
heartbeat_state_t
enum heartbeat_state_t : uint8_t
Enumerator
HEARTBEAT_STATE_PREFLIGHT
HEARTBEAT_STATE_NORMAL
Definition at line 18 of file heartbeat.h.
Function Documentation
heartbeat_task()
void heartbeat_task (status_leds_t * leds) extern
Definition at line 34 of file heartbeat.c.
References CONN_LED_TIMEOUT_MS, status_leds_t::connection_pin, status_leds_t::connection_port, status_leds_t::error_pin, status_leds_t::error_port, getTick, status_leds_t::heartbeat_pin, status_leds_t::heartbeat_port, HEARTBEAT_STATE_NORMAL, HEARTBEAT_STATE_PREFLIGHT, last_can_rx_time_ms, PHAL_toggleGPIO(), PHAL_writeGPIO(), status_leds_t::preflight_callback, PREFLIGHT_DURATION_MS, preflight_led_sweep(), and status_leds_t::state.
Variable Documentation
CONN_LED_TIMEOUT_MS
uint32_t CONN_LED_TIMEOUT_MS = 1000 static constexpr
Definition at line 16 of file heartbeat.h.
Referenced by heartbeat_task().
HEARTBEAT_PERIOD_MS
uint32_t HEARTBEAT_PERIOD_MS = 100 static constexpr
Definition at line 15 of file heartbeat.h.
PREFLIGHT_DURATION_MS
uint32_t PREFLIGHT_DURATION_MS = 1500 static constexpr
Definition at line 14 of file heartbeat.h.
Referenced by heartbeat_task().