PER Firmware: common/phal_L4/i2c_alt/i2c_alt.c File Reference
i2c_alt.c File Reference
#include "common/phal_L4/i2c_alt/i2c_alt.h"
Functions
static void I2C_IRQHandler (I2C_TypeDef *instance)
static int gen_start (I2C_TypeDef *instance, uint8_t addr, uint8_t len, bool read)
static void i2c_unmask_irq (I2C_TypeDef *instance)
static void i2c_mask_irq (I2C_TypeDef *instance)
int PHAL_I2C_init (I2C_TypeDef *instance, i2c_handle_t *handle, uint32_t freq, const uint32_t fck)
int PHAL_I2C_write_a (I2C_TypeDef *instance, uint8_t addr, const uint8_t *data, uint8_t len, bool stop, bool force)
int PHAL_I2C_read_a (I2C_TypeDef *instance, uint8_t addr, uint8_t *data, uint8_t len, bool stop, bool force)
int PHAL_I2C_stop (I2C_TypeDef *instance)
int PHAL_I2C_check_state (void)
void DMA1_Channel6_IRQHandler ()
void DMA1_Channel7_IRQHandler ()
void I2C1_EV_IRQHandler ()
void I2C3_EV_IRQHandler ()
Variables
i2c_handle_t * core
Function Documentation
DMA1_Channel6_IRQHandler()
void DMA1_Channel6_IRQHandler ()
Definition at line 164 of file i2c_alt.c.
DMA1_Channel7_IRQHandler()
void DMA1_Channel7_IRQHandler (void)
Definition at line 176 of file i2c_alt.c.
gen_start()
static int gen_start (I2C_TypeDef * instance, uint8_t addr, uint8_t len, bool read) static
Definition at line 239 of file i2c_alt.c.
References addr.
Referenced by PHAL_I2C_read_a(), and PHAL_I2C_write_a().
I2C1_EV_IRQHandler()
void I2C1_EV_IRQHandler ()
Definition at line 188 of file i2c_alt.c.
References I2C_IRQHandler().
I2C3_EV_IRQHandler()
void I2C3_EV_IRQHandler ()
Definition at line 192 of file i2c_alt.c.
References I2C_IRQHandler().
I2C_IRQHandler()
static void I2C_IRQHandler (I2C_TypeDef * instance) static
Definition at line 196 of file i2c_alt.c.
References i2c_handle_t::_rx_busy, i2c_handle_t::_tx_busy, core, E_ARLO, E_BAD_BUSY, E_BERR, E_NACK, i2c_handle_t::err_idx, i2c_handle_t::error, MAX_ERR, PHAL_I2C_stop(), and i2c_handle_t::stop.
Referenced by I2C1_EV_IRQHandler(), and I2C3_EV_IRQHandler().
i2c_mask_irq()
static void i2c_mask_irq (I2C_TypeDef * instance) static
Definition at line 266 of file i2c_alt.c.
i2c_unmask_irq()
static void i2c_unmask_irq (I2C_TypeDef * instance) static
Definition at line 250 of file i2c_alt.c.
Referenced by PHAL_I2C_init().
PHAL_I2C_check_state()
int PHAL_I2C_check_state (void)
Definition at line 160 of file i2c_alt.c.
References i2c_handle_t::_rx_busy, i2c_handle_t::_tx_busy, core, and E_BUSY.
PHAL_I2C_init()
int PHAL_I2C_init (I2C_TypeDef * instance, i2c_handle_t * handle, uint32_t freq, const uint32_t fck)
Definition at line 11 of file i2c_alt.c.
References core, E_CONFIG, i2c_unmask_irq(), PHAL_initDMA(), i2c_handle_t::rx_dma_cfg, and i2c_handle_t::tx_dma_cfg.
PHAL_I2C_read_a()
int PHAL_I2C_read_a (I2C_TypeDef * instance, uint8_t addr, uint8_t * data, uint8_t len, bool stop, bool force)
Definition at line 117 of file i2c_alt.c.
References i2c_handle_t::_rx_busy, addr, core, E_BUSY, gen_start(), PHAL_DMA_setMemAddress(), PHAL_DMA_setTxferLength(), PHAL_I2C_stop(), PHAL_startTxfer(), PHAL_stopTxfer(), i2c_handle_t::rx_dma_cfg, and i2c_handle_t::stop.
PHAL_I2C_stop()
int PHAL_I2C_stop (I2C_TypeDef * instance)
Definition at line 153 of file i2c_alt.c.
References i2c_handle_t::_rx_busy, i2c_handle_t::_tx_busy, and core.
Referenced by I2C_IRQHandler(), PHAL_I2C_read_a(), and PHAL_I2C_write_a().
PHAL_I2C_write_a()
int PHAL_I2C_write_a (I2C_TypeDef * instance, uint8_t addr, const uint8_t * data, uint8_t len, bool stop, bool force)
Definition at line 81 of file i2c_alt.c.
References i2c_handle_t::_tx_busy, addr, core, E_BUSY, gen_start(), PHAL_DMA_setMemAddress(), PHAL_DMA_setTxferLength(), PHAL_I2C_stop(), PHAL_startTxfer(), PHAL_stopTxfer(), i2c_handle_t::stop, and i2c_handle_t::tx_dma_cfg.
Variable Documentation
core
i2c_handle_t* core
Definition at line 9 of file i2c_alt.c.
Referenced by I2C_IRQHandler(), PHAL_I2C_check_state(), PHAL_I2C_init(), PHAL_I2C_read_a(), PHAL_I2C_stop(), and PHAL_I2C_write_a().