PER Firmware: source/g4_testing/izze_imu_config.c File Reference
izze_imu_config.c File Reference
#include "g4_testing.h"
#include "common/can_library/generated/G4_TESTING.h"
#include "common/phal/can.h"
#include "common/phal/gpio.h"
#include "common/phal/rcc.h"
#include "common/freertos/freertos.h"
#include "common/izze_imu/izze_imu.h"
Macros
#define HEARTBEAT_LED_PORT (GPIOB)
#define HEARTBEAT_LED_PIN (4)
#define ERROR_LED_PORT (GPIOA)
#define ERROR_LED_PIN (15)
#define CONNECTION_LED_PORT (GPIOB)
#define CONNECTION_LED_PIN (3)
#define TargetCoreClockrateHz 16'000'000
Functions
void HardFault_Handler ()
void config_imu ()
DEFINE_TASK (CAN_rx_update, 0, osPriorityHigh, STACK_2048)
DEFINE_TASK (CAN_tx_update, 2, osPriorityNormal, STACK_2048)
DEFINE_TASK (config_imu, IZZE_IMU_CONFIG_PERIOD_MS, osPriorityNormal, 1024)
int main ()
Variables
GPIOInitConfig_t gpio_config []
ClockRateConfig_t clock_config
uint32_t APB1ClockRateHz
uint32_t APB2ClockRateHz
uint32_t AHBClockRateHz
uint32_t PLLClockRateHz
static constexpr uint16_t NEW_CAN_BASE_ID = 0x4EE
static constexpr uint32_t IMU_CONFIG_TIME_MS = 12'000
Macro Definition Documentation
CONNECTION_LED_PIN
#define CONNECTION_LED_PIN (3)
Definition at line 17 of file izze_imu_config.c.
Referenced by config_imu(), and main().
CONNECTION_LED_PORT
#define CONNECTION_LED_PORT (GPIOB)
Definition at line 16 of file izze_imu_config.c.
Referenced by config_imu(), and main().
ERROR_LED_PIN
#define ERROR_LED_PIN (15)
Definition at line 15 of file izze_imu_config.c.
Referenced by HardFault_Handler(), and main().
ERROR_LED_PORT
#define ERROR_LED_PORT (GPIOA)
Definition at line 14 of file izze_imu_config.c.
Referenced by HardFault_Handler(), and main().
HEARTBEAT_LED_PIN
#define HEARTBEAT_LED_PIN (4)
Definition at line 13 of file izze_imu_config.c.
Referenced by config_imu(), and main().
HEARTBEAT_LED_PORT
#define HEARTBEAT_LED_PORT (GPIOB)
Definition at line 12 of file izze_imu_config.c.
Referenced by config_imu(), and main().
TargetCoreClockrateHz
#define TargetCoreClockrateHz 16'000'000
Definition at line 27 of file izze_imu_config.c.
Function Documentation
config_imu()
void config_imu ()
Definition at line 51 of file izze_imu_config.c.
References ACCEL_SCALE_2G, BIT_RATE_1MBPS, CONNECTION_LED_PIN, CONNECTION_LED_PORT, GYRO_SCALE_250DPS, HEARTBEAT_LED_PIN, HEARTBEAT_LED_PORT, IMU_CONFIG_TIME_MS, IZZE_IMU_PROGRAMMING_CONSTANT, NEW_CAN_BASE_ID, ODR_104HZ, PHAL_toggleGPIO(), and PHAL_writeGPIO().
Referenced by main().
DEFINE_TASK() [1/3]
DEFINE_TASK (CAN_rx_update , 0 , osPriorityHigh , STACK_2048)
DEFINE_TASK() [2/3]
DEFINE_TASK (CAN_tx_update , 2 , osPriorityNormal , STACK_2048)
DEFINE_TASK() [3/3]
DEFINE_TASK (config_imu , IZZE_IMU_CONFIG_PERIOD_MS , osPriorityNormal , 1024)
HardFault_Handler()
void HardFault_Handler (void)
Definition at line 103 of file izze_imu_config.c.
References ERROR_LED_PIN, and ERROR_LED_PORT.
Referenced by main().
main()
int main (void)
Definition at line 70 of file izze_imu_config.c.
References CAN_library_init(), CAN_rx_update(), CAN_tx_update(), clock_config, config_imu(), CONNECTION_LED_PIN, CONNECTION_LED_PORT, ERROR_LED_PIN, ERROR_LED_PORT, gpio_config, HardFault_Handler(), HEARTBEAT_LED_PIN, HEARTBEAT_LED_PORT, PHAL_configureClockRates(), PHAL_FDCAN_init(), PHAL_initGPIO(), PHAL_writeGPIO(), and START_TASK.
Variable Documentation
AHBClockRateHz
uint32_t AHBClockRateHz extern
Definition at line 17 of file rcc.c.
APB1ClockRateHz
uint32_t APB1ClockRateHz extern
Definition at line 15 of file rcc.c.
APB2ClockRateHz
uint32_t APB2ClockRateHz extern
Definition at line 16 of file rcc.c.
clock_config
ClockRateConfig_t clock_config
Initial value:
= {
    .clock_source              = CLOCK_SOURCE_HSI,
    .use_pll                   = false,
    .vco_output_rate_target_hz = 16'000'000,
    .system_clock_target_hz    = 16'000'000 ,
    .ahb_clock_target_hz       = ( 16'000'000 / 1),
    .apb1_clock_target_hz      = ( 16'000'000 / (1)),
    .apb2_clock_target_hz      = ( 16'000'000 / (1)),
}
Definition at line 28 of file izze_imu_config.c.
Referenced by main().
gpio_config
GPIOInitConfig_t gpio_config[]
Initial value:
= {
    GPIO_INIT_OUTPUT( (GPIOB) , (4) , GPIO_OUTPUT_LOW_SPEED),
    GPIO_INIT_OUTPUT( (GPIOA) , (15) , GPIO_OUTPUT_LOW_SPEED),
    GPIO_INIT_OUTPUT( (GPIOB) , (3) , GPIO_OUTPUT_LOW_SPEED),
    GPIO_INIT_FDCAN2RX_PB12,
    GPIO_INIT_FDCAN2TX_PB13
}
Definition at line 19 of file izze_imu_config.c.
Referenced by main().
IMU_CONFIG_TIME_MS
uint32_t IMU_CONFIG_TIME_MS = 12'000 static constexpr
Definition at line 50 of file izze_imu_config.c.
Referenced by config_imu().
NEW_CAN_BASE_ID
uint16_t NEW_CAN_BASE_ID = 0x4EE static constexpr
Definition at line 45 of file izze_imu_config.c.
Referenced by config_imu().
PLLClockRateHz
uint32_t PLLClockRateHz extern
Definition at line 18 of file rcc.c.