PER Firmware: source/dashboard/lcd/lcd.h File Reference
lcd.h File Reference
LCD display management.
#include "common_defs.h"
Data Structures
struct page_handler_t
Macros
#define PREFLIGHT_STRING "preflight"
#define RACE_STRING "race"
#define CALIBRATION_STRING "calibration"
#define FAULT_STRING "fault"
#define FAULT1_BUTTON "ERROR1"
#define FAULT2_BUTTON "ERROR2"
#define FAULT3_BUTTON "ERROR3"
#define FAULT4_BUTTON "ERROR4"
#define FAULT5_BUTTON "ERROR5"
#define FAULT6_BUTTON "ERROR6"
#define FAULT7_BUTTON "ERROR7"
#define FAULT8_BUTTON "ERROR8"
#define FAULT1_TXT "ERROR1"
#define FAULT2_TXT "ERROR2"
#define FAULT3_TXT "ERROR3"
#define FAULT4_TXT "ERROR4"
#define FAULT5_TXT "ERROR5"
#define FAULT6_TXT "ERROR6"
#define FAULT7_TXT "ERROR7"
#define FAULT8_TXT "ERROR8"
#define FAULT_NONE_STRING "NONE\0"
#define THROT_BAR "throt"
#define BRK_BAR "brake"
#define RGN_BAR "regen"
#define FL_BAR "FL"
#define FR_BAR "FR"
#define RL_BAR "RL"
#define RR_BAR "RR"
#define PUMP_CHECK "pump"
#define BATT_TEMP "BTemp"
#define BATT_VOLT "volt"
#define BATT_CURR "amp"
#define MOT_TEMP "MTemp"
#define MC_TEMP "IGBTemp"
#define CAR_STAT "stat"
#define SPEED "speed"
#define RACE_TV_ON "tv"
#define CURRENT_TIME "current"
#define BEST_TIME "best"
#define LAP_TIME "lap"
#define CALIBRATION_THROTTLE1 "thr1"
#define CALIBRATION_THROTTLE2 "thr2"
#define CALIBRATION_BRAKE1 "brk1"
#define CALIBRATION_BRAKE2 "brk2"
#define CALIBRATION_BRAKE_PRS1 "brkprs1"
#define CALIBRATION_BRAKE_PRS2 "brkprs2"
#define CALIBRATION_STATUS "status"
Enumerations
enum page_t : uint8_t {
PAGE_PREFLIGHT = 0 , PAGE_RACE = 1 , PAGE_CALIBRATION = 2 , PAGE_FAULTS = 3 ,
NUM_PAGES = 4
}
Functions
void initLCD ()
void updatePage ()
Updates LCD display page.
void advancePage ()
Advances to the next selectable page.
void backPage ()
Moves to the previous selectable page.
void moveUp ()
void moveDown ()
void selectItem ()
void updateFaultDisplay ()
Updates fault messages on LCD screen based on priority and timing.
void updateTelemetryPages ()
Updates current telemetry page by calling its handler if available.
void sendTVParameters ()
void sendCoolingParameters ()
void sendLoggingParameters ()
Variables
constexpr float WHEEL_RADIUS_IN = 8.0f
constexpr float GEAR_RATIO = 12.51f
constexpr float WHEEL_CIRCUMFERENCE_IN = 2.0f * PI * WHEEL_RADIUS_IN
constexpr float OUTPUT_REV_PER_MOTOR_REV = 1.0f / GEAR_RATIO
constexpr float INCHES_PER_MOTOR_REV = WHEEL_CIRCUMFERENCE_IN * OUTPUT_REV_PER_MOTOR_REV
constexpr float MINUTES_PER_HOUR = 60.0f
constexpr float INCHES_PER_MILE = 63360.0f
static constexpr float RPM_TO_MPH = INCHES_PER_MOTOR_REV * MINUTES_PER_HOUR / INCHES_PER_MILE
Detailed Description
LCD display management.
Author
Irving Wang (irvin.nosp@m.gw@p.nosp@m.urdue.nosp@m..edu)
Definition in file lcd.h.
Macro Definition Documentation
BATT_CURR
#define BATT_CURR "amp"
Definition at line 62 of file lcd.h.
Referenced by raceTelemetryUpdate().
BATT_TEMP
#define BATT_TEMP "BTemp"
Definition at line 60 of file lcd.h.
Referenced by raceTelemetryUpdate().
BATT_VOLT
#define BATT_VOLT "volt"
Definition at line 61 of file lcd.h.
Referenced by raceTelemetryUpdate().
BEST_TIME
#define BEST_TIME "best"
Definition at line 69 of file lcd.h.
BRK_BAR
#define BRK_BAR "brake"
Definition at line 53 of file lcd.h.
Referenced by raceTelemetryUpdate().
CALIBRATION_BRAKE1
#define CALIBRATION_BRAKE1 "brk1"
Definition at line 75 of file lcd.h.
Referenced by calibrationTelemetryUpdate().
CALIBRATION_BRAKE2
#define CALIBRATION_BRAKE2 "brk2"
Definition at line 76 of file lcd.h.
Referenced by calibrationTelemetryUpdate().
CALIBRATION_BRAKE_PRS1
#define CALIBRATION_BRAKE_PRS1 "brkprs1"
Definition at line 77 of file lcd.h.
Referenced by calibrationTelemetryUpdate().
CALIBRATION_BRAKE_PRS2
#define CALIBRATION_BRAKE_PRS2 "brkprs2"
Definition at line 78 of file lcd.h.
Referenced by calibrationTelemetryUpdate().
CALIBRATION_STATUS
#define CALIBRATION_STATUS "status"
Definition at line 79 of file lcd.h.
Referenced by calibrationTelemetryUpdate().
CALIBRATION_STRING
#define CALIBRATION_STRING "calibration"
Definition at line 16 of file lcd.h.
Referenced by updatePage().
CALIBRATION_THROTTLE1
#define CALIBRATION_THROTTLE1 "thr1"
Definition at line 73 of file lcd.h.
Referenced by calibrationTelemetryUpdate().
CALIBRATION_THROTTLE2
#define CALIBRATION_THROTTLE2 "thr2"
Definition at line 74 of file lcd.h.
Referenced by calibrationTelemetryUpdate().
CAR_STAT
#define CAR_STAT "stat"
Definition at line 65 of file lcd.h.
Referenced by style_car_stat().
CURRENT_TIME
#define CURRENT_TIME "current"
Definition at line 68 of file lcd.h.
FAULT1_BUTTON
#define FAULT1_BUTTON "ERROR1"
Definition at line 33 of file lcd.h.
FAULT1_TXT
#define FAULT1_TXT "ERROR1"
Definition at line 41 of file lcd.h.
FAULT2_BUTTON
#define FAULT2_BUTTON "ERROR2"
Definition at line 34 of file lcd.h.
FAULT2_TXT
#define FAULT2_TXT "ERROR2"
Definition at line 42 of file lcd.h.
FAULT3_BUTTON
#define FAULT3_BUTTON "ERROR3"
Definition at line 35 of file lcd.h.
FAULT3_TXT
#define FAULT3_TXT "ERROR3"
Definition at line 43 of file lcd.h.
FAULT4_BUTTON
#define FAULT4_BUTTON "ERROR4"
Definition at line 36 of file lcd.h.
FAULT4_TXT
#define FAULT4_TXT "ERROR4"
Definition at line 44 of file lcd.h.
FAULT5_BUTTON
#define FAULT5_BUTTON "ERROR5"
Definition at line 37 of file lcd.h.
FAULT5_TXT
#define FAULT5_TXT "ERROR5"
Definition at line 45 of file lcd.h.
FAULT6_BUTTON
#define FAULT6_BUTTON "ERROR6"
Definition at line 38 of file lcd.h.
FAULT6_TXT
#define FAULT6_TXT "ERROR6"
Definition at line 46 of file lcd.h.
FAULT7_BUTTON
#define FAULT7_BUTTON "ERROR7"
Definition at line 39 of file lcd.h.
FAULT7_TXT
#define FAULT7_TXT "ERROR7"
Definition at line 47 of file lcd.h.
FAULT8_BUTTON
#define FAULT8_BUTTON "ERROR8"
Definition at line 40 of file lcd.h.
FAULT8_TXT
#define FAULT8_TXT "ERROR8"
Definition at line 48 of file lcd.h.
FAULT_NONE_STRING
#define FAULT_NONE_STRING "NONE\0"
Definition at line 49 of file lcd.h.
FAULT_STRING
#define FAULT_STRING "fault"
Definition at line 17 of file lcd.h.
Referenced by updatePage().
FL_BAR
#define FL_BAR "FL"
Definition at line 55 of file lcd.h.
FR_BAR
#define FR_BAR "FR"
Definition at line 56 of file lcd.h.
LAP_TIME
#define LAP_TIME "lap"
Definition at line 70 of file lcd.h.
MC_TEMP
#define MC_TEMP "IGBTemp"
Definition at line 64 of file lcd.h.
Referenced by raceTelemetryUpdate().
MOT_TEMP
#define MOT_TEMP "MTemp"
Definition at line 63 of file lcd.h.
Referenced by raceTelemetryUpdate().
PREFLIGHT_STRING
#define PREFLIGHT_STRING "preflight"
Definition at line 14 of file lcd.h.
PUMP_CHECK
#define PUMP_CHECK "pump"
Definition at line 59 of file lcd.h.
RACE_STRING
#define RACE_STRING "race"
Definition at line 15 of file lcd.h.
Referenced by updatePage().
RACE_TV_ON
#define RACE_TV_ON "tv"
Definition at line 67 of file lcd.h.
RGN_BAR
#define RGN_BAR "regen"
Definition at line 54 of file lcd.h.
RL_BAR
#define RL_BAR "RL"
Definition at line 57 of file lcd.h.
RR_BAR
#define RR_BAR "RR"
Definition at line 58 of file lcd.h.
SPEED
#define SPEED "speed"
Definition at line 66 of file lcd.h.
Referenced by raceTelemetryUpdate().
THROT_BAR
#define THROT_BAR "throt"
Definition at line 52 of file lcd.h.
Referenced by raceTelemetryUpdate().
Enumeration Type Documentation
page_t
enum page_t : uint8_t
Enumerator
PAGE_PREFLIGHT
PAGE_RACE
PAGE_CALIBRATION
PAGE_FAULTS
NUM_PAGES
Definition at line 81 of file lcd.h.
Function Documentation
advancePage()
void advancePage ()
Advances to the next selectable page.
Definition at line 149 of file lcd.c.
References curr_page, current_page_index, NUM_SELECTABLE_PAGES, selectable_pages, and updatePage().
Referenced by service_button_inputs().
backPage()
void backPage ()
Moves to the previous selectable page.
Definition at line 158 of file lcd.c.
References curr_page, current_page_index, NUM_SELECTABLE_PAGES, selectable_pages, and updatePage().
Referenced by service_button_inputs().
initLCD()
void initLCD ()
moveDown()
void moveDown ()
Definition at line 216 of file lcd.c.
References curr_page, page_handler_t::move_down, NUM_PAGES, and page_handlers.
Referenced by service_button_inputs().
moveUp()
void moveUp ()
Definition at line 205 of file lcd.c.
References curr_page, page_handler_t::move_up, NUM_PAGES, and page_handlers.
Referenced by service_button_inputs().
selectItem()
void selectItem ()
Definition at line 227 of file lcd.c.
References curr_page, NUM_PAGES, page_handlers, and page_handler_t::select.
Referenced by service_button_inputs().
sendCoolingParameters()
void sendCoolingParameters ()
sendLoggingParameters()
void sendLoggingParameters ()
sendTVParameters()
void sendTVParameters ()
updateFaultDisplay()
void updateFaultDisplay ()
Updates fault messages on LCD screen based on priority and timing.
Manages fault display rotation, processes new faults from queue, and updates screen according to fault priorities and display timing requirements.
Definition at line 293 of file lcd.c.
updatePage()
void updatePage ()
Updates LCD display page.
Key behaviors:
Maintains display of error pages when active
Definition at line 170 of file lcd.c.
References CALIBRATION_STRING, curr_page, FAULT_STRING, NUM_PAGES, NXT_setPage(), PAGE_CALIBRATION, PAGE_FAULTS, page_handlers, PAGE_RACE, prev_page, RACE_STRING, and page_handler_t::update.
Referenced by advancePage(), backPage(), LCD_init(), and service_button_inputs().
updateTelemetryPages()
void updateTelemetryPages ()
Updates current telemetry page by calling its handler if available.
Definition at line 241 of file lcd.c.
References curr_page, NUM_PAGES, page_handlers, and page_handler_t::telemetry.
Referenced by main().
Variable Documentation
GEAR_RATIO
float GEAR_RATIO = 12.51f constexpr
Definition at line 21 of file lcd.h.
INCHES_PER_MILE
float INCHES_PER_MILE = 63360.0f constexpr
Definition at line 28 of file lcd.h.
INCHES_PER_MOTOR_REV
float INCHES_PER_MOTOR_REV = WHEEL_CIRCUMFERENCE_IN * OUTPUT_REV_PER_MOTOR_REV constexpr
Definition at line 25 of file lcd.h.
MINUTES_PER_HOUR
float MINUTES_PER_HOUR = 60.0f constexpr
Definition at line 27 of file lcd.h.
OUTPUT_REV_PER_MOTOR_REV
float OUTPUT_REV_PER_MOTOR_REV = 1.0f / GEAR_RATIO constexpr
Definition at line 24 of file lcd.h.
RPM_TO_MPH
float RPM_TO_MPH = INCHES_PER_MOTOR_REV * MINUTES_PER_HOUR / INCHES_PER_MILE static constexpr
Definition at line 30 of file lcd.h.
WHEEL_CIRCUMFERENCE_IN
float WHEEL_CIRCUMFERENCE_IN = 2.0f * PI * WHEEL_RADIUS_IN constexpr
Definition at line 23 of file lcd.h.
WHEEL_RADIUS_IN
float WHEEL_RADIUS_IN = 8.0f constexpr
Definition at line 20 of file lcd.h.