PER Firmware: source/dashboard/lcd/lcd.c File Reference
lcd.c File Reference
#include "lcd.h"
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include "common/can_library/generated/DASHBOARD.h"
#include "common/can_library/faults_common.h"
#include "common_defs.h"
#include "menu_system.h"
#include "nextion.h"
#include "pedals.h"
#include "main.h"
Functions
void faultsPageUpdate ()
void faultsMoveUp ()
void faultsMoveDown ()
void faultsSelect ()
void updateFaultMessages ()
Updates the display of fault messages on the LCD screen.
void faultsClearButton_CALLBACK ()
Callback function for fault button press that clears faults.
void racePageUpdate ()
void raceSelect ()
void raceUpCallback ()
void raceDownCallback ()
void raceTelemetryUpdate ()
Updates telemetry data on the race dashboard LCD display.
void sdcTelemetryUpdate ()
void faultTelemetryUpdate ()
Updates the color of fault text indicators on the faults page.
void calibrationTelemetryUpdate ()
Updates the LCD display with current pedal telemetry data when on CALIBRATION page.
void updateSDCStatus (uint8_t status, char *element)
Updates the background color of an LCD element based on status.
void set_faultIndicator (uint16_t fault, char *element)
Sets the color of a fault indicator element based on fault status.
void LCD_init (uint32_t baud_rate)
void advancePage ()
Advances to the next selectable page.
void backPage ()
Moves to the previous selectable page.
void updatePage ()
Updates LCD display page.
void moveUp ()
void moveDown ()
void selectItem ()
void updateTelemetryPages ()
Updates current telemetry page by calling its handler if available.
void updateFaultDisplay ()
Updates fault messages on LCD screen based on priority and timing.
void clearFault (int index)
Clears a fault from the fault buffer by removing it and shifting remaining faults.
Variables
volatile page_t curr_page
volatile page_t prev_page
char * errorText = nullptr
pedal_values_t pedal_values
q_handle_t q_fault_history
volatile dashboard_input_state_t input_state
const page_handler_t page_handlers []
menu_element_t race_elements []
menu_page_t race_page
menu_element_t faults_elements []
menu_page_t faults_page
Function Documentation
advancePage()
void advancePage ()
Advances to the next selectable page.
Definition at line 124 of file lcd.c.
References updatePage().
Referenced by service_button_inputs().
backPage()
void backPage ()
Moves to the previous selectable page.
Definition at line 132 of file lcd.c.
References updatePage().
Referenced by service_button_inputs().
calibrationTelemetryUpdate()
void calibrationTelemetryUpdate ()
Updates the LCD display with current pedal telemetry data when on CALIBRATION page.
Updates brake and throttle bars, raw ADC values, deviation percentages, and status indicators for brake and throttle pedals. Also displays fault statuses if detected.
Note
Only executes when current page is PAGE_CALIBRATION
Definition at line 237 of file lcd.c.
References curr_page, and PAGE_CALIBRATION.
clearFault()
void clearFault (int index)
Clears a fault from the fault buffer by removing it and shifting remaining faults.
Parameters
index Position of the fault to clear (0-4)
Definition at line 301 of file lcd.c.
Referenced by faultsClearButton_CALLBACK().
faultsClearButton_CALLBACK()
void faultsClearButton_CALLBACK ()
Callback function for fault button press that clears faults.
If hover index is 5, clears all faults (indices 0-4) If hover index is 0-4, clears only that specific fault Updates fault messages after clearing
Definition at line 312 of file lcd.c.
References clearFault(), menu_page_t::current_index, faults_page, and updateFaultMessages().
faultsMoveDown()
void faultsMoveDown ()
Definition at line 288 of file lcd.c.
References faults_page, and MS_moveDown().
faultsMoveUp()
void faultsMoveUp ()
Definition at line 284 of file lcd.c.
References faults_page, and MS_moveUp().
faultsPageUpdate()
void faultsPageUpdate ()
Definition at line 278 of file lcd.c.
References faults_page, MS_refreshPage(), and updateFaultMessages().
faultsSelect()
void faultsSelect ()
Definition at line 292 of file lcd.c.
References faults_page, and MS_select().
faultTelemetryUpdate()
void faultTelemetryUpdate ()
Updates the color of fault text indicators on the faults page.
Definition at line 259 of file lcd.c.
References curr_page, and PAGE_FAULTS.
LCD_init()
void LCD_init (uint32_t baud_rate)
Definition at line 112 of file lcd.c.
References curr_page, NXT_setBaud(), NXT_setBrightness(), PAGE_RACE, and updatePage().
moveDown()
void moveDown ()
Definition at line 193 of file lcd.c.
References curr_page, page_handler_t::move_down, NUM_PAGES, and page_handlers.
Referenced by service_button_inputs().
moveUp()
void moveUp ()
Definition at line 182 of file lcd.c.
References curr_page, page_handler_t::move_up, NUM_PAGES, and page_handlers.
Referenced by service_button_inputs().
raceDownCallback()
void raceDownCallback ()
racePageUpdate()
void racePageUpdate ()
Definition at line 325 of file lcd.c.
References MS_refreshPage(), and race_page.
raceSelect()
void raceSelect ()
Definition at line 413 of file lcd.c.
References MS_select(), and race_page.
raceTelemetryUpdate()
void raceTelemetryUpdate ()
Updates telemetry data on the race dashboard LCD display.
Only updates on race page. Displays 'S' for stale values.
Definition at line 334 of file lcd.c.
References BATT_CURR, BATT_TEMP, BATT_VOLT, pedal_values_t::brake, BRK_BAR, can_data, CAR_STAT, curr_page, GREEN, INFO_GRAY, MPS_TO_MPH, NXT_setFontColor(), NXT_setText(), NXT_setTextFormatted(), NXT_setValue(), ORANGE, PAGE_RACE, pedal_values, RED, SPEED, THROT_BAR, pedal_values_t::throttle, and WHITE.
raceUpCallback()
void raceUpCallback ()
sdcTelemetryUpdate()
void sdcTelemetryUpdate ()
selectItem()
void selectItem ()
Definition at line 204 of file lcd.c.
References curr_page, NUM_PAGES, page_handlers, and page_handler_t::select.
Referenced by service_button_inputs().
set_faultIndicator()
void set_faultIndicator (uint16_t fault, char * element)
Sets the color of a fault indicator element based on fault status.
Parameters
fault The fault code to check (0xFFFF indicates no fault)
element Pointer to the display element to be colored
Definition at line 425 of file lcd.c.
References GREEN, is_latched(), NXT_setFontColor(), RED, and WHITE.
updateFaultDisplay()
void updateFaultDisplay ()
Updates fault messages on LCD screen based on priority and timing.
Manages fault display rotation, processes new faults from queue, and updates screen according to fault priorities and display timing requirements.
Definition at line 251 of file lcd.c.
updateFaultMessages()
void updateFaultMessages ()
Updates the display of fault messages on the LCD screen.
Checks fault buffer entries and displays either the corresponding fault message or "No Fault" message for each of the 5 fault text fields on screen
Definition at line 274 of file lcd.c.
Referenced by faultsClearButton_CALLBACK(), and faultsPageUpdate().
updatePage()
void updatePage ()
Updates LCD display page.
Key behaviors:
Maintains display of error pages when active
Definition at line 144 of file lcd.c.
References APPS_STRING, curr_page, FAULT_STRING, NUM_PAGES, NXT_setPage(), PAGE_CALIBRATION, PAGE_FAULTS, page_handlers, PAGE_RACE, PAGE_SDC_INFO, prev_page, RACE_STRING, SDCINFO_STRING, and page_handler_t::update.
Referenced by advancePage(), backPage(), LCD_init(), and service_button_inputs().
updateSDCStatus()
void updateSDCStatus (uint8_t status, char * element)
Updates the background color of an LCD element based on status.
Parameters
status Boolean indicating if element should be marked as active (1) or inactive (0)
element Pointer to the LCD element to update
Definition at line 444 of file lcd.c.
References GREEN, NXT_setBackground(), and RED.
updateTelemetryPages()
void updateTelemetryPages ()
Updates current telemetry page by calling its handler if available.
Definition at line 218 of file lcd.c.
References curr_page, NUM_PAGES, page_handlers, and page_handler_t::telemetry.
Variable Documentation
curr_page
volatile page_t curr_page
Definition at line 15 of file lcd.c.
Referenced by calibrationTelemetryUpdate(), faultTelemetryUpdate(), LCD_init(), moveDown(), moveUp(), raceTelemetryUpdate(), selectItem(), updatePage(), and updateTelemetryPages().
errorText
char* errorText = nullptr
Definition at line 17 of file lcd.c.
faults_elements
menu_element_t faults_elements[]
Definition at line 70 of file lcd.c.
faults_page
menu_page_t faults_page
Initial value:
= {
    .elements            = faults_elements,
    .num_elements        = sizeof(faults_elements) / sizeof(faults_elements[0]),
    .current_index       = 0,
    .is_element_selected = false}
Definition at line 103 of file lcd.c.
Referenced by faultsClearButton_CALLBACK(), faultsMoveDown(), faultsMoveUp(), faultsPageUpdate(), and faultsSelect().
input_state
volatile dashboard_input_state_t input_state extern
Definition at line 130 of file main.c.
Referenced by EXTI15_10_IRQHandler(), EXTI9_5_IRQHandler(), and service_button_inputs().
page_handlers
const page_handler_t page_handlers[]
Initial value:
= {
    [PAGE_RACE]        = {racePageUpdate, nullptr, nullptr, raceSelect, raceTelemetryUpdate},
    [PAGE_FAULTS]      = {faultsPageUpdate, faultsMoveUp, faultsMoveDown, faultsSelect, faultTelemetryUpdate},
    [PAGE_CALIBRATION] = {nullptr, nullptr, nullptr, nullptr, calibrationTelemetryUpdate},
}
Definition at line 47 of file lcd.c.
Referenced by moveDown(), moveUp(), selectItem(), updatePage(), and updateTelemetryPages().
pedal_values
pedal_values_t pedal_values extern
Definition at line 32 of file pedals.c.
Referenced by raceTelemetryUpdate().
prev_page
volatile page_t prev_page
Definition at line 16 of file lcd.c.
Referenced by updatePage().
q_fault_history
q_handle_t q_fault_history extern
race_elements
menu_element_t race_elements[]
Initial value:
= {
    {
        .type          = ELEMENT_OPTION,
        .object_name   = "tv" ,
        .current_value = 0,
        .on_change     = nullptr,
    }
}
Definition at line 54 of file lcd.c.
race_page
menu_page_t race_page
Initial value:
= {
    .elements            = race_elements,
    .num_elements        = sizeof(race_elements) / sizeof(race_elements[0]),
    .current_index       = 0,
    .is_element_selected = false,
}
Definition at line 63 of file lcd.c.
Referenced by racePageUpdate(), and raceSelect().