PER Firmware: common/log/log.c File Reference
log.c File Reference
#include "log.h"
#include "common/common_defs/common_defs.h"
#include "vsprintf.h"
Functions
int snprintf (char *buffer, size_t size, const char *fmt,...)
int sprintf (char *buffer, const char *fmt,...)
Function Documentation
snprintf()
int snprintf (char * buffer, size_t size, const char * fmt, ...)
Definition at line 7 of file log.c.
References buffer, and vsnprintf().
sprintf()
int sprintf (char * buffer, const char * fmt, ...)
Definition at line 17 of file log.c.
References buffer, and vsprintf().
Referenced by sd_create_new_file().