PER Firmware: common/log/log.h File Reference
log.h File Reference
#include "common/common_defs/common_defs.h"
#include "common/log/vsprintf.h"
Macros
#define DEBUG_PRINTF_USART_DEFINE(HANDLEPTR)
#define plog(...)
#define ANSI_RED "\x1b[31m"
#define ANSI_GREEN "\x1b[32m"
#define ANSI_YELLOW "\x1b[33m"
#define ANSI_BLUE "\x1b[34m"
#define ANSI_MAGENTA "\x1b[35m"
#define ANSI_CYAN "\x1b[36m"
#define ANSI_RESET "\x1b[37m"
#define __mu_log_color(color, ...)
#define log_msg(...)
#define log_int(n)
#define log_str(s)
#define log_char(c)
#define log_addr(addr)
#define log_red(...)
#define log_green(...)
#define log_yellow(...)
#define log_blue(...)
#define log_magenta(...)
#define log_cyan(...)
Functions
int snprintf (char *buffer, size_t size, const char *fmt,...)
int sprintf (char *buffer, const char *fmt,...)
int debug_printf (const char *fmt,...)
Macro Definition Documentation
__mu_log_color
#define __mu_log_color (color, ...)
Value:
    do { \
        debug_printf("%s", color); \
        debug_printf(__VA_ARGS__); \
        debug_printf("%s", ANSI_RESET); \
    } while (0)
Definition at line 57 of file log.h.
ANSI_BLUE
#define ANSI_BLUE "\x1b[34m"
Definition at line 52 of file log.h.
ANSI_CYAN
#define ANSI_CYAN "\x1b[36m"
Definition at line 54 of file log.h.
ANSI_GREEN
#define ANSI_GREEN "\x1b[32m"
Definition at line 50 of file log.h.
ANSI_MAGENTA
#define ANSI_MAGENTA "\x1b[35m"
Definition at line 53 of file log.h.
ANSI_RED
#define ANSI_RED "\x1b[31m"
Definition at line 49 of file log.h.
ANSI_RESET
#define ANSI_RESET "\x1b[37m"
Definition at line 55 of file log.h.
ANSI_YELLOW
#define ANSI_YELLOW "\x1b[33m"
Definition at line 51 of file log.h.
DEBUG_PRINTF_USART_DEFINE
#define DEBUG_PRINTF_USART_DEFINE (HANDLEPTR)
Value:
    static inline void _iodev_write(usart_init_t* handle, char* buffer, int size) { \
        if (handle) { \
            PHAL_usartTxBl(handle, (uint8_t*)buffer, size); \
        } \
    } \
\
    int debug_printf(const char* fmt, ...) { \
        va_list args; \
        char buffer[512]; \
        int i; \
\
        va_start(args, fmt); \
        i = vsnprintf(buffer, sizeof(buffer), fmt, args); \
        va_end(args); \
\
        _iodev_write((HANDLEPTR), buffer, MIN(i, (int)(sizeof(buffer) - 1))); \
\
        return i; \
    }
Definition at line 24 of file log.h.
log_addr
#define log_addr (addr)
Value:
(debug_printf("%s == %p\n", (#addr), (void*)(addr)))
Definition at line 68 of file log.h.
log_blue
#define log_blue (...)
Value:
__mu_log_color(ANSI_BLUE, __VA_ARGS__)
Definition at line 72 of file log.h.
log_char
#define log_char (c)
Value:
(debug_printf("%s == '%c'\n", (#c), (c)))
Definition at line 67 of file log.h.
log_cyan
#define log_cyan (...)
Value:
__mu_log_color(ANSI_CYAN, __VA_ARGS__)
Definition at line 74 of file log.h.
log_green
#define log_green (...)
Value:
__mu_log_color(ANSI_GREEN, __VA_ARGS__)
Definition at line 70 of file log.h.
log_int
#define log_int (n)
Value:
(debug_printf("%s == %d\n", (#n), (n)))
Definition at line 65 of file log.h.
log_magenta
#define log_magenta (...)
Value:
__mu_log_color(ANSI_MAGENTA, __VA_ARGS__)
Definition at line 73 of file log.h.
log_msg
#define log_msg (...)
Value:
debug_printf(__VA_ARGS__)
Definition at line 64 of file log.h.
log_red
#define log_red (...)
Value:
__mu_log_color(ANSI_RED, __VA_ARGS__)
Definition at line 69 of file log.h.
log_str
#define log_str (s)
Value:
(debug_printf("%s == %s\n", (#s), (s)))
Definition at line 66 of file log.h.
log_yellow
#define log_yellow (...)
Value:
__mu_log_color(ANSI_YELLOW, __VA_ARGS__)
Definition at line 71 of file log.h.
Referenced by main().
plog
#define plog (...)
Value:
debug_printf(__VA_ARGS__)
Definition at line 47 of file log.h.
Function Documentation
debug_printf()
int debug_printf (const char * fmt, ...)
Definition at line 113 of file main.c.
Referenced by _eth_handle_error(), eth_update_periodic(), sd_create_new_file(), sd_handle_error(), and sd_update_periodic().
snprintf()
int snprintf (char * buffer, size_t size, const char * fmt, ...)
Definition at line 7 of file log.c.
References buffer, and vsnprintf().
sprintf()
int sprintf (char * buffer, const char * fmt, ...)
Definition at line 17 of file log.c.
References buffer, and vsprintf().
Referenced by sd_create_new_file().