PER Firmware: source/main_module/main.c File Reference
main.c File Reference
"Main Module" node source code
#include "main.h"
#include "pindefs.h"
#include "common/common_defs/common_defs.h"
#include "common/can_library/generated/MAIN_MODULE.h"
#include "common/can_library/faults_common.h"
#include "common/freertos/freertos.h"
#include "common/phal/can.h"
#include "common/phal/gpio.h"
#include "common/phal/rcc.h"
#include "common/amk/amk.h"
Functions
void HardFault_Handler (void)
void heartbeat_task ()
void background_can_update ()
void AMK_task ()
defineThreadStack (heartbeat_task, HEARTBEAT_PERIOD_MS, osPriorityLow, 256)
defineThreadStack (update_SDC, 5, osPriorityLow, 512)
defineThreadStack (background_can_update, 10, osPriorityHigh, 1024)
defineThreadStack (fsm_periodic, 20, osPriorityNormal, 2048)
defineThreadStack (AMK_task, 15, osPriorityNormal, 1024)
defineThreadStack (fault_library_periodic, 100, osPriorityLow, 1024)
int main (void)
Variables
car_t g_car
torque_request_t g_torque_request
GPIOInitConfig_t gpio_config []
static constexpr uint32_t TargetCoreClockrateHz = 16'000'000
ClockRateConfig_t clock_config
uint32_t APB1ClockRateHz
uint32_t APB2ClockRateHz
uint32_t AHBClockRateHz
uint32_t PLLClockRateHz
Detailed Description
"Main Module" node source code
Author
Irving Wang (irvin.nosp@m.gw@p.nosp@m.urdue.nosp@m..edu)
Definition in file main.c.
Function Documentation
AMK_task()
void AMK_task ()
Definition at line 124 of file main.c.
References AMK_periodic(), car_t::front_left, car_t::front_right, g_car, car_t::rear_left, and car_t::rear_right.
Referenced by main().
background_can_update()
void background_can_update ()
Definition at line 119 of file main.c.
References CAN_rx_update(), and CAN_tx_update().
Referenced by main().
defineThreadStack() [1/6]
defineThreadStack (AMK_task , 15 , osPriorityNormal , 1024)
defineThreadStack() [2/6]
defineThreadStack (background_can_update , 10 , osPriorityHigh , 1024)
defineThreadStack() [3/6]
defineThreadStack (fault_library_periodic , 100 , osPriorityLow , 1024)
defineThreadStack() [4/6]
defineThreadStack (fsm_periodic , 20 , osPriorityNormal , 2048)
defineThreadStack() [5/6]
defineThreadStack (heartbeat_task , HEARTBEAT_PERIOD_MS , osPriorityLow , 256)
defineThreadStack() [6/6]
defineThreadStack (update_SDC , 5 , osPriorityLow , 512)
HardFault_Handler()
void HardFault_Handler (void) extern
Definition at line 176 of file main.c.
References ERROR_LED_PIN, and ERROR_LED_PORT.
heartbeat_task()
void heartbeat_task ()
Definition at line 83 of file main.c.
References CONN_LED_TIMEOUT_MS, CONNECTION_LED_PIN, CONNECTION_LED_PORT, ERROR_LED_PIN, ERROR_LED_PORT, HEARTBEAT_LED_PIN, HEARTBEAT_LED_PORT, last_can_rx_time_ms, PHAL_toggleGPIO(), PHAL_writeGPIO(), and PREFLIGHT_DURATION_MS.
Referenced by main().
main()
int main (void)
Definition at line 138 of file main.c.
References AMK_task(), background_can_update(), CAN_library_init(), car_init(), clock_config, createThread, fault_library_periodic(), fsm_periodic(), gpio_config, HardFault_Handler(), heartbeat_task(), PHAL_configureClockRates(), PHAL_FDCAN_init(), PHAL_initGPIO(), and update_SDC().
Variable Documentation
AHBClockRateHz
uint32_t AHBClockRateHz extern
Definition at line 17 of file rcc.c.
APB1ClockRateHz
uint32_t APB1ClockRateHz extern
Definition at line 15 of file rcc.c.
APB2ClockRateHz
uint32_t APB2ClockRateHz extern
Definition at line 16 of file rcc.c.
clock_config
ClockRateConfig_t clock_config
Initial value:
= {
    .clock_source           = CLOCK_SOURCE_HSE,
    .use_pll                = false,
    .system_clock_target_hz = TargetCoreClockrateHz,
    .ahb_clock_target_hz    = (TargetCoreClockrateHz / 1),
    .apb1_clock_target_hz   = (TargetCoreClockrateHz / (1)),
    .apb2_clock_target_hz   = (TargetCoreClockrateHz / (1)),
}
Definition at line 66 of file main.c.
g_car
car_t g_car
Definition at line 22 of file main.c.
Referenced by AMK_task(), car_init(), flush_inva(), flush_invb(), flush_invc(), flush_invd(), fsm_periodic(), init_amks(), is_all_AMKS_running(), is_buzzing_time_elapsed(), and set_brake_light().
g_torque_request
torque_request_t g_torque_request
Definition at line 23 of file main.c.
Referenced by fsm_periodic(), and ready2drive_periodic().
gpio_config
GPIOInitConfig_t gpio_config[]
Definition at line 26 of file main.c.
PLLClockRateHz
uint32_t PLLClockRateHz extern
Definition at line 18 of file rcc.c.
TargetCoreClockrateHz
uint32_t TargetCoreClockrateHz = 16'000'000 static constexpr
Definition at line 65 of file main.c.