PER Firmware: source/main_module/main.h File Reference
main.h File Reference
"Main Module" node source code
#include "common/amk/amk.h"
Data Structures
struct car_t
struct torque_request_t
Functions
void fsm_periodic ()
void car_init ()
void update_SDC ()
Variables
car_t g_car
torque_request_t g_torque_request
Detailed Description
"Main Module" node source code
Author
Irving Wang (irvin.nosp@m.gw@p.nosp@m.urdue.nosp@m..edu)
Definition in file main.h.
Function Documentation
car_init()
void car_init ()
Definition at line 137 of file amk_init.c.
References car_t::current_state, g_car, init_amks(), and car_t::next_state.
Referenced by main().
fsm_periodic()
void fsm_periodic ()
Definition at line 94 of file state_machine.c.
References AMK_set_torque(), car_t::brake_light, BRAKE_LIGHT_PIN, BRAKE_LIGHT_PORT, car_t::buzzer_enable, BUZZER_PIN, BUZZER_PORT, car_t::buzzer_start_time, car_t::current_state, car_t::front_left, torque_request_t::front_left, car_t::front_right, torque_request_t::front_right, g_car, g_torque_request, is_all_AMKS_running(), is_buzzing_time_elapsed(), is_fatal_latched(), is_init_complete(), is_latched(), car_t::is_precharge_complete, is_precharge_complete(), is_start_button_pressed(), is_TSMS_closed(), car_t::next_state, PHAL_readGPIO(), PHAL_writeGPIO(), PRECHARGE_COMPLETE_PIN, PRECHARGE_COMPLETE_PORT, ready2drive_periodic(), car_t::rear_left, torque_request_t::rear_left, car_t::rear_right, torque_request_t::rear_right, set_brake_light(), TSAL_GREEN_CTRL_PIN, TSAL_GREEN_CTRL_PORT, car_t::tsal_green_enable, TSAL_RED_CTRL_PIN, TSAL_RED_CTRL_PORT, car_t::tsal_red_enable, and update_fault().
Referenced by main().
update_SDC()
void update_SDC ()
Definition at line 38 of file sdc.c.
References sdc_node_t::fault_id, sdc_node_t::mux_addr, NUM_SDC_NODES, PHAL_readGPIO(), PHAL_writeGPIO(), SDC_MUX_PIN, SDC_MUX_PORT, SDC_MUX_S0_PIN, SDC_MUX_S0_PORT, SDC_MUX_S1_PIN, SDC_MUX_S1_PORT, SDC_MUX_S2_PIN, SDC_MUX_S2_PORT, SDC_MUX_S3_PIN, SDC_MUX_S3_PORT, SDC_NODE_LUT, SDC_UNREADABLE, and update_fault().
Referenced by main().
Variable Documentation
g_car
car_t g_car extern
Definition at line 22 of file main.c.
Referenced by AMK_task(), car_init(), flush_inva(), flush_invb(), flush_invc(), flush_invd(), fsm_periodic(), init_amks(), is_all_AMKS_running(), is_buzzing_time_elapsed(), and set_brake_light().
g_torque_request
torque_request_t g_torque_request extern
Definition at line 23 of file main.c.
Referenced by fsm_periodic(), and ready2drive_periodic().