PER Firmware: source/dashboard/lcd/menu_system.c File Reference
menu_system.c File Reference
Implementation of menu system for LCD display interface.
#include "menu_system.h"
#include <stdint.h>
#include "nextion.h"
Macros
#define RUSH (56640)
#define BOILERMAKER (52690)
#define FIELD (56776)
#define STEEL (21196)
#define COOL_GRAY (27535)
#define STEAM (50680)
Functions
void MS_setStyleNormal (menu_element_t *element)
Applies normal (default) styling to a menu element.
void MS_setStyleHover (menu_element_t *element)
Applies hover styling effect to a menu element.
void MS_setStyleSelected (menu_element_t *element)
Applies selected state styling to a menu element.
void MS_moveUp (menu_page_t *page)
Moves menu selection up or increments selected element value.
void MS_moveDown (menu_page_t *page)
Moves menu selection down or increments selected element value.
void MS_select (menu_page_t *page)
Handles menu element selection and actions.
void MS_incrementValue (menu_element_t *element)
Increments the value of a menu element and updates its display.
void MS_decrementValue (menu_element_t *element)
Decrements the value of a menu element and updates its display.
void MS_refreshPage (menu_page_t *page)
Refreshes the menu page by resetting selection state and updating all elements.
int8_t MS_listGetSelected (menu_page_t *page)
Gets the index of the selected element in a menu page.
Detailed Description
Implementation of menu system for LCD display interface.
Provides functions for managing menu navigation, element styling, and user interaction with the LCD display menu system.
Author
Irving Wang (wang5.nosp@m.952@.nosp@m.purdu.nosp@m.e.ed.nosp@m.u)
Definition in file menu_system.c.
Macro Definition Documentation
BOILERMAKER
#define BOILERMAKER (52690)
Definition at line 19 of file menu_system.c.
COOL_GRAY
#define COOL_GRAY (27535)
Definition at line 22 of file menu_system.c.
FIELD
#define FIELD (56776)
Definition at line 20 of file menu_system.c.
RUSH
#define RUSH (56640)
Definition at line 18 of file menu_system.c.
Referenced by MS_setStyleSelected().
STEAM
#define STEAM (50680)
Definition at line 23 of file menu_system.c.
Referenced by MS_setStyleHover().
STEEL
#define STEEL (21196)
Definition at line 21 of file menu_system.c.
Referenced by MS_setStyleNormal().
Function Documentation
MS_decrementValue()
void MS_decrementValue (menu_element_t * element)
Decrements the value of a menu element and updates its display.
If decrementing would exceed min_value, wraps around to max_value. Updates display based on element type (float or integer value).
Parameters
element Pointer to the menu element to decrement
Definition at line 191 of file menu_system.c.
References menu_element_t::current_value, ELEMENT_FLT, ELEMENT_VAL, menu_element_t::increment, menu_element_t::max_value, menu_element_t::min_value, NXT_setTextFormatted(), NXT_setValue(), menu_element_t::object_name, and menu_element_t::type.
Referenced by MS_moveDown().
MS_incrementValue()
void MS_incrementValue (menu_element_t * element)
Increments the value of a menu element and updates its display.
If incrementing would exceed max_value, wraps around to min_value. Updates display based on element type (float or integer value).
Parameters
element Pointer to the menu element to increment
Definition at line 164 of file menu_system.c.
References menu_element_t::current_value, ELEMENT_FLT, ELEMENT_VAL, menu_element_t::increment, menu_element_t::max_value, menu_element_t::min_value, NXT_setTextFormatted(), NXT_setValue(), menu_element_t::object_name, and menu_element_t::type.
Referenced by MS_moveUp().
MS_listGetSelected()
int8_t MS_listGetSelected (menu_page_t * page)
Gets the index of the selected element in a menu page.
Parameters
page Pointer to the menu page structure
Returns
Index of the selected element, -1 if no element is selected
Definition at line 246 of file menu_system.c.
References menu_element_t::current_value, menu_page_t::elements, and menu_page_t::num_elements.
Referenced by pedalProfilesPageUpdate(), and pedalProfilesSaveButton_CALLBACK().
MS_moveDown()
void MS_moveDown (menu_page_t * page)
Moves menu selection down or increments selected element value.
Parameters
page Pointer to the menu page structure
Definition at line 82 of file menu_system.c.
References menu_page_t::current_index, menu_page_t::elements, menu_page_t::is_element_selected, MS_decrementValue(), MS_setStyleHover(), MS_setStyleNormal(), and menu_page_t::num_elements.
Referenced by coolingMoveDown(), driverMoveDown(), faultsMoveDown(), pedalProfilesMoveDown(), and tvMoveDown().
MS_moveUp()
void MS_moveUp (menu_page_t * page)
Moves menu selection up or increments selected element value.
Parameters
page Pointer to the menu page structure
Definition at line 61 of file menu_system.c.
References menu_page_t::current_index, menu_page_t::elements, menu_page_t::is_element_selected, MS_incrementValue(), MS_setStyleHover(), MS_setStyleNormal(), and menu_page_t::num_elements.
Referenced by coolingMoveUp(), driverMoveUp(), faultsMoveUp(), pedalProfilesMoveUp(), and tvMoveUp().
MS_refreshPage()
void MS_refreshPage (menu_page_t * page)
Refreshes the menu page by resetting selection state and updating all elements.
Parameters
page Pointer to the menu page to refresh
Definition at line 215 of file menu_system.c.
References menu_page_t::current_index, menu_element_t::current_value, ELEMENT_FLT, ELEMENT_LIST, ELEMENT_OPTION, ELEMENT_VAL, menu_page_t::elements, menu_page_t::is_element_selected, MS_setStyleSelected(), menu_page_t::num_elements, NXT_setTextFormatted(), NXT_setValue(), menu_element_t::object_name, and menu_element_t::type.
Referenced by coolingPageUpdate(), driverPageUpdate(), faultsPageUpdate(), loggingPageUpdate(), pedalProfilesPageUpdate(), racePageUpdate(), and tvPageUpdate().
MS_select()
void MS_select (menu_page_t * page)
Handles menu element selection and actions.
Parameters
page Pointer to the menu page
Definition at line 103 of file menu_system.c.
References menu_page_t::current_index, menu_element_t::current_value, ELEMENT_BUTTON, ELEMENT_FLT, ELEMENT_LIST, ELEMENT_OPTION, ELEMENT_VAL, menu_page_t::elements, menu_page_t::is_element_selected, MS_setStyleHover(), MS_setStyleNormal(), MS_setStyleSelected(), menu_page_t::num_elements, NXT_setValue(), menu_element_t::object_name, menu_element_t::on_change, and menu_element_t::type.
Referenced by coolingSelect(), driverSelect(), faultsSelect(), loggingSelect(), pedalProfilesSelect(), raceSelect(), and tvSelect().
MS_setStyleHover()
void MS_setStyleHover (menu_element_t * element)
Applies hover styling effect to a menu element.
Parameters
element Pointer to the menu element to be styled
Definition at line 40 of file menu_system.c.
References BLACK, NXT_setBackground(), NXT_setFontColor(), menu_element_t::object_name, and STEAM.
Referenced by MS_moveDown(), MS_moveUp(), and MS_select().
MS_setStyleNormal()
void MS_setStyleNormal (menu_element_t * element)
Applies normal (default) styling to a menu element.
Parameters
element Pointer to the menu element to be styled
Definition at line 29 of file menu_system.c.
References NXT_setBackground(), NXT_setFontColor(), menu_element_t::object_name, STEEL, and WHITE.
Referenced by MS_moveDown(), MS_moveUp(), and MS_select().
MS_setStyleSelected()
void MS_setStyleSelected (menu_element_t * element)
Applies selected state styling to a menu element.
Parameters
element Pointer to the menu element to be styled
Definition at line 51 of file menu_system.c.
References NXT_setBackground(), NXT_setFontColor(), menu_element_t::object_name, RUSH, and WHITE.
Referenced by MS_refreshPage(), and MS_select().