PER Firmware: parser Namespace Reference
parser Namespace Reference
Data Structures
class Bus
class BusView
class Fault
class FaultModule
class Message
class Node
class RxMessage
class Signal
class SystemContext
Functions
SystemContext create_system_context (nodes, mappings, bus_configs, custom_types)
Dict load_custom_types ()
Dict load_bus_configs ()
List[Node] parse_all ()
validate_node (Node node, Dict custom_types)
Signal parse_signal (Dict data)
Message parse_message (Dict data, Dict bus_config)
RxMessage parse_rx_message (Dict data)
'Fault' parse_fault (Dict data)
Bus parse_bus (str name, Dict data, Dict bus_configs)
Node parse_internal_node (Path filepath, Dict bus_configs)
Node parse_external_node (Path filepath, Dict bus_configs)
Detailed Description
parser.py
Author: Irving Wang (irvingw@purdue.edu)
Function Documentation
create_system_context()
SystemContext parser.create_system_context (nodes, mappings, bus_configs, custom_types)
Aggregates all system data into a single context object and performs final validation.
Definition at line 219 of file parser.py.
load_bus_configs()
Dict parser.load_bus_configs ()
Load bus configurations from bus_configs.json
Definition at line 275 of file parser.py.
load_custom_types()
Dict parser.load_custom_types ()
Load custom types from common_types.json
Definition at line 264 of file parser.py.
parse_all()
List[Node] parser.parse_all ()
Parse all configuration files into Node objects.
Performs semantic validation during parsing.
Definition at line 283 of file parser.py.
References parse_external_node(), parse_internal_node(), and validate_node().
parse_bus()
Bus parser.parse_bus (str name, Dict data, Dict bus_configs)
Definition at line 367 of file parser.py.
References parse_message(), and parse_rx_message().
Referenced by parse_internal_node().
parse_external_node()
Node parser.parse_external_node (Path filepath, Dict bus_configs)
Definition at line 394 of file parser.py.
References parse_message(), and parse_rx_message().
Referenced by parse_all().
parse_fault()
'Fault' parser.parse_fault (Dict data)
Definition at line 356 of file parser.py.
Referenced by parse_internal_node().
parse_internal_node()
Node parser.parse_internal_node (Path filepath, Dict bus_configs)
Definition at line 377 of file parser.py.
References parse_bus(), and parse_fault().
Referenced by parse_all().
parse_message()
Message parser.parse_message (Dict data, Dict bus_config)
Definition at line 335 of file parser.py.
References parse_signal().
Referenced by parse_bus(), and parse_external_node().
parse_rx_message()
RxMessage parser.parse_rx_message (Dict data)
Definition at line 349 of file parser.py.
Referenced by parse_bus(), and parse_external_node().
parse_signal()
Signal parser.parse_signal (Dict data)
Definition at line 321 of file parser.py.
Referenced by parse_message().
validate_node()
parser.validate_node (Node node, Dict custom_types)
Run semantic validation and resolve bit layouts for a node
Definition at line 314 of file parser.py.
Referenced by parse_all().