PER Firmware: codegen Namespace Reference
codegen Namespace Reference
Functions
generate_headers (SystemContext context)
generate_types_header (env, Dict custom_types)
generate_router_header (env, List[Node] nodes)
generate_node_headers (env, SystemContext context)
generate_node_header (env, Node node, SystemContext context)
generate_bus_header (env, str bus_name, Dict config, List[Message] messages)
Detailed Description
codegen.py
Author: Irving Wang (irvingw@purdue.edu)
Function Documentation
generate_bus_header()
codegen.generate_bus_header (env, str bus_name, Dict config, List[Message] messages)
Definition at line 82 of file codegen.py.
Referenced by generate_headers().
generate_headers()
codegen.generate_headers (SystemContext context)
Definition at line 11 of file codegen.py.
References generate_bus_header(), generate_node_headers(), generate_router_header(), and generate_types_header().
generate_node_header()
codegen.generate_node_header (env, Node node, SystemContext context)
Definition at line 52 of file codegen.py.
Referenced by generate_node_headers().
generate_node_headers()
codegen.generate_node_headers (env, SystemContext context)
Definition at line 46 of file codegen.py.
References generate_node_header().
Referenced by generate_headers().
generate_router_header()
codegen.generate_router_header (env, List[Node] nodes)
Definition at line 40 of file codegen.py.
Referenced by generate_headers().
generate_types_header()
codegen.generate_types_header (env, Dict custom_types)
Definition at line 34 of file codegen.py.
Referenced by generate_headers().