PER Firmware: mapper Namespace Reference
mapper Namespace Reference
Data Structures
class FDCANFilters
class FilterBank
class NodeMapping
Functions
Dict[str, NodeMapping] map_hardware (List[Node] nodes, Dict bus_configs)
bool is_fdcan_peripheral (str periph)
NodeMapping map_node_hardware (Node node, Dict bus_configs)
FDCANFilters map_fdcan_filters (str node_name, str periph, List msgs)
List[FilterBank] map_bxcan_filters (str node_name, str periph, List msgs)
Variables
int MAX_FDCAN_SID_FILTERS = 28
int MAX_FDCAN_XID_FILTERS = 8
Detailed Description
mapper.py
Author: Irving Wang (irvingw@purdue.edu)
Function Documentation
is_fdcan_peripheral()
bool mapper.is_fdcan_peripheral (str periph)
Check if peripheral is FDCAN (G4) vs bxCAN (F4/F7/L4)
Definition at line 59 of file mapper.py.
Referenced by map_node_hardware().
map_bxcan_filters()
List[FilterBank] mapper.map_bxcan_filters (str node_name, str periph, List msgs)
Map messages to bxCAN filter banks
Definition at line 126 of file mapper.py.
Referenced by map_node_hardware().
map_fdcan_filters()
FDCANFilters mapper.map_fdcan_filters (str node_name, str periph, List msgs)
Map messages to FDCAN standard and extended ID filter lists
Definition at line 98 of file mapper.py.
Referenced by map_node_hardware().
map_hardware()
Dict[str, NodeMapping] mapper.map_hardware (List[Node] nodes, Dict bus_configs)
Hardware Mapper stage.
Assigns physical resources (like bxCAN filter banks or FDCAN filter lists) to nodes.
Definition at line 46 of file mapper.py.
References map_node_hardware().
map_node_hardware()
NodeMapping mapper.map_node_hardware (Node node, Dict bus_configs)
Definition at line 64 of file mapper.py.
References is_fdcan_peripheral(), map_bxcan_filters(), and map_fdcan_filters().
Referenced by map_hardware().
Variable Documentation
MAX_FDCAN_SID_FILTERS
int mapper.MAX_FDCAN_SID_FILTERS = 28
Definition at line 12 of file mapper.py.
MAX_FDCAN_XID_FILTERS
int mapper.MAX_FDCAN_XID_FILTERS = 8
Definition at line 13 of file mapper.py.