PER Firmware: validator Namespace Reference
validator Namespace Reference
Functions
bool validate_against_schema (data, schema, schema_store=None, base_uri='', filename="<unknown>")
bool validate_common_types ()
bool validate_bus_config (schema_store)
bool validate_internal_nodes (schema_store)
bool validate_external_nodes (schema_store)
bool validate_all ()
Detailed Description
validator.py
Author: Irving Wang (irvingw@purdue.edu)
Function Documentation
validate_against_schema()
bool validator.validate_against_schema (data, schema, schema_store = None, base_uri = '', filename = "<unknown>")
Validate data against schema and return success status.
Prints all validation errors found in the file.
Definition at line 11 of file validator.py.
Referenced by validate_bus_config(), validate_common_types(), validate_external_nodes(), and validate_internal_nodes().
validate_all()
bool validator.validate_all ()
Definition at line 77 of file validator.py.
References validate_bus_config(), validate_common_types(), validate_external_nodes(), and validate_internal_nodes().
validate_bus_config()
bool validator.validate_bus_config (schema_store)
Definition at line 40 of file validator.py.
References validate_against_schema().
Referenced by validate_all().
validate_common_types()
bool validator.validate_common_types ()
Definition at line 31 of file validator.py.
References validate_against_schema().
Referenced by validate_all().
validate_external_nodes()
bool validator.validate_external_nodes (schema_store)
Definition at line 64 of file validator.py.
References validate_against_schema().
Referenced by validate_all().
validate_internal_nodes()
bool validator.validate_internal_nodes (schema_store)
Definition at line 51 of file validator.py.
References validate_against_schema().
Referenced by validate_all().