PER Firmware: source/pdu/main.c File Reference
main.c File Reference
"PDU" node source code
#include "common/can_library/faults_common.h"
#include "common/common_defs/common_defs.h"
#include "common/freertos/freertos.h"
#include "common/phal/adc.h"
#include "common/phal/can.h"
#include "common/phal/dma.h"
#include "common/phal/gpio.h"
#include "common/phal/rcc.h"
#include "auto_switch.h"
#include "common/can_library/generated/PDU.h"
#include "cooling.h"
#include "fan_control.h"
#include "flow_rate.h"
#include "led.h"
#include "main.h"
Macros
#define TargetCoreClockrateHz 16'000'000
Functions
void HardFault_Handler ()
void heartbeat_task ()
void background_can_update ()
void send_iv_readings ()
void send_flowrates ()
DEFINE_TASK (heartbeat_task, 500, osPriorityLow, STACK_256)
DEFINE_TASK (background_can_update, 5, osPriorityHigh, STACK_1024)
DEFINE_TASK (autoSwitchPeriodic, 15, osPriorityNormal, STACK_512)
DEFINE_TASK (update_cooling_periodic, 100, osPriorityNormal, STACK_1024)
DEFINE_TASK (LED_periodic, 500, osPriorityLow, STACK_512)
DEFINE_TASK (send_iv_readings, 500, osPriorityLow, STACK_512)
DEFINE_TASK (checkSwitchFaults, 100, osPriorityLow, STACK_512)
DEFINE_TASK (send_flowrates, 200, osPriorityLow, STACK_256)
DEFINE_TASK (fault_library_periodic, 100, osPriorityLow, STACK_1024)
int main ()
void CAN1_RX0_IRQHandler ()
Variables
GPIOInitConfig_t gpio_config []
ADCInitConfig_t adc_config
dma_init_t spi_rx_dma_config = SPI1_RXDMA_CONT_CONFIG(NULL, 2)
dma_init_t spi_tx_dma_config = SPI1_TXDMA_CONT_CONFIG(NULL, 1)
SPI_InitConfig_t spi_config
volatile ADCReadings_t adc_readings
ADCChannelConfig_t adc_channel_config []
dma_init_t adc_dma_config
ClockRateConfig_t clock_config
uint32_t APB1ClockRateHz
uint32_t APB2ClockRateHz
uint32_t AHBClockRateHz
uint32_t PLLClockRateHz
Detailed Description
"PDU" node source code
Author
Luke Oxley (lcoxl.nosp@m.ey@p.nosp@m.urdue.nosp@m..edu)
Ronak Jain (jain7.nosp@m.17@p.nosp@m.urdue.nosp@m..edu)
Irving Wang (irvin.nosp@m.gw@p.nosp@m.urdue.nosp@m..edu)
Definition in file main.c.
Macro Definition Documentation
TargetCoreClockrateHz
#define TargetCoreClockrateHz 16'000'000
Definition at line 214 of file main.c.
Function Documentation
background_can_update()
void background_can_update (void)
Definition at line 294 of file main.c.
References CAN_rx_update(), and CAN_tx_update().
CAN1_RX0_IRQHandler()
void CAN1_RX0_IRQHandler ()
Definition at line 408 of file main.c.
References CAN_handle_irq().
DEFINE_TASK() [1/9]
DEFINE_TASK (autoSwitchPeriodic , 15 , osPriorityNormal , STACK_512)
DEFINE_TASK() [2/9]
DEFINE_TASK (background_can_update , 5 , osPriorityHigh , STACK_1024)
DEFINE_TASK() [3/9]
DEFINE_TASK (checkSwitchFaults , 100 , osPriorityLow , STACK_512)
DEFINE_TASK() [4/9]
DEFINE_TASK (fault_library_periodic , 100 , osPriorityLow , STACK_1024)
DEFINE_TASK() [5/9]
DEFINE_TASK (heartbeat_task , 500 , osPriorityLow , STACK_256)
DEFINE_TASK() [6/9]
DEFINE_TASK (LED_periodic , 500 , osPriorityLow , STACK_512)
DEFINE_TASK() [7/9]
DEFINE_TASK (send_flowrates , 200 , osPriorityLow , STACK_256)
DEFINE_TASK() [8/9]
DEFINE_TASK (send_iv_readings , 500 , osPriorityLow , STACK_512)
DEFINE_TASK() [9/9]
DEFINE_TASK (update_cooling_periodic , 100 , osPriorityNormal , STACK_1024)
HardFault_Handler()
void HardFault_Handler (void)
Definition at line 412 of file main.c.
References ERR_LED_GPIO_Port, ERR_LED_Pin, and PHAL_writeGPIO().
heartbeat_task()
void heartbeat_task (void)
Definition at line 239 of file main.c.
References CAN1_IDX, can_stats_t::can_peripheral_stats, can_stats, CONN_LED_GPIO_Port, CONN_LED_MS_THRESH, CONN_LED_Pin, ERR_LED_GPIO_Port, ERR_LED_Pin, HEARTBEAT_GPIO_Port, HEARTBEAT_Pin, last_can_rx_time_ms, LED_control(), LED_OFF, LED_ON, MAX_NUM_LED, PHAL_toggleGPIO(), PHAL_writeGPIO(), PREFLIGHT_ANIMATION_DURATION_MS, can_stats_t::rx_of, can_peripheral_stats_t::rx_overrun, can_peripheral_stats_t::tx_fail, and can_peripheral_stats_t::tx_of.
main()
int main (void)
Definition at line 345 of file main.c.
References adc_channel_config, adc_config, adc_dma_config, autoSwitchPeriodic(), background_can_update(), CAN_library_init(), checkSwitchFaults(), clock_config, coolingInit(), fanControlInit(), fault_library_periodic(), flowRateInit(), gpio_config, HardFault_Handler(), heartbeat_task(), HSI_TRIM_PDU, LED_CTRL_BLANK_GPIO_Port, LED_CTRL_BLANK_Pin, LED_periodic(), PHAL_configureClockRates(), PHAL_initADC(), PHAL_initCAN(), PHAL_initDMA(), PHAL_initGPIO(), PHAL_SPI_init(), PHAL_startADC(), PHAL_startTxfer(), PHAL_trimHSI(), PHAL_writeGPIO(), send_flowrates(), send_iv_readings(), setSwitch(), spi_config, START_TASK, SW_ABOX, SW_BLT, SW_CRIT_5V, SW_DAQ, SW_DASH, SW_MAIN, SW_SDC, SW_TV, and update_cooling_periodic().
send_flowrates()
void send_flowrates ()
Definition at line 299 of file main.c.
References getFlowRate1(), and getFlowRate2().
Referenced by main().
send_iv_readings()
void send_iv_readings ()
Definition at line 303 of file main.c.
References adc_readings, auto_switches, CS_24V, CS_5V, auto_switches_t::current, voltage_t::in_24v, ADCReadings_t::internal_therm, voltage_t::out_3v3, voltage_t::out_5v, SW_ABOX, SW_DASH, SW_FAN_1, SW_FAN_2, SW_FAN_3, SW_FAN_4, SW_HXFAN, SW_MAIN, SW_PUMP_1, SW_PUMP_2, SW_SDC, update_fault(), and auto_switches_t::voltage.
Referenced by main().
Variable Documentation
adc_channel_config
ADCChannelConfig_t adc_channel_config[]
Initial value:
= {
    {.channel = (6) , .rank = 1, .sampling_time = ADC_CHN_SMP_CYCLES_480},
    {.channel = (5) , .rank = 2, .sampling_time = ADC_CHN_SMP_CYCLES_480},
    {.channel = (13) , .rank = 3, .sampling_time = ADC_CHN_SMP_CYCLES_480},
    {.channel = (0) , .rank = 4, .sampling_time = ADC_CHN_SMP_CYCLES_480},
    {.channel = (2) , .rank = 5, .sampling_time = ADC_CHN_SMP_CYCLES_480},
    {.channel = (3) , .rank = 6, .sampling_time = ADC_CHN_SMP_CYCLES_480},
    {.channel = (12) , .rank = 7, .sampling_time = ADC_CHN_SMP_CYCLES_480},
    {.channel = (11) , .rank = 8, .sampling_time = ADC_CHN_SMP_CYCLES_480},
    {.channel = (10) , .rank = 9, .sampling_time = ADC_CHN_SMP_CYCLES_480},
    {.channel = (7) , .rank = 10, .sampling_time = ADC_CHN_SMP_CYCLES_480},
    {.channel = (8) , .rank = 11, .sampling_time = ADC_CHN_SMP_CYCLES_480},
    {.channel = (4) , .rank = 12, .sampling_time = ADC_CHN_SMP_CYCLES_480},
    {.channel = (15) , .rank = 13, .sampling_time = ADC_CHN_SMP_CYCLES_480},
    {.channel = (1) , .rank = 14, .sampling_time = ADC_CHN_SMP_CYCLES_480},
    {.channel = (14) , .rank = 15, .sampling_time = ADC_CHN_SMP_CYCLES_480},
    {.channel = (16) , .rank = 16, .sampling_time = ADC_CHN_SMP_CYCLES_480},
    {.channel = (9) , .rank = 17, .sampling_time = ADC_CHN_SMP_CYCLES_480},
}
Definition at line 191 of file main.c.
adc_config
ADCInitConfig_t adc_config
Initial value:
= {
    .clock_prescaler = ADC_CLK_PRESC_6,
    .resolution      = ADC_RES_12_BIT,
    .data_align      = ADC_DATA_ALIGN_RIGHT,
    .cont_conv_mode  = true,
    .adc_number      = 1,
    .dma_mode        = ADC_DMA_CIRCULAR
}
Definition at line 168 of file main.c.
adc_dma_config
dma_init_t adc_dma_config
Initial value:
= ADC1_DMA_CONT_CONFIG((uint32_t)&adc_readings,
                                                 sizeof(adc_readings) / sizeof(adc_readings.v24_vs),
                                                 0b01)
Definition at line 210 of file main.c.
adc_readings
volatile ADCReadings_t adc_readings
Definition at line 190 of file main.c.
Referenced by calcCurrent_Total(), send_iv_readings(), updateCurrent(), updateMux(), and updateVoltage().
AHBClockRateHz
uint32_t AHBClockRateHz extern
Definition at line 17 of file rcc.c.
APB1ClockRateHz
uint32_t APB1ClockRateHz extern
Definition at line 15 of file rcc.c.
APB2ClockRateHz
uint32_t APB2ClockRateHz extern
Definition at line 16 of file rcc.c.
clock_config
ClockRateConfig_t clock_config
Initial value:
= {
    .clock_source              = CLOCK_SOURCE_HSE,
    .use_pll                   = false,
    .vco_output_rate_target_hz = 160'000'000,
    .pll_src                   = PLL_SRC_HSE,
    .system_clock_target_hz    = 16'000'000 ,
    .ahb_clock_target_hz       = ( 16'000'000 / 1),
    .apb1_clock_target_hz      = ( 16'000'000 / (1)),
    .apb2_clock_target_hz      = ( 16'000'000 / (1)),
}
Definition at line 215 of file main.c.
gpio_config
GPIOInitConfig_t gpio_config[]
Definition at line 29 of file main.c.
PLLClockRateHz
uint32_t PLLClockRateHz extern
Definition at line 18 of file rcc.c.
spi_config
SPI_InitConfig_t spi_config
Initial value:
= {
    .data_len   = 8,
    .nss_sw     = false,
    .rx_dma_cfg = &spi_rx_dma_config,
    .tx_dma_cfg = &spi_tx_dma_config,
    .periph     = SPI1
}
Definition at line 181 of file main.c.
Referenced by LED_control().
spi_rx_dma_config
dma_init_t spi_rx_dma_config = SPI1_RXDMA_CONT_CONFIG(NULL, 2)
Definition at line 179 of file main.c.
spi_tx_dma_config
dma_init_t spi_tx_dma_config = SPI1_TXDMA_CONT_CONFIG(NULL, 1)
Definition at line 180 of file main.c.