PER Firmware: source/dashboard/pedals/pedals.c File Reference
pedals.c File Reference
#include "pedals.h"
#include <stdint.h>
#include "common/can_library/generated/DASHBOARD.h"
#include "common/can_library/faults_common.h"
#include "common_defs.h"
#include "main.h"
Functions
static uint16_t normalize (uint16_t value, uint16_t min, uint16_t max)
Normalizes a value between min and max to a range of 0 to MAX_PEDAL_MEAS (4095)
void pedalsPeriodic (void)
Processes pedal sensor readings and sets faults as necessary.
int writePedalProfiles ()
void readPedalProfiles ()
Variables
pedal_faults_t pedal_faults = {0}
uint16_t thtl_limit = 4096
uint16_t t1_raw
uint16_t t2_raw
uint16_t b1_raw
uint16_t b2_raw
uint16_t t1_final
uint16_t t2_final
uint16_t b1_final
uint16_t b2_final
pedal_calibration_t pedal_calibration
pedal_values_t pedal_values
driver_pedal_profile_t driver_pedal_profiles [4]
Function Documentation
normalize()
static uint16_t normalize (uint16_t value, uint16_t min, uint16_t max) inline static
Normalizes a value between min and max to a range of 0 to MAX_PEDAL_MEAS (4095)
Parameters
value Raw value to normalize
min Minimum value of the input range
max Maximum value of the input range
Definition at line 60 of file pedals.c.
References MAX_PEDAL_MEAS.
Referenced by pedalsPeriodic().
pedalsPeriodic()
void pedalsPeriodic (void)
Processes pedal sensor readings and sets faults as necessary.
Note
This function is called periodically by the scheduler
Definition at line 70 of file pedals.c.
References ABS, APPS_BRAKE_THRESHOLD, APPS_THROTTLE_CLEARFAULT_THRESHOLD, APPS_THROTTLE_FAULT_THRESHOLD, raw_adc_values_t::b1, b1_final, pedal_calibration_t::b1_max, pedal_calibration_t::b1_min, b1_raw, raw_adc_values_t::b2, b2_final, pedal_calibration_t::b2_max, pedal_calibration_t::b2_min, b2_raw, pedal_values_t::brake, CLAMP, is_latched(), normalize(), pedal_calibration, pedal_values, raw_adc_values, raw_adc_values_t::t1, t1_final, pedal_calibration_t::t1_max, pedal_calibration_t::t1_min, t1_raw, raw_adc_values_t::t2, t2_final, pedal_calibration_t::t2_max, pedal_calibration_t::t2_min, t2_raw, pedal_values_t::throttle, and update_fault().
Referenced by preflight_task().
readPedalProfiles()
void readPedalProfiles (void)
Definition at line 141 of file pedals.c.
Referenced by initLCD().
writePedalProfiles()
int writePedalProfiles (void)
Definition at line 122 of file pedals.c.
References PROFILE_WRITE_SUCCESS.
Referenced by pedalProfilesSaveButton_CALLBACK().
Variable Documentation
b1_final
uint16_t b1_final
Definition at line 21 of file pedals.c.
Referenced by pedalsPeriodic().
b1_raw
uint16_t b1_raw
Definition at line 17 of file pedals.c.
Referenced by pedalsPeriodic().
b2_final
uint16_t b2_final
Definition at line 22 of file pedals.c.
Referenced by pedalsPeriodic().
b2_raw
uint16_t b2_raw
Definition at line 18 of file pedals.c.
Referenced by pedalsPeriodic().
driver_pedal_profiles
driver_pedal_profile_t driver_pedal_profiles[4]
Initial value:
= {
    {0, 10, 10, 0},
    {1, 10, 10, 0},
    {2, 10, 10, 0},
    {3, 10, 10, 0},
}
Definition at line 45 of file pedals.c.
Referenced by pedalProfilesPageUpdate(), and pedalProfilesSaveButton_CALLBACK().
pedal_calibration
pedal_calibration_t pedal_calibration
Initial value:
= {
    .t1_min = 980,
    .t1_max = 1600,
    .t2_min = 1550,
    .t2_max = 2050,
    .b1_min = 475,
    .b1_max = 1490,
    .b2_min = 500,
    .b2_max = 1490,
}
Definition at line 26 of file pedals.c.
Referenced by pedalsPeriodic().
pedal_faults
pedal_faults_t pedal_faults = {0}
Definition at line 10 of file pedals.c.
pedal_values
pedal_values_t pedal_values
Initial value:
= {
    .throttle = 0,
    .brake    = 0,
}
Definition at line 39 of file pedals.c.
Referenced by pedalsPeriodic(), and raceTelemetryUpdate().
t1_final
uint16_t t1_final
Definition at line 19 of file pedals.c.
Referenced by pedalsPeriodic().
t1_raw
uint16_t t1_raw
Definition at line 15 of file pedals.c.
Referenced by pedalsPeriodic().
t2_final
uint16_t t2_final
Definition at line 20 of file pedals.c.
Referenced by pedalsPeriodic().
t2_raw
uint16_t t2_raw
Definition at line 16 of file pedals.c.
Referenced by pedalsPeriodic().
thtl_limit
uint16_t thtl_limit = 4096
Definition at line 12 of file pedals.c.