PER Firmware: source/dashboard/pedals/pedals.h File Reference
pedals.h File Reference
#include <stdint.h>
Data Structures
struct pedal_values_t
Functions
void pedalsPeriodic (void)
Processes pedal sensor readings and sets faults as necessary.
Variables
pedal_values_t pedal_values
Function Documentation
pedalsPeriodic()
void pedalsPeriodic (void)
Processes pedal sensor readings and sets faults as necessary.
Note
This function is called periodically by the scheduler
Definition at line 68 of file pedals.c.
References APPS_BRAKE_THRESHOLD, APPS_THROTTLE_THRESHOLD, raw_adc_values_t::b1, raw_adc_values_t::b2, pedal_values_t::brake, BRAKE1_MAX, BRAKE1_MIN, BRAKE2_MAX, BRAKE2_MIN, clamp(), is_latched(), normalize(), pedal_values, raw_adc_values, raw_adc_values_t::t1, raw_adc_values_t::t2, pedal_values_t::throttle, THROTTLE1_MAX, THROTTLE1_MIN, THROTTLE2_MAX, THROTTLE2_MIN, and update_fault().
Referenced by main().
Variable Documentation
pedal_values
pedal_values_t pedal_values extern
Definition at line 36 of file pedals.c.
Referenced by pedalsPeriodic(), and update_pedal_telemetry().