PER Firmware: common/phal_L4/spi/spi.h File Reference
spi.h File Reference
#include <stdbool.h>
#include <stddef.h>
#include "common/phal_L4/dma/dma.h"
#include "common/phal_L4/gpio/gpio.h"
#include "common/phal_L4/rcc/rcc.h"
#include "common_defs.h"
#include "stm32l4xx.h"
Data Structures
struct SPI_InitConfig_t
Configuration entry for SPI initilization.
Macros
#define SPI1_RXDMA_CONT_CONFIG(rx_addr_, priority_)
#define SPI1_TXDMA_CONT_CONFIG(tx_addr_, priority_)
#define SPI2_RXDMA_CONT_CONFIG(rx_addr_, priority_)
#define SPI2_TXDMA_CONT_CONFIG(tx_addr_, priority_)
Functions
bool PHAL_SPI_init (SPI_InitConfig_t *handle)
Initilize SPI peripheral with the configuired structure.
bool PHAL_SPI_transfer (SPI_InitConfig_t *spi, const uint8_t *out_data, const uint32_t data_len, const uint8_t *in_data)
Transfer data_len bytes from out_data to SPI device and place MISO data in in_data This function just starts the DMA transfer,.
bool PHAL_SPI_transfer_noDMA (SPI_InitConfig_t *spi, const uint8_t *out_data, uint32_t txlen, uint32_t rxlen, uint8_t *in_data)
SPI handle.
bool PHAL_SPI_busy (SPI_InitConfig_t *cfg)
Check for current SPI transaction to complete.
uint8_t PHAL_SPI_writeByte (SPI_InitConfig_t *spi, uint8_t address, uint8_t writeDat)
Blocking function to write a single byte to a SPI device. Useful for Initilization functions that just need to write a single byte in a blocking function.
uint8_t PHAL_SPI_readByte (SPI_InitConfig_t *spi, uint8_t address, bool skipDummy)
Blocking function to read a single byte from a SPI device. Useful for Initilization functions that just need to read a single byte in a blocking function.
Detailed Description
Author
Adam Busch (busch.nosp@m.8@pu.nosp@m.rdue..nosp@m.edu)
Version
0.1
Date
2022-01-22
Copyright
Copyright (c) 2021
Definition in file spi.h.
Macro Definition Documentation
SPI1_RXDMA_CONT_CONFIG
#define SPI1_RXDMA_CONT_CONFIG (rx_addr_, priority_)
Value:
    { \
        .periph_addr      = (uint32_t)&(SPI1->DR), \
        .mem_addr         = (uint32_t)(rx_addr_), \
        .tx_size          = 1, \
        .increment        = false, \
        .circular         = false, \
        .dir              = 0b0, \
        .mem_inc          = true, \
        .periph_inc       = false, \
        .mem_to_mem       = false, \
        .priority         = (priority_), \
        .mem_size         = 0b00, \
        .periph_size      = 0b00, \
        .tx_isr_en        = true, \
        .dma_chan_request = 0b0001, \
        .channel_idx      = 2, \
        .periph           = DMA1, \
        .channel          = DMA1_Channel2, \
        .request          = DMA1_CSELR}
Definition at line 107 of file spi.h.
SPI1_TXDMA_CONT_CONFIG
#define SPI1_TXDMA_CONT_CONFIG (tx_addr_, priority_)
Value:
    { \
        .periph_addr      = (uint32_t)&(SPI1->DR), \
        .mem_addr         = (uint32_t)(tx_addr_), \
        .tx_size          = 1, \
        .increment        = false, \
        .circular         = false, \
        .dir              = 0b1, \
        .mem_inc          = true, \
        .periph_inc       = false, \
        .mem_to_mem       = false, \
        .priority         = (priority_), \
        .mem_size         = 0b00, \
        .periph_size      = 0b00, \
        .tx_isr_en        = false, \
        .dma_chan_request = 0b0001, \
        .channel_idx      = 3, \
        .periph           = DMA1, \
        .channel          = DMA1_Channel3, \
        .request          = DMA1_CSELR}
Definition at line 128 of file spi.h.
SPI2_RXDMA_CONT_CONFIG
#define SPI2_RXDMA_CONT_CONFIG (rx_addr_, priority_)
Value:
    { \
        .periph_addr      = (uint32_t)&(SPI2->DR), \
        .mem_addr         = (uint32_t)(rx_addr_), \
        .tx_size          = 1, \
        .increment        = false, \
        .circular         = false, \
        .dir              = 0b0, \
        .mem_inc          = true, \
        .periph_inc       = false, \
        .mem_to_mem       = false, \
        .priority         = (priority_), \
        .mem_size         = 0b00, \
        .periph_size      = 0b00, \
        .tx_isr_en        = true, \
        .dma_chan_request = 0b0001, \
        .channel_idx      = 4, \
        .periph           = DMA1, \
        .channel          = DMA1_Channel4, \
        .request          = DMA1_CSELR}
Definition at line 149 of file spi.h.
SPI2_TXDMA_CONT_CONFIG
#define SPI2_TXDMA_CONT_CONFIG (tx_addr_, priority_)
Value:
    { \
        .periph_addr      = (uint32_t)&(SPI2->DR), \
        .mem_addr         = (uint32_t)(tx_addr_), \
        .tx_size          = 1, \
        .increment        = false, \
        .circular         = false, \
        .dir              = 0b1, \
        .mem_inc          = true, \
        .periph_inc       = false, \
        .mem_to_mem       = false, \
        .priority         = (priority_), \
        .mem_size         = 0b00, \
        .periph_size      = 0b00, \
        .tx_isr_en        = false, \
        .dma_chan_request = 0b0001, \
        .channel_idx      = 5, \
        .periph           = DMA1, \
        .channel          = DMA1_Channel5, \
        .request          = DMA1_CSELR}
Definition at line 170 of file spi.h.
Function Documentation
PHAL_SPI_busy()
bool PHAL_SPI_busy (SPI_InitConfig_t * cfg)
Check for current SPI transaction to complete.
Parameters
cfg Spi config
Returns
true
false
Definition at line 215 of file spi.c.
References SPI_InitConfig_t::_busy, active_transfer, and SPI_InitConfig_t::periph.
Referenced by BMI088_readAccel(), BMI088_readGyro(), LED_control(), PHAL_SPI_readByte(), PHAL_SPI_transfer(), PHAL_SPI_transfer(), PHAL_SPI_transfer_noDMA(), PHAL_SPI_writeByte(), readMem(), readPage(), and writePage().
PHAL_SPI_init()
bool PHAL_SPI_init (SPI_InitConfig_t * handle)
Initilize SPI peripheral with the configuired structure.
Parameters
handle SPI handle to configure.
Returns
true
false
Definition at line 22 of file spi.c.
References SPI_InitConfig_t::_busy, SPI_InitConfig_t::_direct_mode_error, SPI_InitConfig_t::_error, SPI_InitConfig_t::_fifo_overrun, APB1ClockRateHz, APB2ClockRateHz, CLAMP, SPI_InitConfig_t::cpha, SPI_InitConfig_t::cpol, SPI_InitConfig_t::data_len, SPI_InitConfig_t::data_rate, LOG2_DOWN(), SPI_InitConfig_t::mode, SPI_InitConfig_t::nss_gpio_pin, SPI_InitConfig_t::nss_gpio_port, SPI_InitConfig_t::nss_sw, SPI_InitConfig_t::periph, PHAL_initDMA(), PHAL_writeGPIO(), SPI_InitConfig_t::rx_dma_cfg, SPI_MODE_MASTER, SPI_InitConfig_t::tx_dma_cfg, and zero.
Referenced by main(), main(), and preflightChecks().
PHAL_SPI_readByte()
uint8_t PHAL_SPI_readByte (SPI_InitConfig_t * spi, uint8_t address, bool skipDummy)
Blocking function to read a single byte from a SPI device. Useful for Initilization functions that just need to read a single byte in a blocking function.
Parameters
spi Spi handle
address Address of data to read
skipDummy Return the 3rd byte read instead of the 2nd byte
Blocking function to read a single byte from a SPI device. Useful for Initilization functions that just need to read a single byte in a blocking function.
Definition at line 421 of file spi.c.
References PHAL_SPI_busy(), PHAL_SPI_transfer(), PHAL_SPI_transfer_noDMA(), and SPI_InitConfig_t::rx_dma_cfg.
Referenced by BMI088_checkGyroHealth(), BMI088_gyroSelfTestComplete(), BMI088_gyroSelfTestPass(), BMI088_init(), and BMI088_initAccel().
PHAL_SPI_transfer()
bool PHAL_SPI_transfer (SPI_InitConfig_t * spi, const uint8_t * out_data, const uint32_t data_len, const uint8_t * in_data)
Transfer data_len bytes from out_data to SPI device and place MISO data in in_data This function just starts the DMA transfer,.
Parameters
spi SPI handle
out_data Address of data buffer to put on MOSI line
data_len Number of SPI packets to send
in_data Address of data buffer to put data coming in MISO line
Returns
true Able to start DMA transaction
false Unable to start DMA transaction
Definition at line 153 of file spi.c.
References SPI_InitConfig_t::_busy, active_transfer, dma_init_t::channel, SPI_InitConfig_t::nss_gpio_pin, SPI_InitConfig_t::nss_gpio_port, SPI_InitConfig_t::nss_sw, SPI_InitConfig_t::periph, PHAL_DMA_setMemAddress(), PHAL_DMA_setTxferLength(), PHAL_reEnable(), PHAL_SPI_busy(), PHAL_startTxfer(), PHAL_writeGPIO(), SPI_InitConfig_t::rx_dma_cfg, dma_init_t::stream, trash_can, SPI_InitConfig_t::tx_dma_cfg, and zero.
Referenced by LED_control(), PHAL_SPI_readByte(), PHAL_SPI_writeByte(), readPage(), and writePage().
PHAL_SPI_transfer_noDMA()
bool PHAL_SPI_transfer_noDMA (SPI_InitConfig_t * spi, const uint8_t * out_data, uint32_t txlen, uint32_t rxlen, uint8_t * in_data)
SPI handle.
Parameters
spi SPI handle
out_data Address of data buffer to put on MOSI line
txlen Number of SPI Packets to Send
rxlen Number of SPI Packets to Receive
in_data Address of data buffer to put data coming in MISO line
Returns
true Successfully completed non-DMA SPI transaction
false Unable to complete non-DMA SPI transaction
Definition at line 87 of file spi.c.
References SPI_InitConfig_t::_busy, active_transfer, SPI_InitConfig_t::mode, SPI_InitConfig_t::nss_gpio_pin, SPI_InitConfig_t::nss_gpio_port, SPI_InitConfig_t::nss_sw, SPI_InitConfig_t::periph, PHAL_SPI_busy(), PHAL_writeGPIO(), and SPI_MODE_MASTER.
Referenced by adbms6380_read(), adbms_connect(), adbms_read_therms(), adbms_write_rega(), adbms_write_regb(), BMI088_readAccel(), BMI088_readGyro(), PHAL_SPI_readByte(), and PHAL_SPI_writeByte().
PHAL_SPI_writeByte()
uint8_t PHAL_SPI_writeByte (SPI_InitConfig_t * spi, uint8_t address, uint8_t writeDat)
Blocking function to write a single byte to a SPI device. Useful for Initilization functions that just need to write a single byte in a blocking function.
Parameters
spi Spi handle
address Address of data to read
writeDat Data to write to address
Definition at line 440 of file spi.c.
References PHAL_SPI_busy(), PHAL_SPI_transfer(), PHAL_SPI_transfer_noDMA(), and SPI_InitConfig_t::tx_dma_cfg.
Referenced by BMI088_getGyroScale(), BMI088_gyroSelfTestStart(), BMI088_init(), BMI088_initAccel(), and BMI088_wakeAccel().