PER Firmware: common/phal_G4/adc/adc.c File Reference
adc.c File Reference
#include "common/phal_G4/adc/adc.h"
Functions
static bool PHAL_configureOversampling (ADCInitConfig_t *config)
static bool PHAL_configureADCChannels (ADCInitConfig_t *config, ADCChannelConfig_t channels[], uint8_t num_channels)
bool PHAL_initADC (ADCInitConfig_t *config, ADCChannelConfig_t channels[], uint8_t num_channels)
Initializes the ADC, requires GPIO config prior.
bool PHAL_startADC (ADCInitConfig_t *config)
Starts the ADC conversions, requires PHAL_initADC to be called prior.
bool PHAL_stopADC (ADCInitConfig_t *config)
Stops the ADC conversions, requires PHAL_initADC to be called prior.
uint16_t PHAL_readADC (ADCInitConfig_t *config)
Reads the ADC data register.
Detailed Description
Author
Eilen Yoon - Port of F4 HAL by Aditya Anand, Chris McGalliard
Version
0.1
Date
2023-09-17
Definition in file adc.c.
Function Documentation
PHAL_configureADCChannels()
static bool PHAL_configureADCChannels (ADCInitConfig_t * config, ADCChannelConfig_t channels[], uint8_t num_channels) static
Definition at line 53 of file adc.c.
References ADCChannelConfig_t::channel, config, ADCChannelConfig_t::rank, and ADCChannelConfig_t::sampling_time.
Referenced by PHAL_initADC().
PHAL_configureOversampling()
static bool PHAL_configureOversampling (ADCInitConfig_t * config) static
Definition at line 13 of file adc.c.
References ADC_OVERSAMPLE_NONE, and config.
Referenced by PHAL_initADC().
PHAL_initADC()
bool PHAL_initADC (ADCInitConfig_t * config, ADCChannelConfig_t channels[], uint8_t num_channels)
Initializes the ADC, requires GPIO config prior.
Parameters
adc ADC handle
config ADC initial config settings
channels List of channel configurations
num_channels Number of channels in the channel configuration list
Definition at line 104 of file adc.c.
References ADC_DMA_CIRCULAR, ADC_DMA_ONESHOT, config, PHAL_configureADCChannels(), and PHAL_configureOversampling().
PHAL_readADC()
uint16_t PHAL_readADC (ADCInitConfig_t * config)
Reads the ADC data register.
Parameters
adc ADC handle
Returns
contents of the data register
Definition at line 196 of file adc.c.
References config.
PHAL_startADC()
bool PHAL_startADC (ADCInitConfig_t * config)
Starts the ADC conversions, requires PHAL_initADC to be called prior.
Parameters
adc ADC handle
Definition at line 182 of file adc.c.
References config.
PHAL_stopADC()
bool PHAL_stopADC (ADCInitConfig_t * config)
Stops the ADC conversions, requires PHAL_initADC to be called prior.
Parameters
adc ADC handle
Definition at line 187 of file adc.c.
References config.