PER Firmware: common/phal_G4/usart/usart.h File Reference
usart.h File Reference
#include "common/phal_G4/dma/dma.h"
#include "common/phal_G4/phal_G4.h"
Data Structures
struct usart_rx_errors_t
struct usart_tx_errors_t
struct usart_init_t
Macros
#define TOTAL_NUM_UART 8
#define USART1_ACTIVE_IDX 0
#define USART2_ACTIVE_IDX 1
#define USART3_ACTIVE_IDX 2
#define UART4_ACTIVE_IDX 3
#define LPUART1_ACTIVE_IDX 4
#define USART5_ACTIVE_IDX 5
#define USART6_ACTIVE_IDX 6
#define USART7_ACTIVE_IDX 7
#define _DEF_USART_RXDMA_CONFIG(rx_addr_, priority_, USARTx, dma_num, channel_num, req_id)
#define _DEF_USART_TXDMA_CONFIG(tx_addr_, priority_, USARTx, dma_num, channel_num, req_id)
#define USART1_RXDMA_CONT_CONFIG(a, p)
#define USART1_TXDMA_CONT_CONFIG(a, p)
#define USART2_RXDMA_CONT_CONFIG(a, p)
#define USART2_TXDMA_CONT_CONFIG(a, p)
#define USART3_RXDMA_CONT_CONFIG(a, p)
#define USART3_TXDMA_CONT_CONFIG(a, p)
#define UART4_RXDMA_CONT_CONFIG(a, p)
#define UART4_TXDMA_CONT_CONFIG(a, p)
#define LPUART1_RXDMA_CONT_CONFIG(a, p)
#define LPUART1_TXDMA_CONT_CONFIG(a, p)
Enumerations
enum parity_t { PT_EVEN = 0b010 , PT_ODD = 0b100 , PT_NONE = 0b000 }
enum word_length_t { WORD_7 , WORD_8 , WORD_9 }
enum stop_bits_t { SB_ONE = 0b00 , SB_TWO = 0b01 , SB_HALF = 0b10 , SB_ONE_HALF = 0b11 }
enum hw_flow_ctl_t { HW_DISABLE , CTS , RTS , CTS_RTS }
enum ovsample_t { OV_16 = 0 , OV_8 = 1 }
enum obsample_t { OB_DISABLE , OB_ENABLE }
Functions
bool PHAL_initUSART (usart_init_t *handle, const uint32_t fck)
Initialize a USART Peripheral with desired settings.
void PHAL_usartTxBl (usart_init_t *handle, uint8_t *data, uint32_t len)
TX using no DMA (blocks until complete)
void PHAL_usartRxBl (usart_init_t *handle, uint8_t *data, uint32_t len)
RX using no DMA (blocks until complete)
bool PHAL_usartTxDma (usart_init_t *handle, uint8_t *data, uint32_t len)
Starts a tx using dma, use PHAL_usartTxDmaComplete to ensure the previous transmission is complete.
bool PHAL_usartRxDma (usart_init_t *handle, uint8_t *data, uint32_t len, bool cont)
Starts an rx using dma of a specific length.
bool PHAL_disableContinousRxDMA (usart_init_t *handle)
Disables the Continous RX that was previously used.
volatile bool PHAL_usartTxBusy (usart_init_t *handle)
Returns whether USART peripheral is currently transmitting data.
bool PHAL_usartRxBusy (usart_init_t *handle)
Returns whether USART peripheral is currently receiving data.
void usart_receive_complete_callback (usart_init_t *handle)
Callback function called immediately after reception of a USART RX message Uses USART IDLE line interrupt.
Macro Definition Documentation
_DEF_USART_RXDMA_CONFIG
#define _DEF_USART_RXDMA_CONFIG (rx_addr_, priority_, USARTx, dma_num, channel_num, req_id)
Value:
    { \
        .periph_addr = (uint32_t)&((USARTx)->RDR), \
        .mem_addr    = (uint32_t)(rx_addr_), \
        .tx_size     = 1, \
        .circular    = false, \
        .mem_inc     = true, \
        .periph_inc  = false, \
        .mem_to_mem  = false, \
        .priority    = (priority_), \
        .dir         = 0, \
        .mem_size    = DMA_SIZE_8BIT, \
        .periph_size = DMA_SIZE_8BIT, \
        .tx_isr_en   = true, \
        .mux_request = (req_id), \
        .channel_idx = (channel_num), \
        .periph      = DMA##dma_num, \
    }
Definition at line 188 of file usart.h.
_DEF_USART_TXDMA_CONFIG
#define _DEF_USART_TXDMA_CONFIG (tx_addr_, priority_, USARTx, dma_num, channel_num, req_id)
Value:
    { \
        .periph_addr = (uint32_t)&((USARTx)->TDR), \
        .mem_addr    = (uint32_t)(tx_addr_), \
        .tx_size     = 1, \
        .circular    = false, \
        .mem_inc     = true, \
        .periph_inc  = false, \
        .mem_to_mem  = false, \
        .priority    = (priority_), \
        .dir         = 1, \
        .mem_size    = DMA_SIZE_8BIT, \
        .periph_size = DMA_SIZE_8BIT, \
        .tx_isr_en   = true, \
        .mux_request = (req_id), \
        .channel_idx = (channel_num), \
        .periph      = DMA##dma_num, \
    }
Definition at line 207 of file usart.h.
LPUART1_ACTIVE_IDX
#define LPUART1_ACTIVE_IDX 4
Definition at line 12 of file usart.h.
Referenced by DMA2_Channel6_IRQHandler(), DMA2_Channel7_IRQHandler(), and LPUART1_IRQHandler().
LPUART1_RXDMA_CONT_CONFIG
#define LPUART1_RXDMA_CONT_CONFIG (a, p)
Value:
    _DEF_USART_RXDMA_CONFIG(a, p, LPUART1, 2, 6, DMA_REQUEST_LPUART1_RX)
Definition at line 246 of file usart.h.
LPUART1_TXDMA_CONT_CONFIG
#define LPUART1_TXDMA_CONT_CONFIG (a, p)
Value:
    _DEF_USART_TXDMA_CONFIG(a, p, LPUART1, 2, 7, DMA_REQUEST_LPUART1_TX)
Definition at line 248 of file usart.h.
TOTAL_NUM_UART
#define TOTAL_NUM_UART 8
Definition at line 5 of file usart.h.
UART4_ACTIVE_IDX
#define UART4_ACTIVE_IDX 3
Definition at line 11 of file usart.h.
UART4_RXDMA_CONT_CONFIG
#define UART4_RXDMA_CONT_CONFIG (a, p)
Value:
    _DEF_USART_RXDMA_CONFIG(a, p, UART4, 2, 5, DMA_REQUEST_UART4_RX)
Definition at line 241 of file usart.h.
UART4_TXDMA_CONT_CONFIG
#define UART4_TXDMA_CONT_CONFIG (a, p)
Value:
    _DEF_USART_TXDMA_CONFIG(a, p, UART4, 2, 3, DMA_REQUEST_UART4_TX)
Definition at line 243 of file usart.h.
USART1_ACTIVE_IDX
#define USART1_ACTIVE_IDX 0
Definition at line 8 of file usart.h.
Referenced by DMA1_Channel5_IRQHandler(), DMA1_Channel7_IRQHandler(), and USART1_IRQHandler().
USART1_RXDMA_CONT_CONFIG
#define USART1_RXDMA_CONT_CONFIG (a, p)
Value:
    _DEF_USART_RXDMA_CONFIG(a, p, USART1, 1, 5, DMA_REQUEST_USART1_RX)
Definition at line 226 of file usart.h.
USART1_TXDMA_CONT_CONFIG
#define USART1_TXDMA_CONT_CONFIG (a, p)
Value:
    _DEF_USART_TXDMA_CONFIG(a, p, USART1, 1, 7, DMA_REQUEST_USART1_TX)
Definition at line 228 of file usart.h.
USART2_ACTIVE_IDX
#define USART2_ACTIVE_IDX 1
Definition at line 9 of file usart.h.
Referenced by DMA1_Channel3_IRQHandler(), DMA1_Channel4_IRQHandler(), and USART2_IRQHandler().
USART2_RXDMA_CONT_CONFIG
#define USART2_RXDMA_CONT_CONFIG (a, p)
Value:
    _DEF_USART_RXDMA_CONFIG(a, p, USART2, 1, 3, DMA_REQUEST_USART2_RX)
Definition at line 231 of file usart.h.
USART2_TXDMA_CONT_CONFIG
#define USART2_TXDMA_CONT_CONFIG (a, p)
Value:
    _DEF_USART_TXDMA_CONFIG(a, p, USART2, 1, 4, DMA_REQUEST_USART2_TX)
Definition at line 233 of file usart.h.
USART3_ACTIVE_IDX
#define USART3_ACTIVE_IDX 2
Definition at line 10 of file usart.h.
Referenced by DMA1_Channel1_IRQHandler(), DMA1_Channel2_IRQHandler(), and USART3_IRQHandler().
USART3_RXDMA_CONT_CONFIG
#define USART3_RXDMA_CONT_CONFIG (a, p)
Value:
    _DEF_USART_RXDMA_CONFIG(a, p, USART3, 1, 1, DMA_REQUEST_USART3_RX)
Definition at line 236 of file usart.h.
USART3_TXDMA_CONT_CONFIG
#define USART3_TXDMA_CONT_CONFIG (a, p)
Value:
    _DEF_USART_TXDMA_CONFIG(a, p, USART3, 1, 2, DMA_REQUEST_USART3_TX)
Definition at line 238 of file usart.h.
USART5_ACTIVE_IDX
#define USART5_ACTIVE_IDX 5
Definition at line 13 of file usart.h.
USART6_ACTIVE_IDX
#define USART6_ACTIVE_IDX 6
Definition at line 14 of file usart.h.
USART7_ACTIVE_IDX
#define USART7_ACTIVE_IDX 7
Definition at line 15 of file usart.h.
Enumeration Type Documentation
hw_flow_ctl_t
enum hw_flow_ctl_t
Enumerator
HW_DISABLE
Hardware flow control disable.
CTS
Enable Clear to send control.
RTS
Enable Request to send control.
CTS_RTS
Enable both CTS and RTS.
Definition at line 44 of file usart.h.
obsample_t
enum obsample_t
Enumerator
OB_DISABLE
Disable one bit sampling.
OB_ENABLE
Enable one bit sampling.
Definition at line 56 of file usart.h.
ovsample_t
enum ovsample_t
Enumerator
OV_16
Oversample by 16.
OV_8
Oversample by 8.
Definition at line 51 of file usart.h.
parity_t
enum parity_t
Enumerator
PT_EVEN
Even Parity.
PT_ODD
Odd Parity.
PT_NONE
Disable Parity bits.
Definition at line 25 of file usart.h.
stop_bits_t
enum stop_bits_t
Enumerator
SB_ONE
One Stop bit.
SB_TWO
Two Stop bits.
SB_HALF
One half stop bit.
SB_ONE_HALF
1.5 Stop bits
Definition at line 37 of file usart.h.
word_length_t
enum word_length_t
Enumerator
WORD_7
WORD_8
8-Bit word length
WORD_9
9-Bit word length
Definition at line 31 of file usart.h.
Function Documentation
PHAL_disableContinousRxDMA()
bool PHAL_disableContinousRxDMA (usart_init_t * handle)
Disables the Continous RX that was previously used.
Parameters
handle The handle for the usart configuration
Disables the Continous RX that was previously used.
Parameters
handle Pointer to the USART handle.
Returns
true if the operation was successful, false otherwise.
Definition at line 337 of file usart.c.
References usart_active_transfer_t::_rx_busy, usart_active_transfer_t::active_handle, active_uarts, dma_init_t::channel_idx, usart_active_transfer_t::cont_rx, dma_init_t::periph, usart_init_t::periph, usart_init_t::rx_dma_cfg, and usart_init_t::usart_active_num.
PHAL_initUSART()
bool PHAL_initUSART (usart_init_t * handle, const uint32_t fck)
Initialize a USART Peripheral with desired settings.
Parameters
handle Handle containing settings for USART peripheral
fck Clock rate going to USART peripheral (APBx bus)
Returns
true Successfully initialized USART peripheral
false Failed to initialize USART peripheral
Initialize a USART Peripheral with desired settings.
This function configures the USART peripheral, calculates and sets the baud rate, and enables the necessary clocks and DMA streams.
Parameters
handle Pointer to a usart_init_t struct containing the configuration.
fck The clock frequency of the peripheral in Hz.
Returns
true if initialization is successful, false otherwise.
Definition at line 34 of file usart.c.
References usart_active_transfer_t::active_handle, active_uarts, usart_init_t::address, usart_init_t::baud_rate, usart_init_t::obsample, OV_16, OV_8, usart_init_t::ovsample, usart_init_t::parity, usart_init_t::periph, PHAL_initDMA(), PT_NONE, ROUNDDOWN(), ROUNDUP(), usart_init_t::rx_dma_cfg, usart_init_t::stop_bits, usart_init_t::tx_dma_cfg, usart_init_t::usart_active_num, usart_init_t::wake_addr, WORD_7, WORD_9, and usart_init_t::word_length.
Referenced by main(), and main().
PHAL_usartRxBl()
void PHAL_usartRxBl (usart_init_t * handle, uint8_t * data, uint32_t len)
RX using no DMA (blocks until complete)
Parameters
handle The handle for the usart configuration
data The address of the data to receive
len Number of u8s expected to receive. Will block if not received.
RX using no DMA (blocks until complete)
Parameters
handle Pointer to the USART handle.
data Pointer to the buffer to store received data.
len The length of the data to receive in bytes.
Definition at line 182 of file usart.c.
References usart_init_t::periph.
PHAL_usartRxBusy()
bool PHAL_usartRxBusy (usart_init_t * handle)
Returns whether USART peripheral is currently receiving data.
Parameters
handle Handle of USART peripheral check
Returns
true USART peripheral is currently receiving a message
false USART peripheal is not currently receiving a message
Returns whether USART peripheral is currently receiving data.
Parameters
handle Pointer to the USART handle.
Returns
true if the peripheral is busy, false otherwise.
Definition at line 396 of file usart.c.
References usart_active_transfer_t::_rx_busy, active_uarts, and usart_init_t::usart_active_num.
PHAL_usartRxDma()
bool PHAL_usartRxDma (usart_init_t * handle, uint8_t * data, uint32_t len, bool cont)
Starts an rx using dma of a specific length.
Parameters
handle The handle for the usart configuration
data The address to put the received data, ensure a cast to (uint16_t *), even if 8 bits
len Number of units of data, depending on the configured word length
cont Enable Continous RX using the idle line interrupt (only need to call this function once, and HAL will keep recieving messages of the same length)
Starts an rx using dma of a specific length.
Parameters
handle Pointer to the USART handle.
data Pointer to the buffer to store received data.
len The length of the data to receive in bytes.
cont true for continuous reception, false for single reception.
Returns
true if the transfer was started, false otherwise.
Definition at line 213 of file usart.c.
References usart_active_transfer_t::active_handle, active_uarts, dma_init_t::channel_idx, usart_active_transfer_t::cont_rx, dma_init_t::periph, usart_init_t::periph, PHAL_DMA_setMemAddress(), PHAL_DMA_setTxferLength(), PHAL_startTxfer(), usart_init_t::rx_dma_cfg, usart_active_transfer_t::rxfer_size, and usart_init_t::usart_active_num.
PHAL_usartTxBl()
void PHAL_usartTxBl (usart_init_t * handle, uint8_t * data, uint32_t len)
TX using no DMA (blocks until complete)
Parameters
handle The handle for the usart configuration
data The address of the data to send
len Number of u8s
TX using no DMA (blocks until complete)
Parameters
handle Pointer to the USART handle.
data Pointer to the data to transmit.
len The length of the data in bytes.
Definition at line 150 of file usart.c.
References usart_init_t::periph.
PHAL_usartTxBusy()
volatile bool PHAL_usartTxBusy (usart_init_t * handle)
Returns whether USART peripheral is currently transmitting data.
Parameters
handle Handle of USART peripheral to check
Returns
true USART peripheral is currently sending a message
false USART peripheal is not currently sending a message
Returns whether USART peripheral is currently transmitting data.
Parameters
handle Pointer to the USART handle.
Returns
true if the peripheral is busy, false otherwise.
Definition at line 273 of file usart.c.
References usart_active_transfer_t::_tx_busy, active_uarts, and usart_init_t::usart_active_num.
Referenced by lcd_tx_cmd().
PHAL_usartTxDma()
bool PHAL_usartTxDma (usart_init_t * handle, uint8_t * data, uint32_t len)
Starts a tx using dma, use PHAL_usartTxDmaComplete to ensure the previous transmission is complete.
Parameters
handle The handle for the usart configuration
data The address of the data to send, ensure a cast to (uint16_t *), even if 8 bits
len Number of units of data, depending on the configured word length
Starts a tx using dma, use PHAL_usartTxDmaComplete to ensure the previous transmission is complete.
Parameters
handle Pointer to the USART handle.
data Pointer to the data to transmit.
len The length of the data in bytes.
Returns
true if the transfer was started, false otherwise.
Definition at line 160 of file usart.c.
References usart_active_transfer_t::_tx_busy, usart_active_transfer_t::active_handle, active_uarts, dma_init_t::channel_idx, dma_init_t::periph, usart_init_t::periph, PHAL_DMA_setMemAddress(), PHAL_DMA_setTxferLength(), PHAL_reEnable(), PHAL_startTxfer(), PHAL_stopTxfer(), usart_init_t::tx_dma_cfg, and usart_init_t::usart_active_num.
usart_receive_complete_callback()
void usart_receive_complete_callback (usart_init_t * handle) extern
Callback function called immediately after reception of a USART RX message Uses USART IDLE line interrupt.
NOTE: this is executed during an interrupt handler call, so keep code in this function light
Parameters
handle Handle of USART peripheral that just recieved a message
Definition at line 436 of file usart.c.
Referenced by handleUsartIRQ().