PER Firmware: common/phal_L4/dma/dma.h File Reference
dma.h File Reference
Basic DMA Peripheral HAL library for setting up DMA transfers.
#include <stdbool.h>
Data Structures
struct dma_init_t
Functions
bool PHAL_initDMA (dma_init_t *init)
Initialize DMA peripheral to set m2m, p2p, or p2m with set size and length of txfer.
void PHAL_startTxfer (dma_init_t *init)
Start txfer after sucessful DMA peripheral initialization.
void PHAL_stopTxfer (dma_init_t *init)
Stop txfer.
void PHAL_reEnable (dma_init_t *init)
Re-enable DMA txfer after error ISR fires.
void PHAL_DMA_setMemAddress (dma_init_t *init, const uint32_t address)
Set memory address for DMA transfer. In Mem to Mem this acts as the source address.
void PHAL_DMA_setTxferLength (dma_init_t *init, const uint32_t length)
Set transfer length for DMA transaction.
Detailed Description
Basic DMA Peripheral HAL library for setting up DMA transfers.
Author
Dawson Moore (moore.nosp@m.800@.nosp@m.purdu.nosp@m.e.ed.nosp@m.u)
Version
0.1
Date
2022-01-10
Copyright
Copyright (c) 2021
Definition in file dma.h.
Function Documentation
PHAL_DMA_setMemAddress()
void PHAL_DMA_setMemAddress (dma_init_t * init, const uint32_t address)
Set memory address for DMA transfer. In Mem to Mem this acts as the source address.
Parameters
init -> Address of initialization structure
Definition at line 136 of file dma.c.
References dma_init_t::channel, and dma_init_t::stream.
Referenced by PHAL_I2C_read_a(), PHAL_I2C_write_a(), PHAL_SPI_transfer(), PHAL_SPI_transfer(), PHAL_usartRxDma(), PHAL_usartRxDma(), PHAL_usartRxDma(), PHAL_usartTxDma(), PHAL_usartTxDma(), and PHAL_usartTxDma().
PHAL_DMA_setTxferLength()
void PHAL_DMA_setTxferLength (dma_init_t * init, const uint32_t length)
Set transfer length for DMA transaction.
Parameters
init -> Address of initialization structure
Definition at line 140 of file dma.c.
References dma_init_t::channel, and dma_init_t::stream.
Referenced by handleUsartIRQ(), handleUsartIRQ(), PHAL_I2C_read_a(), PHAL_I2C_write_a(), PHAL_initDMA(), PHAL_SPI_transfer(), PHAL_SPI_transfer(), PHAL_usartRxDma(), PHAL_usartRxDma(), PHAL_usartTxDma(), PHAL_usartTxDma(), and PHAL_usartTxDma().
PHAL_initDMA()
bool PHAL_initDMA (dma_init_t * init)
Initialize DMA peripheral to set m2m, p2p, or p2m with set size and length of txfer.
Parameters
init -> Address of initialization structure
Returns
true -> Successful init (no clashing params)
false -> Init not complete (parameters clash)
Definition at line 14 of file dma.c.
References dma_init_t::channel, dma_init_t::channel_idx, dma_init_t::circular, dma_init_t::dir, dma_init_t::dma_chan_request, dma_init_t::mem_addr, dma_init_t::mem_inc, dma_init_t::mem_size, dma_init_t::mem_to_mem, dma_init_t::mux_request, dma_init_t::periph, dma_init_t::periph_addr, dma_init_t::periph_inc, dma_init_t::periph_size, PHAL_DMA_setTxferLength(), dma_init_t::priority, dma_init_t::request, dma_init_t::stream, dma_init_t::stream_idx, dma_init_t::tx_isr_en, and dma_init_t::tx_size.
Referenced by main(), main(), PHAL_I2C_init(), PHAL_initUSART(), PHAL_initUSART(), PHAL_SPI_init(), SD_LowLevel_DMA_RxConfig(), and SD_LowLevel_DMA_TxConfig().
PHAL_reEnable()
void PHAL_reEnable (dma_init_t * init)
Re-enable DMA txfer after error ISR fires.
Parameters
init -> Address of initialization structure
Definition at line 104 of file dma.c.
References dma_init_t::channel, dma_init_t::channel_idx, dma_init_t::periph, dma_init_t::stream, and dma_init_t::stream_idx.
Referenced by handleUsartIRQ(), handleUsartIRQ(), PHAL_SPI_transfer(), PHAL_SPI_transfer(), PHAL_usartRxDma(), and PHAL_usartTxDma().
PHAL_startTxfer()
void PHAL_startTxfer (dma_init_t * init)
Start txfer after sucessful DMA peripheral initialization.
Parameters
init -> Address of initialization structure
Definition at line 94 of file dma.c.
References dma_init_t::channel, and dma_init_t::stream.
Referenced by main(), main(), PHAL_I2C_read_a(), PHAL_I2C_write_a(), PHAL_SPI_transfer(), PHAL_usartRxDma(), PHAL_usartTxDma(), PHAL_usartTxDma(), PHAL_usartTxDma(), SD_LowLevel_DMA_RxConfig(), and SD_LowLevel_DMA_TxConfig().
PHAL_stopTxfer()
void PHAL_stopTxfer (dma_init_t * init)
Stop txfer.
Parameters
init -> Address of initialization structure
Definition at line 99 of file dma.c.
References dma_init_t::channel, and dma_init_t::stream.
Referenced by DMA1_Channel2_IRQHandler(), DMA2_Channel1_IRQHandler(), handleDMAxComplete(), handleDMAxComplete(), handleTxComplete(), handleTxComplete(), handleUsartIRQ(), handleUsartIRQ(), PHAL_I2C_read_a(), PHAL_I2C_write_a(), PHAL_usartRxDma(), PHAL_usartTxDma(), and PHAL_usartTxDma().