PER Firmware: common/phal_F4_F7/flash/flash.c File Reference
flash.c File Reference
#include "common/phal_F4_F7/flash/flash.h"
Functions
static uint32_t flashGetSector (uint32_t addr)
Convert address to sector number Assumes addr is within flash addr space.
static uint8_t flashUnlock ()
static void flashLock ()
uint32_t PHAL_flashReadU32 (uint32_t addr)
uint8_t PHAL_flashWriteU32 (uint32_t Address, uint32_t value)
uint8_t PHAL_flashWriteU64 (uint32_t Address, uint64_t Data)
Writes 64 bits to flash memory.
uint8_t PHAL_flashWriteU32_Buffered (uint32_t Address, uint32_t *data, uint32_t count)
uint8_t PHAL_flashErasePage (uint8_t page)
uint8_t PHAL_flashErase (uint32_t *addr, uint32_t words)
Erase pages containing [addr, addr+words)
Detailed Description
Author
Chris McGalliard - port of L4 by Adam Busch (busch.nosp@m.8@pu.nosp@m.rdue..nosp@m.edu)
Version
0.1
Date
2023-08-28
Copyright
Copyright (c) 2023
Definition in file flash.c.
Function Documentation
flashGetSector()
static uint32_t flashGetSector (uint32_t addr) static
Convert address to sector number Assumes addr is within flash addr space.
Parameters
addr Flash address
Returns
The flash sector
Definition at line 21 of file flash.c.
References addr.
Referenced by PHAL_flashErase().
flashLock()
static void flashLock () static
Definition at line 68 of file flash.c.
Referenced by PHAL_flashErasePage(), PHAL_flashErasePage(), PHAL_flashReadU32(), PHAL_flashWriteU32(), PHAL_flashWriteU32_Buffered(), and PHAL_flashWriteU64().
flashUnlock()
static uint8_t flashUnlock () static
Definition at line 54 of file flash.c.
References FLASH_KEY_1, FLASH_KEY_2, FLASH_OK, FLASH_TIMEOUT, and PHAL_FLASH_TIMEOUT.
Referenced by PHAL_flashErasePage(), PHAL_flashErasePage(), PHAL_flashReadU32(), PHAL_flashWriteU32(), PHAL_flashWriteU32_Buffered(), and PHAL_flashWriteU64().
PHAL_flashErase()
uint8_t PHAL_flashErase (uint32_t * addr, uint32_t words)
Erase pages containing [addr, addr+words)
Parameters
addr
words
Returns
uint8_t Operation result
Definition at line 222 of file flash.c.
References addr, FLASH_FAIL, FLASH_OK, flashGetSector(), and PHAL_flashErasePage().
Referenced by BL_memcpy_buffer(), BL_processCommand_Start(), and BL_setCRCConfig().
PHAL_flashErasePage()
uint8_t PHAL_flashErasePage (uint8_t page)
Definition at line 185 of file flash.c.
References FLASH_FAIL, FLASH_OK, FLASH_TIMEOUT, flashLock(), flashUnlock(), MAX_FLASH_SECTOR, and PHAL_FLASH_TIMEOUT.
Referenced by PHAL_flashErase().
PHAL_flashReadU32()
uint32_t PHAL_flashReadU32 (uint32_t addr)
Definition at line 73 of file flash.c.
References addr, FLASH_OK, flashLock(), and flashUnlock().
Referenced by BL_checkAndBoot().
PHAL_flashWriteU32()
uint8_t PHAL_flashWriteU32 (uint32_t Address, uint32_t value)
Definition at line 93 of file flash.c.
References FLASH_ADDR_NOT_CLEARED, FLASH_FAIL, FLASH_OK, FLASH_TIMEOUT, flashLock(), flashUnlock(), and PHAL_FLASH_TIMEOUT.
Referenced by BL_memcpy_buffer(), BL_setCRCConfig(), and PHAL_flashWriteU64().
PHAL_flashWriteU32_Buffered()
uint8_t PHAL_flashWriteU32_Buffered (uint32_t Address, uint32_t * data, uint32_t count)
Definition at line 148 of file flash.c.
References FLASH_OK, FLASH_TIMEOUT, flashLock(), flashUnlock(), and PHAL_FLASH_TIMEOUT.
Referenced by bitstream_data_CALLBACK().
PHAL_flashWriteU64()
uint8_t PHAL_flashWriteU64 (uint32_t address, uint64_t data)
Writes 64 bits to flash memory.
Parameters
address Location to write
data Data to write
Definition at line 139 of file flash.c.
References FLASH_OK, and PHAL_flashWriteU32().