PER Firmware: common/phal_F4_F7/can/can.c File Reference
can.c File Reference
#include "common/phal_F4_F7/can/can.h"
Functions
bool PHAL_initCAN (CAN_TypeDef *bus, bool test_mode, uint32_t bit_rate)
Initilize CAN peripheral to bit_rate.
bool PHAL_deinitCAN (CAN_TypeDef *bus)
De-initialize the CAN peripheral.
bool PHAL_txCANMessage (CanMsgTypeDef_t *msg, uint8_t txMbox)
Find an empty TX mailbox and transmit a CAN message if one is found. Function will block until sucessful transmission of message until a specified timeout.
bool PHAL_txMailboxFree (CAN_TypeDef *bus, uint8_t mbx)
void PHAL_txCANAbort (CAN_TypeDef *bus, uint8_t mbx)
bool PHAL_rxCANMessage (CAN_TypeDef *bus, uint8_t fifo, CanMsgTypeDef_t *msg)
void CAN1_RX0_IRQHandler ()
void CAN1_RX1_IRQHandler ()
Variables
uint32_t APB1ClockRateHz
Function Documentation
CAN1_RX0_IRQHandler()
void CAN1_RX0_IRQHandler ()
Definition at line 255 of file can.c.
CAN1_RX1_IRQHandler()
void CAN1_RX1_IRQHandler ()
Definition at line 259 of file can.c.
PHAL_deinitCAN()
bool PHAL_deinitCAN (CAN_TypeDef * bus)
De-initialize the CAN peripheral.
Parameters
bus The CAN peripheral to de-initialize (i.e. CAN1)
Returns
Perihperal succesfully de-initialized
Definition at line 124 of file can.c.
Referenced by daq_shutdown_hook().
PHAL_initCAN()
bool PHAL_initCAN (CAN_TypeDef * bus, bool test_mode, uint32_t bit_rate)
Initilize CAN peripheral to bit_rate.
Initilize CAN peripheral to 500k.
Parameters
test_mode Initilize CAN peripheral for self test mode
bit_rate Bit rate in bps (i.e. 500000)
Returns
true Peripheral sucessfully initalized
false Peripheral stalled during initilization
Definition at line 15 of file can.c.
References APB1ClockRateHz, PHAL_CAN_16MHz_250k, PHAL_CAN_16MHz_500k, PHAL_CAN_24MHz_250k, PHAL_CAN_24MHz_500k, PHAL_CAN_36MHz_250k, PHAL_CAN_36MHz_500k, PHAL_CAN_42MHz_500k, and PHAL_CAN_INIT_TIMEOUT.
Referenced by main(), main(), and preflightChecks().
PHAL_rxCANMessage()
bool PHAL_rxCANMessage (CAN_TypeDef * bus, uint8_t fifo, CanMsgTypeDef_t * msg)
Definition at line 221 of file can.c.
PHAL_txCANAbort()
void PHAL_txCANAbort (CAN_TypeDef * bus, uint8_t mbx)
Definition at line 205 of file can.c.
PHAL_txCANMessage()
bool PHAL_txCANMessage (CanMsgTypeDef_t * msg, uint8_t mbx)
Find an empty TX mailbox and transmit a CAN message if one is found. Function will block until sucessful transmission of message until a specified timeout.
Parameters
can CAN peripheral to transmit with
msgId Message ID
Returns
true Sucessful TX of message.
false Unable to find empty message or transmit took too long.
Definition at line 138 of file can.c.
Referenced by canTxSendToBack(), canTxUpdate(), and send_pending_can().
PHAL_txMailboxFree()
bool PHAL_txMailboxFree (CAN_TypeDef * bus, uint8_t mbx)
Definition at line 192 of file can.c.
Referenced by canTxSendToBack(), canTxUpdate(), and send_pending_can().
Variable Documentation
APB1ClockRateHz
uint32_t APB1ClockRateHz extern
Definition at line 15 of file rcc.c.
Referenced by PHAL_initCAN().