PER Firmware: common/phal_L4/flash/flash.c File Reference
flash.c File Reference
#include "common/phal_L4/flash/flash.h"
Functions
static uint32_t flashGetSector (uint32_t addr)
Convert address to sector number Assumes addr is within flash addr space.
static uint8_t flashUnlock ()
static void flashLock ()
uint8_t PHAL_flashWriteU64 (uint32_t Address, uint64_t Data)
Writes 64 bits to flash memory.
uint8_t PHAL_flashErasePage (uint16_t page)
Erase a page in flash.
uint8_t PHAL_flashErase (uint32_t *addr, uint32_t words)
Erase pages containing [addr, addr+words)
Function Documentation
flashGetSector()
static uint32_t flashGetSector (uint32_t addr) static
Convert address to sector number Assumes addr is within flash addr space.
Parameters
addr Flash address
Returns
The flash sector
Definition at line 21 of file flash.c.
References addr, FLASH_PAGE_SIZE, and USER_FLASH_BASE_ADDRESS.
flashLock()
static void flashLock () static
Definition at line 39 of file flash.c.
flashUnlock()
static uint8_t flashUnlock () static
Definition at line 25 of file flash.c.
References FLASH_KEY_1, FLASH_KEY_2, FLASH_OK, FLASH_TIMEOUT, and PHAL_FLASH_TIMEOUT.
PHAL_flashErase()
uint8_t PHAL_flashErase (uint32_t * addr, uint32_t words)
Erase pages containing [addr, addr+words)
Parameters
addr
words
Returns
uint8_t Operation result
Definition at line 138 of file flash.c.
References addr, FLASH_FAIL, FLASH_OK, flashGetSector(), and PHAL_flashErasePage().
PHAL_flashErasePage()
uint8_t PHAL_flashErasePage (uint16_t page)
Erase a page in flash.
Parameters
page Page to erase
Definition at line 96 of file flash.c.
References FLASH_BANK_PG_COUNT, FLASH_FAIL, FLASH_OK, FLASH_TIMEOUT, flashLock(), flashUnlock(), MAX_FLASH_SECTOR, and PHAL_FLASH_TIMEOUT.
PHAL_flashWriteU64()
uint8_t PHAL_flashWriteU64 (uint32_t address, uint64_t data)
Writes 64 bits to flash memory.
Parameters
address Location to write
data Data to write
Definition at line 44 of file flash.c.
References FLASH_ADDR_NOT_CLEARED, FLASH_FAIL, FLASH_OK, FLASH_TIMEOUT, flashLock(), flashUnlock(), and PHAL_FLASH_TIMEOUT.