PER Firmware: common/psched/psched.c File Reference
psched.c File Reference
#include "psched.h"
#include <stddef.h>
Functions
static void checkPreflightEnd (void)
static void schedLoop (void)
static void schedBg (void)
static void updateTime (cpu_time_t *time)
static void calcTime (cpu_time_t *time, uint8_t count, int type)
static void memsetu (uint8_t *ptr, uint8_t val, size_t size)
int taskCreate (func_ptr_t func, uint16_t task_time)
int taskCreateBackground (func_ptr_t func)
void taskDelete (uint8_t type, uint8_t task)
void configureAnim (func_ptr_t anim, func_ptr_t preflight, uint16_t anim_time, uint16_t anim_min_time)
void registerPreflightComplete (uint8_t status)
void schedInit (uint32_t freq)
void schedStart ()
void schedPause ()
void waitMicros (uint8_t time)
void TIM7_IRQHandler ()
Variables
sched_t sched
Function Documentation
calcTime()
static void calcTime (cpu_time_t * time, uint8_t count, int type) static
Definition at line 318 of file psched.c.
References E_BG_MISS, sched_t::error, sched, and updateTime().
Referenced by schedLoop().
checkPreflightEnd()
static void checkPreflightEnd (void) static
Definition at line 216 of file psched.c.
References sched_t::anim_complete, sched_t::anim_min_time, and sched.
Referenced by schedLoop().
configureAnim()
void configureAnim (func_ptr_t anim, func_ptr_t preflight, uint16_t anim_time, uint16_t anim_min_time)
Definition at line 84 of file psched.c.
References sched_t::anim, sched_t::anim_min_time, sched_t::anim_time, sched_t::preflight, sched_t::preflight_required, and sched.
Referenced by main().
memsetu()
static void memsetu (uint8_t * ptr, uint8_t val, size_t size) static
Definition at line 352 of file psched.c.
Referenced by schedInit().
registerPreflightComplete()
void registerPreflightComplete (uint8_t status)
Definition at line 100 of file psched.c.
References sched_t::preflight_complete, and sched.
Referenced by preflightChecks().
schedBg()
static void schedBg (void) static
Definition at line 280 of file psched.c.
References sched_t::anim_complete, sched_t::bg_count, sched_t::bg_pointer, sched_t::bg_time, cpu_time_t::cnt_entry, cpu_time_t::cnt_exit, sched_t::os_ticks, sched_t::preflight_complete, sched_t::preflight_required, sched_t::run_next, sched, cpu_time_t::tick_entry, and cpu_time_t::tick_exit.
Referenced by schedLoop().
schedInit()
void schedInit (uint32_t freq)
Definition at line 109 of file psched.c.
References ARR_SET, memsetu(), sched_t::of, and sched.
Referenced by main(), and main().
schedLoop()
static void schedLoop (void) static
Definition at line 229 of file psched.c.
References sched_t::anim, sched_t::anim_complete, sched_t::anim_time, sched_t::bg_time, calcTime(), checkPreflightEnd(), cpu_time_t::cnt_entry, cpu_time_t::cnt_exit, E_BG_MISS, E_FG_MISS, E_IND_FG_MISS, sched_t::fg_count, sched_t::fg_time, sched_t::ind_fg_time, sched_t::os_ticks, sched_t::preflight, sched_t::preflight_complete, sched_t::preflight_required, sched_t::run_next, sched_t::running, sched, schedBg(), sched_t::skips, sched_t::task_pointer, sched_t::task_time, cpu_time_t::tick_entry, and cpu_time_t::tick_exit.
Referenced by schedStart().
schedPause()
void schedPause ()
Definition at line 174 of file psched.c.
References sched_t::run_next, sched_t::running, and sched.
schedStart()
void schedStart ()
Definition at line 145 of file psched.c.
References sched_t::running, sched, and schedLoop().
Referenced by main(), and main().
taskCreate()
int taskCreate (func_ptr_t func, uint16_t task_time)
Definition at line 20 of file psched.c.
References E_NO_FREE_TASK, sched_t::fg_count, MAX_TASKS, sched, sched_t::task_pointer, and sched_t::task_time.
Referenced by main(), and main().
taskCreateBackground()
int taskCreateBackground (func_ptr_t func)
Definition at line 36 of file psched.c.
References sched_t::bg_count, sched_t::bg_pointer, E_NO_FREE_TASK, MAX_TASKS, and sched.
Referenced by main().
taskDelete()
void taskDelete (uint8_t type, uint8_t task)
Definition at line 52 of file psched.c.
References sched_t::bg_pointer, sched_t::fg_count, sched, TASK, sched_t::task_pointer, and sched_t::task_time.
TIM7_IRQHandler()
void TIM7_IRQHandler ()
Definition at line 377 of file psched.c.
References sched_t::os_ticks, sched_t::run_next, and sched.
updateTime()
static void updateTime (cpu_time_t * time) static
Definition at line 305 of file psched.c.
References ARR_SET.
Referenced by calcTime().
waitMicros()
void waitMicros (uint8_t time)
Definition at line 194 of file psched.c.
Variable Documentation
sched
sched_t sched
Definition at line 12 of file psched.c.
Referenced by calcTime(), checkPreflightEnd(), configureAnim(), heatBeatLED(), registerPreflightComplete(), schedBg(), schedInit(), schedLoop(), schedPause(), schedStart(), taskCreate(), taskCreateBackground(), taskDelete(), and TIM7_IRQHandler().