PER Firmware: source/dashboard/lcd/pages/race.c File Reference
race.c File Reference
Race page implementation.
#include "race.h"
#include "nextion.h"
#include "common/can_library/generated/DASHBOARD.h"
#include "pedals.h"
#include "common_defs.h"
#include "colors.h"
Functions
static void update_car_state_telemetry ()
static void update_motor_telemetry ()
static void update_igbt_telemetry ()
static void update_pack_telemetry ()
static void update_speed_telemetry ()
static void update_pedal_telemetry ()
void race_telemetry_update ()
Updates telemetry data on the race dashboard LCD display.
Variables
static constexpr float WHEEL_RADIUS_IN = 8.0f
static constexpr float GEAR_RATIO = 12.51f
static constexpr float WHEEL_CIRCUMFERENCE_IN = 2.0f * PI * WHEEL_RADIUS_IN
static constexpr float OUTPUT_REV_PER_MOTOR_REV = 1.0f / GEAR_RATIO
static constexpr float INCHES_PER_MOTOR_REV = WHEEL_CIRCUMFERENCE_IN * OUTPUT_REV_PER_MOTOR_REV
static constexpr float MINUTES_PER_HOUR = 60.0f
static constexpr float INCHES_PER_MILE = 63360.0f
static constexpr float RPM_TO_MPH = INCHES_PER_MOTOR_REV * MINUTES_PER_HOUR / INCHES_PER_MILE
Detailed Description
Race page implementation.
Author
Irving Wang (irvin.nosp@m.gw@p.nosp@m.urdue.nosp@m..edu)
Definition in file race.c.
Function Documentation
race_telemetry_update()
void race_telemetry_update ()
Updates telemetry data on the race dashboard LCD display.
Only updates on race page. Displays 'S' for stale values.
Definition at line 153 of file race.c.
References update_car_state_telemetry(), update_igbt_telemetry(), update_motor_telemetry(), update_pack_telemetry(), update_pedal_telemetry(), and update_speed_telemetry().
update_car_state_telemetry()
static void update_car_state_telemetry () inline static
Definition at line 29 of file race.c.
References BLACK, can_data, CAR_STATE, GREEN, MUTED_GREEN, MUTED_RED, MUTED_YELLOW, NXT_setBackground(), NXT_setBorderColor(), NXT_setFontColor(), NXT_setText(), RED, WHITE, and YELLOW.
Referenced by race_telemetry_update().
update_igbt_telemetry()
static void update_igbt_telemetry () inline static
Definition at line 92 of file race.c.
References can_data, IGBT_TEMP, MAX4, NXT_setText(), and NXT_setTextFormatted().
Referenced by race_telemetry_update().
update_motor_telemetry()
static void update_motor_telemetry () inline static
Definition at line 76 of file race.c.
References can_data, MAX4, MOTOR_TEMP, NXT_setText(), and NXT_setTextFormatted().
Referenced by race_telemetry_update().
update_pack_telemetry()
static void update_pack_telemetry () inline static
Definition at line 108 of file race.c.
References BATT_CURR, BATT_TEMP, BATT_VOLT, can_data, NXT_setText(), and NXT_setTextFormatted().
Referenced by race_telemetry_update().
update_pedal_telemetry()
static void update_pedal_telemetry () inline static
Definition at line 143 of file race.c.
References pedal_values_t::brake, BRK_BAR, NXT_setValue(), pedal_values, THROT_BAR, and pedal_values_t::throttle.
Referenced by race_telemetry_update().
update_speed_telemetry()
static void update_speed_telemetry () inline static
Definition at line 123 of file race.c.
References can_data, MAX4, NXT_setText(), NXT_setTextFormatted(), RPM_TO_MPH, and SPEED.
Referenced by race_telemetry_update().
Variable Documentation
GEAR_RATIO
float GEAR_RATIO = 12.51f static constexpr
Definition at line 18 of file race.c.
INCHES_PER_MILE
float INCHES_PER_MILE = 63360.0f static constexpr
Definition at line 25 of file race.c.
INCHES_PER_MOTOR_REV
float INCHES_PER_MOTOR_REV = WHEEL_CIRCUMFERENCE_IN * OUTPUT_REV_PER_MOTOR_REV static constexpr
Definition at line 22 of file race.c.
MINUTES_PER_HOUR
float MINUTES_PER_HOUR = 60.0f static constexpr
Definition at line 24 of file race.c.
OUTPUT_REV_PER_MOTOR_REV
float OUTPUT_REV_PER_MOTOR_REV = 1.0f / GEAR_RATIO static constexpr
Definition at line 21 of file race.c.
RPM_TO_MPH
float RPM_TO_MPH = INCHES_PER_MOTOR_REV * MINUTES_PER_HOUR / INCHES_PER_MILE static constexpr
Definition at line 27 of file race.c.
Referenced by update_speed_telemetry().
WHEEL_CIRCUMFERENCE_IN
float WHEEL_CIRCUMFERENCE_IN = 2.0f * PI * WHEEL_RADIUS_IN static constexpr
Definition at line 20 of file race.c.
WHEEL_RADIUS_IN
float WHEEL_RADIUS_IN = 8.0f static constexpr
Definition at line 17 of file race.c.