PER Firmware: source/dashboard/lcd/pages/race.h File Reference
race.h File Reference
Race page implementation.
Macros
#define RACE_STRING "race"
#define THROT_BAR "throt"
#define BRK_BAR "break"
#define RGN_BAR "regen"
#define FL_BAR "FL"
#define FR_BAR "FR"
#define RL_BAR "RL"
#define RR_BAR "RR"
#define PUMP_CHECK "pump"
#define BATT_TEMP "BTemp"
#define BATT_VOLT "volt"
#define BATT_CURR "amp"
#define MOTOR_TEMP "MTemp"
#define IGBT_TEMP "IGBTemp"
#define CAR_STATE "stat"
#define SPEED "speed"
#define RACE_TV_ON "tv"
#define CURRENT_TIME "current"
#define BEST_TIME "best"
#define LAP_TIME "lap"
Functions
void race_telemetry_update ()
Updates telemetry data on the race dashboard LCD display.
Detailed Description
Race page implementation.
Author
Irving Wang (irvin.nosp@m.gw@p.nosp@m.urdue.nosp@m..edu)
Definition in file race.h.
Macro Definition Documentation
BATT_CURR
#define BATT_CURR "amp"
Definition at line 24 of file race.h.
Referenced by update_pack_telemetry().
BATT_TEMP
#define BATT_TEMP "BTemp"
Definition at line 22 of file race.h.
Referenced by update_pack_telemetry().
BATT_VOLT
#define BATT_VOLT "volt"
Definition at line 23 of file race.h.
Referenced by update_pack_telemetry().
BEST_TIME
#define BEST_TIME "best"
Definition at line 31 of file race.h.
BRK_BAR
#define BRK_BAR "break"
Definition at line 15 of file race.h.
Referenced by update_pedal_telemetry().
CAR_STATE
#define CAR_STATE "stat"
Definition at line 27 of file race.h.
Referenced by update_car_state_telemetry().
CURRENT_TIME
#define CURRENT_TIME "current"
Definition at line 30 of file race.h.
FL_BAR
#define FL_BAR "FL"
Definition at line 17 of file race.h.
FR_BAR
#define FR_BAR "FR"
Definition at line 18 of file race.h.
IGBT_TEMP
#define IGBT_TEMP "IGBTemp"
Definition at line 26 of file race.h.
Referenced by update_igbt_telemetry().
LAP_TIME
#define LAP_TIME "lap"
Definition at line 32 of file race.h.
MOTOR_TEMP
#define MOTOR_TEMP "MTemp"
Definition at line 25 of file race.h.
Referenced by update_motor_telemetry().
PUMP_CHECK
#define PUMP_CHECK "pump"
Definition at line 21 of file race.h.
RACE_STRING
#define RACE_STRING "race"
Definition at line 11 of file race.h.
RACE_TV_ON
#define RACE_TV_ON "tv"
Definition at line 29 of file race.h.
RGN_BAR
#define RGN_BAR "regen"
Definition at line 16 of file race.h.
RL_BAR
#define RL_BAR "RL"
Definition at line 19 of file race.h.
RR_BAR
#define RR_BAR "RR"
Definition at line 20 of file race.h.
SPEED
#define SPEED "speed"
Definition at line 28 of file race.h.
Referenced by update_speed_telemetry().
THROT_BAR
#define THROT_BAR "throt"
Definition at line 14 of file race.h.
Referenced by update_pedal_telemetry().
Function Documentation
race_telemetry_update()
void race_telemetry_update ()
Updates telemetry data on the race dashboard LCD display.
Only updates on race page. Displays 'S' for stale values.
Definition at line 153 of file race.c.
References update_car_state_telemetry(), update_igbt_telemetry(), update_motor_telemetry(), update_pack_telemetry(), update_pedal_telemetry(), and update_speed_telemetry().