PER Firmware: source/main_module/sdc.c File Reference
sdc.c File Reference
#include "main.h"
#include "pindefs.h"
#include "common/phal/gpio.h"
#include "common/can_library/faults_common.h"
#include "common/freertos/freertos.h"
Data Structures
struct sdc_node_t
Functions
void update_SDC ()
Variables
static constexpr uint8_t SDC_UNREADABLE = 0xFF
static constexpr int NUM_SDC_NODES = 17
static const sdc_node_t SDC_NODE_LUT [NUM_SDC_NODES]
Function Documentation
update_SDC()
void update_SDC ()
Definition at line 38 of file sdc.c.
References sdc_node_t::fault_id, sdc_node_t::mux_addr, NUM_SDC_NODES, PHAL_readGPIO(), PHAL_writeGPIO(), SDC_MUX_PIN, SDC_MUX_PORT, SDC_MUX_S0_PIN, SDC_MUX_S0_PORT, SDC_MUX_S1_PIN, SDC_MUX_S1_PORT, SDC_MUX_S2_PIN, SDC_MUX_S2_PORT, SDC_MUX_S3_PIN, SDC_MUX_S3_PORT, SDC_NODE_LUT, SDC_UNREADABLE, and update_fault().
Referenced by main().
Variable Documentation
NUM_SDC_NODES
int NUM_SDC_NODES = 17 static constexpr
Definition at line 15 of file sdc.c.
Referenced by update_SDC().
SDC_NODE_LUT
const sdc_node_t SDC_NODE_LUT[NUM_SDC_NODES] static
Initial value:
= {
    {FAULT_ID_MAIN_MODULE_SDC1_IMD,  11},
    {FAULT_ID_MAIN_MODULE_SDC2_BMS,  10},
    {FAULT_ID_MAIN_MODULE_SDC3_BSPD,  9},
    {FAULT_ID_MAIN_MODULE_SDC4_MAIN_OK,  8},
    {FAULT_ID_MAIN_MODULE_SDC5_BOTS,  7},
    {FAULT_ID_MAIN_MODULE_SDC6_INERTIA,  6},
    {FAULT_ID_MAIN_MODULE_SDC7_COCKPIT_ESTOP,  5},
    {0,  SDC_UNREADABLE},
    {FAULT_ID_MAIN_MODULE_SDC9_FRONT_INTERLOCK,  4},
    {FAULT_ID_MAIN_MODULE_SDC10_RIGHT_ESTOP, 12},
    {FAULT_ID_MAIN_MODULE_SDC11_LEFT_ESTOP, 3},
    {FAULT_ID_MAIN_MODULE_SDC12_MSD, 2},
    {FAULT_ID_MAIN_MODULE_SDC13_E_METER, 13},
    {0, SDC_UNREADABLE},
    {FAULT_ID_MAIN_MODULE_SDC15_REAR_INTERLOCK, 1},
    {FAULT_ID_MAIN_MODULE_SDC16_TSMS, 14},
    {FAULT_ID_MAIN_MODULE_SDC17_AIR_M, 0}
}
Definition at line 18 of file sdc.c.
Referenced by update_SDC().
SDC_UNREADABLE
uint8_t SDC_UNREADABLE = 0xFF static constexpr
Definition at line 14 of file sdc.c.
Referenced by update_SDC().