PER Firmware: source/daq/sdio/sdio.c File Reference
sdio.c File Reference
Secure Digital Input Output Interface driver for STM32F4.
#include "sdio.h"
#include "main.h"
#include "string.h"
Macros
#define SD_LOG(...)
#define SDIO_TXDMA_CONFIG(tx_addr_, priority_)
#define SDIO_RXDMA_CONFIG(rx_addr_, priority_)
Functions
static SD_Error CmdError (void)
Checks for error conditions for CMD0.
static SD_Error CmdResp1Error (uint8_t cmd)
Checks for error conditions for R1 response.
static SD_Error CmdResp7Error (void)
Checks for error conditions for R7 response.
static SD_Error CmdResp3Error (void)
Checks for error conditions for R3 (OCR) response.
static SD_Error CmdResp2Error (void)
Checks for error conditions for R2 (CID or CSD) response.
static SD_Error CmdResp6Error (uint8_t cmd, uint16_t *prca)
Checks for error conditions for R6 (RCA) response.
static SD_Error SDEnWideBus (FunctionalState NewState)
Enables or disables the SDIO wide bus mode.
static SD_Error FindSCR (uint16_t rca, uint32_t *pscr)
Find the SD card SCR register value.
bool PHAL_SDIO_init (void)
Configures the SDIO peripheral.
SD_Error SD_Init (void)
Initialize the SD Card for Data Transfer.
SDTransferState SD_GetStatus (void)
Gets the cuurent sd card data transfer status.
SDCardState SD_GetState (void)
Returns the current card's state.
uint8_t SD_Detect (void)
Detect if SD card is correctly plugged in the memory slot.
SD_Error SD_PowerON (void)
Enquires cards about their operating voltage and configures clock controls.
SD_Error SD_InitializeCards (void)
Intialises all cards or single card as the case may be Card(s) come into standby state.
SD_Error SD_GetCardInfo (SD_CardInfo *cardinfo)
Returns information about specific card.
SD_Error SD_EnableWideBusOperation (uint32_t WideMode)
Enables wide bus opeartion for the requeseted card if supported by card.
SD_Error SD_SelectDeselect (uint64_t addr)
Selects od Deselects the corresponding card.
void PHAL_SDIO_SendCommand (PHAL_SD_Cmd_t *cmd)
Send a command.
SD_Error SD_ReadMultiBlocks (uint8_t *readbuff, uint64_t ReadAddr, uint16_t BlockSize, uint32_t NumberOfBlocks)
Allows to read blocks from a specified address in a card. The Data transfer can be managed by DMA mode or Polling mode.
SD_Error SD_WaitReadOperation (void)
This function waits until the SDIO DMA data transfer is finished. This function should be called after SDIO_ReadMultiBlocks() function to insure that all data sent by the card are already transferred by the DMA controller.
SD_Error SD_WriteMultiBlocks (uint8_t *writebuff, uint64_t WriteAddr, uint16_t BlockSize, uint32_t NumberOfBlocks)
Allows to write blocks starting from a specified address in a card. The Data transfer can be managed by DMA mode only.
SD_Error SD_WaitWriteOperation (void)
This function waits until the SDIO DMA data transfer is finished. This function should be called after SDIO_WriteBlock() and SDIO_WriteMultiBlocks() function to insure that all data sent by the card are already transferred by the DMA controller.
SD_Error SD_StopTransfer (void)
Aborts an ongoing data transfer.
SD_Error SD_SendStatus (uint32_t *pcardstatus)
Returns the current card's status.
void SDIO_IRQHandler (void)
Allows to process all the interrupts that are high.
void DMA2_Stream6_IRQHandler (void)
void SD_LowLevel_DMA_TxConfig (uint32_t *BufferSRC, uint32_t BufferSize)
Configures the DMA2 Channel4 for SDIO Tx request.
void SD_LowLevel_DMA_RxConfig (uint32_t *BufferDST, uint32_t BufferSize)
Configures the DMA2 Channel4 for SDIO Rx request.
void SD_DeInit (void)
Variables
static uint32_t CardType = ((uint32_t)0x00000000)
static uint32_t CSD_Tab [4]
static uint32_t CID_Tab [4]
static uint32_t RCA = 0
static uint8_t SDSTATUS_Tab [16]
__IO uint32_t StopCondition = 0
__IO SD_Error TransferError = SD_OK
__IO uint32_t TransferEnd = 0
__IO uint32_t DMAEndOfTransfer = 0
SD_CardInfo SDCardInfo
static uint32_t last_read_length = 0
static dma_init_t sdio_tx_config = { .periph_addr = (uint32_t)&(SDIO->FIFO), .mem_addr = (uint32_t)(NULL), .tx_size = 1, .increment = false, .circular = false, .dir = 0b1, .mem_inc = true, .periph_inc = false, .mem_to_mem = false, .priority = (3), .mem_size = 0b10, .periph_size = 0b10, .tx_isr_en = true, .dma_chan_request = 0b0100, .stream_idx = 6, .periph = DMA2, .stream = DMA2_Stream6}
static dma_init_t sdio_rx_config = { .periph_addr = (uint32_t)&(SDIO->FIFO), .mem_addr = (uint32_t)(NULL), .tx_size = 1, .increment = false, .circular = false, .dir = 0b0, .mem_inc = true, .periph_inc = false, .mem_to_mem = false, .priority = (3), .mem_size = 0b10, .periph_size = 0b10, .tx_isr_en = true, .dma_chan_request = 0b0100, .stream_idx = 6, .periph = DMA2, .stream = DMA2_Stream6}
Detailed Description
Secure Digital Input Output Interface driver for STM32F4.
Author
Tilen Majerle, modified by Luke Oxley for PER usage (lcoxl.nosp@m.ey@p.nosp@m.urdue.nosp@m..edu)
Version
0.1
Date
2023-12-31
Copyright
Copyright (c) 2023
Definition in file sdio.c.
Macro Definition Documentation
SD_LOG
#define SD_LOG (...)
Definition at line 16 of file sdio.c.
Referenced by CmdResp1Error(), SD_Init(), and SDIO_IRQHandler().
SDIO_RXDMA_CONFIG
#define SDIO_RXDMA_CONFIG (rx_addr_, priority_)
Value:
    { \
        .periph_addr      = (uint32_t)&(SDIO->FIFO), \
        .mem_addr         = (uint32_t)(rx_addr_), \
        .tx_size          = 1, \
        .increment        = false, \
        .circular         = false, \
        .dir              = 0b0, \
        .mem_inc          = true, \
        .periph_inc       = false, \
        .mem_to_mem       = false, \
        .priority         = (priority_), \
        .mem_size         = 0b10, \
        .periph_size      = 0b10, \
        .tx_isr_en        = true, \
        .dma_chan_request = 0b0100, \
        .stream_idx       = 6, \
        .periph           = DMA2, \
        .stream           = DMA2_Stream6}
Definition at line 1611 of file sdio.c.
SDIO_TXDMA_CONFIG
#define SDIO_TXDMA_CONFIG (tx_addr_, priority_)
Value:
    { \
        .periph_addr      = (uint32_t)&(SDIO->FIFO), \
        .mem_addr         = (uint32_t)(tx_addr_), \
        .tx_size          = 1, \
        .increment        = false, \
        .circular         = false, \
        .dir              = 0b1, \
        .mem_inc          = true, \
        .periph_inc       = false, \
        .mem_to_mem       = false, \
        .priority         = (priority_), \
        .mem_size         = 0b10, \
        .periph_size      = 0b10, \
        .tx_isr_en        = true, \
        .dma_chan_request = 0b0100, \
        .stream_idx       = 6, \
        .periph           = DMA2, \
        .stream           = DMA2_Stream6}
Definition at line 1571 of file sdio.c.
Function Documentation
CmdError()
static SD_Error CmdError (void) static
Checks for error conditions for CMD0.
Parameters
None
Return values
SD_Error SD Card Error code.
< 10000
Definition at line 1043 of file sdio.c.
References SD_CMD_RSP_TIMEOUT, SD_OK, SDIO_CMD0TIMEOUT, and SDIO_STATIC_FLAGS.
Referenced by SD_PowerON().
CmdResp1Error()
static SD_Error CmdResp1Error (uint8_t cmd) static
Checks for error conditions for R1 response.
Parameters
cmd The sent command index.
Return values
SD_Error SD Card Error code.
< We have received response, retrieve it for analysis
Definition at line 1101 of file sdio.c.
References SD_ADDR_MISALIGNED, SD_ADDR_OUT_OF_RANGE, SD_AKE_SEQ_ERROR, SD_ALLZERO, SD_BAD_ERASE_PARAM, SD_BLOCK_LEN_ERR, SD_CARD_ECC_DISABLED, SD_CARD_ECC_FAILED, SD_CC_ERROR, SD_CID_CSD_OVERWRITE, SD_CMD_CRC_FAIL, SD_CMD_RSP_TIMEOUT, SD_COM_CRC_FAILED, SD_ERASE_RESET, SD_ERASE_SEQ_ERR, SD_GENERAL_UNKNOWN_ERROR, SD_ILLEGAL_CMD, SD_LOCK_UNLOCK_FAILED, SD_LOG, SD_OCR_ADDR_MISALIGNED, SD_OCR_ADDR_OUT_OF_RANGE, SD_OCR_AKE_SEQ_ERROR, SD_OCR_BAD_ERASE_PARAM, SD_OCR_BLOCK_LEN_ERR, SD_OCR_CARD_ECC_DISABLED, SD_OCR_CARD_ECC_FAILED, SD_OCR_CC_ERROR, SD_OCR_CID_CSD_OVERWRIETE, SD_OCR_COM_CRC_FAILED, SD_OCR_ERASE_RESET, SD_OCR_ERASE_SEQ_ERR, SD_OCR_ERRORBITS, SD_OCR_GENERAL_UNKNOWN_ERROR, SD_OCR_ILLEGAL_CMD, SD_OCR_LOCK_UNLOCK_FAILED, SD_OCR_STREAM_READ_UNDERRUN, SD_OCR_STREAM_WRITE_OVERRUN, SD_OCR_WP_ERASE_SKIP, SD_OCR_WRITE_PROT_VIOLATION, SD_OK, SD_STREAM_READ_UNDERRUN, SD_STREAM_WRITE_OVERRUN, SD_WP_ERASE_SKIP, SD_WRITE_PROT_VIOLATION, and SDIO_STATIC_FLAGS.
Referenced by FindSCR(), SD_PowerON(), SD_ReadMultiBlocks(), SD_SelectDeselect(), SD_SendStatus(), SD_StopTransfer(), SD_WriteMultiBlocks(), and SDEnWideBus().
CmdResp2Error()
static SD_Error CmdResp2Error (void) static
Checks for error conditions for R2 (CID or CSD) response.
Parameters
None
Return values
SD_Error SD Card Error code.
Definition at line 1247 of file sdio.c.
References SD_CMD_CRC_FAIL, SD_CMD_RSP_TIMEOUT, SD_OK, and SDIO_STATIC_FLAGS.
Referenced by SD_InitializeCards().
CmdResp3Error()
static SD_Error CmdResp3Error (void) static
Checks for error conditions for R3 (OCR) response.
Parameters
None
Return values
SD_Error SD Card Error code.
Definition at line 1222 of file sdio.c.
References SD_CMD_RSP_TIMEOUT, SD_OK, and SDIO_STATIC_FLAGS.
Referenced by SD_PowerON().
CmdResp6Error()
static SD_Error CmdResp6Error (uint8_t cmd, uint16_t * prca) static
Checks for error conditions for R6 (RCA) response.
Parameters
cmd The sent command index.
prca pointer to the variable that will contain the SD card relative address RCA.
Return values
SD_Error SD Card Error code.
< We have received response, retrieve it.
Definition at line 1280 of file sdio.c.
References SD_ALLZERO, SD_CMD_CRC_FAIL, SD_CMD_RSP_TIMEOUT, SD_COM_CRC_FAILED, SD_GENERAL_UNKNOWN_ERROR, SD_ILLEGAL_CMD, SD_OK, SD_R6_COM_CRC_FAILED, SD_R6_GENERAL_UNKNOWN_ERROR, SD_R6_ILLEGAL_CMD, and SDIO_STATIC_FLAGS.
Referenced by SD_InitializeCards().
CmdResp7Error()
static SD_Error CmdResp7Error (void) static
Checks for error conditions for R7 response.
Parameters
None
Return values
SD_Error SD Card Error code.
< Card is not V2.0 complient or card does not support the set voltage range
< Card is SD V2.0 compliant
Definition at line 1068 of file sdio.c.
References SD_CMD_RSP_TIMEOUT, SD_OK, and SDIO_CMD0TIMEOUT.
Referenced by SD_PowerON().
DMA2_Stream6_IRQHandler()
void DMA2_Stream6_IRQHandler (void)
Definition at line 1564 of file sdio.c.
References DMAEndOfTransfer.
FindSCR()
static SD_Error FindSCR (uint16_t rca, uint32_t * pscr) static
Find the SD card SCR register value.
Parameters
rca selected card address.
pscr pointer to the buffer that will contain the SCR value.
Return values
SD_Error SD Card Error code.
< Set Block Size To 8 Bytes
< Send CMD55 APP_CMD with argument as card's RCA
< Send ACMD51 SD_APP_SEND_SCR with argument as 0
< For SD Card only
< For SD Card only
Definition at line 1430 of file sdio.c.
References PHAL_SD_Cmd_t::arg, CmdResp1Error(), PHAL_SD_Cmd_t::idx, PHAL_SDIO_SendCommand(), RCA, PHAL_SD_Cmd_t::res, SD_0TO7BITS, SD_16TO23BITS, SD_24TO31BITS, SD_8TO15BITS, SD_CMD_APP_CMD, SD_CMD_SD_APP_SEND_SCR, SD_CMD_SET_BLOCKLEN, SD_DATA_CRC_FAIL, SD_DATA_TIMEOUT, SD_DATATIMEOUT, SD_OK, SD_RESP_SHORT, SD_RX_OVERRUN, SD_START_BIT_ERR, and SDIO_STATIC_FLAGS.
Referenced by SDEnWideBus().
PHAL_SDIO_init()
bool PHAL_SDIO_init (void)
Configures the SDIO peripheral.
Initialize SDIO peripheral with the configuired structure.
Parameters
cfg
Returns
true Success
false Fail
Definition at line 44 of file sdio.c.
References CardType, CID_Tab, CSD_Tab, DMAEndOfTransfer, RCA, SD_Init(), SD_OK, SDCardInfo, SDIO_STD_CAPACITY_SD_CARD_V1_1, SDSTATUS_Tab, TransferEnd, and TransferError.
Referenced by disk_initialize().
PHAL_SDIO_SendCommand()
void PHAL_SDIO_SendCommand (PHAL_SD_Cmd_t * cmd)
Send a command.
Parameters
cmd
Definition at line 706 of file sdio.c.
References PHAL_SD_Cmd_t::arg, PHAL_SD_Cmd_t::idx, and PHAL_SD_Cmd_t::res.
Referenced by FindSCR(), SD_InitializeCards(), SD_PowerON(), SD_ReadMultiBlocks(), SD_SelectDeselect(), SD_SendStatus(), SD_StopTransfer(), SD_WriteMultiBlocks(), and SDEnWideBus().
SD_DeInit()
void SD_DeInit (void)
< Disable SDIO Clock
< Set Power State to OFF
< DeInitializes the SDIO peripheral
Definition at line 1655 of file sdio.c.
Referenced by sd_shutdown().
SD_Detect()
uint8_t SD_Detect (void)
Detect if SD card is correctly plugged in the memory slot.
Parameters
None
Return values
Return if SD is detected or not
Definition at line 221 of file sdio.c.
References PHAL_readGPIO(), SD_CD_PIN, SD_CD_PORT, SD_NOT_PRESENT, and SD_PRESENT.
Referenced by _sdio_disk_write(), disk_status(), SD_GetState(), and sd_update_periodic().
SD_EnableWideBusOperation()
SD_Error SD_EnableWideBusOperation (uint32_t WideMode)
Enables wide bus opeartion for the requeseted card if supported by card.
Parameters
WideMode Specifies the SD card wide bus mode. This parameter can be one of the following values:
SDIO_BusWide_8b: 8-bit data transfer (Only for MMC)
SDIO_BusWide_4b: 4-bit data transfer
SDIO_BusWide_1b: 1-bit data transfer
Return values
SD_Error SD Card Error code.
< MMC Card doesn't support this feature
< Configure the SDIO peripheral
< Configure the SDIO peripheral
Definition at line 643 of file sdio.c.
References CardType, SD_OK, SD_UNSUPPORTED_FEATURE, SDEnWideBus(), SDIO_BusWide_4b, SDIO_BusWide_8b, SDIO_HIGH_CAPACITY_SD_CARD, SDIO_MULTIMEDIA_CARD, SDIO_STD_CAPACITY_SD_CARD_V1_1, SDIO_STD_CAPACITY_SD_CARD_V2_0, and SDIO_TRANSFER_CLK_DIV.
Referenced by SD_Init().
SD_GetCardInfo()
SD_Error SD_GetCardInfo (SD_CardInfo * cardinfo)
Returns information about specific card.
Parameters
cardinfo pointer to a SD_CardInfo structure that contains all SD card information.
Return values
SD_Error SD Card Error code.
< Byte 0
< Byte 1
< Byte 2
< Byte 3
< Byte 4
< Byte 5
< Byte 6
< Reserved
< Byte 7
< Byte 8
< Byte 9
< Byte 10
< Byte 7
< Byte 8
< Byte 9
< Byte 10
< Byte 11
< Byte 12
< Byte 13
< Byte 14
< Byte 15
< Byte 0
< Byte 1
< Byte 2
< Byte 3
< Byte 4
< Byte 5
< Byte 6
< Byte 7
< Byte 8
< Byte 9
< Byte 10
< Byte 11
< Byte 12
< Byte 13
< Byte 14
< Byte 15
Definition at line 437 of file sdio.c.
References SD_CardInfo::CardBlockSize, SD_CardInfo::CardCapacity, SD_CSD::CardComdClasses, CardType, SD_CardInfo::CardType, SD_CID::CID_CRC, CID_Tab, SD_CSD::ContentProtectAppli, SD_CSD::CopyFlag, SD_CSD::CSD_CRC, CSD_Tab, SD_CSD::CSDStruct, SD_CSD::DeviceSize, SD_CSD::DeviceSizeMul, SD_CSD::DSRImpl, SD_CSD::ECC, SD_CSD::EraseGrMul, SD_CSD::EraseGrSize, SD_CSD::FileFormat, SD_CSD::FileFormatGrouop, SD_CSD::ManDeflECC, SD_CID::ManufactDate, SD_CID::ManufacturerID, SD_CSD::MaxBusClkFrec, SD_CSD::MaxRdCurrentVDDMax, SD_CSD::MaxRdCurrentVDDMin, SD_CSD::MaxWrBlockLen, SD_CSD::MaxWrCurrentVDDMax, SD_CSD::MaxWrCurrentVDDMin, SD_CSD::NSAC, SD_CID::OEM_AppliID, SD_CSD::PartBlockRead, SD_CSD::PermWrProtect, SD_CID::ProdName1, SD_CID::ProdName2, SD_CID::ProdRev, SD_CID::ProdSN, RCA, SD_CardInfo::RCA, SD_CSD::RdBlockLen, SD_CSD::RdBlockMisalign, SD_CID::Reserved1, SD_CSD::Reserved1, SD_CID::Reserved2, SD_CSD::Reserved2, SD_CSD::Reserved3, SD_CSD::Reserved4, SD_CardInfo::SD_cid, SD_CardInfo::SD_csd, SD_OK, SDIO_HIGH_CAPACITY_SD_CARD, SDIO_STD_CAPACITY_SD_CARD_V1_1, SDIO_STD_CAPACITY_SD_CARD_V2_0, SD_CSD::SysSpecVersion, SD_CSD::TAAC, SD_CSD::TempWrProtect, SD_CSD::WrBlockMisalign, SD_CSD::WriteBlockPaPartial, SD_CSD::WrProtectGrEnable, SD_CSD::WrProtectGrSize, and SD_CSD::WrSpeedFact.
Referenced by SD_Init().
SD_GetState()
SDCardState SD_GetState (void)
Returns the current card's state.
Parameters
None
Return values
SDCardState SD Card Error or SD Card Current State.
Definition at line 202 of file sdio.c.
References SD_CARD_ERROR, SD_Detect(), SD_OK, SD_PRESENT, and SD_SendStatus().
Referenced by SD_GetStatus().
SD_GetStatus()
SDTransferState SD_GetStatus (void)
Gets the cuurent sd card data transfer status.
Parameters
None
Return values
SDTransferState Data Transfer state. This value can be:
SD_TRANSFER_OK: No data transfer is acting
SD_TRANSFER_BUSY: Data transfer is acting
Definition at line 183 of file sdio.c.
References SD_CARD_ERROR, SD_CARD_TRANSFER, SD_GetState(), SD_TRANSFER_BUSY, SD_TRANSFER_ERROR, and SD_TRANSFER_OK.
Referenced by _sdio_disk_read(), and _sdio_disk_write().
SD_Init()
SD_Error SD_Init (void)
Initialize the SD Card for Data Transfer.
Returns
DSTATUS
Initializes the SD Card and put it into StandBy State (Ready for data transfer).
Parameters
None
Return values
SD_Error SD Card Error code.
< CMD Response TimeOut (wait for CMDSENT flag)
< Configure the SDIO peripheral
< SDIO_CK = SDIOCLK / (SDIO_TRANSFER_CLK_DIV + 2)
< on STM32F4xx devices, SDIOCLK is fixed to 48MHz
Definition at line 111 of file sdio.c.
References SD_CardInfo::RCA, SD_EnableWideBusOperation(), SD_GetCardInfo(), SD_InitializeCards(), SD_LOG, SD_OK, SD_PowerON(), SD_SelectDeselect(), SDCardInfo, SDIO_BusWide_1b, SDIO_BusWide_4b, and SDIO_TRANSFER_CLK_DIV.
Referenced by PHAL_SDIO_init().
SD_InitializeCards()
SD_Error SD_InitializeCards (void)
Intialises all cards or single card as the case may be Card(s) come into standby state.
Parameters
None
Return values
SD_Error SD Card Error code.
< Send CMD2 ALL_SEND_CID
< Send CMD3 SET_REL_ADDR with argument 0
< SD Card publishes its RCA.
< SDIO_SEND_REL_ADDR for SD Card
< SDIO_SEND_REL_ADDR for SD Card
< Send CMD9 SEND_CSD with argument as card's RCA
Definition at line 362 of file sdio.c.
References PHAL_SD_Cmd_t::arg, CardType, CID_Tab, CmdResp2Error(), CmdResp6Error(), PHAL_SD_Cmd_t::idx, PHAL_SDIO_SendCommand(), RCA, PHAL_SD_Cmd_t::res, SD_CMD_ALL_SEND_CID, SD_CMD_SEND_CSD, SD_CMD_SET_REL_ADDR, SD_OK, SD_REQUEST_NOT_APPLICABLE, SD_RESP_LONG, SD_RESP_SHORT, SDIO_HIGH_CAPACITY_SD_CARD, SDIO_SECURE_DIGITAL_IO_CARD, SDIO_SECURE_DIGITAL_IO_COMBO_CARD, SDIO_STD_CAPACITY_SD_CARD_V1_1, and SDIO_STD_CAPACITY_SD_CARD_V2_0.
Referenced by SD_Init().
SD_LowLevel_DMA_RxConfig()
void SD_LowLevel_DMA_RxConfig (uint32_t * BufferDST, uint32_t BufferSize)
Configures the DMA2 Channel4 for SDIO Rx request.
Parameters
BufferDST pointer to the destination buffer
BufferSize buffer size
Return values
None
Definition at line 1639 of file sdio.c.
References dma_init_t::mem_addr, PHAL_initDMA(), PHAL_startTxfer(), sdio_rx_config, and dma_init_t::stream.
Referenced by SD_ReadMultiBlocks().
SD_LowLevel_DMA_TxConfig()
void SD_LowLevel_DMA_TxConfig (uint32_t * BufferSRC, uint32_t BufferSize)
Configures the DMA2 Channel4 for SDIO Tx request.
Parameters
BufferSRC pointer to the source buffer
BufferSize buffer size
Return values
None
Definition at line 1598 of file sdio.c.
References dma_init_t::mem_addr, PHAL_initDMA(), PHAL_startTxfer(), sdio_tx_config, and dma_init_t::stream.
Referenced by SD_WriteMultiBlocks().
SD_PowerON()
SD_Error SD_PowerON (void)
Enquires cards about their operating voltage and configures clock controls.
Parameters
None
Return values
SD_Error SD Card Error code.
< CMD0: GO_IDLE_STATE ------------------------------------------------—
< No CMD response required
< CMD Response TimeOut (wait for CMDSENT flag)
< CMD8: SEND_IF_COND -------------------------------------------------—
< Send CMD8 to verify SD card interface operating condition
< Argument: - [31:12]: Reserved (shall be set to '0')
[11:8]: Supply Voltage (VHS) 0x1 (Range: 2.7-3.6 V)
[7:0]: Check Pattern (recommended 0xAA)
< CMD Response: R7
< SD Card 2.0
< CMD55
< If errorstatus is Command TimeOut, it is a MMC card
< If errorstatus is SD_OK it is a SD card: SD card 2.0 (voltage range mismatch) or SD card 1.x
< SD CARD
< Send ACMD41 SD_APP_OP_COND with Argument 0x80100000
< SEND CMD55 APP_CMD with RCA as 0
< For SD Card only
Definition at line 239 of file sdio.c.
References PHAL_SD_Cmd_t::arg, CardType, CmdError(), CmdResp1Error(), CmdResp3Error(), CmdResp7Error(), PHAL_SD_Cmd_t::idx, PHAL_SDIO_SendCommand(), PHAL_SD_Cmd_t::res, SD_CHECK_PATTERN, SD_CMD_APP_CMD, SD_CMD_GO_IDLE_STATE, SD_CMD_SD_APP_OP_COND, SD_HIGH_CAPACITY, SD_INVALID_VOLTRANGE, SD_MAX_VOLT_TRIAL, SD_OK, SD_RESP_NONE, SD_RESP_SHORT, SD_STD_CAPACITY, SD_VOLTAGE_WINDOW_SD, SDIO_HIGH_CAPACITY_SD_CARD, SDIO_INIT_CLK_DIV, SDIO_SEND_IF_COND, and SDIO_STD_CAPACITY_SD_CARD_V2_0.
Referenced by SD_Init().
SD_ReadMultiBlocks()
SD_Error SD_ReadMultiBlocks (uint8_t * readbuff, uint64_t ReadAddr, uint16_t BlockSize, uint32_t NumberOfBlocks)
Allows to read blocks from a specified address in a card. The Data transfer can be managed by DMA mode or Polling mode.
Note
This operation should be followed by two functions to check if the DMA Controller and SD Card status.
SD_ReadWaitOperation(): this function insure that the DMA controller has finished all data transfer.
SD_GetStatus(): to check that the SD Card has finished the data transfer and it is ready for data.
Parameters
readbuff pointer to the buffer that will contain the received data.
ReadAddr Address from where data are to be read.
BlockSize the SD card Data block size. The Block size should be 512.
NumberOfBlocks number of blocks to be read.
Return values
SD_Error SD Card Error code.
< Send CMD18 READ_MULT_BLOCK with argument data address
< Send CMD17 READ_SINGLE_BLOCK with argument data address
Definition at line 726 of file sdio.c.
References PHAL_SD_Cmd_t::arg, CardType, CmdResp1Error(), PHAL_SD_Cmd_t::idx, last_read_length, PHAL_SDIO_SendCommand(), PHAL_SD_Cmd_t::res, SD_CMD_READ_MULT_BLOCK, SD_CMD_SET_BLOCKLEN, SD_DATATIMEOUT, SD_LowLevel_DMA_RxConfig(), SD_OK, SD_RESP_SHORT, SDIO_DATABLOCKSIZE, SDIO_HIGH_CAPACITY_SD_CARD, StopCondition, TransferEnd, and TransferError.
Referenced by _sdio_disk_read().
SD_SelectDeselect()
SD_Error SD_SelectDeselect (uint64_t addr)
Selects od Deselects the corresponding card.
Parameters
addr Address of the Card to be selected.
Return values
SD_Error SD Card Error code.
< Send CMD7 SDIO_SEL_DESEL_CARD
Definition at line 686 of file sdio.c.
References addr, PHAL_SD_Cmd_t::arg, CmdResp1Error(), PHAL_SD_Cmd_t::idx, PHAL_SDIO_SendCommand(), PHAL_SD_Cmd_t::res, SD_CMD_SEL_DESEL_CARD, SD_OK, and SD_RESP_SHORT.
Referenced by SD_Init().
SD_SendStatus()
SD_Error SD_SendStatus (uint32_t * pcardstatus)
Returns the current card's status.
Parameters
pcardstatus pointer to the buffer that will contain the SD card status (Card Status register).
Return values
SD_Error SD Card Error code.
Definition at line 1009 of file sdio.c.
References PHAL_SD_Cmd_t::arg, CmdResp1Error(), PHAL_SD_Cmd_t::idx, PHAL_SDIO_SendCommand(), RCA, PHAL_SD_Cmd_t::res, SD_CMD_SEND_STATUS, SD_INVALID_PARAMETER, SD_OK, and SD_RESP_SHORT.
Referenced by SD_GetState().
SD_StopTransfer()
SD_Error SD_StopTransfer (void)
Aborts an ongoing data transfer.
Parameters
None
Return values
SD_Error SD Card Error code.
< Send CMD12 STOP_TRANSMISSION
Definition at line 982 of file sdio.c.
References PHAL_SD_Cmd_t::arg, CmdResp1Error(), PHAL_SD_Cmd_t::idx, PHAL_SDIO_SendCommand(), PHAL_SD_Cmd_t::res, SD_CMD_RSP_TIMEOUT, SD_CMD_STOP_TRANSMISSION, SD_OK, and SD_RESP_SHORT.
Referenced by SD_WaitReadOperation(), and SD_WaitWriteOperation().
SD_WaitReadOperation()
SD_Error SD_WaitReadOperation (void)
This function waits until the SDIO DMA data transfer is finished. This function should be called after SDIO_ReadMultiBlocks() function to insure that all data sent by the card are already transferred by the DMA controller.
Parameters
None.
Return values
SD_Error SD Card Error code.
Definition at line 800 of file sdio.c.
References DMAEndOfTransfer, SD_DATA_TIMEOUT, SD_DATATIMEOUT, SD_OK, SD_StopTransfer(), SDIO_STATIC_FLAGS, StopCondition, TransferEnd, and TransferError.
Referenced by _sdio_disk_read().
SD_WaitWriteOperation()
SD_Error SD_WaitWriteOperation (void)
This function waits until the SDIO DMA data transfer is finished. This function should be called after SDIO_WriteBlock() and SDIO_WriteMultiBlocks() function to insure that all data sent by the card are already transferred by the DMA controller.
Parameters
None.
Return values
SD_Error SD Card Error code.
Definition at line 940 of file sdio.c.
References DMAEndOfTransfer, SD_DATA_TIMEOUT, SD_DATATIMEOUT, SD_OK, SD_StopTransfer(), SDIO_STATIC_FLAGS, StopCondition, TransferEnd, and TransferError.
Referenced by _sdio_disk_write().
SD_WriteMultiBlocks()
SD_Error SD_WriteMultiBlocks (uint8_t * writebuff, uint64_t WriteAddr, uint16_t BlockSize, uint32_t NumberOfBlocks)
Allows to write blocks starting from a specified address in a card. The Data transfer can be managed by DMA mode only.
Note
This operation should be followed by two functions to check if the DMA Controller and SD Card status.
SD_ReadWaitOperation(): this function insure that the DMA controller has finished all data transfer.
SD_GetStatus(): to check that the SD Card has finished the data transfer and it is ready for data.
Parameters
WriteAddr Address from where data are to be read.
writebuff pointer to the buffer that contain the data to be transferred.
BlockSize the SD card Data block size. The Block size should be 512.
NumberOfBlocks number of blocks to be written.
Return values
SD_Error SD Card Error code.
< SD Card doesn't support it
< SD Card doesn't support it
Definition at line 858 of file sdio.c.
References PHAL_SD_Cmd_t::arg, CardType, CmdResp1Error(), PHAL_SD_Cmd_t::idx, PHAL_SDIO_SendCommand(), RCA, PHAL_SD_Cmd_t::res, SD_CMD_APP_CMD, SD_CMD_SET_BLOCK_COUNT, SD_CMD_SET_BLOCKLEN, SD_CMD_WRITE_MULT_BLOCK, SD_DATATIMEOUT, SD_LowLevel_DMA_TxConfig(), SD_OK, SD_RESP_SHORT, SDIO_DATABLOCKSIZE, SDIO_HIGH_CAPACITY_SD_CARD, StopCondition, TransferEnd, and TransferError.
Referenced by _sdio_disk_write().
SDEnWideBus()
static SD_Error SDEnWideBus (FunctionalState NewState) static
Enables or disables the SDIO wide bus mode.
Parameters
NewState new state of the SDIO wide bus mode. This parameter can be: ENABLE or DISABLE.
Return values
SD_Error SD Card Error code.
< If requested card supports wide bus operation
< Send CMD55 APP_CMD with argument as card's RCA.
< For SD Card only
< For SD Card only
< If wide bus operation to be disabled
< If requested card supports 1 bit mode operation
< Send CMD55 APP_CMD with argument as card's RCA.
< For SD Card only
< For SD Card only
Definition at line 1339 of file sdio.c.
References PHAL_SD_Cmd_t::arg, CmdResp1Error(), FindSCR(), PHAL_SD_Cmd_t::idx, PHAL_SDIO_SendCommand(), RCA, PHAL_SD_Cmd_t::res, SD_ALLZERO, SD_CARD_LOCKED, SD_CMD_APP_CMD, SD_CMD_APP_SD_SET_BUSWIDTH, SD_LOCK_UNLOCK_FAILED, SD_OK, SD_REQUEST_NOT_APPLICABLE, SD_RESP_SHORT, SD_SINGLE_BUS_SUPPORT, and SD_WIDE_BUS_SUPPORT.
Referenced by SD_EnableWideBusOperation().
SDIO_IRQHandler()
void SDIO_IRQHandler (void)
Allows to process all the interrupts that are high.
Definition at line 1521 of file sdio.c.
References SD_DATA_CRC_FAIL, SD_DATA_TIMEOUT, SD_LOG, SD_OK, SD_RX_OVERRUN, SD_START_BIT_ERR, SD_TX_UNDERRUN, TransferEnd, and TransferError.
Variable Documentation
CardType
uint32_t CardType = ((uint32_t)0x00000000) static
Definition at line 18 of file sdio.c.
Referenced by PHAL_SDIO_init(), SD_EnableWideBusOperation(), SD_GetCardInfo(), SD_InitializeCards(), SD_PowerON(), SD_ReadMultiBlocks(), and SD_WriteMultiBlocks().
CID_Tab
uint32_t CID_Tab[4] static
Definition at line 19 of file sdio.c.
Referenced by PHAL_SDIO_init(), SD_GetCardInfo(), and SD_InitializeCards().
CSD_Tab
uint32_t CSD_Tab[4] static
Definition at line 19 of file sdio.c.
Referenced by PHAL_SDIO_init(), and SD_GetCardInfo().
DMAEndOfTransfer
__IO uint32_t DMAEndOfTransfer = 0
Definition at line 23 of file sdio.c.
Referenced by DMA2_Stream6_IRQHandler(), PHAL_SDIO_init(), SD_WaitReadOperation(), and SD_WaitWriteOperation().
last_read_length
uint32_t last_read_length = 0 static
Definition at line 25 of file sdio.c.
Referenced by SD_ReadMultiBlocks().
RCA
uint32_t RCA = 0 static
Definition at line 19 of file sdio.c.
Referenced by FindSCR(), PHAL_SDIO_init(), SD_GetCardInfo(), SD_InitializeCards(), SD_SendStatus(), SD_WriteMultiBlocks(), and SDEnWideBus().
SDCardInfo
SD_CardInfo SDCardInfo
Definition at line 24 of file sdio.c.
Referenced by PHAL_SDIO_init(), and SD_Init().
sdio_rx_config
dma_init_t sdio_rx_config = { .periph_addr = (uint32_t)&(SDIO->FIFO), .mem_addr = (uint32_t)(NULL), .tx_size = 1, .increment = false, .circular = false, .dir = 0b0, .mem_inc = true, .periph_inc = false, .mem_to_mem = false, .priority = (3), .mem_size = 0b10, .periph_size = 0b10, .tx_isr_en = true, .dma_chan_request = 0b0100, .stream_idx = 6, .periph = DMA2, .stream = DMA2_Stream6} static
Definition at line 1631 of file sdio.c.
Referenced by SD_LowLevel_DMA_RxConfig().
sdio_tx_config
dma_init_t sdio_tx_config = { .periph_addr = (uint32_t)&(SDIO->FIFO), .mem_addr = (uint32_t)(NULL), .tx_size = 1, .increment = false, .circular = false, .dir = 0b1, .mem_inc = true, .periph_inc = false, .mem_to_mem = false, .priority = (3), .mem_size = 0b10, .periph_size = 0b10, .tx_isr_en = true, .dma_chan_request = 0b0100, .stream_idx = 6, .periph = DMA2, .stream = DMA2_Stream6} static
Definition at line 1590 of file sdio.c.
Referenced by SD_LowLevel_DMA_TxConfig().
SDSTATUS_Tab
uint8_t SDSTATUS_Tab[16] static
Definition at line 20 of file sdio.c.
Referenced by PHAL_SDIO_init().
StopCondition
__IO uint32_t StopCondition = 0
Definition at line 21 of file sdio.c.
Referenced by SD_ReadMultiBlocks(), SD_WaitReadOperation(), SD_WaitWriteOperation(), and SD_WriteMultiBlocks().
TransferEnd
__IO uint32_t TransferEnd = 0
Definition at line 23 of file sdio.c.
Referenced by PHAL_SDIO_init(), SD_ReadMultiBlocks(), SD_WaitReadOperation(), SD_WaitWriteOperation(), SD_WriteMultiBlocks(), and SDIO_IRQHandler().
TransferError
__IO SD_Error TransferError = SD_OK
Definition at line 22 of file sdio.c.
Referenced by PHAL_SDIO_init(), SD_ReadMultiBlocks(), SD_WaitReadOperation(), SD_WaitWriteOperation(), SD_WriteMultiBlocks(), and SDIO_IRQHandler().