PER Firmware: source/g4_testing/fdcan.c File Reference
fdcan.c File Reference
#include "g4_testing.h"
#include <string.h>
#include "common/freertos/freertos.h"
#include "common/phal/adc.h"
#include "common/phal/can.h"
#include "common/phal/dma.h"
#include "common/phal/gpio.h"
#include "common/phal/rcc.h"
#include "main.h"
Macros
#define TargetCoreClockrateHz 16000000
Functions
void HardFault_Handler ()
static void can_tx_100hz (void)
static void can_rx_1khz (void)
defineThreadStack (can_tx_100hz, 10, osPriorityHigh, 256)
defineThreadStack (can_rx_1khz, 1, osPriorityHigh, 256)
defineStaticQueue (q_can_rx, CanMsgTypeDef_t, 256)
int main ()
void PHAL_FDCAN_rxCallback (CanMsgTypeDef_t *msg)
static void PHAL_FDCAN_testExtended (void)
Variables
GPIOInitConfig_t gpio_config []
ADCInitConfig_t adc_config
ADCChannelConfig_t adc_channel_config []
volatile raw_adc_values_t raw_adc_values = {0}
dma_init_t adc_dma_config = ADC1_DMA_CONT_CONFIG((uint32_t)&raw_adc_values, (sizeof(raw_adc_values) / sizeof(uint16_t)) , 0b01)
ClockRateConfig_t clock_config
uint32_t APB1ClockRateHz
uint32_t APB2ClockRateHz
uint32_t AHBClockRateHz
uint32_t PLLClockRateHz
volatile CanMsgTypeDef_t rx_frame_0
Macro Definition Documentation
TargetCoreClockrateHz
#define TargetCoreClockrateHz 16000000
Definition at line 47 of file fdcan.c.
Function Documentation
can_rx_1khz()
static void can_rx_1khz (void) static
Definition at line 162 of file fdcan.c.
References rx_frame_0.
Referenced by main().
can_tx_100hz()
static void can_tx_100hz (void) static
Definition at line 155 of file fdcan.c.
References PHAL_FDCAN_testExtended().
Referenced by main().
defineStaticQueue()
defineStaticQueue (q_can_rx , CanMsgTypeDef_t , 256)
defineThreadStack() [1/2]
defineThreadStack (can_rx_1khz , 1 , osPriorityHigh , 256)
defineThreadStack() [2/2]
defineThreadStack (can_tx_100hz , 10 , osPriorityHigh , 256)
HardFault_Handler()
void HardFault_Handler (void)
Definition at line 170 of file fdcan.c.
Referenced by main().
main()
int main (void)
Definition at line 75 of file fdcan.c.
References adc_channel_config, adc_config, adc_dma_config, ADC_NUM_CHANNELS, can_rx_1khz(), can_tx_100hz(), clock_config, createStaticQueue, createThread, gpio_config, HardFault_Handler(), PHAL_configureClockRates(), PHAL_FDCAN_init(), PHAL_FDCAN_setFilters(), PHAL_initADC(), PHAL_initDMA(), PHAL_initGPIO(), PHAL_startADC(), and PHAL_startTxfer().
PHAL_FDCAN_rxCallback()
void PHAL_FDCAN_rxCallback (CanMsgTypeDef_t * msg)
Definition at line 125 of file fdcan.c.
PHAL_FDCAN_testExtended()
static void PHAL_FDCAN_testExtended (void) static
Definition at line 133 of file fdcan.c.
References PHAL_FDCAN_send().
Referenced by can_tx_100hz().
Variable Documentation
adc_channel_config
ADCChannelConfig_t adc_channel_config[]
Initial value:
= {
    {.channel = ADC_CHANNEL_1, .rank = 1, .sampling_time = ADC_CHN_SMP_CYCLES_480},
    {.channel = ADC_CHANNEL_2, .rank = 2, .sampling_time = ADC_CHN_SMP_CYCLES_480},
    {.channel = ADC_CHANNEL_3, .rank = 3, .sampling_time = ADC_CHN_SMP_CYCLES_480},
    {.channel = ADC_CHANNEL_4, .rank = 4, .sampling_time = ADC_CHN_SMP_CYCLES_480},
}
Definition at line 37 of file fdcan.c.
Referenced by main().
adc_config
ADCInitConfig_t adc_config
Initial value:
= {
    .periph         = ADC1,
    .prescaler      = ADC_CLK_PRESC_0,
    .resolution     = ADC_RES_12_BIT,
    .data_align     = ADC_DATA_ALIGN_RIGHT,
    .cont_conv_mode = true,
    .dma_mode       = ADC_DMA_CIRCULAR,
    .oversample     = ADC_OVERSAMPLE_16,
}
Definition at line 27 of file fdcan.c.
Referenced by main().
adc_dma_config
dma_init_t adc_dma_config = ADC1_DMA_CONT_CONFIG((uint32_t)&raw_adc_values, (sizeof(raw_adc_values) / sizeof(uint16_t)) , 0b01)
Definition at line 45 of file fdcan.c.
Referenced by main().
AHBClockRateHz
uint32_t AHBClockRateHz extern
Definition at line 17 of file rcc.c.
APB1ClockRateHz
uint32_t APB1ClockRateHz extern
Definition at line 15 of file rcc.c.
APB2ClockRateHz
uint32_t APB2ClockRateHz extern
Definition at line 16 of file rcc.c.
clock_config
ClockRateConfig_t clock_config
Initial value:
= {
    .clock_source              = CLOCK_SOURCE_HSI,
    .use_pll                   = false,
    .vco_output_rate_target_hz = 16000000,
    .system_clock_target_hz    = 16000000 ,
    .ahb_clock_target_hz       = ( 16000000 / 1),
    .apb1_clock_target_hz      = ( 16000000 / (1)),
    .apb2_clock_target_hz      = ( 16000000 / (1)),
}
Definition at line 48 of file fdcan.c.
Referenced by main().
gpio_config
GPIOInitConfig_t gpio_config[]
Initial value:
= {
    GPIO_INIT_ANALOG(ADC1_CH1_GPIO_Port, ADC1_CH1_Pin),
    GPIO_INIT_ANALOG(ADC1_CH2_GPIO_Port, ADC1_CH2_Pin),
    GPIO_INIT_ANALOG(ADC1_CH3_GPIO_Port, ADC1_CH3_Pin),
    GPIO_INIT_ANALOG(ADC1_CH4_GPIO_Port, ADC1_CH4_Pin),
    GPIO_INIT_FDCAN2RX_PB12,
    GPIO_INIT_FDCAN2TX_PB13,
    GPIO_INIT_FDCAN3RX_PA8,
    GPIO_INIT_FDCAN3TX_PB4,
}
Definition at line 15 of file fdcan.c.
Referenced by main().
PLLClockRateHz
uint32_t PLLClockRateHz extern
Definition at line 18 of file rcc.c.
raw_adc_values
volatile raw_adc_values_t raw_adc_values = {0}
Definition at line 44 of file fdcan.c.
rx_frame_0
volatile CanMsgTypeDef_t rx_frame_0
Definition at line 160 of file fdcan.c.
Referenced by can_rx_1khz().