PER Firmware: source/daq/spmc/spmc.h File Reference
spmc.h File Reference
Custom SPMC designed for high throughput handling of CAN message streams.
#include <stddef.h>
#include <stdint.h>
#include <string.h>
Data Structures
struct timestamped_frame_t
struct SPMC_t
Enumerations
enum SPMC_status_t : int { SPMC_OK = 0 , SPMC_FULL = -1 , SPMC_EMPTY = -2 }
Functions
void SPMC_init (SPMC_t *spmc)
Initializes the SPMC instance and configures CAN RX interrupts.
SPMC_status_t SPMC_enqueue_from_ISR (SPMC_t *spmc, timestamped_frame_t *incoming_frame)
Enqueues a received CAN message into the SPMC buffer from an ISR context. ! the two producer ISRs must have the same priority to prevent preemption in the middle of a write.
size_t SPMC_master_peek_all (SPMC_t *spmc, timestamped_frame_t **first_item, size_t *total_unread)
Peeks at the next batch of frames available for processing by the master (SD logging) without committing the tail. Intended to be used with a DMA operation.
void SPMC_master_commit_tail (SPMC_t *spmc, size_t num_consumed)
Commits the specified number of consumed frames by advancing the master tail pointer.
SPMC_status_t SPMC_follower_pop (SPMC_t *spmc, timestamped_frame_t **out, uint32_t *consecutive_items)
Pops a single frame for the follower (Ethernet transmission) and advances the follower tail pointer. todo: this function is incomplete todo: optimize for DMA batch transfers, similar to the master's function.
Variables
static constexpr size_t SPMC_CAPACITY = 512
static constexpr size_t SD_WRITE_THRESHOLD = 32
static constexpr size_t SPMC_ALLOCATED_CAPACITY = SPMC_CAPACITY + 1
Detailed Description
Custom SPMC designed for high throughput handling of CAN message streams.
Author
Irving Wang (irvin.nosp@m.gw@p.nosp@m.urdue.nosp@m..edu)
Shriya Balu (balu@.nosp@m.purd.nosp@m.ue.ed.nosp@m.u)
Definition in file spmc.h.
Enumeration Type Documentation
SPMC_status_t
enum SPMC_status_t : int
Enumerator
SPMC_OK
SPMC_FULL
SPMC_EMPTY
Definition at line 22 of file spmc.h.
Function Documentation
SPMC_enqueue_from_ISR()
SPMC_status_t SPMC_enqueue_from_ISR (SPMC_t * spmc, timestamped_frame_t * incoming_frame)
Enqueues a received CAN message into the SPMC buffer from an ISR context. ! the two producer ISRs must have the same priority to prevent preemption in the middle of a write.
Parameters
spmc Pointer to the SPMC instance.
incoming_frame Pointer to the timestamped_frame_t containing the received CAN message.
Returns
SPMC_OK if the frame was enqueued successfully, or SPMC_FULL if the buffer is full and the frame was dropped.
Definition at line 49 of file spmc.c.
References SPMC_t::data, SPMC_t::head, SPMC_t::master_tail, SPMC_t::overflows, spmc, SPMC_CAPACITY, SPMC_FULL, and SPMC_OK.
Referenced by can_rx_irq_handler().
SPMC_follower_pop()
SPMC_status_t SPMC_follower_pop (SPMC_t * spmc, timestamped_frame_t ** out, uint32_t * consecutive_items)
Pops a single frame for the follower (Ethernet transmission) and advances the follower tail pointer. todo: this function is incomplete todo: optimize for DMA batch transfers, similar to the master's function.
Parameters
spmc Pointer to the SPMC instance.
out Output pointer to the popped frame.
consecutive_items Output pointer to the number of consecutive frames available.
Returns
SPMC_OK if a frame was successfully popped, or SPMC_EMPTY if the buffer is empty.
Definition at line 130 of file spmc.c.
References SPMC_t::data, SPMC_t::follower_tail, SPMC_t::head, spmc, SPMC_CAPACITY, SPMC_EMPTY, and SPMC_OK.
Referenced by eth_udp_send_periodic().
SPMC_init()
void SPMC_init (SPMC_t * spmc)
Initializes the SPMC instance and configures CAN RX interrupts.
Parameters
spmc Pointer to the SPMC instance to initialize.
Definition at line 26 of file spmc.c.
References CAN_RX_IRQ_PRIO, SPMC_t::follower_tail, SPMC_t::head, SPMC_t::master_tail, and spmc.
Referenced by main().
SPMC_master_commit_tail()
void SPMC_master_commit_tail (SPMC_t * spmc, size_t num_consumed)
Commits the specified number of consumed frames by advancing the master tail pointer.
Parameters
spmc Pointer to the SPMC instance.
num_consumed The number of frames to commit.
Definition at line 107 of file spmc.c.
References CAN_RX_IRQ_PRIO, SPMC_t::master_tail, spmc, and SPMC_CAPACITY.
Referenced by _sd_write_periodic().
SPMC_master_peek_all()
size_t SPMC_master_peek_all (SPMC_t * spmc, timestamped_frame_t ** first_item, size_t * total_unread)
Peeks at the next batch of frames available for processing by the master (SD logging) without committing the tail. Intended to be used with a DMA operation.
Parameters
spmc Pointer to the SPMC instance.
first_item Output pointer that will point to the first item in the batch if available, or NULL if no items are available.
total_unread Output pointer that will be set to the total number of unread frames available in the buffer.
Returns
The number of contiguous items available in the batch.
Definition at line 82 of file spmc.c.
References SPMC_t::data, SPMC_t::head, SPMC_t::master_tail, spmc, and SPMC_CAPACITY.
Referenced by _sd_write_periodic().
Variable Documentation
SD_WRITE_THRESHOLD
size_t SD_WRITE_THRESHOLD = 32 static constexpr
Definition at line 35 of file spmc.h.
SPMC_ALLOCATED_CAPACITY
size_t SPMC_ALLOCATED_CAPACITY = SPMC_CAPACITY + 1 static constexpr
Definition at line 42 of file spmc.h.
SPMC_CAPACITY
size_t SPMC_CAPACITY = 512 static constexpr
Definition at line 34 of file spmc.h.
Referenced by SPMC_enqueue_from_ISR(), SPMC_follower_pop(), SPMC_master_commit_tail(), and SPMC_master_peek_all().