PER Firmware: source/daq/spmc/spmc.c File Reference
spmc.c File Reference
Custom SPMC designed for high throughput handling of CAN message streams.
#include "spmc.h"
Functions
void SPMC_init (SPMC_t *spmc, TaskHandle_t master_task, TaskHandle_t follower_task)
int SPMC_enqueue_ISR (SPMC_t *spmc, timestamped_frame_t *incoming_frame)
size_t SPMC_master_peek_batch (SPMC_t *spmc, timestamped_frame_t **first_item)
size_t SPMC_master_get_total (SPMC_t *spmc, timestamped_frame_t **first_item)
void SPMC_master_commit (SPMC_t *spmc, size_t num_consumed)
int SPMC_follower_pop (SPMC_t *spmc, timestamped_frame_t **out, uint32_t *consecutive_items)
Detailed Description
Custom SPMC designed for high throughput handling of CAN message streams.
Author
Irving Wang (irvin.nosp@m.gw@p.nosp@m.urdue.nosp@m..edu)
Shriya Balu (balu@.nosp@m.purd.nosp@m.ue.ed.nosp@m.u)
Definition in file spmc.c.
Function Documentation
SPMC_enqueue_ISR()
int SPMC_enqueue_ISR (SPMC_t * spmc, timestamped_frame_t * incoming_frame)
Definition at line 27 of file spmc.c.
References SPMC_t::data, SPMC_t::head, SPMC_t::master_tail, SPMC_t::overflows, and SPMC_NUM_FRAMES.
Referenced by can_rx_irq_handler().
SPMC_follower_pop()
int SPMC_follower_pop (SPMC_t * spmc, timestamped_frame_t ** out, uint32_t * consecutive_items)
Definition at line 111 of file spmc.c.
References SPMC_t::data, SPMC_t::follower_tail, SPMC_t::head, and SPMC_NUM_FRAMES.
Referenced by eth_udp_send_periodic().
SPMC_init()
void SPMC_init (SPMC_t * spmc, TaskHandle_t master_task, TaskHandle_t follower_task)
Definition at line 13 of file spmc.c.
References SPMC_t::follower_tail, SPMC_t::follower_task, SPMC_t::head, SPMC_t::master_tail, and SPMC_t::master_task.
Referenced by main().
SPMC_master_commit()
void SPMC_master_commit (SPMC_t * spmc, size_t num_consumed)
Definition at line 100 of file spmc.c.
References SPMC_t::master_tail, and SPMC_NUM_FRAMES.
Referenced by _sd_write_periodic().
SPMC_master_get_total()
size_t SPMC_master_get_total (SPMC_t * spmc, timestamped_frame_t ** first_item)
Definition at line 75 of file spmc.c.
References SPMC_t::data, SPMC_t::head, SPMC_t::master_tail, and SPMC_NUM_FRAMES.
Referenced by _sd_write_periodic().
SPMC_master_peek_batch()
size_t SPMC_master_peek_batch (SPMC_t * spmc, timestamped_frame_t ** first_item)
Definition at line 53 of file spmc.c.
References SPMC_t::data, SPMC_t::head, SPMC_t::master_tail, and SPMC_NUM_FRAMES.
Referenced by _sd_write_periodic().