PER Firmware: source/main_module/state_machine.c File Reference
state_machine.c File Reference
"Main Module" master state machine implementation
#include "main.h"
#include "pindefs.h"
#include "common/can_library/faults_common.h"
#include "common/can_library/generated/MAIN_MODULE.h"
#include "common/can_library/generated/can_types.h"
#include "common/phal/gpio.h"
Functions
void ready2drive_periodic ()
static bool is_init_complete ()
static bool is_TSMS_closed ()
static bool is_precharge_complete ()
static bool is_all_AMKS_running ()
static bool is_start_button_pressed ()
static bool is_buzzing_time_elapsed ()
void set_brake_light ()
void fsm_periodic ()
Variables
static constexpr uint32_t MIN_BUZZING_TIME_MS = 2500
static constexpr uint16_t BRAKE_LIGHT_ON_THRESHOLD = 200
static constexpr uint16_t BRAKE_LIGHT_OFF_THRESHOLD = 100
Detailed Description
"Main Module" master state machine implementation
Author
Irving Wang (irvin.nosp@m.gw@p.nosp@m.urdue.nosp@m..edu)
Definition in file state_machine.c.
Function Documentation
fsm_periodic()
void fsm_periodic ()
Definition at line 94 of file state_machine.c.
References AMK_set_torque(), car_t::brake_light, BRAKE_LIGHT_PIN, BRAKE_LIGHT_PORT, car_t::buzzer_enable, BUZZER_PIN, BUZZER_PORT, car_t::buzzer_start_time, car_t::current_state, car_t::front_left, torque_request_t::front_left, car_t::front_right, torque_request_t::front_right, g_car, g_torque_request, is_all_AMKS_running(), is_buzzing_time_elapsed(), is_fatal_latched(), is_init_complete(), is_latched(), car_t::is_precharge_complete, is_precharge_complete(), is_start_button_pressed(), is_TSMS_closed(), car_t::next_state, PHAL_readGPIO(), PHAL_writeGPIO(), PRECHARGE_COMPLETE_PIN, PRECHARGE_COMPLETE_PORT, ready2drive_periodic(), car_t::rear_left, torque_request_t::rear_left, car_t::rear_right, torque_request_t::rear_right, set_brake_light(), TSAL_GREEN_CTRL_PIN, TSAL_GREEN_CTRL_PORT, car_t::tsal_green_enable, TSAL_RED_CTRL_PIN, TSAL_RED_CTRL_PORT, car_t::tsal_red_enable, and update_fault().
Referenced by main().
is_all_AMKS_running()
static bool is_all_AMKS_running () inline static
Definition at line 57 of file state_machine.c.
References AMK_STATE_RUNNING, car_t::front_left, car_t::front_right, g_car, car_t::rear_left, car_t::rear_right, and AMK_t::state.
Referenced by fsm_periodic().
is_buzzing_time_elapsed()
static bool is_buzzing_time_elapsed () inline static
Definition at line 72 of file state_machine.c.
References car_t::buzzer_start_time, g_car, and MIN_BUZZING_TIME_MS.
Referenced by fsm_periodic().
is_init_complete()
static bool is_init_complete () inline static
Definition at line 45 of file state_machine.c.
Referenced by fsm_periodic().
is_precharge_complete()
static bool is_precharge_complete () inline static
Definition at line 53 of file state_machine.c.
References is_latched().
Referenced by fsm_periodic().
is_start_button_pressed()
static bool is_start_button_pressed () inline static
Definition at line 64 of file state_machine.c.
References can_data.
Referenced by fsm_periodic().
is_TSMS_closed()
static bool is_TSMS_closed () inline static
Definition at line 49 of file state_machine.c.
References is_latched().
Referenced by fsm_periodic().
ready2drive_periodic()
void ready2drive_periodic ()
Definition at line 21 of file state_machine.c.
References can_data, torque_request_t::front_left, torque_request_t::front_right, g_torque_request, torque_request_t::rear_left, and torque_request_t::rear_right.
Referenced by fsm_periodic().
set_brake_light()
void set_brake_light ()
Brake Light Control The on threshold is larger than the off threshold to behave similar to a Shmitt-trigger, preventing blinking during a transition
Definition at line 82 of file state_machine.c.
References car_t::brake_light, BRAKE_LIGHT_OFF_THRESHOLD, BRAKE_LIGHT_ON_THRESHOLD, can_data, and g_car.
Referenced by fsm_periodic().
Variable Documentation
BRAKE_LIGHT_OFF_THRESHOLD
uint16_t BRAKE_LIGHT_OFF_THRESHOLD = 100 static constexpr
Definition at line 19 of file state_machine.c.
Referenced by set_brake_light().
BRAKE_LIGHT_ON_THRESHOLD
uint16_t BRAKE_LIGHT_ON_THRESHOLD = 200 static constexpr
Definition at line 18 of file state_machine.c.
Referenced by set_brake_light().
MIN_BUZZING_TIME_MS
uint32_t MIN_BUZZING_TIME_MS = 2500 static constexpr
Definition at line 17 of file state_machine.c.
Referenced by is_buzzing_time_elapsed().