PER Firmware: common/strbuf/strbuf.h File Reference
strbuf.h File Reference
Fixed-size string builder. Useful for building large CMD strings before transmission.
#include <stdint.h>
#include <stddef.h>
Data Structures
struct strbuf_t
Macros
#define ALLOCATE_STRBUF(NAME, MAX_SIZE)
Macro to allocate and initialize a strbuf_t with a fixed-size buffer. Also creates the underlying data buffer in the same scope.
Functions
void strbuf_clear (strbuf_t *sb)
Clears the buffer by resetting length to 0.
size_t strbuf_append (strbuf_t *sb, const void *data, size_t length)
Appends raw data to the buffer. If the data exceeds the buffer size, no data is appended.
size_t strbuf_printf (strbuf_t *sb, const char *format,...)
Appends formatted data to the buffer using printf-style formatting. !
Detailed Description
Fixed-size string builder. Useful for building large CMD strings before transmission.
Author
Irving Wang (irvin.nosp@m.gw@p.nosp@m.urdue.nosp@m..edu)
Definition in file strbuf.h.
Macro Definition Documentation
ALLOCATE_STRBUF
#define ALLOCATE_STRBUF (NAME, MAX_SIZE)
Value:
    uint8_t NAME##_data[(MAX_SIZE)]; \
    strbuf_t NAME = { \
        .data    = NAME##_data, \
        .length  = 0, \
        .max_len = (MAX_SIZE), \
    }
Macro to allocate and initialize a strbuf_t with a fixed-size buffer. Also creates the underlying data buffer in the same scope.
Parameters
NAME The name of the strbuf_t variable to create.
MAX_SIZE The maximum size of the buffer. Usage: ALLOCATE_STRBUF(my_buf, 128); This creates a strbuf_t named my_buf with a buffer of 128 bytes.
Definition at line 34 of file strbuf.h.
Function Documentation
strbuf_append()
size_t strbuf_append (strbuf_t * sb, const void * data, size_t length)
Appends raw data to the buffer. If the data exceeds the buffer size, no data is appended.
Returns
Num bytes written to the buffer
Definition at line 25 of file strbuf.c.
References strbuf_t::data, strbuf_t::length, and strbuf_t::max_len.
Referenced by adbms6380_prepare_command(), adbms6380_prepare_data_packet(), NXT_setBackground(), NXT_setBaud(), NXT_setBorderWidth(), NXT_setBrightness(), NXT_setFloat(), NXT_setFontColor(), NXT_setPage(), NXT_setText(), NXT_setTextFormatted(), and NXT_setValue().
strbuf_clear()
void strbuf_clear (strbuf_t * sb)
Clears the buffer by resetting length to 0.
Definition at line 17 of file strbuf.c.
References strbuf_t::length.
Referenced by adbms6380_read_cell_voltages(), adbms6380_read_gpio_voltages(), adbms_connect(), adbms_read_and_check_rega(), adbms_read_and_check_regb(), adbms_read_therms(), adbms_write_rega(), adbms_write_regb(), and lcd_tx_cmd().
strbuf_printf()
size_t strbuf_printf (strbuf_t * sb, const char * format, ...)
Appends formatted data to the buffer using printf-style formatting. !
Warning
This function is unsafe if the formatted string exceeds the remaining buffer space.
Definition at line 41 of file strbuf.c.
References strbuf_t::data, strbuf_t::length, strbuf_t::max_len, and vsnprintf().
Referenced by NXT_setBackground(), NXT_setBaud(), NXT_setBorderWidth(), NXT_setBrightness(), NXT_setFloat(), NXT_setFontColor(), NXT_setPage(), NXT_setText(), NXT_setTextFormatted(), and NXT_setValue().