PER Firmware: ADBMS_module_t Struct Reference
ADBMS_module_t Struct Reference
Per-ADBMS module measurements, config, and error flags.
#include <source/a_box/adbms/adbms.h>
Data Fields
float cell_voltages [(16)]
int16_t cell_voltages_raw [(16)]
float min_voltage
float max_voltage
float avg_voltage
float sum_voltage
float therms_voltages [(10)]
float therms_temps [(10)]
float min_therm_temp
float max_therm_temp
float avg_therm_temp
bool is_discharging [(16)]
uint8_t rega [(6)]
uint8_t regb [(6)]
bool err_rega_mismatch
bool err_regb_mismatch
Detailed Description
Per-ADBMS module measurements, config, and error flags.
Definition at line 62 of file adbms.h.
Field Documentation
avg_therm_temp
float ADBMS_module_t::avg_therm_temp
Average thermistor temperature within this module (Celsius).
Definition at line 86 of file adbms.h.
Referenced by adbms_read_therms().
avg_voltage
float ADBMS_module_t::avg_voltage
Average cell voltage within this module (volts).
Definition at line 72 of file adbms.h.
Referenced by adbms_read_cells().
cell_voltages
float ADBMS_module_t::cell_voltages[(16)]
Latest cell voltage readings for this module (volts).
Definition at line 64 of file adbms.h.
Referenced by adbms_calculate_balance_cells(), and adbms_read_cells().
cell_voltages_raw
int16_t ADBMS_module_t::cell_voltages_raw[(16)]
Latest raw cell voltage readings for this module.
Definition at line 66 of file adbms.h.
Referenced by adbms_read_cells().
err_rega_mismatch
bool ADBMS_module_t::err_rega_mismatch
Set if a read-back REGA does not match cached REGA.
Definition at line 97 of file adbms.h.
Referenced by adbms_init(), and adbms_read_and_check_rega().
err_regb_mismatch
bool ADBMS_module_t::err_regb_mismatch
Set if a read-back REGB does not match cached REGB.
Definition at line 99 of file adbms.h.
Referenced by adbms_init(), and adbms_read_and_check_regb().
is_discharging
bool ADBMS_module_t::is_discharging[(16)]
Per-cell discharge enable flags used for balancing. Set by BMS, not higher level logic.
Definition at line 89 of file adbms.h.
Referenced by adbms_calculate_balance_cells(), adbms_init(), and adbms_write_regb().
max_therm_temp
float ADBMS_module_t::max_therm_temp
Maximum thermistor temperature within this module (Celsius).
Definition at line 84 of file adbms.h.
Referenced by adbms_read_therms().
max_voltage
float ADBMS_module_t::max_voltage
Maximum cell voltage within this module (volts).
Definition at line 70 of file adbms.h.
Referenced by adbms_read_cells().
min_therm_temp
float ADBMS_module_t::min_therm_temp
Minimum thermistor temperature within this module (Celsius).
Definition at line 82 of file adbms.h.
Referenced by adbms_read_therms().
min_voltage
float ADBMS_module_t::min_voltage
Minimum cell voltage within this module (volts).
Definition at line 68 of file adbms.h.
Referenced by adbms_read_cells().
rega
uint8_t ADBMS_module_t::rega[(6)]
Cached REGA bytes written to the device. Used to compare against read-back data.
Definition at line 92 of file adbms.h.
Referenced by adbms_read_and_check_rega(), and adbms_write_rega().
regb
uint8_t ADBMS_module_t::regb[(6)]
Cached REGB bytes written to the device. Used to compare against read-back data.
Definition at line 94 of file adbms.h.
Referenced by adbms_read_and_check_regb(), and adbms_write_regb().
sum_voltage
float ADBMS_module_t::sum_voltage
Sum of cell voltages within this module (volts).
Definition at line 74 of file adbms.h.
Referenced by adbms_read_cells().
therms_temps
float ADBMS_module_t::therms_temps[(10)]
Latest thermistor temperatures in Celsius
Definition at line 79 of file adbms.h.
Referenced by adbms_read_therms().
therms_voltages
float ADBMS_module_t::therms_voltages[(10)]
Latest thermistor readings as volts.
Definition at line 77 of file adbms.h.
Referenced by adbms_read_therms().
The documentation for this struct was generated from the following file:
source/a_box/adbms/adbms.h