PER Firmware: source/daq/buffer/test_buffer.c File Reference
test_buffer.c File Reference
#include "buffer.h"
#include "test_helper.h"
Data Structures
struct timestamped_frame_t
Macros
#define RX_CT 32
#define RX_TAIL_CT 2
Typedefs
typedef uint32_t canid_t
typedef uint8_t busid_t
Functions
static int _check_write (void)
static int _test_basic ()
int main (int argc, char *argv[])
Variables
timestamped_frame_t rx_buffer [32]
b_tail_t tails [2]
b_handle_t b_rx_can
Macro Definition Documentation
RX_CT
#define RX_CT 32
Definition at line 17 of file test_buffer.c.
Referenced by _check_write(), and _test_basic().
RX_TAIL_CT
#define RX_TAIL_CT 2
Definition at line 18 of file test_buffer.c.
Referenced by _test_basic().
Typedef Documentation
busid_t
typedef uint8_t busid_t
Definition at line 7 of file test_buffer.c.
canid_t
typedef uint32_t canid_t
Definition at line 6 of file test_buffer.c.
Function Documentation
_check_write()
static int _check_write (void) static
Definition at line 28 of file test_buffer.c.
References b_handle_t::_head, b_rx_can, bCommitWrite(), bGetHeadForWrite(), rx_buffer, RX_CT, t_check, t_end, and t_start.
Referenced by _test_basic().
_test_basic()
static int _test_basic () static
Definition at line 45 of file test_buffer.c.
References _check_write(), b_handle_t::_head, b_handle_t::_item_size, b_handle_t::_max_items, b_handle_t::_min_tail, b_tail_t::_tail, b_rx_can, bActivateTail(), bCommitRead(), bCommitWrite(), bConstruct(), bGetHeadForWrite(), bGetTailForRead(), rx_buffer, RX_CT, RX_TAIL_CT, t_check, t_end, t_start, and tails.
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 110 of file test_buffer.c.
References _test_basic(), and t_run.
Variable Documentation
b_rx_can
b_handle_t b_rx_can
Initial value:
= {
    .buffer    = (uint8_t*)rx_buffer,
    .tails     = tails,
    .num_tails = 2 ,
}
Definition at line 22 of file test_buffer.c.
Referenced by _check_write(), _sd_write_periodic(), _test_basic(), eth_udp_send_frame(), eth_udp_send_periodic(), eth_update_periodic(), sd_shutdown(), and sd_update_periodic().
rx_buffer
timestamped_frame_t rx_buffer[32]
Definition at line 19 of file test_buffer.c.
Referenced by _check_write(), _test_basic(), adbms6380_read(), adbms6380_read_cell_voltages(), adbms6380_read_data(), adbms6380_read_data_with_retries(), adbms6380_read_gpio_voltages(), BMI088_readAccel(), BMI088_readGyro(), and GPS_Decode().
tails
b_tail_t tails[2]
Definition at line 20 of file test_buffer.c.
Referenced by _test_basic().