PER Firmware: source/torque_vector/main.c File Reference
main.c File Reference
"Torque Vector" node source code
#include "main.h"
#include <stdint.h>
#include "common/can_library/generated/TORQUE_VECTOR.h"
#include "common/freertos/freertos.h"
#include "common/phal/can.h"
#include "common/phal/gpio.h"
#include "common/phal/rcc.h"
Functions
void HardFault_Handler (void)
void ledblink ()
void can_worker_thread ()
defineThreadStack (ledblink, 500, osPriorityLow, 256)
defineThreadStack (can_worker_thread, 15, osPriorityNormal, 2048)
int main (void)
Variables
GPIOInitConfig_t gpio_config []
static constexpr uint32_t TargetCoreClockrateHz = 16000000
ClockRateConfig_t clock_config
uint32_t APB1ClockRateHz
uint32_t APB2ClockRateHz
uint32_t AHBClockRateHz
uint32_t PLLClockRateHz
Detailed Description
"Torque Vector" node source code
Author
Irving Wang (irvin.nosp@m.gw@p.nosp@m.urdue.nosp@m..edu)
Definition in file main.c.
Function Documentation
can_worker_thread()
void can_worker_thread ()
Definition at line 59 of file main.c.
References CAN_rx_update(), and CAN_tx_update().
Referenced by main().
defineThreadStack() [1/2]
defineThreadStack (can_worker_thread , 15 , osPriorityNormal , 2048)
defineThreadStack() [2/2]
defineThreadStack (ledblink , 500 , osPriorityLow , 256)
HardFault_Handler()
void HardFault_Handler (void) extern
Definition at line 96 of file main.c.
References ERROR_LED_PIN, and ERROR_LED_PORT.
ledblink()
void ledblink ()
Definition at line 55 of file main.c.
References HEARTBEAT_LED_PIN, HEARTBEAT_LED_PORT, and PHAL_toggleGPIO().
main()
int main (void)
Definition at line 67 of file main.c.
References CAN_library_init(), can_worker_thread(), clock_config, createThread, gpio_config, HardFault_Handler(), ledblink(), PHAL_configureClockRates(), PHAL_FDCAN_init(), and PHAL_initGPIO().
Variable Documentation
AHBClockRateHz
uint32_t AHBClockRateHz extern
Definition at line 17 of file rcc.c.
Referenced by PHAL_configureAHBClock(), PHAL_configureAPB1Clock(), and PHAL_configureAPB2Clock().
APB1ClockRateHz
uint32_t APB1ClockRateHz extern
Definition at line 15 of file rcc.c.
APB2ClockRateHz
uint32_t APB2ClockRateHz extern
Definition at line 16 of file rcc.c.
clock_config
ClockRateConfig_t clock_config
Initial value:
= {
    .clock_source           = CLOCK_SOURCE_HSE,
    .use_pll                = false,
    .system_clock_target_hz = TargetCoreClockrateHz,
    .ahb_clock_target_hz    = (TargetCoreClockrateHz / 1),
    .apb1_clock_target_hz   = (TargetCoreClockrateHz / (1)),
    .apb2_clock_target_hz   = (TargetCoreClockrateHz / (1)),
}
Definition at line 37 of file main.c.
gpio_config
GPIOInitConfig_t gpio_config[]
Initial value:
= {
    GPIO_INIT_OUTPUT( (GPIOB) , (4) , GPIO_OUTPUT_LOW_SPEED),
    GPIO_INIT_OUTPUT( (GPIOA) , (15) , GPIO_OUTPUT_LOW_SPEED),
    GPIO_INIT_OUTPUT( (GPIOB) , (3) , GPIO_OUTPUT_LOW_SPEED),
    GPIO_INIT_FDCAN2TX_PB13,
    GPIO_INIT_FDCAN2RX_PB12,
}
Definition at line 20 of file main.c.
PLLClockRateHz
uint32_t PLLClockRateHz extern
Definition at line 18 of file rcc.c.
Referenced by PHAL_configurePLLSystemClock(), and PHAL_configurePLLVCO().
TargetCoreClockrateHz
uint32_t TargetCoreClockrateHz = 16000000 static constexpr
Definition at line 36 of file main.c.