PER Firmware: common/log/vsprintf.h File Reference
vsprintf.h File Reference
#include <stdarg.h>
#include <stddef.h>
Functions
int vsprintf (char *buf, const char *fmt, va_list args)
int vsnprintf (char *buf, size_t size, const char *fmt, va_list args)
Function Documentation
vsnprintf()
int vsnprintf (char * buf, size_t size, const char * fmt, va_list args)
Definition at line 207 of file vsprintf.c.
References CHARTOINT, fmtint(), fmtstr(), INTMAX_T, ISDIGIT, LLONG, OUTCHAR, PRINT_C_CHAR, PRINT_C_INTMAX, PRINT_C_LLONG, PRINT_C_LONG, PRINT_C_PTRDIFF, PRINT_C_SHORT, PRINT_C_SIZE, PRINT_F_MINUS, PRINT_F_NUM, PRINT_F_PLUS, PRINT_F_QUOTE, PRINT_F_SPACE, PRINT_F_UNSIGNED, PRINT_F_UP, PRINT_F_ZERO, PRINT_S_CONV, PRINT_S_DEFAULT, PRINT_S_DOT, PRINT_S_FLAGS, PRINT_S_MOD, PRINT_S_PRECISION, PRINT_S_WIDTH, PTRDIFF_T, SSIZE_T, UINTMAX_T, UINTPTR_T, ULLONG, and UPTRDIFF_T.
Referenced by NXT_setTextFormatted(), snprintf(), strbuf_printf(), and vsprintf().
vsprintf()
int vsprintf (char * buf, const char * fmt, va_list args)
Definition at line 691 of file vsprintf.c.
References vsnprintf().
Referenced by sprintf().