var searchData=
[
  ['sd_5fcard_2ec_0',['sd_card.c',['../sd__card_8c.html',1,'']]],
  ['sd_5fcard_2eh_1',['sd_card.h',['../sd__card_8h.html',1,'']]],
  ['sd_5ffsm_2edrawio_2epng_2',['SD_FSM.drawio.png',['../SD__FSM_8drawio_8png.html',1,'']]],
  ['sdc_2ec_3',['sdc.c',['../sdc_8c.html',1,'']]],
  ['sdc_2eh_4',['sdc.h',['../sdc_8h.html',1,'']]],
  ['sdio_2ec_5',['sdio.c',['../sdio_8c.html',1,'']]],
  ['sdio_2eh_6',['sdio.h',['../sdio_8h.html',1,'']]],
  ['sensors_2eh_7',['sensors.h',['../sensors_8h.html',1,'']]],
  ['setup_2emd_8',['setup.md',['../setup_8md.html',1,'']]],
  ['spi_2ec_9',['spi.c',['../common_2phal__F4_2spi_2spi_8c.html',1,'(Global Namespace)'],['../common_2phal__G4_2spi_2spi_8c.html',1,'(Global Namespace)'],['../source_2g4__testing_2spi_8c.html',1,'(Global Namespace)']]],
  ['spi_2eh_10',['spi.h',['../phal_2spi_8h.html',1,'(Global Namespace)'],['../phal__F4_2spi_2spi_8h.html',1,'(Global Namespace)'],['../phal__G4_2spi_2spi_8h.html',1,'(Global Namespace)']]],
  ['spmc_2ec_11',['spmc.c',['../spmc_8c.html',1,'']]],
  ['spmc_2eh_12',['spmc.h',['../spmc_8h.html',1,'']]],
  ['stale_5fdetection_2edrawio_2epng_13',['stale_detection.drawio.png',['../stale__detection_8drawio_8png.html',1,'']]],
  ['state_2ec_14',['state.c',['../state_8c.html',1,'']]],
  ['state_2eh_15',['state.h',['../state_8h.html',1,'']]],
  ['strbuf_2ec_16',['strbuf.c',['../strbuf_8c.html',1,'']]],
  ['strbuf_2eh_17',['strbuf.h',['../strbuf_8h.html',1,'']]],
  ['switches_2ec_18',['switches.c',['../switches_8c.html',1,'']]],
  ['switches_2eh_19',['switches.h',['../switches_8h.html',1,'']]],
  ['syscalls_2ec_20',['syscalls.c',['../syscalls_8c.html',1,'']]],
  ['syscalls_2eh_21',['syscalls.h',['../syscalls_8h.html',1,'']]]
];
