var searchData=
[
  ['sd_5fcard_2ec_0',['sd_card.c',['../sd__card_8c.html',1,'']]],
  ['sd_5fcard_2eh_1',['sd_card.h',['../sd__card_8h.html',1,'']]],
  ['sd_5ffsm_2edrawio_2epng_2',['SD_FSM.drawio.png',['../SD__FSM_8drawio_8png.html',1,'']]],
  ['sdc_2ec_3',['sdc.c',['../sdc_8c.html',1,'']]],
  ['sdc_2eh_4',['sdc.h',['../sdc_8h.html',1,'']]],
  ['sdio_2ec_5',['sdio.c',['../sdio_8c.html',1,'']]],
  ['sdio_2eh_6',['sdio.h',['../sdio_8h.html',1,'']]],
  ['sensors_2eh_7',['sensors.h',['../sensors_8h.html',1,'']]],
  ['setup_2emd_8',['setup.md',['../setup_8md.html',1,'']]],
  ['spi_2ec_9',['spi.c',['../phal__F4_2spi_2spi_8c.html',1,'(Global Namespace)'],['../phal__G4_2spi_2spi_8c.html',1,'(Global Namespace)']]],
  ['spi_2eh_10',['spi.h',['../phal__F4_2spi_2spi_8h.html',1,'(Global Namespace)'],['../phal__G4_2spi_2spi_8h.html',1,'(Global Namespace)']]],
  ['spi_5fpriv_2ec_11',['spi_priv.c',['../spi__priv_8c.html',1,'']]],
  ['spi_5fpriv_2eh_12',['spi_priv.h',['../spi__priv_8h.html',1,'']]],
  ['spi_5ftest_2ec_13',['spi_test.c',['../spi__test_8c.html',1,'']]],
  ['spmc_2ec_14',['spmc.c',['../spmc_8c.html',1,'']]],
  ['spmc_2eh_15',['spmc.h',['../spmc_8h.html',1,'']]],
  ['stale_5fdetection_2edrawio_2epng_16',['stale_detection.drawio.png',['../stale__detection_8drawio_8png.html',1,'']]],
  ['state_2ec_17',['state.c',['../state_8c.html',1,'']]],
  ['state_2eh_18',['state.h',['../state_8h.html',1,'']]],
  ['strbuf_2ec_19',['strbuf.c',['../strbuf_8c.html',1,'']]],
  ['strbuf_2eh_20',['strbuf.h',['../strbuf_8h.html',1,'']]],
  ['switches_2ec_21',['switches.c',['../switches_8c.html',1,'']]],
  ['switches_2eh_22',['switches.h',['../switches_8h.html',1,'']]],
  ['syscalls_2ec_23',['syscalls.c',['../syscalls_8c.html',1,'']]],
  ['syscalls_2eh_24',['syscalls.h',['../syscalls_8h.html',1,'']]]
];
