#ifndef PER_FREERTOS_H
#define PER_FREERTOS_H

/**
 * @file freertos.h
 * @brief Wrapper macros for FreeRTOS constructs (tasks, queues, semaphores) to simplify static memory allocation and initialization.
 * 
 * @author Irving Wang (irvingw@purdue.edu)
 * @author Millan Kumar (kumar798@purdue.edu)
 */

// clang-format off
#define myIDENT(x) x
#define myXSTR(x) #x
#define mySTR(x) myXSTR(x)
#define __FREERTOS_PATH(x,y) mySTR(myIDENT(x)y)
#define _FREERTOS_PATH(y) __FREERTOS_PATH(_FREERTOS_DIR, y)

#if defined(STM32F407xx)
#define _FREERTOS_DIR external/STM32CubeF4/Middlewares/Third_Party/FreeRTOS/Source/
#elif defined(STM32G474xx)
#define _FREERTOS_DIR external/STM32CubeG4/Middlewares/Third_Party/FreeRTOS/Source/
#else
#error "Unsupported MCU arch"
#endif

#include _FREERTOS_PATH(include/FreeRTOS.h)

#include _FREERTOS_PATH(include/list.h)
#include _FREERTOS_PATH(include/queue.h)
#include _FREERTOS_PATH(include/semphr.h)
#include _FREERTOS_PATH(include/task.h)
#include _FREERTOS_PATH(include/timers.h)
// clang-format on

#include <stdint.h>
#include <stdbool.h>

// Stack size aliases
#define STACK_256  (256)
#define STACK_512  (512)
#define STACK_1024 (1024)
#define STACK_2048 (2048)
#define STACK_4096 (4096)

// Priority aliases
#define TASK_PRIORITY_LOW     (tskIDLE_PRIORITY + 1)
#define TASK_PRIORITY_NORMAL  (tskIDLE_PRIORITY + 2)
#define TASK_PRIORITY_HIGH    (tskIDLE_PRIORITY + 3)
#define TASK_PRIORITY_HIGHEST (configMAX_PRIORITIES - 1)

typedef struct {
    void (*taskFunction)(void);
    uint32_t period_ms;
} periodic_task_params_t;

// This is the function actually scheduled by freertos
// Arg is of type periodic_task_params_t*
void periodic_task_runner(void* arg);


/**
 * @brief Defines a statically allocated periodic FreeRTOS task.
 *
 * Allocates memory statically here:
 * task control block (TCB), stack, task parameters, and task handle
 *
 * The task is not created until START_TASK is called.
 *
 * The task will be executed periodically by periodic_task_runner.
 *
 * @param NAME       Name of the task function.
 * @param PERIOD_MS  Execution period in milliseconds.
 * @param PRIORITY   FreeRTOS task priority.
 * @param STACK_SIZE Stack size in bytes
 */
#define DEFINE_TASK(NAME, PERIOD_MS, PRIORITY, STACK_SIZE)                     \
    static_assert(                                                             \
        (STACK_SIZE) % sizeof(StackType_t) == 0,                               \
        "Stack size must be a multiple of StackType_t"                         \
    );                                                                         \
                                                                               \
    static StaticTask_t NAME##_tcb;                                            \
    static StackType_t NAME##_stack[(STACK_SIZE) / sizeof(StackType_t)];       \
                                                                               \
    static periodic_task_params_t NAME##_params = {                            \
        .taskFunction = (void (*)(void))NAME,                                  \
        .period_ms    = (PERIOD_MS),                                           \
        .priority     = (PRIORITY),                                            \
    };                                                                         \
                                                                               \
    TaskHandle_t NAME##_handle

/**
 * @brief Creates and starts a previously defined task
 *
 * Creates the task using xTaskCreateStatic() and stores the resulting
 * task handle in the handle generated by DEFINE_TASK.
 *
 * This macro should be called once after the scheduler has been
 * initialized and before vTaskStartScheduler().
 *
 * @param NAME Name passed to DEFINE_TASK.
 *
 * @return TaskHandle_t for the created task, or NULL if task creation failed.
 */
#define START_TASK(NAME)                                                       \
    (NAME##_handle = xTaskCreateStatic(                                        \
        periodic_task_runner,                                                  \
        #NAME,                                                                 \
        sizeof(NAME##_stack) / sizeof(StackType_t),                            \
        &NAME##_params,                                                        \
        NAME##_params.priority,                                                \
        NAME##_stack,                                                          \
        &NAME##_tcb))


/**
 * @brief Retrieves the FreeRTOS task handle for the defined task.
 */
#define HANDLE_OF(NAME) (NAME##_handle)

/**
 * @brief Scaffolds the static memory for a FreeRTOS queue.
 */
#define DEFINE_QUEUE(NAME, ITEM, COUNT)                                        \
    static_assert(COUNT > 0, "Queue count must be greater than 0");            \
    QueueHandle_t NAME;                                                        \
    static StaticQueue_t NAME##_cb;                                            \
    static uint8_t       NAME##_data[sizeof(ITEM) * (COUNT)];

/**
 * @brief Initializes the defined static queue.
 */
#define INIT_QUEUE(NAME, ITEM, COUNT)                                          \
    (NAME = xQueueCreateStatic((COUNT), sizeof(ITEM), NAME##_data, &NAME##_cb))

/**
 * @brief Scaffolds the static memory for a semaphore (and related variants).
 */
#define DEFINE_SEMAPHORE(NAME)                                                 \
    SemaphoreHandle_t NAME;                                                    \
    static StaticSemaphore_t NAME##_cb;

// Aliases for clarity
#define DEFINE_MUTEX(NAME) DEFINE_SEMAPHORE(NAME)
#define DEFINE_COUNTING_SEMAPHORE(NAME) DEFINE_SEMAPHORE(NAME)
#define DEFINE_BINARY_SEMAPHORE(NAME) DEFINE_SEMAPHORE(NAME)

/**
 * @brief Initializes the defined mutex.
 */
#define INIT_MUTEX(NAME)                                                       \
    (NAME = xSemaphoreCreateMutexStatic(&(NAME##_cb)))

/**
 * @brief Initializes the defined static counting semaphore.
 * @note initial count is set to max count (full by default)
 */
#define INIT_COUNTING_SEMAPHORE(NAME, MAX_COUNT)                               \
    (NAME = xSemaphoreCreateCountingStatic((MAX_COUNT), (MAX_COUNT), &(NAME##_cb)))
    
/**
 * @brief Initializes the defined static binary semaphore.
 */
#define INIT_BINARY_SEMAPHORE(NAME)                                            \
    (NAME = xSemaphoreCreateBinaryStatic(&(NAME##_cb)))

#endif // PER_FREERTOS_H