// VCU structs
typedef struct {
    float VCU_MODE_REQ;
    float THROT_RAW;
    float BRAKE_RAW;
    float ST_RAW;
    float VB_RAW;
    float WM_RAW[4];
    float GS_RAW;
    float AV_RAW[3];
    float IB_RAW;
    float MT_RAW;
    float IGBT_T_RAW;
    float INV_T_RAW;
    float MC_RAW[4];
    float IC_RAW[4];
    float BT_RAW;
    float TO_RAW[4];
    float RG_split_FR_RAW;
} xVCU_struct;

typedef struct {
    float VCU_MODE;
    float TH;
    float TH_PO;
    float TH_RG;
    float ST;
    float VB;
    float WM[4];
    float GS;
    float AV[3];
    float IB;
    float MT;
    float IGBT_T;
    float INV_T;
    float OV_MOT[4];
    float OV_INV[4];
    float BT;
    float TO[4];
    float IB_AVG_buffer[10];
    float PB;
    float WW[4];
    float IB_AVG;
    float TO_BL_PO[4];
    float RG_split_FR;
    float TO_BL_RG[4];
    float AC_MW[4];
    float SK_TO[4];
    float AX_TO[4];
    float TORQUE_LIM_NEG[4];
    float TORQUE_LIM_POS[4];
    float SPEED_OUT[4];
} yVCU_struct;

typedef struct {
    float r;
    float ht[2];
    float wb;
    float gr;
    float MAX_ABS_WM;
    float IB_AVG_length;
    float MAX_TO_ABS_PO;
    float PB_derating_full_T;
    float PB_derating_half_T;
    float PB_derating_FR;
    float VB_derating_full_T;
    float VB_derating_zero_T;
    float IB_derating_full_T;
    float IB_derating_zero_T;
    float OV_MOT_derating_full_T;
    float OV_MOT_derating_zero_T;
    float OV_INV_derating_full_T;
    float OV_INV_derating_zero_T;
    float MAX_TO_ABS_RG;
    float VB_RG_derating_full_T;
    float VB_RG_derating_zero_T;
    float IB_RG_derating_full_T;
    float IB_RG_derating_zero_T;
    float GS_RG_derating_zero;
    float GS_RG_derating_full;
    float INV_T_derating_full_T;
    float INV_T_derating_zero_T;
    float IGBT_T_derating_full_T;
    float IGBT_T_derating_zero_T;
    float MT_derating_full_T;
    float MT_derating_zero_T;
    float BT_derating_full_T;
    float BT_derating_zero_T;
    float AC_speed_brkpt[3];
    float AC_speed_table[3];
    float AC_brkpt_lb;
    float AC_brkpt_ub;
    float SK_YAW_des;
    float SK_LR_split_des;
    float SK_FR_split;
    float SK_LR_gain;
    float SK_ST_ZERO_TV;
    float SK_ST_FULL_TV;
} pVCU_struct;

// VCU struct initialization functions
xVCU_struct init_xVCU(void);
yVCU_struct init_yVCU(void);
pVCU_struct init_pVCU(void);

void vcu_step(const pVCU_struct *p, const xVCU_struct *x, yVCU_struct *y);