function(add_cmsis_dsp)
    set(CMSISCORE "${CMAKE_SOURCE_DIR}/external/STM32CubeG4/Drivers/CMSIS/Core")
    add_subdirectory(${CMAKE_SOURCE_DIR}/external/CMSIS-DSP/Source bin_dsp)
    if (TARGET CMSISDSP)
        get_cpu_flags("STM32G4xx" DSP_CPU_FLAGS)
        target_compile_options(CMSISDSP PUBLIC ${DSP_CPU_FLAGS})
        target_link_options(CMSISDSP PUBLIC ${DSP_CPU_FLAGS})
        target_compile_options(CMSISDSP PRIVATE -Wno-error -fno-analyzer)
    endif()
endfunction()