name: Build and Release Firmware

on:
  push:
    branches:
      - master

# Add tags here for versions

permissions:
  contents: write  # Required to create GitHub release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with: 
          submodules: recursive

      - name: Install dependencies (CMake, Ninja, ARM GCC)
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build gcc-arm-none-eabi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install Python requirements
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Get short hash
        id: git_info
        run: |
          SHORT_HASH=$(git rev-parse --short HEAD)
          echo "short_hash=$SHORT_HASH" >> $GITHUB_OUTPUT

      - name: Run per_build.py
        run: python3 per_build.py --release --package

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-${{ steps.git_info.outputs.short_hash }}
          name: Firmware Release ${{ steps.git_info.outputs.short_hash }}
          files: output/firmware*.tar.gz
          prerelease: true
